### ISSUE TITLE
Automatically generate mkdocs.yml

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#100]
This is a bit future looking, but `mkdocs.yml` must contain structural information about the docs (`pages:` section), and this could be generated automatically.

For other formats (e.g. #3) we need to figure out the general structure of the pages anyway and we might even need our own version of `mkdocs.yml`. Once that is in, should we also extend that to mkdocs generation to have a consistent way of structuring docs with Documenter?

**Comment by MichaelHatherly** [comment]
Been wondering how we should handle this, thanks for opening an issue for it.

Perhaps we should define the necessary data in `make.jl` just as a datastructure (`Dict` or something) rather than needing to parse a separate config for this. Then pass that to `makedocs`/`deploydocs` when needed.

**Comment by TotalVerb** [comment]
I think this is a great idea! Sometimes I want to have stuff in `extra` that depends on the version, like:

```
extra:
  version: 0.3.2
```

for the material theme. I think generating `mkdocs.yml` is the only way to allow this kind of variance between versions.

**Comment by hayd** [comment]
see in the distant past https://github.com/MichaelHatherly/Docile.jl/pull/150/commits/dc67ad87de2d8190ac8fa192433e93cc55e245a9

related: documentation ordering (#13)

**Comment by MichaelHatherly** [comment]
(Thanks for linking to that one @hayd.)

**Comment by TranDinhKhang** [comment]
Hello, how about this feature, guys?

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing because Documenter no longer supports `mkdocs`.
