### ISSUE TITLE
[question] where is the html minified in the code?

### ISSUE THREAD

**Issue by tlienart** [JuliaDocs/Documenter.jl#1001]
Sorry for the dumb question, I wasn't able to find where the produced HTML is minified (as it seems to be minified somewhere?); I'm interested in this for another project (where I currently use a python tool to minify the produced html & css). 

Thanks!

**Comment by mortenpi** [comment]
There is no special minification step. The [`DOM` module](https://github.com/JuliaDocs/Documenter.jl/blob/master/src/Utilities/DOM.jl) is used to construct the HTML document in memory as a tree and then it can be printed out as this minified HTML.

**Comment by tlienart** [comment]
ok thanks a lot for the quick response again :)
