### ISSUE TITLE
Unclear how to run a command from the docs directory.

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaDocs/Documenter.jl#1008]
`Leave the newly added file empty and then run the following command from the docs/ directory

$ julia make.jl`

These instructions are not clear as to how I can run the make.jl file in the initial setup of documentor. 

https://juliadocs.github.io/Documenter.jl/stable/man/guide/

**Comment by mortenpi** [comment]
It refers to running the `make.jl` script with Julia from the shell. To me it's pretty clear what is meant, but I probably can't objectively judge it. What do you find confusing there?

**Comment by ryanelandt** [comment]
Not sure if this is @logankilpatrick's issue, but I open Julia from the bin directory of the precompiled binary folder by typing `./julia`. It might not be obvious how to do run this command from the docs directory for those who do not have Julia installed system-wide (hope this is the right term). Perhaps something like `include(joinpath(expanduser("~"), ".julia", "dev", "MyNewModule", "docs", "make.jl"))` might help.

**Comment by logankilpatrick** [comment]
I was just confused about "then run the following command from the docs/ directory"... Using Atom, I was able to just run the file itself by clicking command+shift+return(on mac), but I am unsure how to run the file using that command "make.jl"..... I tried to cd into the repo's folder but that did not help me.  I also have the .julia folder setup properly.

**Comment by logankilpatrick** [comment]
@mortenpi so can we either add a note to just do command+shift+return(on mac) or can you provide more concrete details as to how  to run it from that direcoty? I am confused on that termonology.

**Comment by KristofferC** [comment]
`make.jl` is just a julia file. Julia files can be run by giving them as an argument to the julia executable, e.g. `julia make.jl`. Running something from a directory means that the "working" directory is set to that directory. Typically that is done by traversing to that directory in a command line window using `cd`. In Atom (with Juno) the working direcotry is set using the "Select Working Folder" command. In this case, that should be set to the `docs` directory.

After that you should be able to just run the `make.jl` file with that shortcut.

**Comment by mortenpi** [comment]
> Perhaps something like `include(joinpath(expanduser("~"), ".julia", "dev", "MyNewModule", "docs", "make.jl"))` might help.

Mentioning the `include` workflow would probably be quite helpful actually. But it kind of requires Revise as you won't see updated docstrings otherwise, so it is sort of a dup of #828.

In any case though, I would be more than happy to review a PR clarifying this in the manual.
