### ISSUE TITLE
doctest drops spaces at ends of lines

### ISSUE THREAD

**Issue by holder66** [JuliaDocs/Documenter.jl#101]
Great package, Michael! Thank you!
I'm experiencing problems with doctests failing, because the expected values (copied and pasted from the REPL) include lines with spaces at the end. These spaces disappear when the doctest runs, and so the test fails.
Of course, I can work around it by editing out the spaces in the .md file, but I would like to not have to do that extra several steps.
[terminal output doctest problem.txt](https://github.com/JuliaDocs/Documenter.jl/files/320883/terminal.output.doctest.problem.txt)

**Comment by MichaelHatherly** [comment]
Glad you've found it useful!

The trailing whitespace removal is currently the expected behaviour, though we could perhaps be a bit more lenient with what we allow here. Is it possible to make your output functions strip trailing whitespace when printing, or are they significant in some way? Generally, I believe, most output functions in `Base` and other larger packages don't print trailing whitespace (though perhaps that's not a great indicator).

**Comment by holder66** [comment]
It appears that leading whitespace is also stripped away. So if I have a newline at the start, to improve readability, then the doctest will fail also.

My expectation of behaviour is that it should do a straightforward compare of expected and returned, without modifying either! Of course, I’ve not used doctests before, so that may be somewhat naive on my part.

Henry

**Comment by MichaelHatherly** [comment]
Hmm, it probably shouldn't be stripping leading whitespace. That part's definitely a bug.

> it should do a straightforward compare of expected and returned

Yes, that's definitely the behaviour that should be expected here.

**Comment by MichaelHatherly** [comment]
Some additional whitespace "normalisation" in #111. That should make leading/trailing whitespace irrelevant to whether a test passes or fails. I think leaving whitespace in as part of the test would likely lead to difficult to compare test results.

(Possibly we need some kind of diff highlighting when a test fails to make things more obvious, but that's a bigger project than the fix needed here and can wait for a later time.)

**Comment by MichaelHatherly** [comment]
Closed by #111.
