### ISSUE TITLE
Add individual anchors

### ISSUE THREAD

**Issue by kellertuer** [JuliaDocs/Documenter.jl#1018]
IN my case I am trying to provide a few Literature links at the end of a page (that actually is generated by `Literate.jl` but that should not make that much of a difference, for example

```
* [AB18] Authors, _Title_, Literature details
```

(yes a Literature system, something `bib latex` style based would also be nice), and I would like to link to that Item. How can I introduce an anchor that I can `[see XY](@ref AB18)` to? Is that available? Maybe I am also just missing a feature of Markdown?

**Comment by mortenpi** [comment]
The short answer is that no, not at the moment. The slightly longer answers is:

* Proper bibliography support support should be done via a pluging. There already is [Citations.jl](https://github.com/adamslc/Citations.jl) and you might want to check it out, but I don't know what state it is in.
* Managing custom references and anchors is a dup of #745.

**Comment by kellertuer** [comment]
Thank you for your answer. I wasn't aware of Citations.jl, thanks for the link, though it looks not yet finished; maybe I'll check it out and look whether I can contribute. I would really like to have citations in Documenter.
As a small remark on #745: In Jekyll Markdown anchors are created as `[Text]{anchor}` but maybe the `(@anchor anchor)` is the `Documenter.jl`-style to do so.
