### ISSUE TITLE
Update logo?

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#1022]
In case you want to update the JuliaDocs/Documenter icon/logo to match the newer style, I've done a refreshed version. 

<img width="650" alt="Screenshot 2019-05-17 at 10 00 36" src="https://user-images.githubusercontent.com/52289/57916392-ad4f8300-788a-11e9-95bf-30281a550e19.png">

Here's a 500x500 PNG:

![documenter](https://user-images.githubusercontent.com/52289/57915889-a8d69a80-7889-11e9-8cd0-bcce13f4ee4e.png)

I've got an SVG as well if you want it.

**Comment by fredrikekre** [comment]
Looks nice. PR? Maybe I should update https://github.com/fredrikekre/Literate.jl/blob/master/docs/src/assets/logo.png too then

**Comment by fredrikekre** [comment]
Maybe the white lines make it look a bit blurry when the logo is viewed in a small format? What does it look like without them?

**Comment by cormullion** [comment]
I think I prefer it, but I suppose I was thinking about accessibility/contrast. 

![documenter1](https://user-images.githubusercontent.com/52289/57917833-6e6efc80-788d-11e9-9550-e43ad6ccc3cf.png)

I'm happy to make a PR, if you can point me to the location?

**Comment by fredrikekre** [comment]
I think its just these two files: https://github.com/JuliaDocs/Documenter.jl/tree/master/docs/src/assets

**Comment by mortenpi** [comment]
> to match the newer style

Is there an effort going on to update all the orgs?

**Comment by cormullion** [comment]
It might work in white... The darker color now in use suggests either black or white for the contrast, I can't decide which looks better. 

 ![documenter1](https://user-images.githubusercontent.com/52289/57918360-88f5a580-788e-11e9-9a55-2c0dc1773fe9.png)

@mortenpi After doing the main julialang page (and musm did the Windows icons), I thought JuliaDocs was quite visible (particularly with the new pkg.julialang.org/docs coming on stream. There's not much in the way of effort apart from that... I'm not **yet** regretting observing the inconsistencies between old and new designs... :)

**Comment by fredrikekre** [comment]
Maybe try black with white borders?

**Comment by cormullion** [comment]
You mean: 

![documenter1](https://user-images.githubusercontent.com/52289/57918937-ad05b680-788f-11e9-8dd7-c74da7b4cb36.png)

**Comment by fredrikekre** [comment]
No, I meant the original one :p

**Comment by cormullion** [comment]
I'll let someone else decide... :)

**Comment by fredrikekre** [comment]
I would merged if you make a PR with the original one :)

Btw, should the `?` not be aligned such that the "dot" is in the middle? Looks a bit skew now.

**Comment by cormullion** [comment]
Yes I'll tidy it up and make a PR. Cheers!

**Comment by mortenpi** [comment]
Yeah, I think the black with white border is the best. I had to get used to it a bit, but the contrast is actually good. Although, maybe for the favicon, which has to be scaled down, it's better to use the all black one as a starting point.
