### ISSUE TITLE
Functions from some modules not included in the generated documentation

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaDocs/Documenter.jl#1032]
Nothing is generated for

https://petrkryslucsd.github.io/FinEtools.jl/latest/man/functions.html#Material-for-deformation,-base-functionality-1

and neither is for

https://petrkryslucsd.github.io/FinEtools.jl/latest/man/functions.html#Integration-rule-1

All the other functions are documented. Just these two sections show no functions whatsoever. The types are generated fine from the above modules.

The code for the functions is pretty much the same as for the types.
![image](https://user-images.githubusercontent.com/9855832/58925506-9ae39f00-86fc-11e9-846e-4133b9828acf.png)

I'm not sure what's going on. Would you have any idea?

**Comment by mortenpi** [comment]
I think you only have constructors in e.g. [IntegRuleModule](https://github.com/PetrKryslUCSD/FinEtools.jl/blob/master/src/IntegRuleModule.jl)? So I think all the docstrings are under the [Types section](https://petrkryslucsd.github.io/FinEtools.jl/latest/man/types.html#Integration-rule-1)?

**Comment by PetrKryslUCSD** [comment]
Ahh, that would make sense for  IntegRuleModule! On the other hand, FinEtools.MatDeforModule exports a lot of functions, and they are not included in the generated documentation.

**Comment by mortenpi** [comment]
Hmm, you're right, that's a bit more mysterious. You are getting [a lot of warnings about duplicate docs from that module](https://travis-ci.org/PetrKryslUCSD/FinEtools.jl/jobs/541508621#L702-L848) for some reason. But they might be ignored because you are [exporting them in the main module](https://github.com/PetrKryslUCSD/FinEtools.jl/blob/master/src/FinEtools.jl#L220-L222) and they don't count as private anymore.

**Comment by PetrKryslUCSD** [comment]
Does "private" mean only not-exported, or does it mean both exported and not-exported

**Comment by mortenpi** [comment]
Only not-exported if I remember correctly.

**Comment by PetrKryslUCSD** [comment]
Okay, so that doesn't explain it. It wouldn't, actually, since all the other modules' functions are documented properly.

**Comment by PetrKryslUCSD** [comment]
You might be on the right track with the warnings. Now that I think about it, they seem to be about functions that are actually missing in the documentation. Now to figure out why these warnings occur.

**Comment by mortenpi** [comment]
I think I have it -- you have the `materials.md` file too which duplicates the docs for those modules. Even though you're not including it in `pages`, it is actually being parsed (ref #1031). It looks like that if autodocs runs into a docstring that is already included, it does not include it again.

**Comment by PetrKryslUCSD** [comment]
That is what I just realized too :)  I never thought a file not referenced would be processed. I guess I have to be careful what I put in the docs folder... Thanks for your help.
