### ISSUE TITLE
logo.png and favicon.ico not being detected

### ISSUE THREAD

**Issue by ianshmean** [JuliaDocs/Documenter.jl#1049]
I can't figure out why `docs/assets/logo.png` and `docs/assets/favicon.ico` aren't being detected in the docs I'm trying to initiate in over in  https://github.com/JuliaIO/VideoIO.jl/tree/master/docs

Result: https://juliaio.github.io/VideoIO.jl/dev/

Is it a bug or am I doing something wrong?

**Comment by mortenpi** [comment]
They need to be in `docs/src/assets/`.

**Comment by ianshmean** [comment]
Ah! ok. I think I was confused by the `assets = ["assets/favicon.ico"]` in `docs/make.jl`.. I assumed the path was relative to `make.jl`

Thanks
