### ISSUE TITLE
Feature Request: copy to clipboard

### ISSUE THREAD

**Issue by Roger-luo** [JuliaDocs/Documenter.jl#1055]
I'm wondering if it is possible to enable this automatically for all code blocks in documentation, which make it much easier to try out examples.

**Comment by mortenpi** [comment]
If you mean having a one-click widget to copy a whole code block to the clipboard, then that's something I was considering implementing in the new front end (#1043).

**Comment by Roger-luo** [comment]
Oh, I just searched the issue didn't find it, looking forward to that!

**Comment by mortenpi** [comment]
No issue specific to this feature, so let's leave this open until it's actually implemented :slightly_smiling_face:
