### ISSUE TITLE
Linkcheck tests fail intermittently on CI

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#1057]
The linkcheck tests in `test/dochecks.jl` fail intermittently on Travis CI.

Usually with:

```
┌ Warning: linkcheck 'google.com' status: 301, redirects to http://www.google.com/.
└ @ Documenter.DocChecks ~/build/JuliaDocs/Documenter.jl/src/DocChecks.jl:222
┌ Warning: `curl -sI --proto =http,https,ftp,ftps https://codecov.io/gh/invenia/LibPQ.jl --max-time 10 -o /dev/null --write-out '%{http_code} %{url_effective} %{redirect_url}'` failed:
│   exception = failed process: Process(`curl -sI --proto =http,https,ftp,ftps https://codecov.io/gh/invenia/LibPQ.jl --max-time 10 -o /dev/null --write-out '%{http_code} %{url_effective} %{redirect_url}'`, ProcessExited(28)) [28]
└ @ Documenter.DocChecks ~/build/JuliaDocs/Documenter.jl/src/DocChecks.jl:205
linkcheck: Test Failed at /Users/travis/build/JuliaDocs/Documenter.jl/test/docchecks.jl:23
  Expression: (doc.internal).errors == Set{Symbol}()
   Evaluated: Set(Symbol[:linkcheck]) == Set(Symbol[])
```

**Comment by iamed2** [comment]
Error code 28 is a timeout

I think we should either make that timeout configurable (and set it longer for CI) or just set it longer by default.

This is happening to me often on my nightly LibPQ tests.

**Comment by mortenpi** [comment]
Making it configurable seems reasonable, I'd be happy to take a PR for that.

In Documenter, it seems that the issue has resolved itself for now. We're also now linkchecking Documenter's own manual in a separate GitHub Actions job (#1255). My hope is that Actions timeout less, and if it doesn't, a separate workflow will be easier to ignore.
