### ISSUE TITLE
Specify logo size in deployed docs?

### ISSUE THREAD

**Issue by vlandau** [JuliaDocs/Documenter.jl#1065]
I have an draft logo for my Julia package here:
https://github.com/Circuitscape/Omniscape.jl/blob/master/docs/src/assets/logo.png

When deployed to docs on github pages, it's much smaller than the space available. Is there a way to make it fill up more of the empty space available?

Here's what it looks like in the docs:
![image](https://user-images.githubusercontent.com/17304432/61073420-a187c500-a3d2-11e9-819e-820955afd5c9.png)

Thanks for any insight!

**Comment by fredrikekre** [comment]
You can include your own CSS file, see https://github.com/JuliaLang/Pkg.jl/blob/670927bf8b36094713f3b92d4bff268e1027fd81/docs/src/assets/custom.css#L9-L11 and https://github.com/JuliaLang/Pkg.jl/blob/670927bf8b36094713f3b92d4bff268e1027fd81/docs/make.jl#L12

**Comment by vlandau** [comment]
Will try that out and close this issue once I get it working. Thanks!!
