### ISSUE TITLE
Generalize PR cross references

### ISSUE THREAD

**Issue by tk3369** [JuliaDocs/Documenter.jl#1070]
Currently, it's hardcoding PR references to github.com.  So it doesn't work for GitHub Enterprise or other providers.  It would be nice if we can configure the url reference.

https://github.com/JuliaDocs/Documenter.jl/blob/bf05feea0de7ea419a3d2678985af5a486c589c8/src/CrossReferences.jl#L223

**Comment by mortenpi** [comment]
This was solved by #1808.
