### ISSUE TITLE
codecov doesn't know about doctests?

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaDocs/Documenter.jl#1078]
Here's a example where the last line of the `doctest` tests the method that `coverage` says is not tested

![image](https://user-images.githubusercontent.com/13448787/62068953-d8e0d900-b1fc-11e9-903a-b578e8e4f0c3.png)

**Comment by mortenpi** [comment]
Are you running `doctest` in `runtests.jl`?

**Comment by nickrobinson251** [comment]
ah, thanks! 🤦‍♂ I was missing a `doctest(...)` call from `runtests.jl`
