### ISSUE TITLE
Feature request: duplicatable docstrings

### ISSUE THREAD

**Issue by asinghvi17** [JuliaDocs/Documenter.jl#1079]
For example, if I have two at-docs blocks which reference the same function, only one will actually render the docstring, while the other will be blank.  Is it possible to force both to render the same docstring?

My usecase is primarily documentation of recipes in AbstractPlotting, which I would like to have two pages for: one being a “basics” page and another being a page which just documents all of the available recipes.  I want to put a subset of all recipes on the first page, and then list out all the recipes on the second.  However, currently this isn't possible, simply because the docstrings from the first page will not be written again on the second page.

Another problem is that some functions apply to multiple aspects of a package, and it doesn't make sense to make the user click on hyperlinks and be redirected to another page, just to read a docstring.

**Comment by mattuntergassmair** [comment]
I have a similar use case where there is a "Manual" portion of the docs with all functions and additionally some of the most important functions are documented again in the examples / tutorials to re-introduce their signature and arguments in context.
Also, would be nice to have a way that allows suppressing duplicate docstring warnings.

**Comment by Datseris** [comment]
Morten recommeds:

> if someone wants to take a look at it: it shouldn't be too hard to have a way to annotate an at-docs block so that it would be considered "secondary" (as in, don't get linked to, and we also probably shouldn't run doctests etc in there)

**Comment by asinghvi17** [comment]
https://github.com/JuliaDocs/Documenter.jl/blob/c69fe60cd5ab24c37e735fe6c95aafbeeaf9bab9/src/Expanders.jl#L311-L321

Looks like a good place to start.
