### ISSUE TITLE
Consider adding a feature to hide a sidebar

### ISSUE THREAD

**Issue by bkamins** [JuliaDocs/Documenter.jl#1083]
See the discussion in: https://github.com/JuliaData/DataFrames.jl/issues/1909

**Comment by mortenpi** [comment]
@anandijain: I have slightly changed the width at which the sidebar becomes hidden by default. Would you say that it's sufficient for your use case? You can try it out here:

> https://mortenpi.eu/gsoc2019-mockups/bulma/v9/documenter/

**Comment by bkamins** [comment]
This is fantastic from my perspective. Thank you.

A small question: would it be also possible to have some option to manually hide/show a sidebar (something that e.g. Overleaf has to show/hide file tree sidebar).

**Comment by mortenpi** [comment]
> A small question: would it be also possible to have some option to manually hide/show a sidebar (something that e.g. Overleaf has to show/hide file tree sidebar).

It's technically definitely possible, but what would the purpose be? As the sidebar now becomes hidden pretty much as soon as the main part starts becoming narrower, you wouldn't really get any extra width with that.

**Comment by bkamins** [comment]
When you are on a narrow view the sidebar is hidden so it is not possible to navigate and you are not able to unhide it. The solution, with what I propose, would be:
* manually unhide the sidebar
* navigate to a different section
* hide sidebar to get a maximum view

(this is probably most needed for reading the documentation on mobile devices)

**Comment by mortenpi** [comment]
Ah, but on narrow views, there already is the "hamburger" on the top-right to toggle the sidebar.

**Comment by bkamins** [comment]
Right - I have just checked that 🍔 does exactly what I have requested. Thank you!

**Comment by anandijain** [comment]
Lookin good!!!

**Comment by mortenpi** [comment]
The width at which the sidebar gets hidden was also optimized in #1043, so I this can be closed too.
