### ISSUE TITLE
New API for deployment

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#1087]
We need to change the `deploydocs` API (or perhaps, provide an alternative to it) so that it would not rely directly on (Travis) environment variables.

* The main Julia docs now run on buildbots and we [just set the Travis variables in `make.jl`](https://github.com/JuliaLang/julia/blob/ad8cf8d8f7b2ca9f2612581a21283b14c7b22e7d/doc/make.jl#L195-L214) (although, for future reference, [a few variables are still set in the CI env](https://github.com/JuliaCI/julia-buildbot/blob/2fb4e16de00203ee7ff325e3e6786909b6e4d327/master/doctest.py#L43-L44
)). It would be great if Documenter would target that use case directly.
* It would also help with supporting deployment on other CI systems (#988, https://github.com/JuliaDocs/Documenter.jl/pull/1067#issuecomment-514408057).

I don't have anything specific in mind at the moment though, so suggestions welcome.

Related to #221, #75.

**Comment by davidanthoff** [comment]
I would love to see the general API move towards a setup where I don't run `julia docs/make.jl`, but rather have as entry points something like:
```julia
using Documenter

Documenter.build("MyPackage")
Documenter.test("MyPackage")
Documenter.deploy("MyPackage")
```
That would feel a lot more in line with the Pkg.jl API.

I think that would also imply moving away from this model of having a `make.jl` script that does different things depending on the env it is run, but instead either have a more declarative config file or something like `docs/docconfig.jl` that only populates some data structures about the structure of the docs, but doesn't actually trigger anything like a build or deployment.

**Comment by bliang26** [comment]
My repo is on hosted in my company's internal Github and we don't use Travis. Currently my work around is to manually set the 
TRAVIS_REPO_SLUG, TRAVIS_PULL_REQUEST, TRAVIS_TAG, TRAVIS_BRANCH, DOCUMENTER_KEY, TRAVIS_EVENT_TYPE env variables to trick `deploydocs`. Going forward, having a standalone API for deployment would be very helpful.
