### ISSUE TITLE
Feedback on new Bulma-based front end

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#1091]
This is to track smaller issues with and feedback on the new front end (#1043). These would be good to fix before releasing Documenter 0.24.

The latest Julia manual build with the new front end [is available here (Aug 11)](https://mortenpi.eu/gsoc2019-mockups/bulma/v13/julia/).

**Blockers for 0.24.0:**

- [x] Margins of lists (esp. in admonitions)
- [x] Code links
- [x] Destaturate the link color slightly
- [x] Subpixel antialiasing of the fonts (https://github.com/JuliaLang/julia/pull/32839#issuecomment-520935508)
- [x] Special case code background for docstring header
- [x] #1120

**Other potential enhancements:**

- Link to point to the GitHub repo root
- Global/local theme settings?
- Copy to clipboard (#1055)

**Comment by bkamins** [comment]
@mortenpi - a fantastic achievement. Thank you.

I have noticed one small thing - I am not sure if it is intended. Here are the steps to replicate it:
* open https://mortenpi.eu/gsoc2019-mockups/bulma/v13/documenter/
* open https://mortenpi.eu/gsoc2019-mockups/bulma/v13/julia/
* change theme to dark in "documenter" tab
* reload "julia" tab

The effect is that "julia" also becomes dark. It seems that the theme is a global variable across tabs (at least on Chrome). I expected it to be tab-local, but maybe this is intended?

**Comment by mortenpi** [comment]
It's global for a domain, and sort of intentional (I am just using a [`Window.localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) value to store the theme preference).

But it might make sense to make it local to a specific package by storing a separate value for every document root.. it might become especially relevant when people actually start deploying custom themes. OTOH, a nice feature of the current approach is that when you browse e.g. pkg.julialang.org (or any org. that hosts several packages), your theme preference will be shared by all the packages.

**Comment by bkamins** [comment]
I agree that the approach has its merits (that is why I just wanted to make sure this is intended, as it was somewhat surprising).

Another small issue: in new theme a *code without link* and *code with link* are rendered in exactly the same way. So it is hard to know which parts of the text have links (in the old theme it was clear). Take a look e.g. at https://mortenpi.eu/gsoc2019-mockups/bulma/v13/julia/manual/strings/#. `A` on top is not clickable, but `String` in the first bullet can be clicked on. This problem is in both light and dark theme.

**Comment by jebej** [comment]
Nice, this looks much better, especially the new cards for the standard library methods and the syntax highlighting!

A few comments:
1. I'm not a huge fan of the hashtags in front of the headings in the navbar.
1. The card header seems to have some darker grey highlighting, which seems necessary given that the header is already all grey
2. Some methods don't get syntax highlighting, like the second `droptol!` below.

Keep up the good work!

![image](https://user-images.githubusercontent.com/11141558/63288593-15977180-c28b-11e9-939e-a081a9da6ebd.png)

**Comment by jebej** [comment]
One more thing: all of the code snippets now appear red, which makes it hard to differentiate which are links and which aren't:

Now:
![image](https://user-images.githubusercontent.com/11141558/63289182-80957800-c28c-11e9-836e-600a670adb2a.png)


Compared to:
![image](https://user-images.githubusercontent.com/11141558/63289205-8e4afd80-c28c-11e9-97f6-2bd93e5d7d71.png)

**Comment by Datseris** [comment]
Hi, thanks for your work. From my perspective, here are comments:

* Reduce saturation of the admonition blocks
* I would love it if changing the fonts used for both texts and code would be straightforward: https://github.com/JuliaDocs/Documenter.jl/issues/973

**Comment by mileslucas** [comment]
I have a simple comment: the font in the menu bars for the current pages headers does not contrast well enough with either the light or dark themes, in my opinion.

**Comment by christopher-dG** [comment]
Here is my first impression: string interpolation with parentheses is unreadable with the dark theme. Other than that, love it so far! 

![2019-10-16-223641_548x144_scrot](https://user-images.githubusercontent.com/17228795/66934928-719d2d00-f065-11e9-97e0-96c6b4240686.png)
