### ISSUE TITLE
What are supported markdown file extensions?

### ISSUE THREAD

**Issue by johnnychen94** [JuliaDocs/Documenter.jl#1102]
Does Documenter limit itself to a set of extension convention, e.g., `.md, .markdown`, or simply treats every file passed to `makedocs` as a markdown file?

**Comment by mortenpi** [comment]
We assume that the Markdown files end with `.md` generally.

Although you might be able to pass non-`.md` files to the `pages` variable. But I think we still end up copying these over to `build/` (which we wouldn't do with `.md` files), since we copy everything that does not have `.md` at the end.
