### ISSUE TITLE
LoadError: failed process: Process(`git fetch upstream`, ProcessExited(128)) [128]

### ISSUE THREAD

**Issue by chenwilliam77** [JuliaDocs/Documenter.jl#1106]
When I try to run docs/make.jl for my package locally (before committing to the remote), I get the following error.

```julia
Initialized empty Git repository in /tmp/59671.1.all.q/tmpRgoiq1/.git/
Bad owner or permissions on /home/wyc1/.ssh/config
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
┌ Error: Git failed to fetch git@github.com:FRBNY-DSGE/DSGE.jl.git
│ This can be caused by a DOCUMENTER_KEY variable that is not correctly set up.
│ Make sure that the environment variable is properly set up as a Base64-encoded string
│ of the SSH private key. You may need to re-generate the keys with DocumenterTools.
└ @ Documenter ~/.julia/packages/Documenter/Eayks/src/Documenter.jl:660
ERROR: LoadError: failed process: Process(`git fetch upstream`, ProcessExited(128)) [128]
```

This error is triggered after Travis attempts to deploy my documentation. I'm almost certain I've correctly followed [Hosting Documentation](https://juliadocs.github.io/Documenter.jl/v0.22/man/hosting/) for Documenter.jl because I've gone through the documentation and redone the required steps at least three times (e.g. generating new ssh keys). 

I've also tried to follow the actual code in the Documenter.jl file (lines 649-658 for v0.22.6). I successfully fetched from the remote in a temporary folder, so I'm not sure why it doesn't work when I run make.jl.

Is the issue potentially with the .ssh/config file? Currently, I don't have a .ssh/config file.

FYI, the markdown files in docs/src all look fine; it's just deployment that seems to not work.

**Comment by mortenpi** [comment]
`deploydocs` should immediately bail if you're running locally. Are you setting up the `TRAVIS_*` variables by hand?

**Comment by chenwilliam77** [comment]
I am indeed setting them up by hand. I thought you wanted deploydocs to run when running locally so I added them. If I can get everything to run up to deploydocs locally, then does that mean I should be good to commit to the remote, correct? If so, you can close this issue.

**Comment by mortenpi** [comment]
Normally you only do deployment on Travis. It is possible to make `deploydocs` run locally, but it's not really supported (#1087). Usually, you do not need to deploy locally though -- if the `repo` argument in `make.jl` and `DOCUMENTER_KEY` on Travis are set up properly, the deployment on Travis should just work.
