### ISSUE TITLE
Return page sub-sections in search results?

### ISSUE THREAD

**Issue by ianshmean** [JuliaDocs/Documenter.jl#1110]
As an example, if you search for "macros" in the current main docs, the Macros section of the docs isn't in the search results, because it's a sub-section of the Metaprogramming docs page.

"macros" search results: https://docs.julialang.org/en/v1/search/?q=macros
What I was hoping to find: https://docs.julialang.org/en/v1/manual/metaprogramming/index.html#man-macros-1

Having page sections in search results seems like it would be helpful

**Comment by ianshmean** [comment]
I just noticed that the section result is there, just way down the list.
Perhaps the ranking should be higher for sections that match the string exactly?

**Comment by mortenpi** [comment]
Dup of #631?

**Comment by ianshmean** [comment]
Indeed!
