### ISSUE TITLE
code fence in footnote renders as flow

### ISSUE THREAD

**Issue by tpapp** [JuliaDocs/Documenter.jl#1120]
A footnote that looks like
````markdown
[^5]: An example of how you can benchmark a log density with gradient `∇P`, obtained as described below:
    ```julia
    using BenchmarkTools, LogDensityProblems
    x = randn(LogDensityProblems.dimension(∇P))
    @benchmark LogDensityProblems.logdensity_and_gradient($∇P, $x)
    ```
````
in [the DynamicHMC docs (source)](https://github.com/tpapp/DynamicHMC.jl/blame/b202d456d8ca4b346b7e759b652a08d4279f940f/docs/src/worked_example.md#L15) renders as [flowed text](https://tamaspapp.eu/DynamicHMC.jl/latest/worked_example/#footnote-5) :

![Screenshot_2019-08-29_14-49-21](https://user-images.githubusercontent.com/84122/63941691-674eb180-ca6c-11e9-826a-9ae9475018e8.png)

using `Documenter#master` (specifically 84b56abd).

**Comment by fredrikekre** [comment]
What if you align it with the `A` as
````
[^5]: An example of how you can benchmark a log density with gradient `∇P`, obtained as described below:
      ```julia
      using BenchmarkTools, LogDensityProblems
      x = randn(LogDensityProblems.dimension(∇P))
      @benchmark LogDensityProblems.logdensity_and_gradient($∇P, $x)
      ```
````
?

**Comment by tpapp** [comment]
It's the same output, this does not fix the issue.

In both cases, the HTML is
```html
<code>julia   using BenchmarkTools, LogDensityProblems   x = randn(LogDensityProblems.dimension(∇P))   @benchmark LogDensityProblems.logdensity_and_gradient($∇P, $x)</code>
```
(note absence of newlines, but preserved leading spaces) whereas for code block in the main text it is
```html
<pre><code class="language-julia">
```

**Comment by mortenpi** [comment]
While I, as a style choice, would also align it slightly differently, the Markdown appears to parse as you expect. So this indeed looks like a HTML rendering bug.
