### ISSUE TITLE
Documenter creates version symlink to master

### ISSUE THREAD

**Issue by ppalmes** [JuliaDocs/Documenter.jl#1124]
is there a way to disable symlink creation to my master branch?
zeptodoctor creates the following symlink in my master branch:
stable -> latest version number
v2.3 -> latest version number
v2.0 -> latest vesion number

https://github.com/IBM/TSML.jl/tree/master

**Comment by fredrikekre** [comment]
It looks like you pushed them there yourself? Documenter pushes to the `gh-pages` branch by default.

**Comment by ppalmes** [comment]
https://github.com/IBM/TSML.jl/commit/982d948a8d016ff5b9629d2dab833b377585272b#diff-1b267619c4812cc46ee281747884ca50

i'm at a loss because i don't create symlinks. it is coming from github not from my computer.

**Comment by ppalmes** [comment]
i see the same symlinks in the gh-pages branch which should be there. i wonder why master is getting the same symlinks

**Comment by ppalmes** [comment]
version.js and dev/siteinfo.js also

**Comment by ppalmes** [comment]
my .travis looks like this:

language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
env:
  - JULIA_NUM_THREADS=8
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - if [[ $TRAVIS_OS_NAME = linux ]]; then
      julia --project=coverage/ -e 'using Pkg; Pkg.instantiate();
          using Coverage; Codecov.submit(Codecov.process_folder())';
    fi

jobs:
  include:
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      name: "HTML"
      after_success: skip
    - script:
        - julia --project=docs/pdf/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/pdf/ docs/pdf/make.jl
      name: "PDF"
      after_success: skip
      services: docker
© 2019 GitHub, Inc.

**Comment by ppalmes** [comment]
never mind. i'll investigate more and will reopen the issue if it's still happening.
