### ISSUE TITLE
Add feature to make deploying preview docs for a PR easier

### ISSUE THREAD

**Issue by oxinabox** [JuliaDocs/Documenter.jl#1131]
@fredrikekre has code that works
https://github.com/fredrikekre/Literate.jl/pull/75

But it is pretty evil,
It would be nicer if we could just say  call `deploydocs`
with the right arguments.

**Comment by oxinabox** [comment]
Other issues:
 - Old packages  link to `latest` in readme, but this has been fixed in new version of PkgTemplates https://github.com/invenia/PkgTemplates.jl/pull/52
 - PR doesn't show up in version selector from stable/dev versions because the current hack doesn't  update the `versions.jl`, though I might argue that is actually a feature.

https://github.com/JuliaDiff/ChainRules.jl/pull/105#issuecomment-533511950

**Comment by oxinabox** [comment]
It would be also good if we could have a way to have a comment automatically go back to the PR saying _"Your docs have built, new URL is at"_

**Comment by fredrikekre** [comment]
> PR doesn't show up in version selector from stable/dev versions because the current hack doesn't update the versions.jl, though I might argue that is actually a feature.

Yea, hence the `delete_method` for that, didn't want "real" docs to be affected in any way.

**Comment by oxinabox** [comment]
seems legit, if we has it as a built in option, we might want to make it a kwarg:
"Include preview in main listing" or something?

**Comment by fredrikekre** [comment]
`push_preview` to `deploydocs` now implemented. Pushes to `.../previews/PR$(NUM)`.
