### ISSUE TITLE
is it possible to have custom banner on top?

### ISSUE THREAD

**Issue by Roger-luo** [JuliaDocs/Documenter.jl#1132]
I'm wondering if Documenter provides any API for doing this? I didn't find any in the doc. cuz it is pretty useful for separating tutorials docs etc. if a (large) project contains several small packages. (so users can click back and forth), e.g pytorch's official website has a banner on top: https://pytorch.org/docs/stable/index.html

**Comment by mortenpi** [comment]
Do you mean the navigation bar on top? Either way though, the short answer is no (or, at least, not at the moment).

**Comment by Roger-luo** [comment]
I'm wondering if we could export markdown files (all the things like `@example` are evaluated by Documenter) so I could include it in a jekyll project, and render it with my own style?

**Comment by mortenpi** [comment]
I'd say, just to make a decision here, I don't think we'll make any significant changes like that to the HTML front end in the near future. I don't think we could shoehorn a top bar like that into the front end without re-designing it.

What you suggested would need to be a plugin package that would define a new output format, outputting Jekyll-friendly Markdown. For what it's worth, it's somewhere on the roadmap to move `MarkdownWriter` out [into a separate package](https://github.com/JuliaDocs/DocumenterMarkdown.jl), which could then be forked.

**Comment by Roger-luo** [comment]
Thanks! I see, I tried a bit yesterday it seems that this would just work. But I'm wondering if I should generate the sidebar myself as well... I think all I need for the navbar on top is a link to our new homepage (yaoquantum.org) and tutoiral page (since I don't want to compile the weave files everytime I submit a PR and modify the main repo).

**Comment by Roger-luo** [comment]
I think I find a way to shoehorn a custom top bar in by just add an extra pass to `render_html`, do you want me to make a PR on this?

![image](https://user-images.githubusercontent.com/8445510/70289876-320cda80-17a4-11ea-99e9-6dff7b10196d.png)

**Comment by Roger-luo** [comment]
I think we could allow to add a special asset which is a file named `nav.html` as user's asset, and just include it through `render_html` then this will just work.

All other dependencies of the custom `nav` can be just added as normal custom style sheet and custom js files.

**Comment by mortenpi** [comment]
Including arbitrary HTML doesn't really work well with the way HTMLWriter is built. Also, having a feature for just adding stuff in this one particular location is too specific I feel.

However, what we could experiment with is a way to specify a callback that would, in [`render_html`](https://github.com/JuliaDocs/Documenter.jl/blob/9a7af14adfd8e8da7bf12bcaca254fed210a7ed8/src/Writers/HTMLWriter.jl#L682-L694), do an arbitrary transform on the Documenter-generated `DOM.HTMLDocument` object (which is a tree-type data structure containing the whole HTML tree). What do you think?

> I don't know why adding a boostrap deps in <head> cause the doc-navbar's background become gray...

I guess there is also CSS involved? I think it's just that the Boostrap CSS classes and Bulma ones clash.

**Comment by Roger-luo** [comment]
Yes, I agree, it is better to support more general API to allow customized HTML components. I'm wondering if it is possible to make this function read from a html template function defined with the utils in `DOM`? I think we will also need something related in the Chinese julialang doc: https://github.com/JuliaCN/JuliaZH.jl/tree/master/contrib since currently we do this with some overrides on the existing APIs.

**Comment by mortenpi** [comment]
I'll close this, since I am not sure if there is anything directly actionable here. For top navigation, we do have [MultiDocumenter](https://github.com/JuliaComputing/MultiDocumenter.jl) and there is also work in progress in #2177. The original Yao use case would call something like the former I think (but with custom top bar entries?).
