### ISSUE TITLE
Option to automatically `noindex` old docs pages to prevent old docs in google

### ISSUE THREAD

**Issue by ianshmean** [JuliaDocs/Documenter.jl#1133]
It might be nice to automatically tell google etc. to remove old docs pages, as has been done [manually in base docs](https://github.com/JuliaLang/docs.julialang.org/pull/11). Anything older than current version perhaps?

It would involve adding `<meta name="robots" content="noindex"/>` to the html header (typically after the viewport `meta`)

**Comment by mortenpi** [comment]
This shouldn't be necessary if you have the canonical URL configured correctly (which is the case for Base docs)?

**Comment by ianshmean** [comment]
That is true! Perhaps on top of canonical links set up, auto-generated sitemaps (#1135) might help?
