### ISSUE TITLE
Documentation discrepancy

### ISSUE THREAD

**Issue by charleskawczynski** [JuliaDocs/Documenter.jl#1134]
When reading through the [Adding Private Keys to Travis](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/walkthrough/#Adding-the-Private-Key-to-Travis-1) walkthrough, I ran into `ERROR: UndefVarError: base64encode not defined`. I went to submit a PR to update the documentation to prepend `julia> using Base64`, but found that it's [already there](https://github.com/JuliaDocs/Documenter.jl/blob/master/docs/src/man/hosting/walkthrough.md#if-you-have-ssh-keygen-installed). I'm not sure why there's a discrepancy, and I don't know off-hand how to track this down, but I wanted to record it here.

**Comment by mortenpi** [comment]
That change hasn't landed in a release yet. It is fixed on the master docs: https://juliadocs.github.io/Documenter.jl/dev/man/hosting/walkthrough/#Adding-the-Private-Key-to-Travis-1
