### ISSUE TITLE
Rendering HTML Ouput from @example block

### ISSUE THREAD

**Issue by kiranshila** [JuliaDocs/Documenter.jl#1149]
I have a block of code that returns an `HTML{String}` object, but I can't seem to find a way to capture this outputted HTML into a `@raw html` context to render in the final document.

The reasoning for this is to include the fully interactive PlotlyJS graphs in my documentation. If there is another way to do this, I'd love to hear it.

Thanks!

**Comment by fredrikekre** [comment]
Can you include an example?

**Comment by kiranshila** [comment]
Ah, just figured it out. I need to include the framework somewhere as the exported html doesn't include a link to the plotly.js file. Is there a simple way to add frameworks to the entire document? If not, I can keep manually add `<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>`.

**Comment by mortenpi** [comment]
You could drop a copy of the `.js` file into `docs/src` and use `HTML`'s assets keyword to include it.

**Comment by baggepinnen** [comment]
I would be interested in learning how to display a html file generated by Plotly. The naive
```
savefig("fig.html"); nothing # hide
```
followed by
```
![](fig.html)
```
does not work for html. Could I somhow make use of the `@raw` block to display the figure?
