### ISSUE TITLE
CRLF line endings in code block lead to errors in rendering

### ISSUE THREAD

**Issue by davidanthoff** [JuliaDocs/Documenter.jl#115]
I have a markdown file with various code blocks in it.

When I save it with LF line endings, everything looks great. If I save the same file with CRLF line endings and make the docs, all the code blocks are no longer recognized as such. This is on Windows.

**Comment by MichaelHatherly** [comment]
Thanks for reporting this.

Is this specific to `Documenter`, or does it also happen if you just call `Markdown.parse_file("file.md")`?

Does it happen for both external `.md` files and docstrings in `.jl` source files or just one of those?

Which Julia version are you using?

**Comment by MichaelHatherly** [comment]
(Downgrading to "medium" since I don't have Windows and so can't test this out myself.)

**Comment by MichaelHatherly** [comment]
Upstream issue, fixed in Julia `0.5`. See #143 for details.
