### ISSUE TITLE
Issue with Enum

### ISSUE THREAD

**Issue by Nosferican** [JuliaDocs/Documenter.jl#1157]
I have identified two issues with the handling of `Enum` types...

Define an enum
```
"""
    MyFruits
These are all the fruits I can eat.
"""
@enum MyFruits begin
    banana = -1
    apple = 0
    orange = 1
end
```
The `Filter = obj -> isa(obj, Type)` or `Filter = obj -> isa(obj, DataType)` doesn't seem to pick it up.
The `source` link in the documentation links to https://github.com/JuliaLang/julia/blob/b5ccd0f2ef29f86e1c95f09e148793e9d3bf15ea/base/#L0-L7

**Comment by mortenpi** [comment]
For the source links, the MWE is:

```julia-repl
julia> d = Docs.meta(Main)[Docs.Binding(Main,:MyFruits)].docs[Union{}];

julia> Documenter.Utilities.url("", "", d)
"https://github.com/JuliaLang/julia/blob/c6da87ff4bc7a855e217856757ad3413cf6d1f79/base/#L0-L3"
```

and the issue comes from the `!isabspath` [here in `Utilities.url`](https://github.com/JuliaDocs/Documenter.jl/blob/cc7461fa823e8626fbe6379e597f8461886f6896/src/Utilities/Utilities.jl#L403) returning `true` for enum docstrings, since they don't store proper location metadata:

```
julia> Docs.meta(Main)[Docs.Binding(Main,:MyFruits)].docs[Union{}].data
Dict{Symbol,Any} with 5 entries:
  :typesig    => Union{}
  :module     => Main
  :linenumber => 0
  :binding    => MyFruits
  :path       => ""
```

**Comment by mortenpi** [comment]
The Documenter-side fix would probably be just to add `isempty(file) && return nothing` at the beginning of `url` -- if we do not know anything about the file, we can't do anything useful about the URL anyway.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/issues/33519#issuecomment-1030631156
