### ISSUE TITLE
Confusion regarding the docs Project.toml

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaDocs/Documenter.jl#1164]
I am writing documentation in which I want to create plots and animated gifs. Therefore, I have added packages for this purpose to the `docs/Project.toml`. I'm not sure what environment should be active when I run `julia make.jl`, though, and how this affects the Documenter build.

I've been having trouble with my PyPlot dependency, because depending on from which environment I call `make.jl` there are complaints that matplotlib is missing. With my own library I get Cairo.jl library issues when running `make.jl`, which I don't see if I just do `using Layered` (which is my library that I want to use in the Documenter process) in my normal environment. At this point I'm just confused what should go where..

I have:
Base 1.3 environment
Module environment
Module/docs environment

What should be active when I call `make.jl`? And the whole thing also needs to work on Travis CI, so I need to be sure that I run my local test builds in a way that they also work on the Travis servers.

I have added `- julia --project=docs/ -e 'using Pkg; ENV["PYTHON"]=""; Pkg.build("PyCall");'` to the Travis yaml file to fix PyPlot / matplotlib import issues on Travis which seems to work. But I'm maybe not doing this correctly, at least I don't need to do this step on my own machine.

Here's a link to the (currently working, without Layered.jl) docs folder of my module in case you can spot errors in the setup: https://github.com/jkrumbiegel/Animations.jl/tree/master/docs. For example, I'm not sure if I'm supposed to do `using PyPlot` in an `@eval` block like I'm doing there, or if that needs to go somewhere else, like `make.jl`.

Thank you for your help, I'll gladly clarify anything that's not clear from this description.

**Comment by fredrikekre** [comment]
> I'm not sure what environment should be active when I run julia make.jl, though, and how this affects the Documenter build.

The docs environment. Your current https://github.com/jkrumbiegel/Animations.jl/blob/master/.travis.yml looks okay. What is the failure?
