### ISSUE TITLE
Mixed-up printing from `@example` blocks

### ISSUE THREAD

**Issue by ericphanson** [JuliaDocs/Documenter.jl#1174]
I'm seeing some strange extra printing in an `@example` block: in https://www.juliaopt.org/Convex.jl/stable/quick_tutorial/, we only solve the problem once, and with SCS not ECOS. But somehow it's printing a bunch of solves with ECOS. 

Most of the examples are called with `verbose=0` meaning they don't print during the solve portion. But another place where we do print also has mixed-up output: https://www.juliaopt.org/Convex.jl/stable/examples/supplemental_material/paper_examples/ should have one printed block per solve, and we only use ECOS in that example, but there's output from SCS too. It looks like the printed output from `paper_examples` and `quick_tutorial` got mixed up between them.

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing as stale, and because I think I know the underlying problem: SCS was not flushing the io buffer after solve. It has since been fixed.
