### ISSUE TITLE
DocString code fails docTest - function not defined

### ISSUE THREAD

**Issue by holder66** [JuliaDocs/Documenter.jl#118]
https://github.com/holder66/Mortgage.jl
I'm encountering a problem when putting a block of Julia code in a docString just above a function definition. The Julia code is copied from the REPL. When I execute make.jl, docTests fails. Also, docs deployment is always skipped, even when doctests runs successfully. I'm sure I'm doing something wrong!
Documenter: rendering document.
 !! Test error in the following code block:

        julia> mortgage(principal=54000, rate=2.125, amortization=20, frequency="w", compounding="c", startdate=Date(2016,6,29), term="a") 
        
        (54000,2.125,20,"w","c",2016-06-29,"until paid off",63.50799378958494,2016-07-06,1044,54000.00000000001,12229.766528153477,66229.76652815354,0,54.43699940601391,2036-06-25,Any[1,2016-07-06,41.61279659644556,21.89519719313937,41.61279659644556,21.89519719313937,63.50799378958494,53958.38720340355,2,2016-07-13  …  66175.32952874753,54.41493596613927,1043,2036-06-25,63.485930349710294,0.022063439874642057,54009.070994383575,12229.766528153477,66238.83752253711,-9.0709

    in expression:

        mortgage(principal=54000, rate=2.125, amortization=20, frequency="w", compounding="c", startdate=Date(2016,6,29), term="a")

    expected:

        
        (54000,2.125,20,"w","c",2016-06-29,"until paid off",63.50799378958494,2016-07-06,1044,54000.00000000001,12229.766528153477,66229.76652815354,0,54.43699940601391,2036-06-25,Any[1,2016-07-06,41.61279659644556,21.89519719313937,41.61279659644556,21.89519719313937,63.50799378958494,53958.38720340355,2,2016-07-13  …  66175.32952874753,54.41493596613927,1043,2036-06-25,63.485930349710294,0.022063439874642057,54009.070994383575,12229.766528153477,66238.83752253711,-9.0709

    returned:

        ERROR: UndefVarError: mortgage not defined
         in eval at /Users/henryolders/.julia/v0.4/Documenter/src/DocChecks.jl:4
         in anonymous at /Users/henryolders/.julia/v0.4/Documenter/src/DocChecks.jl:146
         in withoutput at /Users/henryolders/.julia/v0.4/Documenter/src/Utilities/Utilities.jl:454
         in eval_repl at /Users/henryolders/.julia/v0.4/Documenter/src/DocChecks.jl:145
         in doctest at /Users/henryolders/.julia/v0.4/Documenter/src/DocChecks.jl:116
         in anonymous at /Users/henryolders/.julia/v0.4/Documenter/src/DocChecks.jl:103
         in walk at /Users/henryolders/.julia/v0.4/Documenter/src/Walkers.jl:36
         in walk at /Users/henryolders/.julia/v0.4/Documenter/src/Walkers.jl:29
         in walk at /Users/henryolders/.julia/v0.4/Documenter/src/Walkers.jl:36
         in walk at /Users/henryolders/.julia/v0.4/Documenter/src/Walkers.jl:29
         in walk at /Users/henryolders/.julia/v0.4/Documenter/src/Walkers.jl:36
         in walk at /Users/henryolders/.julia/v0.4/Documenter/src/Walkers.jl:47
         in doctest at /Users/henryolders/.julia/v0.4/Documenter/src/DocChecks.jl:102
         in runner at /Users/henryolders/.julia/v0.4/Documenter/src/Builder.jl:136
         in dispatch at /Users/henryolders/.julia/v0.4/Documenter/src/Selectors.jl:164
         in anonymous at /Users/henryolders/.julia/v0.4/Documenter/src/Documenter.jl:136
         in cd at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
         in makedocs at /Users/henryolders/.julia/v0.4/Documenter/src/Documenter.jl:135
         in include at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
         in include_from_node1 at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
         in process_options at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
         in _start at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib

Documenter: skipping docs deployment.

**Comment by MichaelHatherly** [comment]
> When I execute make.jl, docTests fails

Doctesting doesn't implicitly import anything into the sandboxed module that gets created for each code block that is tested &mdash; hence the `UndefVarError` you're seeing. You'll need to add a `@meta` block above the `@docs` block in `src/usage.md` with the needed imports, like so:


    #Mortgage.jl Documentation

    ```@meta
    DocTestSetup = quote
        using Mortgage
    end
    ```
 
    ```@docs
    mortgage()
    ```

>  docs deployment is always skipped, even when doctests runs successfully.

Deployment will only be triggered on Travis built bots, never locally. Scanning through the build logs and `.travis.yml` files here's a few things I noticed that will probably get it building and deploying automatically.

- The `openssl` line in `.travis.yml` isn't needed, that's done by `deploydocs` behind the scenes for you.
- Travis is currently failing because of the tab character on the `openssl` line as well.
- You'll need either the `GITHUB_API_KEY` or the `.documenter.enc` not both, so you'll be able to remove the `GITHUB_API_KEY` environment variable from your Travis settings page.
- Have you added the private key generated by `Travis.genkeys("Mortgage")` to your GitHub repo?

That's probably all you need to get it working, hope it helps. Do let me know if any of that doesn't work.

**Comment by MichaelHatherly** [comment]
Also might need `deploydocs` to specify which version of Julia to use for deployment since by default if tries `nightly`. So if you'd rather deploy using `release` (0.4) you should use

```julia
deploydocs(
    deps  = Deps.pip("mkdocs", "python-markdown-math"),
    repo  = "github.com/holder66/Mortgage.jl.git",
    julia = "release",
)
```

instead in your `docs/make.jl`.

**Comment by MichaelHatherly** [comment]
I assume from the recent commits in your package that your issues are solved now @holder66?
