### ISSUE TITLE
_ in ` breaks admonition headers for PDF output

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#1185]
E.g.
```
!!! warning "`GITHUB_TOKEN`"
    Hello there.
```
becomes
```
\begin{quote}
\textbf{`GITHUB_TOKEN`}
Hello there.
\end{quote}
```

**Comment by mortenpi** [comment]
I think we need to put `latexesc` around `md.title` here: https://github.com/JuliaDocs/Documenter.jl/blob/40c0f5335ada263157c5305bd85ca695a0896509/src/Writers/LaTeXWriter.jl#L487

**Comment by odow** [comment]
Closed by https://github.com/JuliaDocs/Documenter.jl/pull/1299
