### ISSUE TITLE
Support image file formats like .png as asset classes

### ISSUE THREAD

**Issue by rofinn** [JuliaDocs/Documenter.jl#1193]
As of 0.24.0 we get the following error
```
LoadError: Unrecognised asset class unknown for `assets/logo.png`
```

**Comment by fredrikekre** [comment]
You don't need to include the logo in assets, it is just for css and javascript; https://github.com/JuliaDocs/Documenter.jl/blob/0aa0520e67d0cba2e1664a5cb88dfe5e3d49f0ee/src/Writers/HTMLWriter.jl#L81

**Comment by rofinn** [comment]
Was this always the case or did this change?

**Comment by mortenpi** [comment]
Always the case.

**Comment by rofinn** [comment]
Okay, thanks.
