### ISSUE TITLE
`checkdocs=:exports` report non-missing docstring as missing

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaDocs/Documenter.jl#1204]
(Firstly, Documenter is excellent. Thanks a lot!)

I have `makedocs` set to `checkdocs=:exports` but it seems to _stochastically_ gives false negatives: it gives the warning "docstring potentially missing " when is not in fact missing.

It does say "potentially" in the warning, to be fair... But I was hoping to use this in combination with `strict=true` to guarantee all exports are always included in the docs. Unfortunately, right now this means the CI pipeline fails sporadically even when all exported names are documented.

**Comment by mortenpi** [comment]
I wonder if this was the same as #1857. However, this issue is old and doesn't have an MWE, so I'll go ahead and close it.
