### ISSUE TITLE
texinfo/info backend

### ISSUE THREAD

**Issue by non-Jedi** [JuliaDocs/Documenter.jl#1211]
For those of us using emacs, it would be really nice to have a texinfo backend to be able to browse docs directly from emacs (the texinfo->info pipeline would look similar to the latex->pdf pipeline). I'm creating this issue partially as a reminder to myself to work on this later when I have time. It's a <del>much</del> slightly simpler format than latex I believe, so it might be relatively simple.

https://www.gnu.org/software/texinfo/manual/texinfo/html_node/

The second part necessary to enable my desired use-case would be a way of forcing packages to build their documentation in my desired format upon install. Is this currently possible, or will I have to manually go and build all docs I want after I have the texinfo backend?

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing as stale. Adding a new backend is a lot of work, and it also introduces a large maintenance burden.

> Is this currently possible, or will I have to manually go and build all docs I want after I have the texinfo backend?

It's not possible. A key part of the package install is that the installed packages are immutable, so we don't want to go and generate a lot of new files on every install.

**Comment by non-Jedi** [comment]
Thanks @odow. I understand the closure. And thanks for answering my question while you were at it!

As you're triaging in the future, you might want to edit the italicized bit at the top of your reply. As far as I can tell, only accounts with privileged access can re-open an issue on github.

**Comment by odow** [comment]
> As far as I can tell, only accounts with privileged access can re-open an issue on github.

Oh, I didn't know that :smile:
