### ISSUE TITLE
Deploy Docs Broken for GitHub Actions when using a Container

### ISSUE THREAD

**Issue by Nosferican** [JuliaDocs/Documenter.jl#1215]
[Example](https://github.com/Nosferican/DocumenterGHActionContainer.jl)... When using a container,
```
git fetch upstream
```
in the current workflow fails. See workflow CI log for master and the PR.

**Comment by fredrikekre** [comment]
We have https://github.com/JuliaDocs/Documenter.jl/blob/9a7af14adfd8e8da7bf12bcaca254fed210a7ed8/src/Documenter.jl#L579 so this should not happen IIUC. I'm guessing the file `joinpath(homedir(), ".ssh", "config")` that Documenter creates is not beeing used.
