### ISSUE TITLE
align no longer works on newest Documenter

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#1217]
Newest: https://docs.juliadiffeq.org/latest/tutorials/dde_example/

Previous: https://docs.juliadiffeq.org/v6.8/tutorials/dde_example/

**Comment by mortenpi** [comment]
This is working as intended. The default math rendering engine is [KaTeX](https://katex.org/) now, which does not support all the same things as MathJax.

The recommendation would be to make the docs KaTeX-friendly. Or, alternatively, you can switch back to MathJax (see the CHANGELOG for 0.24.0), but KaTeX is a bit better for math-heavy docs (it renders faster).
