### ISSUE TITLE
@example with included files

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaDocs/Documenter.jl#1220]
I would really like to code my documentation examples in separate files and include them in the markdown documents after testing that they work. In Makie, generation of plots etc takes a while so I don't want to build all docs just to check if some example code works. So a separate file is nice to have. Is there a way to include a file in an example block and have its code displayed there?

**Comment by mortenpi** [comment]
No built-in way at the moment, but see #499 for a workaround. Closing this as a duplicate.
