### ISSUE TITLE
Changes to travis cause recommended travis file to fail

### ISSUE THREAD

**Issue by baggepinnen** [JuliaDocs/Documenter.jl#1228]
Previously (like a week ago?) following the instructions at
https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#Travis-CI-1
and just adding the suggested stuff to the travis file worked and the documentation was built. Now, if you click the tab "View config" here
https://travis-ci.org/baggepinnen/MonteCarloMeasurements.jl/builds/640388285/config
you see that the build config validation failed. It seems travis no longer accepts a file that specifies both "matrix" and "jobs". The same travis file did work and pass the build config validation a couple of days ago though so it seems it's a change in travis' side. Changing the travis file to this solved the problem
https://travis-ci.org/baggepinnen/MonteCarloMeasurements.jl/builds/640444914/config

**Comment by fredrikekre** [comment]
Yea, someone else mentioned this too, but when I looked into it (more than a month ago) I could not find anything about this in the Travis docs, and they still mention both `matrix` and `jobs`.

**Comment by fredrikekre** [comment]
Can you try just collapsing them?

**Comment by fredrikekre** [comment]
Putting everything under `matrix` and `jobs` under `matrix` (or `jobs` since Travis claims they are synonyms?).

**Comment by baggepinnen** [comment]
Yeah that's what I did to resolve the issue. Some recent threads on travis forums seem related:
https://travis-ci.community/t/custom-stage-disables-default-stage-matrix-expansion/1884/7
https://travis-ci.community/t/jobs-matrix-include-are-ignored-if-env-is-customized/6313/4

**Comment by Balinus** [comment]
Had the same problem. Copy-pasted @baggepinnen `.travis.yml` file solved the issue. Documentation stage were not starting as expected.
