### ISSUE TITLE
How to redirect `@info` output to my console?

### ISSUE THREAD

**Issue by aborzunov** [JuliaDocs/Documenter.jl#1236]
I have an `@example` block in my `index.md` file that executes quite long.
````
```@example
@info "Plotting gif"
make_gif()
```
````

I want to redirect `@info` output to my console to see everything is good.

**Comment by fredrikekre** [comment]
You can't do this; Documenter captures everything when running that code. Is this a problem with e.g. Travis timeouts?

**Comment by aborzunov** [comment]
> Is this a problem with e.g. Travis timeouts?

Yes.

I have several gifs that changes over time and i want it to be in my documentation. I can generate them locally and place in `assets` folder inside my `docs/src`, upload them with git-lfs time to time and insert `[](../assets/example.gif)` in my docs, but this seems not a good solution.

**Comment by johnnychen94** [comment]
If you're making image gifs, you could use `ImageMagick.save("example.gif", img; fps=2)` where `img` is a 3D image array.

**Comment by fredrikekre** [comment]
> > Is this a problem with e.g. Travis timeouts?
> 
> Yes.

Try setting `JULIA_DEBUG="Documenter"` as an environment variable, that should result in some more output I think.

**Comment by KristofferC** [comment]
You can also use the `travis_wait` command (https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received).
