### ISSUE TITLE
Custom div blocks / admonitions

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#124]
The general idea is to have (extended Markdown) syntax available to wrap Markdown in custom `<div>`-type blocks. This is to support "Tip", "Note", "Warning" etc. type blocks which are a bit out of the normal flow of the document and require special formatting.

Borrowing from Python's Markdown docs, something like this
```markdown
!!! note
    You should note that the title will be automatically capitalized.
```
would get rendered as
```html
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>You should note that the title will be automatically capitalized.</p>
</div>
```
and additional styling could then be defined in the CSS to make the section stand out.

There is precedent for this in Markdown in the form of [rST-style admonitions](https://pythonhosted.org/Markdown/extensions/admonition.html). The rST admonitions are also used in [in the base docs](http://docs.julialang.org/en/latest/manual/mathematical-operations/#updating-operators), meaning this should also be relevant for julialang/julia#12573.

Potential syntax could be either (a) Python's admonitions syntax, or (b) provide another ```` ```@something ```` block in Documenter. (b) would be relatively straightforward to implement in-house, but adopting existing syntax, I feel, would be preferred (but would require extending the Markdown parser in `Base`).

**Comment by MichaelHatherly** [comment]
Already implemented in https://github.com/JuliaLang/julia/pull/17272 yesterday. Was this opened in response to that PR or is it just coincidence?

**Comment by mortenpi** [comment]
Complete coincidence actually, I just happened to be thinking about custom blocks. I commend the speed of the support - a fix is implemented 15 hours before submitting the issue. :laughing:

I guess we can leave this open until whatever adjustments we need to do to Documenter are implemented.
