### ISSUE TITLE
Latex align environment not working

### ISSUE THREAD

**Issue by lindnemi** [JuliaDocs/Documenter.jl#1241]

**Comment by lindnemi** [comment]
I want to do this:

```math
\begin{align}
\varepsilon \dot u & = & u - u^3 - v \\
\dot v & = &  u + a
\end{align}
```

Unfortunately I can't get Documenter to render multiline equations. Is it possible?

**Comment by mortenpi** [comment]
I think you need to use the [`aligned` environment](https://katex.org/docs/supported.html#environments) (if you're using the default KaTeX math engine).

**Comment by lindnemi** [comment]
Works for me. Thank you!
