### ISSUE TITLE
doctest problem with newline characters in strings

### ISSUE THREAD

**Issue by ThomasBreuer** [JuliaDocs/Documenter.jl#1243]
With version 0.24.5 of `Documenter.jl`, the following (valid) example fails when the function `doctest` processes it.
````
```jldoctest
julia> fun( str::String ) = str * "\n" * str;

julia> fun( "abc" )
"abc\nabc"

```
````
Julia claims that it gets the session
````
```jldoctest
julia> fun( str::String ) = str * "
" * str;

julia> fun( "abc" )
"abc
abc"
```
````
where already the function definition is not valid.
One can get around the explicit newline character in the input by writing
````
```jldoctest
julia> fun( str::String ) = str * string( Char( 10 ) ) * str;

julia> fun( "abc" )
"abc\nabc"

```
````
but then Julia claims that the output is wrong.

**Comment by KristofferC** [comment]
Are you putting this in a docstring? In that case, you need to escape the `\`.

**Comment by ThomasBreuer** [comment]
@KristofferC Thanks for the quick reply. Yes, this helps.
