### ISSUE TITLE
makedocs(..., pages = ["index.md", "other.md"])

### ISSUE THREAD

**Issue by kunov** [JuliaDocs/Documenter.jl#1252]
I cannot navigate between panes:

```julia
makedocs(..., pages = ["index.md", "other.md"])
```

my __src__:
src/"index.md"
src/"other.md"

after building:
build/index.html
build/other/index.html

So if I open `build/index.html` and navigate to Other, it brings me to a place in my c drive, and I manually have to select other/index.html.

![image](https://user-images.githubusercontent.com/22423493/76112010-619fce80-5faf-11ea-9dcf-1dfd02aeacc8.png)

Anybody has suggestions on how to make it work without going thorugh the intermediate step.

**Comment by fredrikekre** [comment]
See the third note here: https://juliadocs.github.io/Documenter.jl/stable/man/guide/#Building-an-Empty-Document-1

**Comment by johnnychen94** [comment]
I guess what you want is `pretty_urls`

```julia
format = Documenter.HTML(
        prettyurls = get(ENV, "CI", nothing) == "true"
    )
```
