### ISSUE TITLE
Image in title not displayed properly

### ISSUE THREAD

**Issue by AlexisRenchon** [JuliaDocs/Documenter.jl#1262]
Noticed in GeoMakie.jl documenter:

![image](https://user-images.githubusercontent.com/22160257/77001566-84779e80-6930-11ea-8061-b5c6a0767fe2.png)

however, it is displayed correctly in https://github.com/JuliaPlots/GeoMakie.jl/blob/master/README.md

see issue https://github.com/JuliaPlots/GeoMakie.jl/issues/37

**Comment by mortenpi** [comment]
Dup of #517. The Markdown parser in Base does not support HTML. In fact, the GitHub and Julia Markdown flavors are different, so generally `.md` files that are intended to be rendered on GitHub (e.g. `README.md`) do not render correctly in Documenter.
