### ISSUE TITLE
Cannot use `def_list` with Documenter

### ISSUE THREAD

**Issue by tribut** [JuliaDocs/Documenter.jl#127]
When a [definition list](https://pythonhosted.org/Markdown/extensions/definition_lists.html) is used inside a documentation block, such as
~~~~
Apple
:   Pomaceous fruit of plants of the genus Malus in
    the family Rosaceae.
Orange
:   The fruit of an evergreen tree of the genus Citrus.
~~~~
the file generated in `build/` has the newline before the `:` removed thus the definition list won't be generated even if `extra` or `def_list` is enabled in `mkdocs.yml`.

**Comment by MichaelHatherly** [comment]
Definition lists haven't been implemented in Julia's markdown parser yet &mdash; Documenter doesn't have it's own markdown parser, we just use the one from `Base`.

This is an upstream issue and not specific to Documenter. Please can you open this in https://github.com/JuliaLang/julia as a feature request, thanks.
