### ISSUE TITLE
"text/latex" output not rendered

### ISSUE THREAD

**Issue by NilsKintscher** [JuliaDocs/Documenter.jl#1278]
Example using SymPy:

in md:
```@example tutorial
using SymPy
(x) = SymPy.symbols("x", real=true)
[x 2x]
```
Output in compiled html:
[\left[ \begin{array}{rr}x&2 x\end{array}\right]]

Image of compiled html:
![1](https://user-images.githubusercontent.com/42682680/78341304-becf7580-7597-11ea-9db2-f32f4adf43be.png)

edit: I should mention that it works in jupyter notebooks. For example: https://nbviewer.jupyter.org/github/JuliaPy/SymPy.jl/blob/master/examples/tutorial.ipynb

**Comment by asinghvi17** [comment]
It looks like it's missing a backslash at the first and last square brackets...
