### ISSUE TITLE
possibility of preserving definitions @repl and @jldoctest

### ISSUE THREAD

**Issue by OkonSamuel** [JuliaDocs/Documenter.jl#1282]
Greetings. 
I wanted to find out if its possible to preserve definitions between `@repl` and `@jldoctest` blocks
For example
````markdown
```@repl ex1
a=1
b=2
c=a+b
```
````
some more text then
````markdown
```@jldoctest ex1
julia> c
3
```
````

This is a little over-simplistic of what am trying to do.

**Comment by mortenpi** [comment]
Dup of #652. The short answer is that it is not possible currently.
