### ISSUE TITLE
Automatic noindex tags on versioned docs?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#1302]
Versioned docs get out of date fast, so it would be nice if we could make sure they aren't indexed to push users towards the stable docs.

**Comment by ChrisRackauckas** [comment]
Note that with DiffEqDocs we already have canonical tags but still see v5.0 and v2.0 (from 3 years ago!) in the first page of the search, so https://github.com/JuliaDocs/Documenter.jl/issues/1133 isn't quite a fix.

**Comment by ChrisRackauckas** [comment]
@kanav99

**Comment by mortenpi** [comment]
Definitely worth looking into. Although one issue that comes to mind is that currently `stable/` is just a symlink to the docs of the latest version, i.e. they are literally the same HTML file. So you can't apply `noindex` to versioned docs without also applying it to `stable/`.

**Comment by fredrikekre** [comment]
According to https://www.searchcandy.uk/seo/can-you-use-javascript-gtm-to-add-a-noindex-meta-robots-tag/ it is valid to inject noindex with JavaScript, so that could easily be done.
