### ISSUE TITLE
Collapsed view menu button should be on the same side as the menu

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaDocs/Documenter.jl#1312]
I don't know if this is standard, but I saw it used in docs.juliaplots.org so reporting it here, presuming this package generated it.

<img width="899" alt="Annotation 2020-05-04 153736" src="https://user-images.githubusercontent.com/1438610/81006293-428db380-8e1d-11ea-94c2-32fb95883436.png">

Menu appears on the left but the menu button is on the top right. This just doesn't work well. Please keep them on the same side.

**Comment by mortenpi** [comment]
Yep, it comes from here. I'll leave this open for now if there are others who'd like to chime in, but personally I am inclined to leave it unchanged.

That button is aimed for mobile users, in which case it's not really that disconnected from the menu:

![Screenshot_20200505-123454](https://user-images.githubusercontent.com/147757/81026234-7cb68e00-8ecd-11ea-99b0-6ff8cb3d074c.png)

I prefer having it there, since then I can just use my thumb to tap it, without either having to reach over the screen or using the other hand. Looking around on some websites, it's also quite common to have the menu button on the right, so it should be a familiar UX for the users.

**Comment by BioTurboNick** [comment]
I can understand that motivation.

Do you have an example of a right-side menu button where the menu doesn't open adjacent to the button? Because it wasn't familiar to this user. The menu is on the left side, so that's where I looked for a way to activate it.

It's also going into a collapsed view when the window is occupying a bit less than half of my 3840x2160 (150% dpi) display. So if it's a mobile feature, perhaps it's activating at too wide a view. Traversing that distance with the mouse every time is annoying.

If unchanged, it would at least be really helpful if there was some nub with at the left edge to activate.

**Comment by xgdgsc** [comment]
It' s strange to serve the mobile users. For me I like tiling windows half of screen on 1080p screens. It just triggers the collapse which makes it very far from reach.

**Comment by yuyichao** [comment]
I hit this issue more than once last week. I also use left/right split screen on laptop. I know the table of contents is on the left and it always takes me a while to figure out how to access it.

**Comment by mortenpi** [comment]
> Do you have an example of a right-side menu button where the menu doesn't open adjacent to the button?

I concede that having the hamburger on the left is more common, also e.g. in the Android ecosystem. The Guardian does have it on the right. I also see examples where it _is_ positioned on the right, but the menu opens from the top, so it's not quite the same.

In any case, I do think now that it would be an improvement to have it on the left. So if someone wants to fiddle with the (S)CSS and provide a functioning mockup, I'd be happy to make the change.

> For me I like tiling windows half of screen on 1080p screens. It just triggers the collapse which makes it very far from reach.

Separate from the hamburger issue, we should probably adjust when exactly the sidebar collapses, to better serve this use case (related: #1324).

**Comment by inkydragon** [comment]
> if someone wants to fiddle with the (S)CSS and provide a functioning mockup, I'd be happy to make the change.

Is it enough to just move the hamburger button to the left?
![image](https://user-images.githubusercontent.com/5158738/226087253-836b169e-75ba-41df-b648-a08206e8d9b4.png)
ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside

https://github.com/JuliaDocs/Documenter.jl/blob/579d478b7f66bf83a83fcb1ca8c2aa75b21f450a/src/html/HTMLWriter.jl#L1221-L1225
