### ISSUE TITLE
May I copy some text from your documentation to use in the CompatHelper documentation?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaDocs/Documenter.jl#1319]
The Documenter.jl docs have the following security warning on [this page](https://juliadocs.github.io/Documenter.jl/dev/man/hosting/):
> Security warning
> 
> To reiterate: make sure that this key is hidden. In particular, in the Travis CI settings the "Display value in build log" option should be OFF for the variable, so that it does not get printed when the tests run. This base64-encoded string contains the unencrypted private key that gives full write access to your repository, so it must be kept safe. Also, make sure that you never expose this variable in your tests, nor merge any code that does. You can read more about Travis environment variables in Travis User Documentation.

Would you be okay with me copying this text and using it in the CompatHelper README, in the section on SSH deploy keys?

---

*(Documenter.jl and CompatHelper.jl are both MIT-licensed, so there is no license incompatibility.)*

**Comment by mortenpi** [comment]
While I did _not_ author that paragraph (it was [Michael, with contributions from Fredrik](https://github.com/JuliaDocs/Documenter.jl/blame/master/docs/src/man/hosting.md#L159-L167)), I'd say go ahead, as it's all MIT licensed. Also, in my opinion, this does not constitute a "substantial portion of the Software", so no need to worry about attribution.
