### ISSUE TITLE
Documentation build triggering 

### ISSUE THREAD

**Issue by andreasvarga** [JuliaDocs/Documenter.jl#1322]
Sorry for coming with this recurring issue again.

Since November 2019, I am not anymore able to update the documentation on the GH-sites of my package [MatrixEquations.jl](https://github.com/andreasvarga/MatrixEquations.jl). I would appreciate very much for a clear description of the steps I have to do, when moving from the older way to trigger documentation building to the new one, based on workflows. With the new workflow for TagBot, I was able to automatically update the release of the package and expected that (somehow miraculously) the documentation building will be triggered. I would like to mention that a similar problem I have with a new package [MatrixPencils.jl ](https://github.com/andreasvarga/MatrixPencils.jl), for which I can generate documentation only locally on my home computer.

**Comment by mortenpi** [comment]
Quickly glancing at MatrixEquations, I think the issue is that the documentation stage never runs on Travis because you have both `jobs:` and `matrix:` in `.travis.yml`. This used to work, but Travis made a breaking change at some point. See [the second note here](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Travis-CI-1) for more info.

**Comment by andreasvarga** [comment]
Many thanks for this important hint. After many trials, the documention of  [MatrixEquations.jl](https://github.com/andreasvarga/MatrixEquations.jl) has been updated as expected.  I hope to manage for the second package too (after registration).

**Comment by andreasvarga** [comment]
After the successful registration of the new package [MatrixPencils.jl](https://github.com/andreasvarga/MatrixPencils.jl), I was able to trigger the Documentation Stage, following the advise from  [mortenpi](https://github.com/mortenpi) to remove the `matrix:` section from` .travis.yml`. Although the documentation was apparently correctly built (see [here](https://travis-ci.com/github/andreasvarga/MatrixPencils.jl/jobs/335770277)), the deployment of documentation to the gh-pages was not performed. My GitHub Pages site is currently set to be built from the `/docs` folder in the master branch.  

I would appreciate any further hints how to finish the documentation stage.  Many thanks in advance for helping me.

**Comment by mortenpi** [comment]
> My GitHub Pages site is currently set to be built from the /docs folder in the master branch.

The source should be set to "`gh-pages` branch" instead -- GitHub only understands the HTML files that Documenter pushes to `gh-pages`.

**Comment by andreasvarga** [comment]
As you can check, I don't have this branch for the package [MatrixPencils.jl](https://github.com/andreasvarga/MatrixPencils.jl),  and therefore when selecting the source, this option is not available (for the other package  [MatrixEquations.jl](https://github.com/andreasvarga/MatrixEquations.jl) this option was available and was selected). It is possible to generate the `gh-pages` branch manually (to be later populated with the HTML documentation)?

**Comment by mortenpi** [comment]
Yes, in principle, you could just create an empty orphan branch. But I would actually recommend just letting the documentation from `master` deploy once (Documenter will create the branch for you). It looks like you're missing the `DOCUMENTER_KEY` variable: https://travis-ci.com/github/andreasvarga/MatrixPencils.jl/jobs/335770277#L257

**Comment by andreasvarga** [comment]
Many thanks. It works now.
