### ISSUE TITLE
Add MathJax3 Writer

### ISSUE THREAD

**Issue by simeonschaub** [JuliaDocs/Documenter.jl#1362]
It would be good to support MathJax 3 for LaTeX rendering as well. My main motivation behind this is that MathJax 3 officially supports the [physics package](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/physics/physics.pdf) as a plugin. From quick testing, it also seems to render a lot faster than MathJax 2 and really not much slower than KaTeX. It's probably better to add alongside MathJax 2, since the config formats are not compatible, so this would otherwise be breaking. I'd like to take a stab at this, if that's ok.

**Comment by mortenpi** [comment]
Yes, this would be good. Going forward, MathJax 3 should probably be the default MathJax version anyway. But we should give people the option to also keep using MathJax 2.

From the API perspective we have two options I guess:

* Make it possible to pass a version number to `MathJax` and then check for that in `mathengine!`.
* Create a new type, e.g. `MathJax3`. In this case, we could also deprecate `MathJax` in favor of `MathJax2`.

I think either should be a pretty straightforward addition to here: https://github.com/JuliaDocs/Documenter.jl/blob/f9f0b68ad11b68039b424557bf73511f55fed02f/src/Writers/HTMLWriter.jl#L369-L468

**Comment by simeonschaub** [comment]
I think since MathJax3 uses a completely different config format, I though option 2 made more sense. I would love to hear your initial feedback on my draft.
