### ISSUE TITLE
How to specify `doctestfilters` for the function `doctest`?

### ISSUE THREAD

**Issue by ThomasBreuer** [JuliaDocs/Documenter.jl#1364]
The function `makedocs` supports the keyword argument `doctestfilters`.
This is a documented feature, and it works nicely when one runs the doctests as one step of processing the documentation.
However, if one wants to run the doctests by calling `doctest` in a `@testset` then `doctestfilters` seem to be not supported; `doctest` calls `makedocs` but does not supply keyword arguments such as `doctestfilters`.

**Comment by mortenpi** [comment]
That sounds like an oversight on my part -- we should at least allow passing `doctestfilters` as an argument to `doctest`, that would then get passed on `makedocs`.
