### ISSUE TITLE
Puzzling "Warning: duplicate docs found"

### ISSUE THREAD

**Issue by NicholasWMRitchie** [JuliaDocs/Documenter.jl#1366]
I am so puzzled about why I can't eliminate a "Warning: duplicate docs found" error message.
I'm documenting a structure `Spectrum`.  I've only documented it once.  Yet when I attempt to
```julia
"""@docs
Spectrum
"""
```
I get the mentioned error message.  However in `@autodocs`, the documentation for `Spectrum` shows up just fine.
Even weirder, I remove the structure documentation and I continue to get the error message and the just deleted documentation continues to show up in the `@autodocs`.  It is as though there is a cache that is holding on to the deleted documentation.
Is there a secret cache somewhere that has been corrupted?

**Comment by KristofferC** [comment]
> However in @autodocs, the documentation for Spectrum shows up just fine.

Isn't that the issue? That you have it documented with `@autodocs` and `@docs` thereby having duplicate docs for `Spectrum`?

**Comment by KristofferC** [comment]
Do you have a separate manifest used for the docs?

**Comment by NicholasWMRitchie** [comment]
I guess that even when a page isn't included in the `pages` argument to `makedocs(...)` it is still being processed.  This explains 2).

**Comment by NicholasWMRitchie** [comment]
I have a "Project.toml" but not  a "Manifest.toml"

**Comment by NicholasWMRitchie** [comment]
I'll close this because I don't know there is really a problem here and not just a misunderstanding on my part.
