### ISSUE TITLE
Allow for setting a webpage title independently of the title shown in the sidebar

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#1371]
The sidebar is quite small, so it would be nice to allow a different title to the actual header since that's what shows up in search engines

**Comment by mortenpi** [comment]
You mean what goes into the `<title>` element, right? Possibly something that could be done with an at-meta block option.

**Comment by ChrisRackauckas** [comment]
yeah exactly

**Comment by odow** [comment]
Closing as a duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/1898
