### ISSUE TITLE
`Order = [:function]` broken

### ISSUE THREAD

**Issue by tribut** [JuliaDocs/Documenter.jl#138]
Since 9b1e63c6735e3a95d2f332514b347c91e2092069 (according to `git bisect`) the following does not longer work:

`docs/src/index.md`:

    ```@index
    Pages = ["reference.md"]
    Order = [:function]
    ```

`docs/src/reference.md`:

    ```@autodocs
    Modules = [MyModule]
    ```

This used to result in a list of functions and now it returns nothing. `julia make.jl` complains:

     !! No doc found for reference '[`func1`](@ref)'. [src/reference.md]
     !! No doc found for reference '[`func2`](@ref)'. [src/reference.md]
     [...]

**Comment by MichaelHatherly** [comment]
Thanks for bisecting that. Seems it's due to splicing individual methods with autodocs rather than grouping them as a single function. Fix incoming shortly.
