### ISSUE TITLE
Searching for a page title fails to find

### ISSUE THREAD

**Issue by mhauru** [JuliaDocs/Documenter.jl#1380]
I was looking for the [punctuation](https://docs.julialang.org/en/v1/base/punctuation/#) page of the Julia manual, and noticed that [searching for "punctuation"](https://docs.julialang.org/en/v1/search/?q=punctuation) doesn't return it. Is this possibly because the search function of Documenter doesn't include the title of the page in the search?

**Comment by mortenpi** [comment]
It shows up now with the 1.5 docs. It was fixed in #1311 (x-ref: JuliaLang/julia#35724), but the 1.4 docs were built before that fix was available.
