### ISSUE TITLE
Error: mode == :single requires the Markdown string to parse into a single block │

### ISSUE THREAD

**Issue by blegat** [JuliaDocs/Documenter.jl#1387]
I am getting the following error with the output of an `@example` block. Why are the `_` splitting the block into several paragraphs ?
```
┌ Error: mode == :single requires the Markdown string to parse into a single block
│   s = "\$\$ x^{2}y_{1}^{2} + x^{2}y_{2}^{2} - 2xy_{1}^{2} + 2xy_{1}y_{2} + 2y_{1}^{2} \$\$"
│   md.content =
│    2-element Array{Any,1}:
│     :$                                                                                                                                                                
│     Markdown.Paragraph(Any["x^{2}y", Italic(Any["{1}^{2} + x^{2}y"]), "{2}^{2} - 2xy", Italic(Any["{1}^{2} + 2xy"]), "{1}y", Italic(Any["{2} + 2y"]), "{1}^{2} ", :$])
└ 
```

**Comment by fredrikekre** [comment]
Julia's markdown parser uses ``` `` ``` for inline math and ```` ```math ```` blocks for multiline math.

**Comment by blegat** [comment]
This was generated by Literate.jl. I have a code block that returns a polynomials and the polynomials gets printed in LaTeX so the MIME must be `text/latex` (see https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/blob/9a29d5e691e39794a182b8c99172ea1412d73273/src/show.jl#L3)

**Comment by fredrikekre** [comment]
Right. We probably need to rewrite `$` and `$$` similar to #1283.
