### ISSUE TITLE
deploydocs thinks it's on Travis when it's on Github Actions

### ISSUE THREAD

**Issue by mjohnson541** [JuliaDocs/Documenter.jl#1391]
I'm having an issue getting deploydocs to deploy to gh-pages using Github Actions. Based on the debug output:  https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/runs/961746198?check_suite_focus=true it seems to think it's on Travis and concludes it doesn't have the information to deploy. The Github Actions workflow file is here:  https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/actions/runs/200456591/workflow and make.jl file is here:  https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/blob/master/docs/make.jl.

**Comment by mortenpi** [comment]
It looks like [you're stuck on Documenter 0.20](https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/runs/961746198?check_suite_focus=true#step:4:2637) (bounded by [your `Project.toml` file](https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/blob/master/docs/Project.toml#L5)). GitHub Actions support was [added in 0.24](https://github.com/JuliaDocs/Documenter.jl/blob/master/CHANGELOG.md#version-v0240).

So you'd need to update the Documenter version you're using. Note that there have been a few breaking changes, so my suggestion is to work through the changelog version by version.

**Comment by mjohnson541** [comment]
Oh..XD forgot about the docs specific Project.toml. Thanks so much!
