### ISSUE TITLE
Trouble with docstrings from included file in module

### ISSUE THREAD

**Issue by clu2stanford** [JuliaDocs/Documenter.jl#1406]
In my module (DateUtils), I am including a file with all the functions and exporting them. The included file (utils.jl) has all the docstrings there. I've ran into 2 issues and I'm not sure what's causing them: 
1. If I have an `@autodocs` block in index.md, only 2 docstrings show up
2. If instead I add an `@docs` block for each function, I get a lot of missing docstrings: 
<img width="720" alt="missing docstrings messages" src="https://user-images.githubusercontent.com/20672288/90432601-66a19780-e090-11ea-9696-defdc80eb6c9.png">

Here is the repo on GitLab: https://gitlab.com/cindy.lu/DateUtils.jl
What am I doing wrong?

**Comment by fredrikekre** [comment]
The repository seems to be private so I can not see it. If you don't want to make it public but feel like you can give me access then you can invite me. Same username on gitlab.

**Comment by clu2stanford** [comment]
Thanks for looking into this! I just sent the invite.

**Comment by fredrikekre** [comment]
Thanks. You don't seem to have pushed any code there, the repository is completely empty for me.

**Comment by clu2stanford** [comment]
Hmm try GitHub?

**Comment by fredrikekre** [comment]
Everything worked for me, this is what I did:
```
$ git clone https://github.com/clu2stanford/DateUtils.jl DateUtils
[...]

$ cd DateUtils/

$ julia docs/make.jl 
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: running doctests.
[ Info: ExpandTemplates: expanding markdown templates.
[ Info: CrossReferences: building cross-references.
[ Info: CheckDocument: running document checks.
[ Info: Populate: populating indices.
[ Info: RenderDocument: rendering document.
[ Info: HTMLWriter: rendering HTML pages.
```

**Comment by clu2stanford** [comment]
That's so strange - I did the same exact steps as the above but again I see lots of missing docstrings. Could it be something wrong with my machine? I'm on MacOS

**Comment by mortenpi** [comment]
It also works out of the box for me. Could maybe be due to version differences? What if you do it in a clean environment, i.e.:

```
$ git clone https://github.com/clu2stanford/DateUtils.jl DateUtils
$ julia
pkg> activate docs/
pkg> add Documenter
pkg> dev .
julia> include("docs/make.jl")
```

**Comment by clu2stanford** [comment]
Sorry for my very late response! It worked - Thank you!

**Comment by roseink** [comment]
Hello Morten,

I am working on documenting another package, with docstrings for structs. Again, the docstrings aren't showing up so I decided to try the above clean environment setup. However, I'm getting: "Error the following package names cannot be resolved Documenter (not found in project, manifest or registry)" after I activate docs/.

I tried entering ]registry up but it didn't work. Here's the github repo: https://github.com/roseink/GeoText.jl. How should I be documenting structs?

Thanks very much in advance!

Best,
Cindy
________________________________

**Comment by mortenpi** [comment]
@roseink You need a `Project.toml` with Documenter listed as a dependency under `docs/`. E.g. [something like this](https://github.com/JuliaData/DataFrames.jl/blob/main/docs/Project.toml).

**Comment by roseink** [comment]
I just added that file in, but I still see the same error message come up on my end.
________________________________

**Comment by mortenpi** [comment]
If you do the following in the top level directory of your package, it should work:

```
pkg> activate docs/
julia> using Pkg
julia> Pkg.develop(PackageSpec(path=pwd()))
julia> Pkg.instantiate()
julia> include("docs/make.jl")
```

**Comment by roseink** [comment]
Great thank you so much!

Regarding the issue with Documenter not being registered, I had to delete the registries folder within .julia and typed in ]update in the REPL to redownload everything. Worked great afterwards!
________________________________
