### ISSUE TITLE
Allow `<!--- ... -->` as markdown comment

### ISSUE THREAD

**Issue by felipenoris** [JuliaDocs/Documenter.jl#1409]
If I put this into the markdown file, it gets rendered in the final output. Is there a way to supress it?

```
<!---
comments
-->
```

**Comment by mortenpi** [comment]
Dup of #517. FYI, it's an upstream problem (Base Markdown parser doesn't support HTML). Most likely way around it would be to add support for alternative parsers (e.g. like [CommonMark.jl](https://github.com/MichaelHatherly/CommonMark.jl)). I have an old  WIP branch on this (https://github.com/JuliaDocs/Documenter.jl/issues/1074#issuecomment-515477974) that could work as a source of inspiration if someone wants to tackle this.
