### ISSUE TITLE
Question about using Asciidoc with julia Documenter

### ISSUE THREAD

**Issue by 00krishna** [JuliaDocs/Documenter.jl#1410]
Hello Folks. I was just wondering if there is any way to use `Asciidoc` files with Julia `Documenter.jl`? I have a bunch of documentation in `Asciidoc` files, and usually use `Asciidoctor` to render them. So I figured I would ask. Thanks.

**Comment by MichaelHatherly** [comment]
At the moment it's not possible, since, as far as I know, no one has written an asciidoc parser in Julia, or bindings to a library. Documenter is also quite tightly bound to markdown since docstrings in Julia are, by default, written in markdown.
