### ISSUE TITLE
Including HTML from file

### ISSUE THREAD

**Issue by jebej** [JuliaDocs/Documenter.jl#1424]
I would like to include HTML code from file, but display the actual content, NOT the code. I tried something like this, but that just includes the formatted code in the page:

`````` julia
````@eval
using Markdown: parse
parse("""
```@raw html
$(read(joinpath("img","status_2.html"),String))
```
""")
````
``````

If the `parse` call is removed, the HTML is broken by the escaping.

**Comment by mortenpi** [comment]
You should get it to work if the object you return can `show` the `text/html` MIME. I.e. something similar to how we do [the SVG example in the showcase](https://juliadocs.github.io/Documenter.jl/stable/showcase/#Running-interactive-code) ([`SVGCircle` source](https://github.com/JuliaDocs/Documenter.jl/blob/cee9c16fc8c8ceeaae32b5bae9aa1705de5947ec/docs/DocumenterShowcase.jl#L62-L74)).

**Comment by jebej** [comment]
I'm just reading from a text file here. Do you mind explaining how to do what you are suggesting?

**Comment by mortenpi** [comment]
What I meant was something like this:

````
```@eval
struct HTMLFile
    path :: String
    content :: String
    HTMLFile(path) = new(path, read(path, String))
end
Base.show(io, ::MIME"text/html", html::HTMLFile) = write(io, html.content)
HTMLFile(joinpath("img","status_2.html"))
```
````

Note that I haven't actually tested this code.

**Comment by jebej** [comment]
Yes thanks, that does work!

**Comment by mortenpi** [comment]
Are you sure? I finally tried it out, and as far as I can tell, if you are still using an at-eval block, it shouldn't actually (because we don't handle MIME outputs for those, just [use `repr`](https://github.com/JuliaDocs/Documenter.jl/blob/v0.25.2/src/Writers/HTMLWriter.jl#L1749)) :sweat_smile:  If you are doing it in an at-example block, then it would work though.

**Comment by jebej** [comment]
Oh right I ended up defining the show function in the package code, and used a regular example block. You are right that this didn't work with `@eval`
