### ISSUE TITLE
LaTeX fraction not rendering properly in md files

### ISSUE THREAD

**Issue by khosravipasha** [JuliaDocs/Documenter.jl#1432]
When using `\frac` in math mode in `.md` files the fraction is not shown properly (the line is missing).

This also happens in the documentation as well:  For example, here: https://juliadocs.github.io/Documenter.jl/dev/man/latex/

This following equation is rendered as below:
````markdown
```math
 \frac{n!}{k!(n - k)!} = \binom{n}{k}
```
````
![image](https://user-images.githubusercontent.com/2780093/95396324-8c3f6600-08b5-11eb-8140-9f89d30b04e8.png)

Similar thing happens in [stable docs](https://juliadocs.github.io/Documenter.jl/stable/man/latex/), so its not a new issue I feel.

**Comment by mortenpi** [comment]
It renders fine for me: 
![latex](https://user-images.githubusercontent.com/147757/95520474-dcd4d180-0a23-11eb-9800-dffd0777ccfa.png)

If there is a bug, I suspect it is an upstream issue with KaTeX. But it could be something system-specific. What OS/browser are you using? Can you replicate it in other browsers or operating systems?

**Comment by khosravipasha** [comment]
I think you are correct that the issue was with KaTeX. The issue is gone now.

I was using Chrome + Windows. I also had similar issue with the document for our package. Now both work properly.  Did not try other browers yesterday, so not sure if it would have been different. Anyway, thank you, I guess can close this issue now.
