### ISSUE TITLE
Filters for cross version array printing

### ISSUE THREAD

**Issue by jw3126** [JuliaDocs/Documenter.jl#1436]
Array printing varies across Julia versions.
```julia
julia> [1] # 1.5
1-element Array{Int64,1}:
 1

julia> [1] # master
1-element Vector{Int64}:
 1
```
This can break doctests. So filtering must be applied. For instance @fredrikekre suggests these filters:
> ```
> doctestfilters = [
>     r"{([a-zA-Z0-9]+,\s?)+[a-zA-Z0-9]+}",
>     r"(Array{[a-zA-Z0-9]+,\s?1}|Vector{[a-zA-Z0-9]+})",
>     r"(Array{[a-zA-Z0-9]+,\s?2}|Matrix{[a-zA-Z0-9]+})",
> ]
> ```
See [here](https://discourse.julialang.org/t/doctests-and-array-printing/48477) and [here](https://github.com/JuliaLang/julia/pull/37085#issuecomment-683356098) for context.

How about defining some solid filters in `Documenter.jl`? I am **not** suggesting to apply them by default, just that it is possible
to write something like
```
makedocs(doctestfilters = Documenter.cross_version_filters() )  # fixes most/all cross version printing differences of `Base` objects.
```

**Comment by mortenpi** [comment]
I am not 100% it makes sense to provide them via an API (not sure we want to maintain them). But they are useful filters, so alternatively we could just document them in the manual.

**Comment by fredrikekre** [comment]
Since printing output is pretty sensitive like this I think it makes sense to only recommend running doctest on a single release.
