### ISSUE TITLE
Ability to set IOContext in which `@example`/`@repl` blocks are run

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaDocs/Documenter.jl#1450]
Seems closely related to #942 but unsure if it's the same problem with the same solution

I'd like to print a long Vector in an `@example` block in the docs (or an `@repl` block), e.g.
```md
``@example
f() = collect('a':'z') # hide
f()
``
```

will result in 
```julia
f()
26-element Array{Char,1}:
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)
 'd': ASCII/Unicode U+0064 (category Ll: Letter, lowercase)
 'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)
 'f': ASCII/Unicode U+0066 (category Ll: Letter, lowercase)
 'g': ASCII/Unicode U+0067 (category Ll: Letter, lowercase)
 'h': ASCII/Unicode U+0068 (category Ll: Letter, lowercase)
 'i': ASCII/Unicode U+0069 (category Ll: Letter, lowercase)
 'j': ASCII/Unicode U+006A (category Ll: Letter, lowercase)
 ⋮
 'r': ASCII/Unicode U+0072 (category Ll: Letter, lowercase)
 's': ASCII/Unicode U+0073 (category Ll: Letter, lowercase)
 't': ASCII/Unicode U+0074 (category Ll: Letter, lowercase)
 'u': ASCII/Unicode U+0075 (category Ll: Letter, lowercase)
 'v': ASCII/Unicode U+0076 (category Ll: Letter, lowercase)
 'w': ASCII/Unicode U+0077 (category Ll: Letter, lowercase)
 'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)
 'y': ASCII/Unicode U+0079 (category Ll: Letter, lowercase)
 'z': ASCII/Unicode U+007A (category Ll: Letter, lowercase)
```
But i'd like to be able to show the full 26-element output. Is that's possible right now?

(As a workaround i ended up wriitng `foreach(println, f())`)

**Comment by fredrikekre** [comment]
You can use https://tkf.github.io/DisplayAs.jl/stable/#DisplayAs.Unlimited

**Comment by mortenpi** [comment]
We can leave this open, as this is about at-example/repl blocks and #942 is doctests. But the solution should be the same basically.

`DisplayAs` is a great workaround, but it would probably be good to support this natively. `DisplayAs` sets the following `IOContext` attributes:

```julia
IOContext(
    io,
    :compact => false,
    :limit => false,
    :displaysize => (typemax(Int), typemax(Int)),
)
```

I think we should have some keyword arguments to the at-blocks to control them.

**Comment by pdeffebach** [comment]
I think I have the opposite problem. I am making a tutorial with DataFrames and it by default prints all the rows of a DataFrame in the `@example` blocks. I would like to print a smaller amount.

**Comment by fredrikekre** [comment]
https://github.com/tkf/DisplayAs.jl/pull/14

**Comment by fredrikekre** [comment]
https://github.com/tkf/DisplayAs.jl/pull/14 is merged and released.
