### ISSUE TITLE
Handle control characters in docstrings when building PDFs

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#1467]
Currently, if you somehow manage to end up with e.g. a `\0` in a docstring, it will get literally written into the `.tex` file, which fails the `latexmk` compilation. Probably also true for other control characters. We should probably write them out as escape sequences in TeX.

X-ref: JuliaLang/julia#38356

**Comment by odow** [comment]
Closing as a duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/2226
