### ISSUE TITLE
Long ```math ... ``` overflows the div

### ISSUE THREAD

**Issue by friggog** [JuliaDocs/Documenter.jl#1470]
If you have a long equation in a \``` math ... ``` block then the result will overflow the parent div:

![image](https://user-images.githubusercontent.com/6437437/98693951-d3af8b00-2368-11eb-9190-2302d78a26ae.png)

If you just use inline math \`` ... `` then it wraps OK, although doesn't look quite as nice generally:

![image](https://user-images.githubusercontent.com/6437437/98692721-58010e80-2367-11eb-8920-b7edf5854d4d.png)

I don't know what the preferable solution is here,  but I feel like overflow should be avoided

**Comment by mortenpi** [comment]
I don't really see any other way out of this other than introducing a scrollbar if the equation is too wide?
