### ISSUE TITLE
Wrong Math format for inline math in lists

### ISSUE THREAD

**Issue by kellertuer** [JuliaDocs/Documenter.jl#1483]
I just stumbled upon an interesting display error. Consider the doc string
```julia
@doc raw"""
    update_prox_parameters!(o)
update the prox parameters as described in Algorithm 2 of Chambolle, Pock, 2010, i.e.
1. $\theta_{n} = \frac{1}{\sqrt{1+2\gamma\tau_n}}$
2. $\tau_{n+1} = \theta_n\tau_n$
3. $\sigma_{n+1} = \frac{\sigma_n}{\theta_n}$
"""
```
(from my most recent PR, see https://github.com/JuliaManifolds/Manopt.jl/blob/d14efb9376881e95468d0de9ee018fd6626bc6c4/src/solvers/ChambollePock.jl#L227).
If you look at the result, the three math formulae get rendered as displayed and not as inline math, see
https://manoptjl.org/previews/PR40/solvers/ChambollePock.html#Manopt.update_prox_parameters!

Note that usual renders do not yield displayed math equations
https://babelmark.github.io/?text=1.+%24%5Ctheta_%7Bn%7D+%3D+%5Cfrac%7B1%7D%7B%5Csqrt%7B1%2B2%5Cgamma%5Ctau_n%7D%7D%24%0A2.+%24%5Ctau_%7Bn%2B1%7D+%3D+%5Ctheta_n%5Ctau_n%24%0A3.+%24%5Csigma_%7Bn%2B1%7D+%3D+%5Cfrac%7B%5Csigma_n%7D%7B%5Ctheta_n%7D%24%0A

Any idea why this is happening?

**Comment by mortenpi** [comment]
I have a hunch it's becausewe're losing the information that it's supposed to be inline. If I remember correctly, all math becomes `Markdown.Math` and we need to decide if we render it as inline or block based on the context. If you add any text either before or after the equation on one of the lines, I guess you get an inline equation?

**Comment by kellertuer** [comment]
Yes, adding any text makes the math formulae inline. That's why for quite a while I thought that was a feature. Just today I learned of babel mark and the comparison, so I noticed, that most probably it's a bug.

Actually I did exactly that on the linked PR manual page at the very top in step 3 because it really took too much space there. But I would love to have it without actually.

**Comment by mortenpi** [comment]
Hmm, it looks like it might be an upstream parsing issue after all. Using backticks wraps the equation in a `Paragraph`, which should render as you want:

```
julia> m = md"""
           update_prox_parameters!(o)
       update the prox parameters as described in Algorithm 2 of Chambolle, Pock, 2010, i.e.
       1. ``\theta_{n} = \frac{1}{\sqrt{1+2\gamma\tau_n}}``
       2. ``\tau_{n+1} = \theta_n\tau_n``
       3. ``\sigma_{n+1} = \frac{\sigma_n}{\theta_n}``
       """;

julia> m.content[3].items
3-element Array{Any,1}:
 Any[Markdown.Paragraph(Any[$\theta_{n} = \frac{1}{\sqrt{1+2\gamma\tau_n}}$])]
 Any[Markdown.Paragraph(Any[$\tau_{n+1} = \theta_n\tau_n$])]
 Any[Markdown.Paragraph(Any[$\sigma_{n+1} = \frac{\sigma_n}{\theta_n}$])]
```

compare with

```
julia> m = md"""
           update_prox_parameters!(o)
       update the prox parameters as described in Algorithm 2 of Chambolle, Pock, 2010, i.e.
       1. $\theta_{n} = \frac{1}{\sqrt{1+2\gamma\tau_n}}$
       2. $\tau_{n+1} = \theta_n\tau_n$
       3. $\sigma_{n+1} = \frac{\sigma_n}{\theta_n}$
       """;

julia> m.content[3].items
3-element Array{Any,1}:
 Any[$\theta_{n} = \frac{1}{\sqrt{1+2\gamma\tau_n}}$]
 Any[$\tau_{n+1} = \theta_n\tau_n$]
 Any[$\sigma_{n+1} = \frac{\sigma_n}{\theta_n}$]
```

So in your case, changing to backticks should solve the problem (and is the recommended syntax anyway).

**Comment by kellertuer** [comment]
Ah, I was not aware that double backticks are also usable as math delimiters (nor that that's the recommended way to do so).
The only little sad part is, that “just copying” a formula from a paper does not directly work. But yes it works well (tested locally),

**Comment by mortenpi** [comment]
It looks like `$` and `$$` are intentionally synonymous in the parser, with whether it's display equation or inline decided based on context: https://github.com/JuliaLang/julia/issues/37334#issuecomment-685555046. I'll close this in favor of that issue.
