### ISSUE TITLE
`deploydocs` default to `devbranch="master"`, although github default branch is `main` now.

### ISSUE THREAD

**Issue by lrnv** [JuliaDocs/Documenter.jl#1485]
Everything is in the title. I dont know if you want to fix this, as the switch to `main` instead of `master` is quite recent. 

Just to give you a heads'up :)

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaDocs/Documenter.jl/issues/1443 :)

**Comment by andreasvarga** [comment]
Sorry for interfering in this discusion, but recently I faced this problem with a new repository. While the `deploydocs` failed, other issues have been correctly handled by github, by using for `master`, if not existing, automatically `main`.
I wonder if this strategy could also be adopted for `deploydocs`, for which `main` is now the natural candidate as default. So, `master` can be automatically used  in the case `main` is not present.
