### ISSUE TITLE
Negative number interpreted as bullet list

### ISSUE THREAD

**Issue by blegat** [JuliaDocs/Documenter.jl#1494]
When the return value of an `@example` block is a negative number, the `-` sign is interpreted as a bullet of a bulleted list, see e.g. https://jump.dev/SumOfSquares.jl/v0.4.4/generated/Term%20sparsity/
In fact, even for positive numbers, it may be printed in a weird as as in https://jump.dev/SumOfSquares.jl/v0.4.4/generated/Bound%20on%20Global%20Extremum/.
Is this expected ? If yes, is there a workaround ?

**Comment by mortenpi** [comment]
Do you have an MWE? Doing something like

````markdown
```@example
-3.04
```
````

works fine. Is `bound` a standard number type? My hunch is that it isn't, and that it has some weird overloads for `show` methods that trip Documenter up.

**Comment by blegat** [comment]
It should be a `Float64`. One other possibility is that I am using the branch of https://github.com/JuliaDocs/Documenter.jl/pull/1426 instead of the latest release.

**Comment by blegat** [comment]
Just tried locally, you MWE also fails on that branch, so that should be fixed on master I guess.

![failure](https://user-images.githubusercontent.com/1048205/101760550-4bddad80-3adb-11eb-889a-db002446190c.png)

**Comment by blegat** [comment]
I can confirm that v0.26 solves the issues :tada:
