### ISSUE TITLE
Bikshedding on docstring rendering

### ISSUE THREAD

**Issue by hayd** [JuliaDocs/Documenter.jl#15]
This is going to be a little speculative.

Back over in https://github.com/MichaelHatherly/Lexicon.jl/pull/129 I suggested the following output:

![function documentation](https://cloud.githubusercontent.com/assets/1931852/9125915/c5e7cd3e-3c5a-11e5-9a31-9cd3fe184f77.png)

That is:

- function link
- signature w/ source links
- docstring

---

The tricky thing here is that the convention is that the first part (of each block?) has the simplified signature, however it seems to me that there are two placements for the extracted docstring:

1. in the manual (inline surrounded by discussion) 
2. in the api section (e.g. with all methods listed in alphabetical / module order)

Generally I prefer the in-situ functions, but it can be useful just to list them all out (sometimes it can seems that topics are separated somewhat arbitrarily).

http://lightgraphsjl.readthedocs.org/en/latest/pathing/ has good example of in-situ docs.
http://lexiconjl.readthedocs.org/en/latest/api/Lexicon/ good example of api docs.

I'm of the opinion that having both (in-situ and api sections) is the best policy...

---

Potentially the API to have an additional pass to add the full method table (of methods defined in the Package) with links. This does have the problem of "where to link the function to: the in-situ or the api version of the method?

**Comment by MichaelHatherly** [comment]
> where to link the function to: the in-situ or the api version of the method?

It could get quite confusing having duplicate docs in a single document. Perhaps if one wants both an in-situ and api then two separate docs could be built, something like

```
doc/
    /manual
        /build
        /src
        make.jl
    /api
        /build
        /src
        make.jl
```

(Note, I've used `make.jl` here instead of `build.jl` since I was getting annoyed with tab completion matching both `/build` and `build.jl`. Thoughts on renaming the file?)

> Potentially the API to have an additional pass to add the full method table (of methods defined in the Package) with links.

Showing the method table could be quite nice, so long as it's not too cluttered. Are you thinking of this as opt-in or -out? Maybe a `{methods}` block like the `{docs}` block?

**Comment by hayd** [comment]
That's a good point. How's about this:

1. header for the function name
2. option for adding method signatures (with source links), as an alternative to the Base convention of the signature as an initial codeblock.

Presumably the option should be a kwarg in makedocs.

I think the current `# function` isn't required, as whether it's a function or a type should be immediately obvious from the context/docstring... Will have a play with some ideas & PR to make this less bikesheddy.

**Comment by MichaelHatherly** [comment]
> How's about this

:+1: seems reasonable.

> I think the current `# function` isn't required

Yes, that's just been a placeholder really until deciding on something better. (Though the distinction between objects that do get named in a similar way, such as `Module`s and `Type`s, might be slightly confusing if not explicitly mentioned, perhaps.)

**Comment by hayd** [comment]
Yeah to modules vs types. But I think methods/types shouldn't be distinguished.

**Comment by MichaelHatherly** [comment]
> But I think methods/types shouldn't be distinguished.

Agreed.

**Comment by tshort** [comment]
I definitely like having the source links.

**Comment by MichaelHatherly** [comment]
At the moment `Base.@doc` has some trouble getting the correct line numbers in `0.5`. In `0.4` line numbers aren't tracked at all. I've got some plans to tackle that soon, so having proper source links in `0.5` should happen. At this point `0.4` won't be getting line number support.

**Comment by mortenpi** [comment]
#90 was merged, so all functions have an automatically generated list of methods attached to them now. I am wondering whether that addresses this issue as well? Or is this more about parsing manually written lists?

**Comment by MichaelHatherly** [comment]
Yeah, bikeshedding issues are a bit difficult to close since they're always a bit vague about what the final goal is. We could close this one and open more targeted issues to discuss specific changes/issues as they come up maybe.

**Comment by hayd** [comment]
I preferred the look of the output I was getting above, but at least we're getting all the same data again.

**Comment by MichaelHatherly** [comment]
I'm happy to continue discussing adjustments to the presentation of docs, since I'm sure there's plenty of tweaks we can still make. So either new more specific issues, or this one can stay open. I'm fine with either.
