### ISSUE TITLE
Fix Edit source button

### ISSUE THREAD

**Issue by udistr** [JuliaDocs/Documenter.jl#1508]
Hi,

How can I fix the "Edit source" button if it is not pointing to the correct location:

https://github.com/udistr/CyclicArrays.jl

Thanks

**Comment by mortenpi** [comment]
Your [`repo` argument to `makedocs`](https://github.com/udistr/CyclicArrays.jl/blob/cae42ccd71fc2dd9c26d1ed688d80de526d3563f/docs/make.jl#L11-L12) is broken. But since you have everything in GitHub, just removing it should make the edit links work correctly.

**Comment by udistr** [comment]
Thanks! I looked at this file a thousand times before and still missed it...
