### ISSUE TITLE
Build hanging on Turing sample call

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaDocs/Documenter.jl#1514]
Yesterday evening, I noticed that a Documenter workflow didn't complete after 5 (five!) hours. I now made a minimal working example in a GitHub [repository](https://github.com/rikhuijzer/documenter-hang-example). In this case, the build hangs when calling `sample` from Turing.jl. It occurs when running Documeter locally too, but not when running the same model in the REPL. Very similar code doesn't hang when [built via CI with Franklin](https://statisticalrethinkingjulia.github.io/TuringModels.jl/models/globe-tossing/). 

In the repository, the following code **does** work

     ```@example tutorial
      using Turing
    
      @model function binom(n, k)
           θ ~ Beta(1, 1)
           k ~ Binomial(n, θ)
           return k, θ
      end
      nothing # hide
    ```
However, adding `sample` should increase the running time with at most a few minutes and is, at the time of writing, running for 25 minutes (I'll cancel it soon because there is no point in keeping it running):

      ```@example tutorial
      using Turing
    
      @model function binom(n, k)
           θ ~ Beta(1, 1)
           k ~ Binomial(n, θ)
           return k, θ
      end
      chains = sample(binom(9, 6), NUTS(0.65), 1000)
      nothing # hide
      ```

See https://github.com/rikhuijzer/documenter-hang-example/commit/35eb19e29c7340a40192b439150b2be324843ddf for the commit which passes and https://github.com/rikhuijzer/documenter-hang-example/commit/0e71813f82f91cdf5850be6522d45a612d85f4a3 for the commit which seems to hang.

This issue might be related to #1414.

**Comment by rikhuijzer** [comment]
I'm currently working around this by calling the build from another file (https://github.com/rikhuijzer/TuringPlots.jl/blob/main/docs/src/index.md). I have no clue why this works.

**Comment by arzwa** [comment]
I had the same issue, using `progress=false` in the `sample` call fixed the hang, so it seems something about the default progress bar in Turing isn't playing nicely with Documenter (it used to in the past).

**Comment by mortenpi** [comment]
On Documenter's end, this was probably fixed by  https://github.com/JuliaDocs/IOCapture.jl/pull/9 via #1549 (currently untagged though).
