### ISSUE TITLE
Not getting a .documenter.enc file

### ISSUE THREAD

**Issue by timholy** [JuliaDocs/Documenter.jl#152]
I've had success with mkdocs locally and feel ready to host my documentation. I think I've followed all the steps on the "deployment" page, but my `Travis.genkeys("ImagesCore")` is not saving a `.documenter.enc` file. Instead, I'm getting logfiles like travis.log that begin with content like
```sh
$ cat travis.log | head
Command line:
"travis encrypt-file .documenter"


   ________                                 __
  /        |                               /  |
  ########/ ______    ______    __     __  ##/    _______
     ## |  /      \  /      \  /  \   /  | /  |  /       |
     ## | /######  | ######  | ##  \ /##/  ## | /#######/
     ## | ## |  ##/  /    ## |  ##  /##/   ## | ##      \
tim@diva:~/.julia/v0.5/ImagesCore/docs$ 
```

When `travis` runs, I am seeing red-text messages:

```
    Loading configuration from /home/tim/.travis.conf ...

Unknown parameter: "login".     <--------------- here's the red text

    List of supported command line options:

      -p <file>       Loads position data from the specified trajectory file.
...
 ```

and another one

```
...    Loading configuration from /home/tim/.travis.conf ...

Unknown parameter: "encrypt-file".   <------------- here's the red text

    List of supported command line options:

      -p <file>       Loads position data from the specified trajectory file.
...
```

plus two messages at the end about removing the private and public key.

I installed `travis` via Ubuntu (16.04). Might that be the problem?

**Comment by timholy** [comment]
Looks like the `travis` version was the problem. I installed a newer one as a gem, and it worked like a charm.

**Comment by MichaelHatherly** [comment]
Excellent, glad its working fine now! Could you let me know which version didn't work, and which did so it can be noted in the docs for future readers, thanks.

**Comment by timholy** [comment]
Not sure, since it's not installed anymore I can't easily query its version. I might guess 1.5.0 or 1.5.1 from [this page](https://launchpad.net/ubuntu/xenial/+package/travis)? (Just guessing from the filenames and the fact that the version I installed was 1.8.2.)

**Comment by MichaelHatherly** [comment]
To be on the safe side maybe mention 1.8.2 as working and we can amend it later if someone finds it works with an earlier version.
