### ISSUE TITLE
Printing two methods when only calling for one

### ISSUE THREAD

**Issue by albinahlback** [JuliaDocs/Documenter.jl#1523]
I get two methods printed when I only want the last one printed. The document call gets made by 
```
    ```@docs
    basis(::ModularForms.ModularFormsSpaceSL2Z{R}) where R
    ```
```
See picture below for the result.
![Screenshot from 2021-02-05 23-11-25](https://user-images.githubusercontent.com/59514103/107095030-621c9700-6808-11eb-9460-f9a7c4545b68.png)
This happens for other functions as well. What module they belong to does not seem to matter. Am I doing something wrong?

**Comment by albinahlback** [comment]
I would like to add that I have not called for using or importing `basis`.

**Comment by albinahlback** [comment]
I get this problem also on some places for methods only defined in my module. However, on other functions with multiple methods it seems to work as I think it should.

**Comment by mortenpi** [comment]
What type exactly is `NfAbsOrdFracIdl`? It's quite likely that we're not doing the right thing when selecting for the methods (see also #839). Could put together an MWE based on your example?

**Comment by albinahlback** [comment]
Okay, so this problem seems to arise with types having input arguments, please see the picture below. See [my repository](https://github.com/albinahlback/testdocs) for the MWE.
![Screenshot from 2021-02-10 11-57-15](https://user-images.githubusercontent.com/59514103/107501375-97720d80-6b97-11eb-97b8-7c669fcbc86b.png)

**Comment by kimikage** [comment]
```julia
julia> Base.Docs.signature(:(fun(::Testdocs.foo1{T}) where T))
:(Union{Tuple{Testdocs.foo1{T}}, Tuple{T}} where T <: Any)
```
Where did `Tuple{T}` come from? :thinking:

For now, a workaround is to not use the `where` keyword. :sweat_smile:
```julia
@doc Markdown.doc"""
    fun(a::foo1{T})

Documentation1
"""
fun(a::foo1)
fun(a::foo1{T}) where T = 1
```

**Comment by kimikage** [comment]
xref: https://github.com/JuliaLang/julia/issues/29437
