### ISSUE TITLE
Don't know why travis is being used.

### ISSUE THREAD

**Issue by sbromberger** [JuliaDocs/Documenter.jl#1530]
Hi all,

https://github.com/JuliaGraphs/LightGraphs.jl/pull/1527/checks?check_run_id=1907997279 shows what looks like a deployment failure. We haven't used Travis in a long time (we use github actions). I don't know why the docs aren't being deployed properly, but the fact that the process is checking `TRAVIS` environment variables makes me a bit suspicious.

I've pretty much copied the GitHub Actions example from the Documenter documentation, but I'm obviously missing something. Advice please?

**Comment by sbromberger** [comment]
Closing for now because more testing is needed. Sorry.

**Comment by sbromberger** [comment]
Reopening. Here's the latest: https://github.com/JuliaGraphs/LightGraphs.jl/pull/1528/checks?check_run_id=1908033748#step:5:223

**Comment by fredrikekre** [comment]
You are using a Documenter version that is too old for gh actions: https://github.com/JuliaGraphs/LightGraphs.jl/blob/c137610300f117fc88f6634b9351066ef09576d4/docs/Project.toml#L5

**Comment by sbromberger** [comment]
Thanks, @fredrikekre - I had forgotten there was a `Project.toml` inside `docs`. I've updated it to 0.26.2.

**Comment by sbromberger** [comment]
@fredrikekre - a followup if you don't mind - if you take a look [here](https://github.com/JuliaGraphs/LightGraphs.jl/pull/1528), you'll see that we have a pending test called `documenter/deploy`. I don't know where that's coming from, and why it's not completing. Any ideas where I should be looking?

**Comment by mortenpi** [comment]
@sbromberger It's probably set as a required status check in branch protection settings.

**Comment by sbromberger** [comment]
@mortenpi thank you! I think that was it. It's been so long since I touched any of this stuff that I've forgotten where it lives. Appreciate the help.
