### ISSUE TITLE
Add a section "how to add documentation specific dependencies"

### ISSUE THREAD

**Issue by guilgautier** [JuliaDocs/Documenter.jl#1532]
Hi there,

Thanks for your nice work!

Adding a "how to add documentation specific dependencies" section in the documentation may save a substantial amount of time for newcomers (like me).

Following the section [Test-specific-dependencies-in-Julia](https://julialang.github.io/Pkg.jl/v1/creating-packages/index.html#Test-specific-dependencies-in-Julia-1.2-and-above) from `Pkg.jl`

```bash
$ cd MyProject
$ julia
```

```julia
julia> ]
(@v1.5) pkg> activate .
(MyProject) pkg> activate ./docs
(docs) pkg> add YourFavoritePackage
(docs) pkg> activate
(@v1.5) pkg>
```

Cheers

**Comment by odow** [comment]
Closing in favor of https://github.com/JuliaDocs/Documenter.jl/issues/1413
