### ISSUE TITLE
Flaky Tests during local development

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaDocs/Documenter.jl#1535]
Maybe it is just me understanding the workflow wrong, but the `jldoctest` are very flaky during local devlopment, that is, they sometimes change from pass to fail, or the reverse, while I'm not touching the source code.

For example, on Julia 1.6-rc1 with Documenter 0.26.2 and MCMCChains.jl, I have the following block

    ```jldoctest; setup = :(using MCMCChains)
    julia> chn = Chains(rand(100, 2, 2), ["one", "two"]);
  
    julia> chn2 = replacenames(chn, "one" => "A");
  
    julia> names(chn2)
    2-element Vector{Symbol}:
     :A
     :two
  
    julia> chn3 = replacenames(chn2, Dict("A" => "one", "two" => "B"));
  
    julia> names(chn3)
    2-element Vector{Symbol}:
     :one
     :B
    ```

and I've loaded Revise and loaded a local MCMCChains via `] dev <path>`. Now, calling 
```
using Documenter
doctest(MCMCChains)
```
will mostly pass. Sometimes, when I make an obvious error in the `jldoctest` block, then the tests start to fail when calling `doctest(MCMCChains)`. For example, I change the first lines to

    ```jldoctest; setup = :(using MCMCChains)
    julia> chn = Chains(rand(100, 2, 2), ["one", "two"]);
    lorem ipsum

    [...]
    ```

If I then remove the obvious mistake, the tests pass again. However, when placing the obvious mistake back, the test still pass while they should not.

Am I maybe doing something wrong in the development workflow?

**Comment by rikhuijzer** [comment]
Got it. It's probably a parser problem, because it was fixed by adding fewer statements in each block.

**Comment by rikhuijzer** [comment]
Nope, that was just the flakiness again. I have no idea still.

**Comment by mortenpi** [comment]
What's the diff that Documenter shows? Ultimately, Documenter just does a byte-by-byte comparison of the the two outputs, so something must be changing in the output.

**Comment by rikhuijzer** [comment]
Thank you for thinking about this. I think I've narrowed it down a bit more. The CI also passes unexpectedly at <https://github.com/rikhuijzer/MCMCChains.jl/tree/72629a05f0c1501bfab28f590cc863574a0d608d>. Here, `make.jl` contains

```
using Documenter
using MCMCChains

DocMeta.setdocmeta!(
    MCMCChains,
    :DocTestSetup,
    :(using MCMCChains);
    recursive=true
)

makedocs(
    sitename = "MCMCChains.jl",
    pages = [
        "MCMCChains" => "index.md",
        "Plotting" => [
            "StatsPlots.jl" => "statsplots.md"
        ],
        "API" => [
            "Chains" => "chains.md",
            "Diagnostics" => "diagnostics.md",
            "Posterior statistics" => "stats.md",
            "Model selection" => "modelstats.md"
        ]
    ],
    format = Documenter.HTML(prettyurls = get(ENV, "CI", nothing) == "true"),
    strict = true,
    checkdocs = :exports
)

deploydocs(repo = "github.com/TuringLang/MCMCChains.jl.git", push_preview=true)
```

and [src/MCMCChains.jl](https://github.com/rikhuijzer/MCMCChains.jl/blob/72629a05f0c1501bfab28f590cc863574a0d608d/src/MCMCChains.jl) contains


    """
        Chains
    Parameters:
    - `value`: An `AxisArray` object with axes `iter` × `var` × `chains`
    - `logevidence` : A field containing the logevidence.
    - `name_map` : A `NamedTuple` mapping each variable to a section.
    - `info` : A `NamedTuple` containing miscellaneous information relevant to the chain.
    The `info` field can be set using `setinfo(c::Chains, n::NamedTuple)`.
    ```jldoctest
    julia> foo
    bar
    ```
    """
    struct Chains{T,A<:AxisArray{T,3},L,K<:NamedTuple,I<:NamedTuple} <: AbstractMCMC.AbstractChains
        value::A
        logevidence::L
        name_map::K
        info::I
    end

where

```
julia> foo
bar
```
should fail, also given that `strict = true`. However, CI passes with
```
Run julia --project=docs docs/make.jl
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: running doctests.
[ Info: ExpandTemplates: expanding markdown templates.
[ Info: CrossReferences: building cross-references.
[ Info: CheckDocument: running document checks.
[ Info: Populate: populating indices.
[ Info: RenderDocument: rendering document.
[ Info: HTMLWriter: rendering HTML pages.
┌ Info: Deployment criteria for deploying devbranch build from GitHub Actions:
...
```

**Comment by mortenpi** [comment]
You need to pass `modules = [MCMCChains]` to `makedocs` to make that one fail -- it's not running the doctests in that module currently.

**Comment by rikhuijzer** [comment]
That works. Oh man. I'm so glad that this is resolved. Thanks a lot for taking a look!!
