### ISSUE TITLE
Use URI-encoding for SVG images coming from at-example blocks

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaDocs/Documenter.jl#1537]
If a bitmap plot is returned, it's wrapped in an image tag. If an svg plot is returned, it's not wrapped, which means the svg often will just spill over the column layout, because svg just enforces its own dimensions ruthlessly. I recently made a PR in VSCode about the same issue, which we could use in Documenter as well https://github.com/julia-vscode/julia-vscode/blob/953304c5d00ae68eb33e337110509ca6d63c1152/src/interactive/plots.ts#L139-L162

It involves URI encoding the svg string and then using it as the src for an `img` tag. This could also fix issues such as Cairo-produced svg's invalidating each other such as described here https://discourse.julialang.org/t/cairomakie-and-fontconfig/55931/13?u=jules

**Comment by mortenpi** [comment]
Hmm. In principle, for the layout part, it should be sufficient to make sure that we apply the same CSS to the `<svg>` as we do to the `<img>` one.

But I agree that the interaction between images could still be an issues, so URI-encoding is better. We already do it for the binary images anyway: https://github.com/JuliaDocs/Documenter.jl/blob/80a86d763dea8adde06989c4f2a945c99c668097/src/Writers/HTMLWriter.jl#L1750-L1759

**Comment by jkrumbiegel** [comment]
> make sure that we apply the same CSS to the <svg> as we do to the <img> one

That sadly doesn't help, because svgs don't respect css width/height settings if they have a viewBox attribute. https://css-tricks.com/scale-svg/
