### ISSUE TITLE
Images can get larger than the container in HTML

### ISSUE THREAD

**Issue by tpoisot** [JuliaDocs/Documenter.jl#1539]
See *e.g.* the bottom of the page here: https://ecojulia.github.io/SimpleSDMLayers.jl/latest/examples/consensus/

This seems to be because the SVG is never resized to respect the maximum width of the page.

**Comment by mortenpi** [comment]
I think this is a dup of #1537 and will be fixed by #1538?

**Comment by tpoisot** [comment]
I didn't catch #1537 when looking for previous issues - definitely will be solved by #1538
