### ISSUE TITLE
Option to have source link button always visible? [feature request]

### ISSUE THREAD

**Issue by JeffFessler** [JuliaDocs/Documenter.jl#1548]
The very useful blue source link button in the generated docs is, by default, invisible it seems .
It appears only when you hover your mouse in the magic spot in the bottom right of the documentation of a given function.
(For an example, see https://github.com/JuliaImages/juliaimages.github.io/issues/179)

Personally I'd prefer to have that button always visible, rather than being invisible (in all Julia documentation ideally,
but at least in the docs for my own packages).

It would be great to have an option to the building process that makes it visible for those with this preference.
I'd offer to help with a PR but I am a bit unsure where to begin because I don't know CSS.
I'm pretty sure that the relevant CSS is somewhere near here:
https://github.com/JuliaDocs/Documenter.jl/blob/92447c9d9e2be372f83f20a172ebc4509aa7f47d/assets/html/themes/documenter-light.css#L1516

Two questions: what change there would be needed for visibility, and is it possible to control that from options at build time?
Thanks for the great package BTW.

**Comment by mortenpi** [comment]
You need to hover over the docstring box for it to become visible. If it doesn't work like that somehow, then that would be a bug.

With the current design, you can't really have it always be visible because it may end up covering content in the docstring box. I'm not against having it be visible per se, but it would need a different design.

**Comment by fredrikekre** [comment]
Put this in `docs/src/assets/custom.css`:
```css
.docs-sourcelink {
    opacity:1 !important;
}
```
and in include in `docs/make.jl`:
```julia
makedocs(
    format = Documenter.HTML(
        assets = ["assets/custom.css"], # <--
    ),
   # ...
)
```
