### ISSUE TITLE
xpath root node question

### ISSUE THREAD

**Issue by matianhe3** [JuliaDocs/Documenter.jl#1550]
```
    file = readxml("f0dc19ff.xml")
    nums = findall("//TT", file)
    for num in nums
        counter = findall("//contour", num))
        println(length(counter))
```
```
<TT><contour></contour></TT>
<TT><contour></contour></TT>
<TT><contour></contour></TT>
<TT><contour></contour></TT>
<TT><contour></contour></TT>
<TT><contour></contour></TT>
```
 i think it will print `1` , i want get every <TT> => <contour> num.
but it gives me `6`,  findall seems not in `num` , it still search in `file`?
i must use `counter = findall("//contour", parsexml(string(num)))`  get the result that i need.

**Comment by fredrikekre** [comment]
Wrong repository? I don't see how this relates to Documenter, so will close. If this is some kind of general Julia question you should use the forum: https://discourse.julialang.org/
