### ISSUE TITLE
Is it possible to switch different pictures in light/dark mode?

### ISSUE THREAD

**Issue by HaoxuanGuo** [JuliaDocs/Documenter.jl#1560]
A white background black font picture is ugly in dark mode. A transparent background black font is not clear in dark mode (because the font and background colors are same.) When adapted to dark mode (use light font), the same problem appears in light mode as well.

It is possible to prepare 2 pictures in the article and switch them when the mode changes? (like the logo appears)

**Comment by fredrikekre** [comment]
Yes, see https://juliadocs.github.io/Documenter.jl/dev/man/guide/#Adding-a-logo-or-icon

**Comment by mortenpi** [comment]
@HaoxuanGuo, do you mean the logo or images in general (either included via `![]()` or from an at-block)? For the latter, we don't support choosing different images for different themes.
