### ISSUE TITLE
Feature Request: better support for large screen?

### ISSUE THREAD

**Issue by Roger-luo** [JuliaDocs/Documenter.jl#1563]
I realize currently the layout plays nice for small/middle size screen, but for large screen, there will be a huge white space on the right, e.g

![image](https://user-images.githubusercontent.com/8445510/113778419-552dfe00-96fa-11eb-87d7-ae32777f8a90.png)

it would be nice if the layout can make use of larger screen, e.g print a lower level TOC on the right, or just put what's in the config button (the theme switch etc.) on the right
instead of hiding it inside the button, an example might be: https://pydantic-docs.helpmanual.io/

**Comment by mortenpi** [comment]
Related issue: #1168.

Main question would be what to fill it with though. A more detailed TOC would definitely be an option -- that's quite common in other SSGs.

**Comment by VarLad** [comment]
@mortenpi Got anything in mind?

I'm ready to work on this and open a PR if there exists someone to instruct?

**Comment by VarLad** [comment]
I believe stretching it is the easier solution

**Comment by Roger-luo** [comment]
I think you don't want to stretch too much, it will make some not so long docstring become one line which is also hard to read. I personally like the centric layout plus more detailed table of content on the right hand side

**Comment by VarLad** [comment]
@mortenpi Okay, so... I can make a parser which parses the md files into divs (with ToCs). Then you can implement that function in Franklin?

**Comment by mortenpi** [comment]
> I think you don't want to stretch too much, it will make some not so long docstring become one line which is also hard to read.

I agree, I think we should fill that space with something, but simply stretching the main column would affect readability in my opinion. That said, having an option to widen the page to maximum width is something that has been suggested before: #1168.

> I'm ready to work on this and open a PR if there exists someone to instruct?

I would suggest starting with a HTML/CSS mockup of what you have in mind. You can generate a Documenter site, make the HTML more readable with [Tidy](https://www.html-tidy.org/) and start playing around with the design. Once we have the design down, we can figure out how to implement this in Documenter.

**Comment by VarLad** [comment]
@mortenpi I guess we want something like this
![Screenshot from 2021-06-06 20-01-09](https://user-images.githubusercontent.com/51269425/120928398-1b7d7180-c702-11eb-8964-d78c69e8192d.png)

@Roger-luo, any comments?

**Comment by VarLad** [comment]
@mortenpi I guess we want something like this
![Screenshot from 2021-06-06 20-02-58](https://user-images.githubusercontent.com/51269425/120928446-4cf63d00-c702-11eb-981a-73260a994be3.png)


@Roger-luo, any comments?

**Comment by VarLad** [comment]
The question is, how do you guys want to implement this?

Make it a feature of Documenter or make it an external option?

**Comment by mortenpi** [comment]
> Make it a feature of Documenter or make it an external option?

Sorry for a late reply. But I think it would be fine having it in Documenter.

**Comment by logankilpatrick** [comment]
+1 to this, see the issue I just opened here: https://github.com/JuliaDocs/Documenter.jl/issues/1688

**Comment by VarLad** [comment]
@logankilpatrick Take a look at https://docs.yaoquantum.org/dev/

**Comment by logankilpatrick** [comment]
Nice! That looks so cool, we really need that in the core docs

**Comment by mortenpi** [comment]
As a small breadcrumb: the relevant HTML generation happens here: https://github.com/JuliaDocs/Documenter.jl/blob/68dbd53d4ff6b339e795a4a3328955ad5c689e0e/src/Writers/HTMLWriter.jl#L861-L867

**Comment by mortenpi** [comment]
I'll actually close this issue in favour of #1688, since that is a specific actionable item. Any TOC-related discussion can probably move there. For other suggestions, feel free to open another issue.
