### ISSUE TITLE
Matrix with three rows shows a vertical scrollbar

### ISSUE THREAD

**Issue by jaakkor2** [JuliaDocs/Documenter.jl#1575]
Input like this shows a vertical scrollbar.  Documenter v0.26.3.

```
```math
A = \begin{bmatrix}
a & b\\
c & d
\end{bmatrix}
``` .
```math
B = \begin{bmatrix}
a & b & c\\
d & e & f\\
g & h & i
\end{bmatrix}
``` .
```
![documenter](https://user-images.githubusercontent.com/7318249/117127987-7e978380-ada5-11eb-9221-ecb621ee2afe.png)

**Comment by LazyScholar** [comment]
Add there
https://github.com/JuliaDocs/Documenter.jl/blob/c942201b745abbdf155c880e1231cb8240507b41/assets/html/scss/documenter/layout/_main.scss#L12-L14
```
overflow-y: hidden;
```

or
add here
https://github.com/JuliaDocs/Documenter.jl/blob/c942201b745abbdf155c880e1231cb8240507b41/assets/html/scss/documenter/_patches.scss#L70-L72
```
padding: 0.5em 0 !important;
```
(this will lead increase the overall y size of the page (more y space between formulas))
I would prefer the first solution as it does not change the overall y-spacing although i could not test it for other use cases.
