### ISSUE TITLE
Do a JOSS paper on Documenter.jl

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaDocs/Documenter.jl#1579]
Given the prevalence of Documenter in the community, it would be cool to get a JOSS paper on it so folks have something to cite.

**Comment by mortenpi** [comment]
Could be a nice thing to do when we get to 1.0.

**Comment by odow** [comment]
I understand the "write a paper for credit" argument, but to play devils advocate: why would someone cite Documenter?

**Comment by mortenpi** [comment]
Agreed. And also, I don't think any of the core authors are in academia anymore, so I there's relatively little motivation even for the credit part. Instead, let's write some great docs :slightly_smiling_face:
