### ISSUE TITLE
Documenter builds on CI hang indefinitely when using `DiffEqBase v6.61.0` onwards

### ISSUE THREAD

**Issue by dpad** [JuliaDocs/Documenter.jl#1584]
All of a sudden my documentation CI runs on [dpad/OrbitalTrajectories.jl](https://github.com/dpad/OrbitalTrajectories.jl/) are timing out (after 6 hours stuck in the middle of the Documenter build process). 

I've tracked the issue down to a seemingly innocuous change in this library release: https://github.com/SciML/DiffEqBase.jl/compare/v6.60.1...v6.61.0 .

* **Successful build** (on `DiffEqBase v6.60.1`): https://github.com/dpad/OrbitalTrajectories.jl/runs/2674846755?check_suite_focus=true
* **Indefinitely hanging build** (on `DiffEqBase v6.61.0`): https://github.com/dpad/OrbitalTrajectories.jl/runs/2674848676?check_suite_focus=true

The only difference between these builds is https://github.com/dpad/OrbitalTrajectories.jl/pull/30/commits/8ac49ee548665203f34c27b19ac8e8516dcb9c8e which updates the `DiffEqBase`'s `compat` entry to `"= 6.61.0"`.

The code below is tested as a pure Julia script (see the "(TEMP) Run document test" step) which builds and runs in the order of ~5 minutes. Then, Documenter is used to build the same code from a markdown document containing a single "@example" block:

```
@example 1
using OrbitalTrajectories
using DifferentialEquations  # To propagate trajectories

# Initial guess state
u0 = [0.994, 0., 0., 0., 0.0117, 0.]
state = State(CR3BP(:mars, :phobos), u0, (0., 2π))

trajectories = continuation_simple(state; x_perturbation=3e-4, dc_tolerance=1e-4)
nothing
```

On the successful build, Documenter processes this document in ~2 minutes. 

On the non-working builds, Documenter hangs forever (until the CI times out) on the `ExpanderPipeline`. The same behaviour is seen on the latest versions of `DiffEqBase`, as well as when I disable the CI build caches (I thought maybe it could be due to stale compiled versions or artifacts).

```
┌ Debug: Running ExpanderPipeline on tutorials/QSOFamilies.md
└ @ Documenter.Expanders ~/.julia/packages/Documenter/bFHi4/src/Expanders.jl:39
```

I've tried to debug this with the author of the DiffEqBase release, @chriselrod, but we couldn't find any issues with the code outside of the Documenter build process. I cannot work out where the issue is here, but it might be related also to @YingboMa's  https://github.com/YingboMa/FastBroadcast.jl, which gets added in `DiffEqBase v6.61.0`.

**Comment by vtjnash** [comment]
Looks like this should be fixed by https://github.com/JuliaDocs/IOCapture.jl/pull/9, so may already be fixed on master here, and will be fixed once Documenter makes a new release

**Comment by dpad** [comment]
The new release seems to indeed have solved it, thanks!
