### ISSUE TITLE
Suggestion: Citations from DocumenterCitations.jl

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaDocs/Documenter.jl#1587]
[This package](https://github.com/ali-ramadhan/DocumenterCitations.jl) looks very useful, and someone might want to talk to the developer about adding it to Documenter.jl.

**Comment by fredrikekre** [comment]
Does it not work already?

**Comment by mortenpi** [comment]
I'd say we want this to live in a separate plugin package, as it does now. On Documenter-side, we do need to clean up the internal APIs a bit to make it easier to develop plugins in general, but there is already related discussion of that in #1162.
