### ISSUE TITLE
Documenter Renders Nested Lists Incorrectly

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#159]
An example can be found on master of DifferentialEquations.jl. You can see that the Supported Equations, Implemented Solvers, and Roadmap portions are not rendering the nested lists correctly. However, we can see that Documenter is at fault. If you look at /docs/src/index.md, you'll see that the lists look like:

```
* ODEs
* SODEs
* (Stochastic) PDEs
    * Linear Poisson Equation
    * Semi-linear Poisson Equation
    * Linear Heat Equation
    * Semi-linear Heat Equation (aka Reaction-Diffusion Equation)
    * Stationary Stokes Equation
```

but that same list in /doc/build/index.md, you see

```
  * ODEs
  * SODEs
  * (Stochastic) PDEs     * Linear Poisson Equation     * Semi-linear Poisson Equation     * Linear Heat Equation     * Semi-linear Heat Equation (aka Reaction-Diffusion Equation)     * Stationary Stokes Equation
```

**Comment by MichaelHatherly** [comment]
`versionsinfo()`? I've recently added nested lists in https://github.com/JuliaLang/julia/pull/17359. Do note that we don't support "run-on" lists, i.e. there must always be a blank line before a list starts, even nested lists:

```
...

* ODEs
* SODEs
* (Stochastic) PDEs

    * Linear Poisson Equation
    * Semi-linear Poisson Equation
    * Linear Heat Equation
    * Semi-linear Heat Equation (aka Reaction-Diffusion Equation)
    * Stationary Stokes Equation

...
```

will work fine in a recent 0.5 build.

> However, we can see that Documenter is at fault.

All markdown parsing issues are upstream issues, not particular to Documenter.

**Comment by ChrisRackauckas** [comment]
There are still some issues. I can show you once I can find out how to make the nightly be the one to build the documentation. How do I set that? I tried:

```
deploydocs(deps   = Deps.pip("mkdocs", "mkdocs-material", "python-markdown-math"),
    repo = "github.com/ChrisRackauckas/DifferentialEquations.jl.git",
    julia  = "0.5.0-",
    osname = "linux")
```

**Comment by MichaelHatherly** [comment]
`deploydocs` defaults to `julia = "nightly"` and `osname = "linux"` so you probably can just leave those out.

Potentially an `mkdocs` / `python-markdown` problem, since I believe they don't parse nested lists with non-4-space indents like some other parsers do.

**Comment by ChrisRackauckas** [comment]
My lists were all 4-space indents. The two issues are:

1. The nested lists specified in the documentation .md files don't seem to "go back down" very well. If you leave a space (as suggested above) and then try to drop back down, it tends to go to the next depth instead.

2. The nested lists coming from the docstrings are jumbled. They parse to something that looks like this:

```
The possibilities for the solvers are:   * DifferentialEquations.jl       - `:Euler`- The canonical forward Euler method.       - `:Midpoint` - The second order midpoint method.       - `:RK4` - The canonical Runge-Kutta Order 4 method.       - `:ExplicitRK` - A general Runge-Kutta solver which takes in a tableau. Can be adaptive. Tableaus     are specified via the keyword argument `tab=tableau`. The default tableau is     for Dormand-Prine 4/5. Other supplied tableaus include:           * `constructRalston()` - Returns a tableau for Ralston's method           * `constructRKF()` - Returns a tableau for Runge-Kutta-Fuhlberg 4/5           * `constructBogakiShampine()` - Returns a tableau for Bogakai-Shampine's 2/3 method.           * `constructCashKarp()` - Returns a tableau for the Cash-Karp method 4/5.           * `constructDormandPrince()` - Returns a tableau for Dormand-Prince 4/5.           * `constructRKF8()` - Returns a tableau for Runge-Kutta-Fuhlberg Order 7/8 method.           * `constructDormandPrice8()` - Returns a tableau for the Dormand-Prince Order 7/8 method.       - `:ImplicitEuler` - A 1st order implicit solver. Unconditionally stable.       - `:Trapezoid` - A second order unconditionally stable implicit solver. Good for highly stiff.       - `:Rosenbrock32` - A fast solver which is good for stiff equations.   * ODEInterface.jl       - `:dopri5` - Hairer's classic implementation of the Dormand-Prince 4/5 method.       - `:dop853` - Explicit Runge-Kutta 8(5,3) by Dormand-Prince       - `:odex` - GBS extrapolation-algorithm based on the midpoint rule       - `:seulex` - extrapolation-algorithm bsed on the linear implicit Euler method       - `:radau` - implicit Runge-Kutta (Rdau IIA) of variable order between 5 and 13       - `:radau5` - implicit Runge-Kutta method (Radau IIA) of order 5   * ODE.jl       - `:ode23` - Bogakai-Shampine's 2/3 method       - `:ode45` - Dormand-Prince's 4/5 method       - `:ode78` - Runge-Kutta-Fuhlberg 7/8 method       - `:ode23s` - Rosenbrock's 2/3 method       - `:ode1` - Forward Euler       - `:ode2_midpoint` - Midpoint Method       - `:ode2_heun` - Heun's Method       - `:ode4` - RK4       - `:ode45_fe` - Runge-Kutta-Fuhlberg 4/5 method
```

It's only with nested lists. This is taken from the manual page here: http://chrisrackauckas.github.io/DifferentialEquations.jl/latest/solvers/ode_solve/. From local builds I see it still has these issues even on v0.5. I will let you know when Travis has a v0.5 that deploys the docs to show it.

**Comment by MichaelHatherly** [comment]
With this diff

```diff
diff --git a/src/ode/ode_solve.jl b/src/ode/ode_solve.jl
index 0068a15..7cc2e90 100644
--- a/src/ode/ode_solve.jl
+++ b/src/ode/ode_solve.jl
@@ -35,8 +35,8 @@ Solves the ODE defined by prob on the interval tspan. If not given, tspan defaul
     - `:Midpoint` - The second order midpoint method.
     - `:RK4` - The canonical Runge-Kutta Order 4 method.
     - `:ExplicitRK` - A general Runge-Kutta solver which takes in a tableau. Can be adaptive. Tableaus
-    are specified via the keyword argument `tab=tableau`. The default tableau is
-    for Dormand-Prine 4/5. Other supplied tableaus include:
+      are specified via the keyword argument `tab=tableau`. The default tableau is
+      for Dormand-Prine 4/5. Other supplied tableaus include:
 
       * `constructRalston()` - Returns a tableau for Ralston's method
       * `constructRKF()` - Returns a tableau for Runge-Kutta-Fuhlberg 4/5
```

the list is parsed correctly. Multiline list items need to be indented to the same depth as the first line.

`mkdocs` still parses it incorrectly though. Note that github's and Julia's parsers both handle re-parsing the list fine. https://gist.github.com/MichaelHatherly/89bb5686ef93b0d395ed83036ee963e5 There's not much other than opening and issue or pr with their parser that we can do at the moment. We'll be moving to direct HTML output in the near future, which will side-step this issue.

> The nested lists coming from the docstrings are jumbled. They parse to something that looks like this:

What is your `versionsinfo()` output?

**Comment by MichaelHatherly** [comment]
(Currently `DifferentialEquations` is using `Pkg.clone("https://github.com/MichaelHatherly/Documenter.jl")` to install `Documenter`, would be good to replace that with `Pkg.add("Documenter")`, since current `master` isn't really stable enough to use.)

**Comment by ChrisRackauckas** [comment]
Thanks for pointing out that issue in the formatting. It now parses correctly.

However, I still get output issue. Is this the part that's due to mkdocs?

![capture](https://cloud.githubusercontent.com/assets/1814174/17269540/eed64030-55ff-11e6-9c7e-7cd079a4b67f.PNG)

BTW:

```
julia> versioninfo()
Julia Version 0.5.0-rc0+30
Commit e717ded* (2016-07-28 00:39 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblasp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by MichaelHatherly** [comment]
> However, I still get output issue. Is this the part that's due to mkdocs? (Notice that General Explicit ... and Stiff Solvers are supposed to go down a depth, not up)

Yes, an mkdocs issue. (The `docs/build` directory contains all the markdown files that Documenter outputs and `mkdocs` then reparses. The `build/index.md` nested lists reparse fine in Julia and GitHub's parsers as far as I can see.)

**Comment by ChrisRackauckas** [comment]
Okay then I'll consider this settled. Everything seems to work on v0.5 except for the mkdocs problem.
