### ISSUE TITLE
Package hitlist

### ISSUE THREAD

**Issue by hayd** [JuliaDocs/Documenter.jl#16]
Once this is a little more stable (please add more):

- [ ] [LightGraphs](https://github.com/JuliaGraphs/LightGraphs.jl)
- [ ] [DataStructures](https://github.com/JuliaLang/DataStructures.jl)
- [ ] [Requests](https://github.com/JuliaWeb/Requests.jl)
- [x] [NumericSuffixes](https://github.com/MichaelHatherly/NumericSuffixes.jl)
- [x] [PrivateModules](https://github.com/MichaelHatherly/PrivateModules.jl)
- [x] [MergedMethods](https://github.com/MichaelHatherly/MergedMethods.jl)
- [x] [AnonymousTypes](https://github.com/MichaelHatherly/AnonymousTypes.jl)

Would be good impetus to migrate to new docstring syntax without (non-generated) repetition in the documentation. Looking at this on some larger projects should give insight into features/bug-fixes needed.

Would be great to have #1 fixed before migrating packages. ;)

**Comment by MichaelHatherly** [comment]
Yes, #1 is a must before we could possibly expect packages to rely on this, but :+: to the general idea. 

Some of my small packages, https://github.com/MichaelHatherly/NumericSuffixes.jl, https://github.com/MichaelHatherly/PrivateModules.jl, https://github.com/MichaelHatherly/MergedMethods.jl, and https://github.com/MichaelHatherly/AnonymousTypes.jl will also get moved over to this once ready.

**Comment by MichaelHatherly** [comment]
Probably worth adding an "Examples" or "Gallery" page to the manual with some links to packages that are using Documenter. Some possible (if their authors would like them listed) packages include:

- [ ] https://github.com/JuliaStats/RCall.jl
- [ ] https://github.com/JuliaControl/ControlSystems.jl
- [ ] https://github.com/hshindo/Merlin.jl
- [ ] https://github.com/tshort/OpenDSSDirect.jl
- [ ] https://github.com/JuliaStats/DataFrames.jl
- [ ] https://github.com/tshort/Maker.jl
- [ ] https://github.com/BioJulia/Bio.jl

**Comment by mpastell** [comment]
I have updated the docs of Weave.jl to use Documenter: http://mpastell.github.io/Weave.jl/stable/ .

Many thanks for the excellent library, it was very easy to get started and it works well.

**Comment by MichaelHatherly** [comment]
Cheers for letting me know @mpastell, glad you've found it useful. I'll add a link in the examples page.

**Comment by MichaelHatherly** [comment]
> I'll add a link in the examples page.

Done in https://github.com/MichaelHatherly/Documenter.jl/commit/956050cc835052af92026696abcbdfb732f386b2

**Comment by mpastell** [comment]
Thanks!

**Comment by IainNZ** [comment]
I'm planning on trying this out on JuMPeR.jl first, then maybe JuMP

**Comment by MichaelHatherly** [comment]
I don't feel this issue is all that useful at this point. There's already quite a few packages using Documenter, so the point

> Looking at this on some larger projects should give insight into features/bug-fixes needed.

is being covered sufficiently for the moment.
