### ISSUE TITLE
Interpolation in md strings

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#1603]
This works:
````
```@example
using Markdown
x = 123
Markdown.parse("x = $x")
```
````
but not this
````
```julia
using Markdown
x = 123
md"x = $x"
```
````
The latter fails with
```
MethodError: no method matching latexinline(::IOBuffer, ::Int64)
```
so Documenter interprets this as LaTeX somehow? The reason I think the bug might be in Documenter is that this works fine:
```julia
julia> using Markdown

julia> x = 123;

julia> md = md"x = $x";

julia> md.content[1]
Markdown.Paragraph(Any["x = ", 123])
```

**Comment by mortenpi** [comment]
Hmm. I can't reproduce this. If I put

````
```julia
using Markdown
x = 123
md"x = $x"
```
````

into a docstring, it fails at parse-time, because it's a variable interpolation in the docstring. If I put it into an `.md` file it seems to work fine.

**Comment by fredrikekre** [comment]
Hmm, works for me too now...
