### ISSUE TITLE
Single page edit_link = nothing ?

### ISSUE THREAD

**Issue by t-bltg** [JuliaDocs/Documenter.jl#1620]
Is there a way to specify `edit_link = nothing` for a **single** page in the `makedocs(pages=...)` construct as in [JuliaPlots/PlotDocs.jl](https://github.com/JuliaPlots/PlotDocs.jl/blob/085c531ee0dceff0918e4e2d7dfaa853f62fda7a/docs/make.jl#L81) ?

This is for disabling the broken `Edit on Github` link of [auto-generated ](https://github.com/JuliaPlots/PlotDocs.jl/blob/085c531ee0dceff0918e4e2d7dfaa853f62fda7a/docs/make.jl#L40) md pages, which, by definition, are not editable.

AFAIK, the setting is global ...

https://github.com/JuliaPlots/PlotDocs.jl/issues/235
https://github.com/JuliaPlots/PlotDocs.jl/issues/228

**Comment by fredrikekre** [comment]
Does setting
````
```@meta
EditURL = nothing
```
````
work? Btw, it might make sense to instead include a link to where the generator can be edited.

**Comment by t-bltg** [comment]
> Btw, it might make sense to instead include a link to where the generator can be edited.

Good point there, thanks !

I'm a newcomer to Documenter.j, I believe you meant adding the `@meta` to the .md file ?

I will try this and report asap.

**Comment by fredrikekre** [comment]
> > Btw, it might make sense to instead include a link to where the generator can be edited.
> 
> Good point there, thanks !

Thats what I do in Literate.jl for example, point to the source, see e.g. this page: https://fredrikekre.github.io/Literate.jl/v2/generated/example/

> I'm a newcomer to Documenter.j, I believe you meant adding the @meta to the .md file ?

Yes exactly, see.

**Comment by t-bltg** [comment]
Thanks again, worked flawlessy :tada: !
