### ISSUE TITLE
SVG in table?

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#1621]
I'm trying to put SVG images in tables, generating the Markdown from Julia code. I thought it might work, judging from the Markdown preview in Juno:

<img width="887" alt="Screenshot 2021-07-02 at 09 47 36" src="https://user-images.githubusercontent.com/52289/124248528-d854c980-db1a-11eb-8852-2b36348eaf75.png">

but after generating the documents (`include("docs/make.jl")`) it reverts:

<img width="855" alt="Screenshot 2021-07-02 at 09 51 13" src="https://user-images.githubusercontent.com/52289/124248875-31246200-db1b-11eb-9412-341c4380027a.png">

Is there a way of putting SVG images into table cells?

**Comment by mortenpi** [comment]
It's kind of a combination of two issues:

1. The Markdown parser does not support HTML. A workaround normally is to use at-raw blocks, but...
2. at-blocks only get executed on the top-level of the document, so you can't put an at-raw in a table

Fixing (2) is the easier option -- I don't have any objections to executing at-repl/example/raw blocks in e.g. admonitions and tables. I think there is a duplicate issue for this, but I didn't find it right away.

**Comment by cormullion** [comment]
Ah, OK, thanks.

I'm trying to generate color swatches programmatically (improving on [this](https://juliagraphics.github.io/ColorSchemes.jl/latest/basics/#cmocean)) but I'm struggling to find a way to do it better, using an HTML table and plain text.  Any suggestions?

**Comment by fredrikekre** [comment]
You can always generate the HTML too, and use `@raw html` blocks.

**Comment by cormullion** [comment]
Oh, so if I generate this programmatically:

```

		```@raw html
		<table>
		<thead>
		<tr>
		<th align="left">image in a table</th>
		</tr>
		</thead>
		<tbody><tr>
		<td align="left"><svg height="5em" width="5em" style="display: block; margin: 0 auto;"><circle fill="red" stroke-width=".1em" stroke="black" r="2em" cy="2.5em" cx="2.5em"></circle></svg></td>
		</tr>
		</tbody>
		</table>
		```
```

it should work. Cool.

**Comment by mortenpi** [comment]
If it is generated anyway, you can also have a custom type with a `text/html` `show` method and put it in an [at-eval block](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@eval-block) (something like the [SVG example](https://juliadocs.github.io/Documenter.jl/stable/showcase/#Running-interactive-code), with the [definition of `SVGCircle` here](https://github.com/JuliaDocs/Documenter.jl/blob/6c8679bac445ab1c656744075b13a57835081cc3/docs/DocumenterShowcase.jl#L70-L82)).

**Comment by cormullion** [comment]
Cool. I've got [something](https://juliagraphics.github.io/ColorSchemes.jl/latest/catalogue/) working now - looks quite promising.

**Comment by mortenpi** [comment]
Considering how big the resulting `.md` files are, I think doing it dynamically might be better. I think you more or less just need to turn `write_all_schemes_in_category` into a `show` method. In any case, you probably don't want to commit the generated `.md` files?

**Comment by findmyway** [comment]
> If it is generated anyway, you can also have a custom type with a `text/html` `show` method and put it in an [at-eval block](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@eval-block) (something like the [SVG example](https://juliadocs.github.io/Documenter.jl/stable/showcase/#Running-interactive-code), with the [definition of `SVGCircle` here](https://github.com/JuliaDocs/Documenter.jl/blob/6c8679bac445ab1c656744075b13a57835081cc3/docs/DocumenterShowcase.jl#L70-L82)).

Hi @mortenpi ,

I just find that it only works with the `@example` code block, not the `@eval` code block. Is that expected?

**Comment by mortenpi** [comment]
@findmyway I do have a vague memory of running into that myself.. I think at-eval has its own `show` logic.. but it should probably behave the same way as at-example.
