### ISSUE TITLE
Undef var error in document checks when overloading Base.show for types

### ISSUE THREAD

**Issue by bgroenks96** [JuliaDocs/Documenter.jl#1623]
I have an overload for `Base.show` on `Type` for one of my types (yes, I know, type piracy...) to try and reduce verbosity of the stack traces. This seems to cause an error from `Documenter.jl` when doing the "document checks":

```
ERROR: LoadError: UndefVarError: Q not defined
Stacktrace:
  [1] show(io::IOContext{IOBuffer}, #unused#::ERROR: UndefVarError: Q not defined
Stacktrace:
  [1] show(io::IOContext{IOBuffer}, #unused#::fatal: error thrown and no exception handler available.
UndefVarError(var=:Q)
jl_undefined_var_error at /buildworker/worker/package_linux64/build/src/rtutils.c:132
```

The method definition is:

```
Base.show(io::IO, ::Type{<:Grid{S,Q}}) where {S,Q} = print(io, "Grid{$S,$Q,...}")
```

The method itself works fine and prints the expected output when called in the REPL.

**Comment by KristofferC** [comment]
It's a bug in your function, Q is not guaranteed to be defined. You can use `@isdefined`.

**Comment by bgroenks96** [comment]
I don't understand? Why is `Q` not guaranteed to be defined? It's declared as a type argument. Is this something weird with `Type`?

**Comment by bgroenks96** [comment]
Oh because of `UnionAll` types?

**Comment by bgroenks96** [comment]
Closing because this does not appear to be a `Documenter.jl` issue after all.
