### ISSUE TITLE
Adding images from URL

### ISSUE THREAD

**Issue by tomchor** [JuliaDocs/Documenter.jl#1638]
Sorry if that question is too basic, but I couldn't find the info anywhere. Is it possible to add online-hosted images via their url? If so, what's the syntax?

Thanks!

**Comment by mortenpi** [comment]
The [standard Markdown image syntax](https://docs.julialang.org/en/v1/stdlib/Markdown/#Images) should work for this:

```markdown
![](https://example.com/foo.png)
```

**Comment by tomchor** [comment]
Alright, thanks! I tried that before and it didn't work so I guess I must be doing something else wrong.

I'll close the issue.
