### ISSUE TITLE
Style `julia>` prompt

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#1639]
Wouldn't it be nice to style the prompt in `julia-repl`? highglight.js marks the prompt as `hljs-meta` which is a tag that is used for misc other things too, for example.

However, top level `meta`, which for the `julia-repl` grammar is just the prompt, can be selected by
```css
code.language-julia-repl > span.hljs-meta {
    // ...
}
```
(from https://github.com/highlightjs/highlight.js/issues/3261#issuecomment-874309303).

I suggest it should be colored with green just like the REPL.

**Comment by mortenpi** [comment]
Sounds good, but are we sure that we never get any other spans with `hljs-meta`?

**Comment by fredrikekre** [comment]
Yes, that is the only tag under the `julia-repl` grammar, everything else will be under plain `julia`: https://github.com/highlightjs/highlight.js/blob/1cb086b9509aa6af65e09a8936c5d93c9fe8178b/src/languages/julia-repl.js#L29-L38

**Comment by mortenpi** [comment]
Ah, yes, I see now. It puts a `<span class="language-julia">` around the whole sub-language, so that CSS should be completely safe.

**Comment by kimikage** [comment]
done in PR #1641
