### ISSUE TITLE
Modify "Edit on GitHub" links for specific pages

### ISSUE THREAD

**Issue by ranocha** [JuliaDocs/Documenter.jl#1650]
Thanks for providing this great package! I have a question on the "Edit on GitHub" links. In one of my packages, I copy the files LICENSE.md and CONTRIBUTING.md from the main folder to `docs/src` to include them in the documentation without creating redundant (and possibly outdated) versions of them, see https://github.com/ranocha/SummationByPartsOperators.jl/blob/e160657e25d0db19e43a8b2fa60dc09073b71b28/docs/make.jl#L9-L25 

However, the "Edit on GitHub" links included automatically in the documentation (via Documenter running on GitHub actions) will of course point to files in `docs/src`, which are not present. Is there a way to modify the "Edit on GitHub" links of these two specific pages of the documentation?

**Comment by fredrikekre** [comment]
https://github.com/JuliaDocs/Documenter.jl/issues/1620

**Comment by ranocha** [comment]
Thanks a lot for your quick reply! That fixed my problem.
