### ISSUE TITLE
Build freeze - CI timeout

### ISSUE THREAD

**Issue by t-bltg** [JuliaDocs/Documenter.jl#1652]
Hi, we're trying `Documenter@0.27.4` with `ansicolor` in https://github.com/JuliaPlots/PlotDocs.jl, but the build freezes on expansion of markdown templates.
I can reproduce this locally. Is there a way to debug the build other than setting env var `JULIA_DEBUG=Documenter` ?

See the corresponding issue: https://github.com/JuliaPlots/PlotDocs.jl/issues/248.

**Comment by fredrikekre** [comment]
Are you saying it does *not* freeze if you use 0.27.4 with `ansicolor = false`?

**Comment by t-bltg** [comment]
> Are you saying it does _not_ freeze if you use 0.27.4 with `ansicolor = false`?

Nope, I'm just saying that it freezes with `0.27.4`, but one major change is that we now use `ansicolor=true`. I tried a few days ago with https://github.com/JuliaDocs/Documenter.jl/commit/cd16ae19f4754eaa0416931933b8f882fcf33df8 and it worked. So I guess that the regression is between https://github.com/JuliaDocs/Documenter.jl/commit/cd16ae19f4754eaa0416931933b8f882fcf33df8 and now. I'll try now without `ansicolor` to see what happens.

**Comment by t-bltg** [comment]
Odd, I can now build locally, with https://github.com/JuliaDocs/Documenter.jl/pull/1656:

`1033.287926 seconds (1.13 G allocations: 49.676 GiB, 2.55% gc time, 0.39% compilation time)`

**Comment by fredrikekre** [comment]
> But it still fails on CI.

Even if you enable `@debug` output?

**Comment by t-bltg** [comment]
> > But it still fails on CI.
> 
> Even if you enable `@debug` output?

We did enable `@debug`: https://github.com/JuliaPlots/Plots.jl/blob/f9a1e2e92de63826d02ec55ef03c7e3d8d1b120c/.github/workflows/docs.yml#L47

**Comment by t-bltg** [comment]
Narrowed down to https://github.com/JuliaPlots/Plots.jl/issues/3664.

**Comment by mortenpi** [comment]
It looks like this is unrelated to Documenter then.

**Comment by t-bltg** [comment]
Not yet resolved, but yes, I guess it's reasonable  to close this.
