### ISSUE TITLE
can a doctest depend on an external file?

### ISSUE THREAD

**Issue by rkurchin** [JuliaDocs/Documenter.jl#1653]
I want to have a doctest demonstrating how to read in an object from a file, but I can't figure out how to specify the path to the file. I've tried putting a `cd` in the setup line but that errors in a somewhat opaque way. I created a dummy test that just runs `pwd()` to try to figure out where they're actually running but it prints a blank line. Is what I'm trying to do even possible?

**Comment by fredrikekre** [comment]
`pwd()` should be the output directory.

**Comment by rkurchin** [comment]
Could this have something to do with the fact that I'm trying to build the docs locally but they're set up to deploy online? There are a variety of approaches for doing that in #1413; would that matter? I can try to make an MWE for this but it would take awhile to figure out how to do...

**Comment by fredrikekre** [comment]
Maybe you are experiencing https://github.com/JuliaDocs/Documenter.jl/issues/921

**Comment by rkurchin** [comment]
I don't think so; it works fine if I specify an absolute path on my local system. But that obviously won't work for deployment purposes. I just need some way to figure out in what directory the doctests are actually running, but I don't know how to do that since `pwd()` doesn't print anything...

**Comment by fredrikekre** [comment]
> figure out in what directory the doctests are actually running

It should be the output directory of the markdown (well, html) file.

> since pwd() doesn't print anything...

Hmm, thats strange

**Comment by rkurchin** [comment]
Okay, so I was trying to make an MWE and the issue seems to have gone away. I have no idea what changed; I didn't even restart my REPL or anything. Sorry for the bother! 🤷‍♀️
