### ISSUE TITLE
Doctest are missing location information

### ISSUE THREAD

**Issue by vchuravy** [JuliaDocs/Documenter.jl#166]
I accidentally wrote a doctest while transitioning my package to Documenter.jl and I noticed that a failing doctest didn't have any information about where the test is defined.

**Comment by MichaelHatherly** [comment]
Thanks, just an oversight I think. We can add the filename to the error messages, but until the markdown parser in `Base.Markdown` gets taught about line numbers we won't be able to report those unfortunately.

I'll have a fix for the filenames shortly though.
