### ISSUE TITLE
@autodocs not including macro or struct

### ISSUE THREAD

**Issue by tbenst** [JuliaDocs/Documenter.jl#1666]
Hi, I'm a new user so apologies if I missed something in documentation--I'm wondering how to get Documenter to document a struct & macro that are exported? e.g. https://github.com/tbenst/Thunks.jl/blob/8f13f468c7b2b15b8cca4a33cb42df20cc18c20d/src/Thunks.jl#L120 exports `@thunk` but this is not generated.

Thank you!

**Comment by tbenst** [comment]
To clarify, I believe am following the manual (https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@autodocs-block), and have the following for my `index.md`:
~~~
```@meta
CurrentModule = Thunks
```

# Thunks

Documentation for [Thunks](https://github.com/tbenst/Thunks.jl).

```@index
```

```@autodocs
Modules = [Thunks]
Order   = [:function, :type, :macro]
```
~~~

Alas, no type or macro definitions appear.

**Comment by mortenpi** [comment]
Sorry for not looking into this earlier. I just tried out the latest commit and it looks like I can't reproduce it locally.

But it looks like your GitHub Pages settings are problematic: "No /docs folder was found to build GitHub Pages. Check the source setting for this repository." (https://github.com/tbenst/Thunks.jl/runs/3578057389). You need to make sure that GitHub pages is using the root of the `gh-pages` branch to serve the docs. I have a hunch that the current docs published at https://tbenst.github.io/Thunks.jl/dev/ are just outdated (they're generated on Thursday 5 August 2021 according to Documenter).
