### ISSUE TITLE
Incorrectly displayed version selector in non-versioned docs

### ISSUE THREAD

**Issue by hyrodium** [JuliaDocs/Documenter.jl#1667]
We can generate non-versioned docs since https://github.com/JuliaDocs/Documenter.jl/pull/1616 is merged. But in the following case, versions will be displayed incorrectly.

* `github.com/<user>/<user>.github.io` is versioned
* `github.com/<user>/<repo>` is non-versioned

In this case, `https://<user>.github.io/<repo>` shows a version selector of `github.com/<user>/<user>.github.io`.

**Comment by fredrikekre** [comment]
Do you have a live example? I don't really understand the issue.
