### ISSUE TITLE
Document what happens during deploydocs

### ISSUE THREAD

**Issue by goerz** [JuliaDocs/Documenter.jl#1668]
In the [documentation for the `deploydocs` function](https://juliadocs.github.io/Documenter.jl/stable/lib/public/#Documenter.deploydocs), I'm missing information on what exactly happens during the deployment to a `gh-pages` branch. My natural assumption would be that it simply copies the entire `docs/build` folder from the previous `makedocs` call to the appropriate `gh-pages` subfolder, e.g. `dev`. It seems like it might be skipping certain files (`.ipynb` files for example) in the process though, which is causing me [this problem](https://discourse.julialang.org/t/deploy-literate-non-html-files-with-documenter/66031) with deploying `Literate.jl`-rendered examples.

It would be great if the documentation could elaborate on the deployment process.

Also, I noticed that the documentation for `deploydocs` says

> Converts markdown files generated by makedocs to HTML and pushes them to repo.

Is that actually true, or ist that a "typo"? If true, it seems very confusing: doesn't `makedocs` do the conversion from markdown to HTML? Does `deploydocs` really perform any conversions of its own, or does it simply deploy the HTML files generated by `makedocs`?

**Comment by mortenpi** [comment]
Documentation improvements for the deployment stage would definitely be welcome.

> > Converts markdown files generated by makedocs to HTML and pushes them to repo.
> 
> Is that actually true, or ist that a "typo"?

That's just outdated. It used to be that `deploydocs` would call `mkdocs` to actually do the Markdown -> HTML conversion (Documenter only had the Markdown backend initially). It should be updated to say that it just pushes to `gh-pages`.

**Comment by goerz** [comment]
Thanks! From looking at the source code and adding some debug statements it's now clear that `deploydocs` really just copies the build folder to its destination and then commits it to `gh-pages`.

The problem I was seeing was that my build folder was containing an unexpected `.gitignore` that was preventing some files from being added to `gh-pages`.

I'll see if I can prepare an MR to improve the documentation a little in the near future. I'll leave this issue open until then.
