### ISSUE TITLE
Issue deploying Stable docs

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaDocs/Documenter.jl#1674]
I was browsing through: https://github.com/FluxML/GeometricFlux.jl/tree/master/docs and saw the stable docs 404. It is not clear to me why this is happening. I looked through some things like: https://github.com/JuliaDocs/Documenter.jl/issues/1257 

So all we need to do is tag a new release and it will resolve this? Is there anything on the documenter side that can be done to suggest this to users?

**Comment by KristofferC** [comment]
Seems fixed?
