### ISSUE TITLE
`:(using Catalyst)` in `DocMeta.setdocmeta!(` doesn;t work, but `setup = :(using Catalyst)` in individual block does 

### ISSUE THREAD

**Issue by TorkelE** [JuliaDocs/Documenter.jl#1677]
I am trying to create doctests for the Catalyst package.

I have this in my runtests file:
```julia
@time include("documentation.jl") 
```
the "documentation.jl" looks like this:
```
using Catalyst
using Documenter

DocMeta.setdocmeta!(
    Catalyst,
    :DocTestSetup,
    :(using Catalyst);
    recursive = true,
)
doctest(Catalyst)
```

and I currently have a single doctest

```
'''jldoctest; setup = :(using Catalyst)
repressilator = @reaction_network begin
    hillr(P₃,α,K,n), ∅ --> m₁
    hillr(P₁,α,K,n), ∅ --> m₂
    hillr(P₂,α,K,n), ∅ --> m₃
    (δ,γ), m₁ ↔ ∅
    (δ,γ), m₂ ↔ ∅
    (δ,γ), m₃ ↔ ∅
    β, m₁ --> m₁ + P₁
    β, m₂ --> m₂ + P₂
    β, m₃ --> m₃ + P₃
    μ, P₁ --> ∅
    μ, P₂ --> ∅
    μ, P₃ --> ∅
end α K n δ γ β μ;

# output
Model ##ReactionSystem#258 with 15 equations
States (6):
  m₁(t)
  m₂(t)
  m₃(t)
  P₁(t)
⋮
Parameters (7):
  α
  K
  n
  δ
⋮
'''
```

(using ' instead of ` so you can see the full text)

this works fine. But then I though the idea of adding `:(using Catalyst);` to the `DocMeta.setdocmeta!(` was to avoid having to do that for every block. However, if I use `'''jldoctest` isntead of `'''jldoctest; setup = :(using Catalyst)` I get an error including
```
│ ERROR: LoadError: UndefVarError: @reaction_network not defined
│ in expression starting at none:1
```
when I test.

It might be that I have misunderstood something here, or is there something that is not working as intended.

(I would have tried reating a more minimal example, but not sure how to do it in this case)

**Comment by mortenpi** [comment]
Is the doctest in a docstring or a documentation page? If the latter, you need to use [an at-meta block instead](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@meta-block) -- `setdocmeta!` only applies to docstrings.

**Comment by TorkelE** [comment]
The doctest is basically on this page: https://catalyst.sciml.ai/stable/tutorials/using_catalyst/ and the test is in this file: https://github.com/SciML/Catalyst.jl/blob/master/test/runtests.jl
(sorry for the non-direct description. I wasn't 100% sure what docstring and documentation page would mean in this context, but hopefully, from that it is obvious what I have)

I tried replacing the `setdocmeta!` with this:
```
using Catalyst
using Documenter

'''@meta
CurrentModule = Catalyst
DocTestSetup  = quote
    using Catalyst
end
'''

doctest(Catalyst)
```
(using ' in the code block to avoid escaping it)

however, the result is similar, if I remove `setup = :(using Catalyst)` then the content of `Catalyst` cannot be found when the block is run.

**Comment by mortenpi** [comment]
Sorry. What I meant by "documentation page" is that it is in one of the Markdown files under `docs/src` (which appears to be the case). The at-meta block should also go at the top of that Markdown file.

**Comment by TorkelE** [comment]
Thank you, yes that worked.
(also, this will allow me to work around https://github.com/JuliaDocs/Documenter.jl/issues/1678)
