### ISSUE TITLE
Doctest filter matches line by line by default

### ISSUE THREAD

**Issue by TorkelE** [JuliaDocs/Documenter.jl#1679]
I am trying to get the regex filter function to work for a simple doctest (with the goal of creating a filter which checks whenever there was an error or not).

Checking from here https://github.com/JuliaDocs/Documenter.jl/issues/452, it seems that `filter = r".*"` should create something which accepts any output. So I try:
(in all code blocks I will use ' to denote those things which create code in markdown, so to avoid messing up the formatting).
```julia
'''jldoctest; filter = r".*"
1
# output
1
'''
```
and 
```julia
'''jldoctest; filter = r".*"
1
# output
2
'''
```
which both works.

However, if I try anything a little bit complicated, it fails, e.g.
```julia
'''jldoctest; filter = r".*"
[1,2]
# output
2
'''
```

however, if it is a bit more similar, it does work:
```julia
'''jldoctest; filter = r".*"
[1,2]
# output
2-element Vector{Int64}:
 1
 3
'''
```
I also tried modifying the regex for multiple lines, e.g. `filter = r"\_.\{-}"`. Not sure whenever that is needed/correct though (in either case, didn't work)

**Comment by mortenpi** [comment]
I think the issue is that [the `replace` call here](https://github.com/JuliaDocs/Documenter.jl/blob/68dbd53d4ff6b339e795a4a3328955ad5c689e0e/src/DocTests.jl#L283) is not greedy enough and keeps line endings:

```
julia> replace("""
       foo
       bar
       """, r".*" => "")
"\n\n"
```

So in the end the strings that get compared have a different number of newlines, and so don't match.

**Comment by fredrikekre** [comment]
You can use the `s` modifier to let `.` match newlines (see docs for `@r_str`):
```
julia> replace("""
       foo
       bar
       """, r".*"s => "")
""
```

**Comment by TorkelE** [comment]
Just confirming that 
```julia
'''jldoctest; filter = r".*"s
[1,2]

# output

3
'''
```
works.

Thanks a lot!

**Comment by TorkelE** [comment]
Although maybe I was too fast. But the continuation problem might be separate, so created a new issue: https://github.com/JuliaDocs/Documenter.jl/issues/new

**Comment by mortenpi** [comment]
I'll re-open this to leave it as a documentation issue -- we should mention in the docs that the filtering happens line by line.
