### ISSUE TITLE
Deploydoc only hosting "dev" version

### ISSUE THREAD

**Issue by erathorn** [JuliaDocs/Documenter.jl#1680]
I have set up auto deployment of documentation for my repository using Documenter.jl and GitHubActions. I followed the instructions given [here](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions) in the official documentation.

However, only the `dev` version of the documentation gets generated. 

The newest release of the package was deployed after Documenter.jl set-up was added (#1257). 

Here are some relevant links:
- [Our repo](https://github.com/erathorn/MCPhyloTree.jl/)
- [Documentation](https://erathorn.github.io/MCPhyloTree.jl/dev/)

An abbreviated version of `make.jl` file looks as follows:

````
using Documenter, MCPhyloTree

makedocs(
    modules = MCPhyloTree,
    sitename="MCPhyloTree.jl",
    format = Documenter.HTML(),
    pages = [
       ...
        ]
   )

deploydocs(
    repo = "github.com/erathorn/MCPhyloTree.jl.git",
    devbranch="main"
     )
```

**Comment by fredrikekre** [comment]
CI didn't run at all for the tag, but not sure why. Did tagbot create the tag with the ssh key?

**Comment by erathorn** [comment]
I ran tag bot manually

**Comment by erathorn** [comment]
Okay. I guess I narrowed it down. It seems TagBot successfully runs, after releasing a new version. However, the new tag created by TagBot does not trigger the CI.

**Comment by fredrikekre** [comment]
I suspect https://github.com/erathorn/MCPhyloTree.jl/blob/356136396779c828128343daeb38b27366b463e2/.github/workflows/TagBot.yml#L15 is empty

**Comment by erathorn** [comment]
I redid the keys. I hope there is a new release soon, and I can check again. Manually triggering the workflows did not run CI.

**Comment by mortenpi** [comment]
You can also push tags that act as pseudo-releases to regenerate / test the documentation build. See the ["Fixing broken release deployments" box here](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Documentation-Versions).

**Comment by erathorn** [comment]
Thanks for the help. Everything works as expected now.
