### ISSUE TITLE
optionally exclude non-exported functions in @autodocs

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaDocs/Documenter.jl#169]
so that it would be much easier to separate documentation for public and internal API. Would it be much difficult to implement?

Cheers,
Carlo

**Comment by MichaelHatherly** [comment]
Shouldn't be too difficult, I've been meaning to get it done for a while. Thanks for reminding me, I'll try get to it in the next few days.

**Comment by CarloLucibello** [comment]
nice, thanks!

**Comment by MichaelHatherly** [comment]
(This will be part of a minor version bump sometime this weekend hopefully.)
