### ISSUE TITLE
MethodError: no method matching `getindex(::Nothing, ::Int64)`

### ISSUE THREAD

**Issue by timholy** [JuliaDocs/Documenter.jl#1698]
https://github.com/timholy/SnoopCompile.jl/pull/267/checks?check_run_id=3610545554 shows a MethodError from `report`. I haven't dug into this package yet, though. Seems to happen on both Julia 1.6 and nightly.

**Comment by fredrikekre** [comment]
Probably https://github.com/JuliaDocs/Documenter.jl/pull/1687 (cc @ericphanson ). [`lines` here](https://github.com/JuliaDocs/Documenter.jl/blob/50246d0f3dc9386254e5560184cac942077a826b/src/DocTests.jl#L404) is `nothing` if the source code can't be found (wonder why?).

**Comment by timholy** [comment]
One confusing thing about SnoopCompile is that SnoopCompileCore is a subdir package. Maybe that's it?
