### ISSUE TITLE
Issue embedding youtube videos in documenter

### ISSUE THREAD

**Issue by lucaferranti** [JuliaDocs/Documenter.jl#1701]
I am trying to add a youtube video to the documentation of my package. My first attempt was to do

````
```@raw html
<iframe width="560" height="315" src="https://www.youtube.com/embed/fre0TKgLJwg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```
````

but the style definitions for `iframe` defined in Documenter CSS overrode those. I also tried

````
```@raw html
<iframe style="width=560px; height=315px" src="https://www.youtube.com/embed/fre0TKgLJwg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```
````

that is, by explicitly defining the element style with the `style` attribute, but it still seems that Documenter CSS is taking precedence (maybe an `!important` somewhere)?

For references, the documentation in question: https://juliaintervals.github.io/IntervalLinearAlgebra.jl/stable/#Overview

**Comment by fredrikekre** [comment]
This works (`:` instead of `=`):
```
<iframe style="width:560px;height:315px" src="...."></iframe>
```

**Comment by lucaferranti** [comment]
🤦‍♂️🤦‍♂️ 🤦‍♂️  of course!! thank you
