### ISSUE TITLE
how to deploydoc with push_preview=false ?

### ISSUE THREAD

**Issue by ericqu** [JuliaDocs/Documenter.jl#1703]
I am using version 0.27.6. I am trying to deploy the docs to gh-pages (Github). 
I am using the Github action script mentioned in the documentation v0.27.6.

When I do:
```julia
deploydocs(
    repo = "github.com/ericqu/LinearRegression.jl.git",
    push_preview = true,
)
```

Then the docs are deployed in a ```previews``` directory as expected.

When ```push_preview = false```, then nothing happens.

As I am new to this, I probably do something wrong. What should I do?

Here is the output when nothing is deployed:
```
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: running doctests.
[ Info: ExpandTemplates: expanding markdown templates.
[ Info: CrossReferences: building cross-references.
[ Info: CheckDocument: running document checks.
[ Info: Populate: populating indices.
[ Info: RenderDocument: rendering document.
[ Info: HTMLWriter: rendering HTML pages.
┌ Info: Deployment criteria for deploying preview build from GitHub Actions:
│ - ✔ ENV["GITHUB_REPOSITORY"]="ericqu/LinearRegression.jl" occurs in repo="github.com/ericqu/LinearRegression.jl.git"
│ - ✔ ENV["GITHUB_REF"] corresponds to a PR number
│ - ✔ PR originates from the same repository
│ - ✘ `push_preview` keyword argument to deploydocs is `true`
│ - ✔ ENV["GITHUB_ACTOR"] exists and is non-empty
│ - ✔ ENV["GITHUB_TOKEN"] exists and is non-empty
└ Deploying: ✘
```

**Comment by ericphanson** [comment]
When `push_preview=false`, docs are only built when PRs are merged to the development branch (or a release is tagged). `push_preview=true` means *also* deploy docs from PRs.

**Comment by ericqu** [comment]
Hi @ericphanson, thank you for looking into this.

I checked again, and after I confirm the merge in github, the documentation does not appears in the gh-pages branch (the preview is still there). The other files in the PR are merged into the dev branch "main" in my case without any issue.
I thought maybe I should specify the dev branch using the ```dev_branch``` parameter but that did not help.
I noted that there is another script for tagged release, but I would like to generate the docs even if it is not a tagged release (for now at least).
Is there anything I should do, or information you need?

**Comment by ericphanson** [comment]
I think https://github.com/ericqu/LinearRegression.jl/pull/25 will fix one issue; otherwise the workflow isn't running when you commit to main. You'll also need the dev branch keyword argument too.

**Comment by ericqu** [comment]
Excellent, thank you! it is working now.
