### ISSUE TITLE
How do I pass the output of @eval @example @repl block to @raw html block

### ISSUE THREAD

**Issue by AbhimanyuAryan** [JuliaDocs/Documenter.jl#1713]
Now @eval is evaluating my expression 

```@repl ml
a = 234234
```

```@repl ml
HTML""" <p> $a hello world </p> """
```

But I want to pass the output to @raw html block so it ``renders`` the `<p>` tag with interpolated `$a` value from @repl @eval block

```@raw html
HTML""" <p> $a hello world </p> """
```
it should render `<p>` instead of just outputting execution 
![Screenshot 2021-10-15 at 2 29 03 PM](https://user-images.githubusercontent.com/8083613/137461961-d699d147-6469-4d88-91a0-0e83b23efcda.png)

I did something like this with `Literate.jl` and `Documenter.jl` and it output `<p>` tag with interpolated value of `a`
----------------
api.jl -> compiled with `make.jl`
```
a = 234

HTML(" <p> $a hello world </p> ")
```
How to achieve this with Documenter when not using Literate?

**Comment by fredrikekre** [comment]
`@repl` blocks mimic the Julia repl, and only support text/plain output. Use an `@example` block if you want rich output.
