### ISSUE TITLE
“Old documentation” banner shown for pre-release docs

### ISSUE THREAD

**Issue by sostock** [JuliaDocs/Documenter.jl#1726]
For example, the docs for Julia [1.7-rc2](https://docs.julialang.org/en/v1.7.0-rc2/) and [1.8-DEV](https://docs.julialang.org/en/v1.8-dev/) show the “This is an old version of the documentation. Go to the newest version.” banner with a link to the 1.6 docs, even though these versions are newer than 1.6.

The banner is added for all version numbers that are not equal to the newest version, even if they are newer:

https://github.com/JuliaDocs/Documenter.jl/blob/d2254ba3d6ac38b0147f500d4f346015ac1373ed/assets/html/warner.js#L18-L21

**Comment by fredrikekre** [comment]
The warning is changed to https://github.com/JuliaDocs/Documenter.jl/blob/d2254ba3d6ac38b0147f500d4f346015ac1373ed/assets/html/warner.js#L40
