### ISSUE TITLE
Ref's not resolving to markdown section

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaDocs/Documenter.jl#1733]
In this PR: https://github.com/FluxML/Flux.jl/pull/1785 I am trying to update the ref's for a few sections too point to places like: https://fluxml.ai/Flux.jl/previews/PR1785/training/training/#Loss-Functions but I am not sure how to get it to point there. The syntax seemingly works in some cases where I use the same syntax but in others it does not. Is this because there is a duplicate for the header? Do I need to add ID's per: https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#Duplicate-Headers

**Comment by mortenpi** [comment]
Quickly glancing at it, I think it was indeed because the headers were ambiguous. The at-ids could be used to work around that.
