### ISSUE TITLE
How to include the docstring for a function from another package in my Julia docs?

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaDocs/Documenter.jl#1734]
Cross posting my question / issue from here: https://stackoverflow.com/questions/70137119/how-to-include-the-docstring-for-a-function-from-another-package-in-my-julia-doc

**Comment by mortenpi** [comment]
I think this can be closed? As per the SO answer, having the other package in `docs/Project.toml` and passing it to `modules` should be sufficient to include the docstrings (we also do that for DocumenterTools when building Documenter's docs).

Another related issue is #688, which has to do with at-refing to docstrings hosted somewhere else.
