### ISSUE TITLE
Contrast for 'Note' text boxes in dark mode

### ISSUE THREAD

**Issue by jeremiahpslewis** [JuliaDocs/Documenter.jl#1736]
It seems like there might be a better CSS formatting for these modules in dark mode:

https://juliareach.github.io/LazySets.jl/dev/man/convex_hulls/#Test-point-in-convex-hull
<img width="899" alt="Screen Shot 2021-11-30 at 21 48 08" src="https://user-images.githubusercontent.com/4462211/144125757-74a40beb-8bad-4b1e-87a3-4bef096bb318.png">

**Comment by fredrikekre** [comment]
https://github.com/JuliaReach/LazySets.jl/blob/e4995d5e4cb91082463071b22f5ed1d058116fc6/docs/src/assets/juliareach.css#L7147-L7148
