### ISSUE TITLE
TagBot not tagging after adding DOCUMENTER_KEY

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaDocs/Documenter.jl#1737]
The setup is as follows: Documenters `make.jl` is living on `PlotDocs.jl` however when a release is tagged on `Plots.jl` corresponding documentation should be created.
I have a deploy key on `PlotDocs.jl` which corresponds to the `DOCUMENTER_KEY` secret on `Plots.jl` adding this to the TagBot configuration file as ssh key results in an error https://github.com/JuliaPlots/Plots.jl/runs/4480931845?check_suite_focus=true#step:3:49.

Do I miss something?

**Comment by fredrikekre** [comment]
The failure is from TagBot so I don't really understand what this has to do with Documenter? Does your key have write access?

**Comment by BeastyBlacksmith** [comment]
Well, I was following the Documenter documentation, thats why I opened the issue here.
The key has write access

**Comment by BeastyBlacksmith** [comment]
Do I need to add it as an organization deploy key? Since I can't add it as a Deploy Key to both Plots.jl and PlotDocs.jl

**Comment by fredrikekre** [comment]
The error is not when deploying docs, it is when TagBot tries to push the tag.

**Comment by BeastyBlacksmith** [comment]
Giving TagBot a different key fixed this, maybe we should add a note to the yellow box in the documentation to only reuse the documenter key if they are built for the same repository
