### ISSUE TITLE
Documentation build failing because of `Pairs` reference in precompile() call

### ISSUE THREAD

**Issue by droodman** [JuliaDocs/Documenter.jl#1738]
I hope that I am posting this in the right place, i.e., that my issue does in fact center on Documenter.jl. 

I just triggered an update of my package WildBootTests.jl to the general registry. For the first time I included precompile() statements generated by @timholy's  SnoopCompile.jl. The registration was [successful](https://github.com/JuliaRegistries/General/pull/50426) except that I received messages that the documentation build failed. It [choked](https://github.com/droodman/WildBootTests.jl/actions/runs/1573246097) on a [reference in the precompile()](https://github.com/droodman/WildBootTests.jl/blob/0156c4aa0f5051512c15df1f358f52470a154b7d/src/precompile_WildBootTests.jl#L57) statements to `Base.Pairs`.

I'd appreciate suggestions on how to fix this.

**Comment by KristofferC** [comment]
`Base.Pairs` doesn't exist on 1.6 it seems.

**Comment by fredrikekre** [comment]
`Base.Iterators.Pairs` work on both.
