### ISSUE TITLE
Make doctest report N tests for N jldoctest blocks

### ISSUE THREAD

**Issue by david-macmahon** [JuliaDocs/Documenter.jl#1739]
I just added a call to `doctest` in my package's `test/runtests.jl` script.  It works, but even though I have multiple `jldoctest` blocks in different doc strings, it only reports as running 1 test.  It would really motivate me to write more `jldoctest` blocks if it reported _N_ tests for _N_ `jldoctest` blocks.

The doc tests get wrapped in one `@test` so that's why they all get reported as 1 test.  It would be nice if each `jldoctest` block could be its own test.

**Comment by fredrikekre** [comment]
https://github.com/JuliaDocs/Documenter.jl/issues/1376

**Comment by david-macmahon** [comment]
Oops, sorry, I should have searched existing issues first.  Closing this issue as a duplicate of #1376.
