### ISSUE TITLE
Where is the documentation actually hosted?

### ISSUE THREAD

**Issue by Datseris** [JuliaDocs/Documenter.jl#1740]
I have a problem/bug/not sure. I am building and deploying documentation correctly from CI but I can't find the docs anywhere.

I have a repo that is not a Julia package, but builds documentation with Documenter. The documentation build is successful: https://github.com/JuliaDynamics/Agents.jl_Example_Zoo/runs/4573940055?check_suite_focus=true#step:8:3469 . The gh-pages branch successfully contains the build docs: https://github.com/JuliaDynamics/Agents.jl_Example_Zoo/tree/gh-pages 

However, when I look to where the documentation "should" have been deployed, I find nothing: https://juliadynamics.github.io/Agents.jl_Example_Zoo/dev/ . I've read the docbuild log but I don't seem to find the link of the webpage the documentation has been deployed into...

Not sure if relevant, but this repo has been renamed a couple of times in the past.

**Comment by fingolfin** [comment]
No repository https://github.com/JuliaDynamics/Agents.jl_Example_Zoo exists (anymore?), so it's hard to say what was happening here. Perhaps GitHub Pages were not enabled in the repository settings

**Comment by Datseris** [comment]
Oh damn, I forgot to close this. So, it turns out, outside of Documenter.jl business, you need to go to the settings of a new repository and click a checkbox on the "Pages" section, otherwise the hosting is not propagated to the webserver!
