### ISSUE TITLE
How do I cite Documenter.jl

### ISSUE THREAD

**Issue by ctkelley** [JuliaDocs/Documenter.jl#1742]
I want to cite Documenter.jl in a publication. The format I've been using is

```
@misc{documenter,
author="???",
title="{Documenter.jl}",
year=2021,
note="Julia Package",
howpublished="https://github.com/JuliaDocs/Documenter.jl"
}
```

Who should I be citing as author(s)?

**Comment by fredrikekre** [comment]
Perhaps the people in the license file?

**Comment by ctkelley** [comment]
OK. So is this ok?

```
@misc{documenter,
author="Michael Hatherly and Morten Piibeleht and Fredrik Ekre"
title="{Documenter.jl}",
year=2021,
note="Julia Package",
howpublished="https://github.com/JuliaDocs/Documenter.jl"
}
```

**Comment by fredrikekre** [comment]
Yea why not. Maybe add "and other contributors" or something.

**Comment by ctkelley** [comment]
OK. The "other authors" bit will confuse the publsher and copy editor, but I think I can deal with that.
