### ISSUE TITLE
Documenter unable to recognize certain functions

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaDocs/Documenter.jl#1744]
![Screenshot 2022-01-02 174733](https://user-images.githubusercontent.com/7881863/147891519-c6e170a5-0937-4082-b1e4-4a6a0c6ee831.png)
In my documentation, documenter is classifying some of the constructors as "type" instead of "method", and I'm not sure why.  Could anyone explain how documenter decides whether a constructor is a "type" or "method"?  If anyone would like to replicate my issue, please install the branch of the standard DataStructures package that I am currently revising:
```julia
julia> Pkg.add(PackageSpec(url="https://github.com/StephenVavasis/DataStructures.jl", rev="sortedcontainerupdates"))
```
then navigate to the `docs` directory and use `include("make.jl")`.    The file in which constructors are (sometimes) misclassified as "type" is docs/build/sorted_constainers/index.html.

Here is the source-code of an example of an offending constructor:

```julia
"""
    SortedMultiDict(iter, o::Ordering=Forward)
    SortedMultiDict(o::Ordering, iter)
    SortedMultiDict{K,V}(iter, o::Ordering=Forward) where {K, V}
    SortedMultiDict{K,V}(o::Ordering, iter) where {K, V}

Construct a `SortedMultiDict` from an arbitrary iterable object of
`key=>value` pairs or (key,value) tuples with order object `o`. The key type
and value type are inferred from the given iterable in the
first two forms.  The first two forms copy the
data three times, so
it is more efficient to explicitly specify `K` and `V` as in the
second two forms.  Time: O(*cn* log *n*)

"""
SortedMultiDict(kv, o::Ordering=Forward) = SortedMultiDict(o, kv)
SortedMultiDict{K,D}(kv, o::Ordering=Forward) where {K,D} =
    SortedMultiDict{K,D, typeof(o)}(o, kv)
SortedMultiDict{K,D}(o::Ordering, kv) where {K,D} =
    SortedMultiDict{K,D, typeof(o)}(o, kv)

function SortedMultiDict(o::Ordering, kv)
    c = collect(kv)
    if eltype(c) <: Pair
        c2 = collect((t.first, t.second) for t in c)
    elseif eltype(c) <: Tuple
        c2 = collect((t[1], t[2]) for t in c)
    else
        throw(ArgumentError("In SortedMultiDict(o,kv), kv should contain either pairs or 2-tuples"))
    end
    SortedMultiDict{eltype(c2).parameters[1], eltype(c2).parameters[2], typeof(o)}(o, c2)
end
```

The relevant line from sorted_containers.md is
```
(triplebackquote)@docs
SortedMultiDict(iter, o::Ordering=Forward)
(triplebackquote)
```

**Comment by StephenVavasis** [comment]
Following up on my own message, it appears that Documenter is able to recognize that 
```julia
SortedDict(iter, o::Ord=Forward) where {Ord <: Ordering}
```
is a function (constructor), whereas it is not able to recognize that the following is a function:
```julia
SortedDict(iter, o::Ordering=Forward)
```
Note that `Ordering` is an abstract type from Base.  I would say that this is a bug.

**Comment by mortenpi** [comment]
I would not surprised if this is going wrong sometimes (x-ref: #558, #1192), but I can't actually replicate this on the current DataStructures `master`. Is there an MWE that would demonstrate the issue?

**Comment by StephenVavasis** [comment]
I tried to replicate the bug today in an MWE but was not successful.  So I am going to close the issue.  Thanks for getting back to me.
