### ISSUE TITLE
Reenable auto-switching between light and dark theme

### ISSUE THREAD

**Issue by carstenbauer** [JuliaDocs/Documenter.jl#1745]
**Problem description:**
I find that once I’ve manually selected either the dark or light theme for a documentation there is no easy way to get back to automatic switching (based on my MacOS light/dark mode).

**Potential workaround:**
I guess one could get back auto-switching if one deletes the cache or so. However, that’s just annoyingly inconvenient.

**Suggested solution:**
Would it be possible to simply add an "auto" option (default) besides the light and dark theme options? That would be the simplest and most natural solution IMO.

(For reference: has been mentioned in [this discourse post](https://discourse.julialang.org/t/automatic-light-dark-theme-change-in-documentation/73864/3?u=carstenbauer) already.)

**Comment by fredrikekre** [comment]
A "system default" option makes sense and shouldn't be too difficult to implement if someone is familiar with some basic JavaScript.

**Comment by jebej** [comment]
Probably better to just use CSS for the default:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by mortenpi** [comment]
The default is based on the CSS media feature

https://github.com/JuliaDocs/Documenter.jl/blob/d2ed9b8b171e487835f456524e52799aa9da1d15/assets/html/themeswap.js#L14-L17

but this can be overridden by a user-defined value in `localStorage`, hence why the whole check is done in JS.
