### ISSUE TITLE
[FR] New way to customize LaTeX preamble

### ISSUE THREAD

**Issue by inkydragon** [JuliaDocs/Documenter.jl#1746]
People sometimes need to modify existing preamble sections to achieve some complex effects:
+ Adjusting the TOC style: [inkydragon/julia at doc-pdf-toc+compact-style](https://github.com/inkydragon/julia/tree/doc-pdf-toc%2Bcompact-style)
+ Add a cover page: [en-cover-page](https://github.com/inkydragon/Julia-LaTeX-doc/blob/7d7400595d474a468b50a019360c7cfc19b87612/doc-en/julia-doc-en.tex#L19-L34)
+ Add Chinese language support: [julia-doc-zh-cn.tex](https://github.com/inkydragon/Julia-LaTeX-doc/blob/master/doc-zh/julia-doc-zh-cn.tex#L1-L8)

I customize the preamble by overriding the `writeheader` function.

> Maybe Documenter could accept a keyword argument specifying the path to a custom `preamble.tex` and use its contents to replace the existing preamble.

_Originally posted by `@inkydragon` in https://github.com/JuliaLang/julia/issues/43698#issuecomment-1007244590_

**Comment by mortenpi** [comment]
I think it would be completely fine to add such an option to the `LaTeX` struct:

https://github.com/JuliaDocs/Documenter.jl/blob/bffc8665b9753ec7108b98b9788bef8a5cb4a482/src/Writers/LaTeXWriter.jl#L43-L49

**Comment by inkydragon** [comment]
Do we need to add a new `platform`?

Maybe we just need to add a new optional input file, like `custom.sty`.
