### ISSUE TITLE
Code copy button should stay in the top corner when scrolling horizontally

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#1758]
![Screenshot from 2022-01-24 12-38-59](https://user-images.githubusercontent.com/11698744/150776468-37ba3e03-8e9a-48a6-9f1d-4e90a1504d7f.png)

cc @pfitzseb

**Comment by pfitzseb** [comment]
Hm:
![image](https://user-images.githubusercontent.com/6735977/150778126-a838e674-08fb-4f1c-a214-b359576ae550.png)

What browser? Is that exact example uploaded somewhere?

**Comment by fredrikekre** [comment]
Firefox (on Linux). I found it here: https://aviatesk.github.io/EscapeAnalysis.jl/dev/#EA-Array-Analysis

**Comment by fredrikekre** [comment]
I saw a new failure mode for this:
![Screenshot from 2022-02-25 10-24-44](https://user-images.githubusercontent.com/11698744/155690260-4c8baba3-ccdd-4478-aa23-6b163fd6fc73.png)
but just noticed that was built without this fix, so probably it is fixed too.
