### ISSUE TITLE
Add Twitter summary card meta tags

### ISSUE THREAD

**Issue by mkitti** [JuliaDocs/Documenter.jl#1763]
We can enhance the visibility of Julia when someone links to documentation by adding a few meta tags to the generated webpages.

https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image

**Comment by mkitti** [comment]
Similarly for Facebook, one can use open graph metatags:
https://developers.facebook.com/docs/sharing/webmasters/

**Comment by fredrikekre** [comment]
Who uses Twitter and Facebook in 2022? :)

Anyway, twitter also uses open graph as a fallback according to the docs, so maybe that would be enough?

**Comment by fredrikekre** [comment]
#1321
