### ISSUE TITLE
How would be possible to add multiple-choice quizzes to documenter ?

### ISSUE THREAD

**Issue by sylvaticus** [JuliaDocs/Documenter.jl#1764]
Hello, for a course on Julia I use Moodle quizzes but I would migrate to have everything generated by Literate/Documenter.

Which technological stack would you envisage for creating quizzes within a Documenter generated site ?

At the best, the quiz would load some questions/answers from file (Moodle use the GIFT format), render the quiz and compute the grade for the user (all using JS I suppose)
At the minimum, the quiz is already "rendered" in a markdown page with some way to hide the correct answer until the user selects his/her reply....

**Comment by fredrikekre** [comment]
Closing as fixed by https://github.com/jverzani/QuizQuestions.jl from https://discourse.julialang.org/t/any-package-to-make-quizzes-for-students/75075.
