### ISSUE TITLE
Deprecation warning from Documenter.jl source code

### ISSUE THREAD

**Issue by juliohm** [JuliaDocs/Documenter.jl#1766]
Can you please confirm that this warning is already on your radar?

```
DEPRECATION WARNING on line 18 of /home/juliohm/.julia/packages/Documenter/Nu7Lp/assets/html/scss/documenter/components/_admonition.scss:
!global assignments won't be able to declare new variables in future versions.
Consider adding `$admonition-header-color: null` at the top level.
```

**Comment by juliohm** [comment]
I am triggering it whenever I build the GeoStats.jl docs in the master branch.

**Comment by fredrikekre** [comment]
https://github.com/JuliaEarth/GeoStats.jl/blob/392ac42e239ee71647c79b4e44cdc7ee5f069403/docs/make.jl#L14-L15

**Comment by juliohm** [comment]
@fredrikekre aren't these lines supported? What should I do?

**Comment by Datseris** [comment]
I get the same issue. These lines came from a long back and forth I had with @mortenpi about how to theme your own docs and they are what allows documentation pages to look different, e.g. https://juliadynamics.github.io/DynamicalSystems.jl/dev/ . If the way to theme your docpages has changed, please do let us know of the new way :)

**Comment by fredrikekre** [comment]
You can use a version of libsass that doesn't deprecate those things: https://github.com/JuliaDocs/Documenter.jl/commit/33c53bd43657dbbd26532b35646d842526a86ff8
