### ISSUE TITLE
Using `@ref` macro for a specific method's docstring

### ISSUE THREAD

**Issue by Datseris** [JuliaDocs/Documenter.jl#1767]
Documenter.jl allows expanding a docstring of a _specific method_ into an `@docs` block.

However, how would I refer to this specific method using `@ref`? Is this possible? If yes, it should be added here: https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@ref-link , if not, then consider this a feature request :)

**Comment by mortenpi** [comment]
Does ``[`foo(::Int)`](@ref)`` work by any chance?

But I think the at-ref needs a bit of work in general to make it more versatile (x-ref #781).
