### ISSUE TITLE
Option to show version in sidebar underneath sitename

### ISSUE THREAD

**Issue by goerz** [JuliaDocs/Documenter.jl#1768]
In the default theme, would it be possible to (at least optionally) show the version number underneath the `sitename` in the top left of the sidebar?

For example, I'd like to have https://juliaquantumcontrol.github.io/Krotov.jl/stable/ show `v0.1.0` just like https://qucontrol.github.io/krotov/v1.2.1/01_overview.html shows `v1.2.1`.

Especially in the `dev` folder (which is all a lot of packages use), there's no other indication what version of the documentation I'm looking at.

**Comment by mortenpi** [comment]
I would rule against this. If I remember correctly, the reason I moved the version selector to where it is now is because it jumps into existence a bit after the site loads (it needs to read `versions.js`). If it is under the site name, it makes the menu jump every time you open a new page.

As for making this optional: I think, in general, we do not want options to fiddle with small aspects of the layout. Perhaps in the future we'll have ways to customize the layout and theme more generally, which would allow for this kinds of customization.

**Comment by goerz** [comment]
Ok... I'm not sure I follow the argument, though. The version number for the *current* version would be rendered statically, unlike the dynamic version menu. For the time being, I'm getting around the problem of not knowing what version "dev" is referring to by putting the version in the [footer](https://juliaquantumcontrol.github.io/Krotov.jl/dev/). The version [is determined in `make.jl`](https://github.com/JuliaQuantumControl/Krotov.jl/blob/bbca39a50a670542996516c5914d951b406f9a0b/docs/make.jl#L17) from the compile-time `Project.toml` and [embedded in the footer](https://github.com/JuliaQuantumControl/Krotov.jl/blob/bbca39a50a670542996516c5914d951b406f9a0b/docs/make.jl#L32). So all that would be needed is a field in the template that's blank by default but can be set as an option to `makedocs`. It could even more general, like a "subtitle", just something that renders below `sitename` in a smaller font.

On the other hand, I understand not wanting to add too many micro-twiddle flags to the default template. Adding options to customize the template would definitely be a more general solution, and one that I'd love to see.

**Comment by orenbenkiki** [comment]
Version selection dropdown is nice and all, but I also fail to see the value of *not* clearly showing the version number of the documented package. I work around this by saying `sitename = "$NAME.jl v$VERSION"` after fetching `NAME` and `VERSION` from the `Project.toml` file. I don't see any reason why this shouldn't be the default behavior.

**Comment by goerz** [comment]
I mostly ended up working around this by

* putting the version in the [footer](https://github.com/JuliaDocs/DocumenterCitations.jl/blob/8bdabbdcc3313dc6e9d398e3c05994d6c31e3df8/docs/make.jl#L30)
* having a [version badge on the main page](https://juliadocs.org/DocumenterCitations.jl/stable/#DocumenterCitations.jl) ([source](https://github.com/JuliaDocs/DocumenterCitations.jl/blob/master/docs/src/index.md#documentercitationsjl))

I'd definitely still wouldn't mind to have the version shown in small/light gray between the site name and the search box. Especially since just the current version can be statically rendered, so I never followed the argument about it messing with the layout due to delayed loading. But I guess at this point I've just gotten used to Documenter's layout.

**Comment by orenbenkiki** [comment]
I did it annother way - when I generate documentation locally (to github pages), I added the version number to the `sitename`. Crude but effective.

I also don't get the point of the layout issue - this is a static short number which is as static as the package name itself, it doesn't have to be in a huge font, and I don't see the problem in adding it between the package name and the search box.
