### ISSUE TITLE
Too much space in multiline @repl block

### ISSUE THREAD

**Issue by SimonMandlik** [JuliaDocs/Documenter.jl#1770]
See: https://juliadocs.github.io/Documenter.jl/stable/showcase/#REPL-type

Is this intended?

**Comment by fredrikekre** [comment]
No.

**Comment by fredrikekre** [comment]
Looks like a CSS bug, maybe https://github.com/JuliaDocs/Documenter.jl/pull/1759 @pfitzseb ? It was not present in version 0.27.12.

**Comment by fredrikekre** [comment]
@pfitzseb I still see this in the light theme, but dark one is fixed. See e.g. https://julialogging.github.io/previews/PR1234/tutorials/logging-basics/

**Comment by pfitzseb** [comment]
That case happens because of the gruvbox code theme overwriting the CSS changes in here. Can you give https://github.com/JuliaDocs/Documenter.jl/pull/1774 a go?

**Comment by fredrikekre** [comment]
Ah okay. I thought they were pure color theme files...

**Comment by pfitzseb** [comment]
Yeah, same, but apparently not:
![image](https://user-images.githubusercontent.com/6735977/157407669-8463434d-1cae-494e-9c2a-2ff29e6e7e27.png)
