### ISSUE TITLE
Allow docs build on `schedule`

### ISSUE THREAD

**Issue by Ianlmgoddard** [JuliaDocs/Documenter.jl#1772]
Would it be possible to allow doc deploys on `schedule` jobs? Currently the only events that [trigger a docs build are `push` or `workflow_dispatch](https://github.com/JuliaDocs/Documenter.jl/blob/master/src/deployconfig.jl#L346). 

My use case: I have some examples in my package docs that pull and plot recent data, I think it would be nice if the docs had up to date plots. One possible way to do this is to set up the docs job to run on a schedule (via a github action), however this doesn't trigger a docs build because `schedule` events don't trigger builds. 

Maybe a kwarg could be added to `deploydocs`? so the user could control which events they'd like to trigger builds.

**Comment by fredrikekre** [comment]
Sure, do you want to make a patch? Should be roughly equivalent to this patch: https://github.com/JuliaDocs/Documenter.jl/commit/5f452f48ffe8e243bbac0d1f05b951f8de2755a9

**Comment by Ianlmgoddard** [comment]
Thanks for getting back to me, opened the PR #1773 (if that's not already obvious from above). 

I diverted a bit from https://github.com/JuliaDocs/Documenter.jl/commit/5f452f48ffe8e243bbac0d1f05b951f8de2755a9, because I thought the user would want control of whether or not to deploy the docs on `schedule` jobs. Happy to discuss here/on the PR.
