### ISSUE TITLE
Use Meta refresh instead of symlinks

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaDocs/Documenter.jl#1777]
Currently, Documenter uses two methods for redirecting:

1. `<meta http-equiv="refresh" content="0; url=./stable/"/>` in `index.html` _and_
2. A symlink for versions such as `v4.0` -> `v.4.0.1`

So, this requires static site systems to support both ways to redirect.

Could we replace the symlinks (2) by http refresh (1) by default or is there a reason why both methods are used?

**Comment by fredrikekre** [comment]
For 1., that is not really something that needs to be supported by the server side, right?

The reason for the symlinks is mostly that you want the URLs to be nice and "static"/independent of patches etc.

**Comment by rikhuijzer** [comment]
> For 1., that is not really something that needs to be supported by the server side, right?

You are right.

I've looked more into this and symlinks result in GitHub Pages returning a `301 Moved Permanently`. Compared to the meta refresh, this is better for search engines since they may consider meta refresh as spam.

So, essentially. My idea is a bad idea. I'll close this
