### ISSUE TITLE
Unexpected error expanding markdown with CodeTracking.jl's `code_string`

### ISSUE THREAD

**Issue by bennibolm** [JuliaDocs/Documenter.jl#1779]
When expanding a markdown file with CodeTracking.jl's function `code_string`
```
````@example example
using CodeTracking

f(x) = x
code_string(f, (Float64,))
```
I get the error `c.value = MethodError: no method matching getindex(::Nothing, ::Int64)`, while calling `code_string()` in the REPL, works perfectly.
This results in a failed documentation building process. Did someone get a similar error with CodeTracking.jl in the documentation?

**Comment by fredrikekre** [comment]
Can you post the full stacktrace?

**Comment by bennibolm** [comment]
I don't get a full stacktrace from Documenter.jl (do I?). Only this warning
```
┌ Warning: failed to run `@example` block in src\tutorials\example.md:10-15
│ ```@example example
│ using CodeTracking
│ 
│ f(x) = x
│ code_string(f, (Float64,))
│ ```
│   c.value = MethodError: no method matching getindex(::Nothing, ::Int64)
└ @ Documenter.Expanders C:\Users\benja\.julia\packages\Documenter\tUp2d\src\Expanders.jl:591
```
But I get the same error when calling `code_string()` with for instance JupyterNotebook. There I get the error:
![grafik](https://user-images.githubusercontent.com/74359358/158168950-4b5b734a-6a71-43ef-a534-87c86ea145f3.png)

**Comment by KristofferC** [comment]
The problem is https://github.com/timholy/CodeTracking.jl/blob/719d51d47cfd3a5ec007e0b0093a61824708eda0/src/CodeTracking.jl#L299 and `definition` returning `nothing`.

**Comment by mortenpi** [comment]
As far as I can tell, this is a genuine error being thrown by `code_string(f, (Float64,))`, so Documenter does everything right here I think?

**Comment by bennibolm** [comment]
Yes, you're right. Thanks.
