### ISSUE TITLE
`doctest(...; fix=true)` not working

### ISSUE THREAD

**Issue by eahenle** [JuliaDocs/Documenter.jl#1782]
The `fix=true` functionality has stopped working as it used to.  When attempting to update doctest outputs in this way, the result is now a warning (`Warning: could not find code block in source file` DocTests.jl:421) and the doc source files are unchanged.

Interestingly, _some_ changes do work.  Specifically, if the only changes are line ending characters, there is no problem, but if a snippet of output in the middle of a larger output block must change, the fix fails.

**Comment by AshlinHarris** [comment]
What OS were you using? I have the same issue on Windows, but not on Linux.

**Comment by odow** [comment]
Closing as a duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/1901
