### ISSUE TITLE
Documentation for a specific version never builds

### ISSUE THREAD

**Issue by Saransh-cpp** [JuliaDocs/Documenter.jl#1786]
My Julia package has 3 versions - `v0.1.0`, `v0.1.1`, and `v0.2.0`, but for some reasons, `Documenter.jl` never build the documentation for `v0.2.0`. It rather classifies `v0.1.1` as the stable version and stops right there. Is this a bug?

Documentation - https://saransh-cpp.github.io/ChaoticEncryption.jl
Releases - https://saransh-cpp.github.io/ChaoticEncryption.jl
JuliaHub - https://juliahub.com/ui/Packages/ChaoticEncryption/dtMkN

**Comment by fredrikekre** [comment]
The doc workflow didn't run on the tag push: https://github.com/Saransh-cpp/ChaoticEncryption.jl/actions/workflows/documentation.yml?query=event%3Apush

**Comment by Saransh-cpp** [comment]
Thank you! Didn't notice that. Is there a way to run the CI on that particular tag now? Also, was it a random coincidence (maybe GitHub Actions were down, or Julia's Ci had some problems) or is there something wrong with my docs workflow (https://github.com/Saransh-cpp/ChaoticEncryption.jl/blob/v0.2.0/.github/workflows/documentation.yml)?

**Comment by fredrikekre** [comment]
No I don't think so, you can only retrigger events that were triggered in the first place. You can push another tag on the same commit with build metadata (e.g. `v0.2.0+docs`) yourself. Documenter will remove whats after the `+`. You probably also want to add the deploy key to the doc workflow.

**Comment by Saransh-cpp** [comment]
Thank you! This worked! I have also added the `ssh` key for future!
