### ISSUE TITLE
Allow customizing deploy subfolder

### ISSUE THREAD

**Issue by ericphanson** [JuliaDocs/Documenter.jl#1790]
This way a repo with multiple packages can have independent documenter docs for each package, each deploying to a different subfolder on `gh-pages`. While more complicated than having a single set of documenter docs for all the packages in the repo, this setup would allow using tags like `mypackage/v0.1.0` to tag each package separately, and thus have stable docs for each package (pointing to different tags on the repo).

**Comment by fredrikekre** [comment]
This is already possible with the `dirname` keyword argument to `deploydocs` ([Julias manual deploys to `/en`, for example](https://github.com/JuliaLang/julia/blob/f41eed816f16d54482451754fb14681084fb3321/doc/make.jl#L385)).

**Comment by ericphanson** [comment]
Oh that's great, I didn't realize. Thanks!

**Comment by fredrikekre** [comment]
The tag part doesn't work though (xref https://github.com/JuliaRegistries/TagBot/issues/157).
