### ISSUE TITLE
Support custom tags for release docs

### ISSUE THREAD

**Issue by ericphanson** [JuliaDocs/Documenter.jl#1792]
If I have a subpackage in a repo (possibly more than one), I want to be able to build releases for a package based on tags like `MyPackage-v0.1.0` instead of just `v0.1.0` (since different packages might need different tags).

I thought this is what `versions` did in `deploydocs`, e.g.
```julia
versions = ["stable" => "MyPackage-v^", "MyPackage-v#.#", "dev" => "dev"])
```
but it's not. That's just for mapping from the words in the version-selector to the tags, but not about which tags it will actually deploy on. (Thanks @fredrikekre for clarifying this).

Right now, Documenter [uses](https://cs.github.com/JuliaDocs/Documenter.jl/blob/d2ed9b8b171e487835f456524e52799aa9da1d15/src/deployconfig.jl#L427) `Base.VERSION_REGEX` for determining if a tag is a version:
```julia
julia> Base.VERSION_REGEX
r"^
    v?                                      # prefix        (optional)
    (\d+)                                   # major         (required)
    (?:\.(\d+))?                            # minor         (optional)
    (?:\.(\d+))?                            # patch         (optional)
    (?:(-)|                                 # pre-release   (optional)
    ([a-z][0-9a-z-]*(?:\.[0-9a-z-]+)*|-(?:[0-9a-z-]+\.)*[0-9a-z-]+)?
    (?:(\+)|
    (?:\+((?:[0-9a-z-]+\.)*[0-9a-z-]+))?    # build         (optional)
    ))
$"ix

julia> occursin(Base.VERSION_REGEX, "MyPackage-v0.1.0")
false
```
But if we remove the `^` at the start,
```julia
julia> r = r"v?                                      # prefix        (optional)
           (\d+)                                   # major         (required)
           (?:\.(\d+))?                            # minor         (optional)
           (?:\.(\d+))?                            # patch         (optional)
           (?:(-)|                                 # pre-release   (optional)
           ([a-z][0-9a-z-]*(?:\.[0-9a-z-]+)*|-(?:[0-9a-z-]+\.)*[0-9a-z-]+)?
           (?:(\+)|
           (?:\+((?:[0-9a-z-]+\.)*[0-9a-z-]+))?    # build         (optional)
           ))
       $"ix;

julia> occursin(r, "MyPackage-v0.1.0")
true
````
it will match.

I don't think `version_tag_strip_build` will require any other changes to keep working, but I don't know the broader implications of such a change.

(Well, one is multiple subpackages could deploy on the same tags, so one might need to ensure only the right package builds on the right tag, e.g. by using the `tags` deploy trigger on GHA to specify a pattern)

**Comment by ericphanson** [comment]
We could add a `tag_prefix` argument to `deploydocs`, and make the regex into `tag_prefix * r` where `r` is the regex above. If `tag_prefix` defaults to `""`, then the current behavior is entirely unchanged. But one can pass `tag_prefix = "MyPackage-`, and obtain the behavior to have the feature here. This has the advantage that one doesn't need to know how to conditionally trigger doc builds on tags.

**Comment by mortenpi** [comment]
I agree that an option to `deploydocs` would be the way to go.

Another possibility would be to allow the user to pass a full regex, requiring it to have one capture group which would have to capture the pure version number (i.e. something like `tag_regex = r"^MyPackage-([0-9-+\.]+)$"`; optionally with a named capture group). More general, but at the same time more complicated for the user.
