### ISSUE TITLE
Use tectonic to build the pdf version of the manual

### ISSUE THREAD

**Issue by ViralBShah** [JuliaDocs/Documenter.jl#1802]
Given that tectonic is now in Yggdrasil, it might be nice to move towards using it for building the pdf version of the manual. I am also hearing more people recommending the use of tectonic.

Some discussion on how to do that is in https://github.com/JuliaDocs/Documenter.jl/pull/1785#issuecomment-1088766154

Once this is updated here, we can then use this mechanism in Julia itself, which is discussed in  https://github.com/JuliaLang/julia/issues/45027

**Comment by barucden** [comment]
Do you suggest to replace `latexmk` in the "native" compilation by `tectonic`?

**Comment by fredrikekre** [comment]
Could just be a new option entirely.

**Comment by ViralBShah** [comment]
Awesome. IIRC, to build the Julia manual, one also needed to install some ttf fonts. Should we just provide those through Yggdrasil artifacts as well? At that point, I believe we should be able to build the Julia manual pdf using our package system.

Should I open this issue on the julia repo to track what needs to be done?

**Comment by ViralBShah** [comment]
Or perhaps the solution is to use JuliaMono as discussed in https://github.com/JuliaDocs/Documenter.jl/issues/1791.

**Comment by inkydragon** [comment]
> to build the Julia manual, one also needed to install some [ttf fonts](https://github.com/JuliaDocs/Documenter.jl/pull/1785#issuecomment-1088904632).

Maybe we don't need to install the fonts manually, there are macro packages that provide them.
- [The LaTeX Font Catalogue – DejaVu Sans](https://tug.org/FontCatalogue/dejavusans/)

> Should we just provide those through Yggdrasil artifacts as well?

In the short term, only the Julia Mono font needs to be installed manually. So it's worth distributing it via Yggdrasil artifacts.

> Or perhaps the solution is to use JuliaMono as discussed in #1791.

Yes, we can discuss and decide on font selection and installation and usage in #1791.
Wait until `Documenter.jl` has merged the updates and released a new version, then go to the main julia repo and open a new pr.
