### ISSUE TITLE
GitHub Action documentation.yml template

### ISSUE THREAD

**Issue by baxmittens** [JuliaDocs/Documenter.jl#1812]
In [https://juliadocs.github.io/Documenter.jl/stable/man/hosting/](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/) there is a template for a documentation workflow.

By default the branch is 'master'. Shouldn't this be changed to 'main'? Or maybe add a note that this probably has to  be changed?

It took me ages to realize why my action was never triggered. 

Best, max

**Comment by fredrikekre** [comment]
Could add a comment about it, something like
```
- master # or main, or whatever name used for the development branch
```

Do you want to add that?

**Comment by baxmittens** [comment]
yeah something like that would be nice to prevent overreading that line like I did.

**Comment by baxmittens** [comment]
created a [pull request](https://github.com/JuliaDocs/Documenter.jl/pull/1813).
