### ISSUE TITLE
Excessive padding in some cases (bikeshedding)

### ISSUE THREAD

**Issue by KristofferC** [JuliaDocs/Documenter.jl#1814]
I feel that the padding used in some elements in the default style is a bit excessive and makes these element take up a lot of vertical space.

## Admonitions

![gnome-shell-screenshot-62tlxj](https://user-images.githubusercontent.com/1282691/167101770-ea66c960-e54f-4fb6-ae1b-12ab5ae5d789.png)

Looking at e.g. the docs for Python https://docs.python.org/3/whatsnew/3.10.html and adopting that (7px) would give:

![gnome-shell-screenshot-48ref4](https://user-images.githubusercontent.com/1282691/167101966-fda92593-689c-4635-91c7-52b1d83d57a8.png)

## Code blocks

![image](https://user-images.githubusercontent.com/1282691/167102988-00d2b8a7-5af7-4d59-ad3f-29c00ef9fc3c.png)

Going from 0.7 to 0.3 in the padding gives something like:

![image](https://user-images.githubusercontent.com/1282691/167102963-5918c925-e725-45e1-b70e-7bd42254f11d.png)

**Comment by mortenpi** [comment]
I can get behind reducing the padding in the admonitions for sure. It would also be nice if the left-padding of the content would align with the title. I am not sure I like making the padding this narrow though. Let me make a PR in the next week to bikeshed this a little further.
