### ISSUE TITLE
Formatting error in Documenter.jl documentation, section on "Custom preamble"

### ISSUE THREAD

**Issue by fingolfin** [JuliaDocs/Documenter.jl#1837]
Take a look at https://juliadocs.github.io/Documenter.jl/dev/man/other-formats/#Custom-preamble (same in the release version), it looks like this, which I assume is not what is intended:
<img width="828" alt="Screenshot 2022-06-03 at 12 29 01" src="https://user-images.githubusercontent.com/241512/171837330-e9a2b5c0-1258-4c3f-87c5-bd3444fa8476.png">

**Comment by fingolfin** [comment]
Also, the line ranges in the two final links are outdated. They should probably be 510-522 and 529-541.

I'd offer to submit a fix, but I don't understand what the exact problem is; other Markdown renderer show it fine, e.g. GitHub: https://github.com/JuliaDocs/Documenter.jl/blob/master/docs/src/man/other-formats.md#custom-preamble -- so perhaps this is a bug / missing feature in the Markdown conversion code used by Documenter.jl?

**Comment by mortenpi** [comment]
The Base Markdown parser doesn't support link reference definitions. This is just an oversight from the PR that added these docs.

**Comment by mortenpi** [comment]
To make sure the links don't get outdated again though, I think there are two options:

1. Actually include the necessary code samples in the documentation.
2. Use GitHub permalinks, even though these will eventually be pointing to very old commits.

(1) is probably preferred?
