### ISSUE TITLE
Semicolon after jldoctest changes help output to script-mode

### ISSUE THREAD

**Issue by DrChainsaw** [JuliaDocs/Documenter.jl#1843]
Example:

```julia
    """
    ```jldoctest
    julia> 1+1
    2
    ```
    """
    function testfun1() end
    
    """
    ```jldoctest; 
    julia> 1+1
    2
    ```
    """
    function testfun2() end
    
    """
    ```jldoctest aa;
    julia> 1+1
    2
    ```
    """
    function testfun3() end

```

 The docs for `testfun2` doesn't have the `julia>` prompt. Since this is the way advertised in the documentation for adding things like filter and other parameters maybe the behaviour should be clarified (unless its a bug).
```julia
help?> testfun1
search: testfun1 testfun3 testfun2

  julia> 1+1
  2


help?> testfun2
search: testfun2 testfun3 testfun1

  1+1
  3


help?> testfun3
search: testfun3 testfun2 testfun1

  julia> 1+1
  3
```

**Comment by mortenpi** [comment]
This is would not be a Documenter issue, but a limitation (or a bug) in Julia, as printing Markdown to the REPL is handled there.

However, I am actually not able to replicate this in Julia 1.7.3:

```
help?> testfun1
search: testfun1 testfun3 testfun2

  julia> 1+1
  2

help?> testfun2
search: testfun2 testfun3 testfun1

  julia> 1+1
  2

help?> testfun3
search: testfun3 testfun2 testfun1

  julia> 1+1
  2

julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3612QM CPU @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, ivybridge)
```

What Julia version are you running?

Or, maybe if you pasted the source snippet into the REPL, the `julia>` parts got removed? What if you put the snippet into a file and load it with `julia -i test.jl` (`-i` for interactive REPL after it has executed the script)?

**Comment by DrChainsaw** [comment]
Sorry, forgot to put the versioninfo in the issue. Here is is:

```julia
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 1
```

Functions are defined in a file which is loaded with `include` from the repl.

Could it be the windows boogeyman with its special line endings or whatnot?

**Comment by mortenpi** [comment]
I do vaguely remember that handling the `julia>` prompt on copy-paste was somehow different between Windows and Linux (although I may well be mistaken here), so it wouldn't be entirely surprising. What happens if you load from a file?
