### ISSUE TITLE
Docs dont mention reduce(... dims) reducedim.jl overload or any overloads?

### ISSUE THREAD

**Issue by unrabel** [JuliaDocs/Documenter.jl#1845]
[base/reduce.jl](https://github.com/JuliaLang/julia/blob/742b9abb4dd4621b667ec5bb3434b8b3602f96fd/base/reduce.jl#L425-L457)

I was looking for a reduce method with dimension options. Base documentation does not mention it and could not find it by searching in docs or google so I had given up and thought about maybe implementing a simple version. Only when messing around in REPL when i did ?reduce it also prints an overloaded version. Then i could find it in github through a google exact search. Reduce for dimentions is overloaded in another base package here: [base/reducedim.jl](https://github.com/JuliaLang/julia/blob/7dc132cf5a44717dbb619812dc05fd127c9d805a/base/reducedim.jl#L375) which cant be found on docs https://docs.julialang.org/en/v1/search/?q=reduce

This is more about how web docs are created i guess. REPL approach where it printed all? documentation for that function and its overloads seems better to me as it was challenging to figure out that it existed with no information on docs.

**Comment by mortenpi** [comment]
I think the methods just needs to be added into the at-docs block on the [relevant page](https://github.com/JuliaLang/julia/blob/master/doc/src/base/collections.md)?

**Comment by mortenpi** [comment]
https://github.com/JuliaLang/julia/pull/45788
