### ISSUE TITLE
Headings not always rendered

### ISSUE THREAD

**Issue by milankl** [JuliaDocs/Documenter.jl#1851]
I have some situations where a `### Heading` is consistenly not rendered (locally and on github pages), although all markdown rules seem to be followed
![image](https://user-images.githubusercontent.com/25530332/174303791-7f6c67e3-5c7e-40e4-b7ed-4b18529ec8a9.png)
I consequently get these `Warning`s but no other hint what's going wrong
```julia
┌ Warning: invalid local link: unresolved path in dynamical_core.md
│   link.text =
│    1-element Vector{Any}:
│     "Zonal derivative"
│   link.url = "@ref"
└ @ Documenter.Writers.HTMLWriter ~/.julia/packages/Documenter/HmHje/src/Writers/HTMLWriter.jl:2077
```
Any idea what's going on?

**Comment by fredrikekre** [comment]
Can you create a minimal example markdown file?

**Comment by milankl** [comment]
Haha, I even get this

![image](https://user-images.githubusercontent.com/25530332/174308402-847b951d-0fa5-42a7-ad7c-dc91f66d4c93.png)

with
```
# Title

## Heading 1

### Heading 2

Text

### Heading 3

Also text
```

What?? 😆

**Comment by milankl** [comment]
Okay now it gets spooky 👻 

![image](https://user-images.githubusercontent.com/25530332/174310871-d2f7a4e9-f9eb-442d-87d9-523e137dfd89.png)

I've deleted the `### Heading 2` written by hand another `### Heading 4` underneath and copied the working `### Heading 3` below that. Is it possible that VS Code somehow encodes them differently without displaying the difference?

**Comment by milankl** [comment]
Yeah, current working around is: I take a `### HeadingX` that renders fine, copy it into the place where the non-working heading is and change `HeadingX` to `HeadingY`, how weird??

**Comment by mortenpi** [comment]
It also looks like a parsing issue (so a problem in the Markdown stdlib), rather than a Documenter problem. What does `Markdown.parse_file` output when parsing these files?
