### ISSUE TITLE
Rebinding Module during DocChecks

### ISSUE THREAD

**Issue by louisponet** [JuliaDocs/Documenter.jl#1857]
Hi,

I ran into warnings while generating documentation for [FastLapackInterface](https://github.com/DynareJulia/FastLapackInterface.jl.git), due to the rebinding of certain functions from `LinearAlgebra.LAPACK`, to `FastLapackInterface` in this function:

https://github.com/JuliaDocs/Documenter.jl/blob/0d088e4b42a972bf710c158bed2d803500a6d31d/src/DocChecks.jl#L84

For example:
[LAPACK.getrf!](https://github.com/DynareJulia/FastLapackInterface.jl/blob/df66a83f61a7df457a8654e6d5a420a1e49cca49/src/lu.jl#L76) got rebound to `FastLapackInterface.getrf!`. 

This did not lead to any missing documentation, but it did cause warnings for all similar functions. I managed to fix it by explicitly importing them, but ideally I wouldn't have to.

Is this the desired behavior, if so, why?

Best,
Louis

**Comment by mortenpi** [comment]
When you say rebinding, are you just doing `const getrf! = LAPACK.getrf!` in a different module? And what warnings are you getting exactly? Do you happen to have an example build running on CI for example, or a branch I could try locally?

**Comment by louisponet** [comment]
Not quite. I mean that while running the DocChecks in Documenter it got rebound. Inside `FastLapackInterface` we had a `using LinearAlgebra: LAPACK`, and then overloaded the functions as `LAPACK.getrf!(...) = ...`. 
See:
[LAPACK.getrf!](https://github.com/DynareJulia/FastLapackInterface.jl/blob/df66a83f61a7df457a8654e6d5a420a1e49cca49/src/qr.jl#L79-L97)
and
[Docstring](https://github.com/DynareJulia/FastLapackInterface.jl/blob/df66a83f61a7df457a8654e6d5a420a1e49cca49/src/qr.jl#L153-L162)

The docstring gets added correctly through:
[LAPACK.md](https://github.com/DynareJulia/FastLapackInterface.jl/blob/df66a83f61a7df457a8654e6d5a420a1e49cca49/docs/src/LAPACK.md?plain=1#L5) 

But there are still warnings that they weren't as shown here:
[CI](https://github.com/DynareJulia/FastLapackInterface.jl/runs/7027605606?check_suite_focus=true#step:5:168)

The lines in `Documenter` I referenced in my initial post is where I found that the "binding" inside the document changes from `LinearAlgebra.LAPACK.getrf!` to `FastLapackInterface.getrf!`, which is why I linked it.
