### ISSUE TITLE
doctest for modules without documentation and for separate functions

### ISSUE THREAD

**Issue by xvries** [JuliaDocs/Documenter.jl#1868]
It would be nice to be able to run `doctest()` on:

1. A module without a `*/docs/src/` directory. Right now it throws an error. 
2. A separate function, in order to troubleshoot a single docstring.

**Comment by mortenpi** [comment]
For (1), you should be able to do it with `doctest(MyModule, manual = false)`. (2) would indeed be nice to have.

**Comment by odow** [comment]
Closing a duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/1213
