### ISSUE TITLE
Release branches

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaDocs/Documenter.jl#187]
From `v0.3.0` onwards use `release-*` branches for each minor version bump and use `master` as the unstable dev branch, similar to how Julia itself uses branches.

- [x] Document the use of `release-*` branches and `master` in `README.md`.
- [x] write down policy for backporting changes from `master` to `release-*` branches;
- [x] check that all packages listed in the examples page still work;
- [x] create branch `release-0.3` once all other `0.3` milestone tasks are complete;
- [x] then tag `v0.3.0` and publish to `METADATA.jl` and get on with `0.4` changes.

**Comment by mortenpi** [comment]
I was wondering how does Julia 0.4 support play into this. Will `0.3.x` be the branch where we'll maintain 0.4 support and drop it from master and future releases? Or will that be unrelated to this?

**Comment by MichaelHatherly** [comment]
Yes, we should be able to do that. `release-0.3` will just get bug fixes once released and the `REQUIRE` file will continue to contain `julia 0.4` as it does now. `master` will then change `REQURIE` to `julia 0.5`. I don't think we'll need to put any upperbounds on anything.

**Comment by MichaelHatherly** [comment]
Added the two new PRs to the `0.3` milestone. Once those are sorted we should branch and tag `0.3`.

**Comment by MichaelHatherly** [comment]
Most of the example packages seem to build fine on current `master`. There's a couple of problems here and there that don't appear to be related, so we're good to branch and tag now I think.

@mortenpi, would you like to do the honours? (Create a new `release-0.3` off `master`, push it, and then tag `0.3.0` while on that branch.)

**Comment by mortenpi** [comment]
Can do!

**Comment by MichaelHatherly** [comment]
Closed by https://github.com/JuliaLang/METADATA.jl/pull/6042.
