### ISSUE TITLE
Add Woodpecker in deployments

### ISSUE THREAD

**Issue by uncomfyhalomacro** [JuliaDocs/Documenter.jl#1878]
~~Add support for deploying docs in Gitea instances such as Codeberg.~~
Add woodpecker in doc deployments

**Comment by mortenpi** [comment]
I don't have any personal experience with Gitea. A couple questions that pop into my head:

1. Does it have some GitHub Pages type feature for hosting static websites?
2. How does CI work there usually?
3. Any public examples of Julia packages hosted there that would like to take advantage of this?

**Comment by uncomfyhalomacro** [comment]
> I don't have any personal experience with Gitea. A couple questions that pop into my head:
> 
>     1. Does it have some GitHub Pages type feature for hosting static websites?
> 
>     2. How does CI work there usually?
> 
>     3. Any public examples of Julia packages hosted there that would like to take advantage of this?

Sorry I was thinking about something else. I was talking about adding https://woodpecker-ci.org

**Comment by uncomfyhalomacro** [comment]
So to answer the following questions:
1. https;//codeberg.org supports some form of Pages -> https://docs.codeberg.org/codeberg-pages/
2. Gitea can use any CI. Codeberg is community gitea and they use Woodpecker CI, a clone of Drone.
3. Probably my package or other future packages. here is a sample https://codeberg.org/uncomfyhalomacro/SBOL3.jl/src/branch/pages. Although I have got around using hacks through the woodpecker config i made here https://codeberg.org/uncomfyhalomacro/SBOL3.jl/src/branch/main/.woodpecker/.docs.yml

**Comment by uncomfyhalomacro** [comment]
I can probably open a PR to add Woodpecker. it shouldn't be that hard I suppose

**Comment by mortenpi** [comment]
As for hosting on Gitea/CodeBerg, it looks like it's similar to GitHub --- you just push to a branch of the same repo (with `branch = "pages"` in `deploydocs`). As long as it also supports some deploy keys, it should be easy to set up.

For Woodpecker, it should just be necessary to create the corresponding `DeployConfig` (e.g. [see the GHA one here](https://github.com/JuliaDocs/Documenter.jl/blob/def95680d89ba2ace3275a8e3fb88df1fc28d999/src/deployconfig.jl#L265-L424)). In fact, you should be able to do it all in your `make.jl`, without having to modify Documenter at all, to test it out.

**Comment by uncomfyhalomacro** [comment]
Sure! I should try that on my project first by modifying my make.jl with
the necessary `DeployConfig` to test that out.

**Comment by uncomfyhalomacro** [comment]
Closing in favor of #1880

**Comment by fredrikekre** [comment]
Can be kept open until that is merged.
