### ISSUE TITLE
Control the "edit on Github" link?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#1893]
A lot of times, like in https://docs.sciml.ai/dev/modules/DiffEqDocs/extras/timestepping/, the edit on Github button is incorrect. It would be nice to be able to manually redirect it.

**Comment by fredrikekre** [comment]
Solved 4 years ago: https://github.com/JuliaDocs/Documenter.jl/pull/700 :slightly_smiling_face: 

````
```@meta
EditURL = "https://whatever.com"
```
````
