### ISSUE TITLE
Throw warning for improper math environment

### ISSUE THREAD

**Issue by andrewwinters5000** [JuliaDocs/Documenter.jl#1897]
I was recently writing an `@doc raw"""` string with some LaTeX commands for a project. In doing so I accidentally wrote a faulty math environment with an extra single quote. That is, my math environment block started with ```math  but ended with ````.

Subsequently, the docstring I wrote was not parsed properly in the `autodocs`. When I queried the function name with the help command in the REPL the docstring showed up, but was formatted strangely (this is how I found my typo).

Is it possible for Documenter to throw a kind of "Mismatched delimiters" warning or so, similar to a LaTeX compiler? This would have made tracking down my typo in the docstring easier.

**Comment by mortenpi** [comment]
Not really. Documenter doesn't really deal with the Markdown source itself, as it just takes the AST from the Markdown standard library parser.

In any case though, a bigger problem here is that any sequence of characters is valid Markdown, so a parser can't really tell whether something is a mistake or not. I suppose theoretically you could have some heuristics that issue warnings on the parser level, but neither Markdown nor CommonMark.jl have support for something like this. And it's not something we can do in Documenter anyway.

**Comment by andrewwinters5000** [comment]
Okay, thanks for your quick response!
