### ISSUE TITLE
No space between text and code in breadcrumb

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#1902]
![Screenshot from 2022-08-14 18-41-59](https://user-images.githubusercontent.com/147757/184525681-eae53a61-bfe6-4a53-99fa-fc629c267fe2.png)

Seems to be because the `flex` layout of the breadcrumb makes the `<code>` element have `display: block`. Disabling the `display: flex` on the surrounding element seems to fix it, but probably causes other issues.

**Comment by fredrikekre** [comment]
#1614

**Comment by mortenpi** [comment]
Note to self: search works even if my long-term memory doesn't.
