### ISSUE TITLE
copy button: remove `julia>` prompt ?

### ISSUE THREAD

**Issue by t-bltg** [JuliaDocs/Documenter.jl#1920]
When hitting the copy button added in https://github.com/JuliaDocs/Documenter.jl/pull/1748, the `julia>` prompt prefixes are retained, hence erroring out when pasted in the repl.

E.g. copy/paste the `julia-repl` block in https://docs.juliaplots.org/stable/api/#Plots.surface-Tuple.

**Comment by fredrikekre** [comment]
The Julia REPL itself usually scrubs these. Perhaps that requires a terminal that supports bracketed paste mode? cc @KristofferC

**Comment by t-bltg** [comment]
> The Julia REPL itself usually scrubs these. 

Mmmh, I don't know what went wrong: I've ran another terminal instance, restarted julia and it works as expected.

I'm very sorry for the noise.
