### ISSUE TITLE
Overfull elements in LaTeXWriter

### ISSUE THREAD

**Issue by odow** [JuliaDocs/Documenter.jl#1930]
The JuMP documentation (https://jump.dev/JuMP.jl/stable/JuMP.pdf) has a bunch of examples where the text is overfull. Are there any tools in Documenter to improve the layout of things? 

I guess the hard part is dealing without put from types (like dataframes) which implement `show(io, ::MIME"text/latex", x::MyType)`, but perhaps every output should have a `\resizebox{\textwidth}{!}{...}` around it? It's probably better to have things too small than to go off the page.

## Equations

<img width="704" alt="image" src="https://user-images.githubusercontent.com/8177701/190057741-7e764700-ebec-4e76-8d2e-09ce41326fd8.png">

## DataFrame tables

<img width="704" alt="image" src="https://user-images.githubusercontent.com/8177701/190057771-39a572e6-4d89-44da-98e1-e573ac6d7265.png">

## In-line code `snippets`

<img width="704" alt="image" src="https://user-images.githubusercontent.com/8177701/190057963-20c4821b-9b83-48ef-92ef-7cf58bde9306.png">

**Comment by mortenpi** [comment]
No tooling per se, but you [can set `DOCUMENTER_LATEX_DEBUG`](https://github.com/JuliaDocs/Documenter.jl/blob/6b8f8f917bdfdbb3a095fe1eb380b4c614b489cc/src/Writers/LaTeXWriter.jl#L147-L154) to get the source files and play with them.

`\resizebox` seems like a good solution for this, but would it also not make small things bigger?

**Comment by odow** [comment]
A good option might be `adjustbox`: 

 * https://tex.stackexchange.com/questions/329223/shrink-table-with-adjustbox-and-handling-booktabs-margins
 * https://ctan.org/pkg/adjustbox?lang=en

```
\usepackage{adjustbox}

\begin{document}

\adjustbox{max width = \textwidth}{
\begin{tabular}{c c c c c}
A very very wide table & A very very wide table & A very very wide table & A very very wide table & A very very wide table\\
A very very wide table & A very very wide table & A very very wide table & A very very wide table & A very very wide table\\
\end{tabular}
}
```

It's in `texlive-latex-extra` so it should be installed by default (#1931): https://packages.debian.org/bullseye/tex/texlive-latex-extra
