### ISSUE TITLE
Styling of admonitions in LaTeXWriter

### ISSUE THREAD

**Issue by odow** [JuliaDocs/Documenter.jl#1931]
The styling of admonitions in the latex writer does't make them stand out: 

![image](https://user-images.githubusercontent.com/8177701/190065805-2344e8d9-3c0d-45cf-92c9-60d1704c5317.png)

It's just a `quote` with `textbf` for the header:
https://github.com/JuliaDocs/Documenter.jl/blob/6b8f8f917bdfdbb3a095fe1eb380b4c614b489cc/src/Writers/LaTeXWriter.jl#L568-L576

If we used something like https://ctan.org/pkg/tcolorbox?lang=en, we could have:
```
\begin{tcolorbox}[colback=red!5!white,colframe=red!75!black,title=Tip]
If you aren't sure if you should use JuMP, read "Should I use JuMP?"
\end{tcolorbox}
```

<img width="349" alt="image" src="https://user-images.githubusercontent.com/8177701/190066008-9de1a354-3025-4399-9fd6-c230f9ef2bd6.png">

Is there a workflow for adding new dependency packages? Do we have to update the docker image?

**Comment by mortenpi** [comment]
We install `texlive-latex-base`, `texlive-latex-recommended` and `texlive-latex-extra`, so if it is in one of those, updating the [Docker image](https://github.com/JuliaDocs/DocumenterLaTeX.jl/blob/master/docker/Dockerfile) shouldn't be necessary.

**Comment by mortenpi** [comment]
The package itself should be loaded here: https://github.com/JuliaDocs/Documenter.jl/blob/master/assets/latex/documenter.sty

**Comment by odow** [comment]
> We install texlive-latex-base, texlive-latex-recommended and texlive-latex-extra, so if it is in one of those

Oh, nice. This may help the table issue (#1930) as well then.

**Comment by odow** [comment]
`tcolorbox` is in `texlive-latex-extra`: https://packages.debian.org/bullseye/tex/texlive-latex-extra

So this should be reasonably easy to implement.
