### ISSUE TITLE
Styling of code blocks in LaTeXWriter

### ISSUE THREAD

**Issue by odow** [JuliaDocs/Documenter.jl#1933]
The styling of code blocks in the PDF output could be improved: it's hard to distinguish code from text, and code that should be typed from output. Here are some examples from the JuMP documentation: https://jump.dev/JuMP.jl/stable/JuMP.pdf.

 ---

<img width="374" alt="image" src="https://user-images.githubusercontent.com/8177701/190283301-dcef540f-67c5-4d3e-99b4-0a896bccfbd3.png">

---

<img width="487" alt="image" src="https://user-images.githubusercontent.com/8177701/190283207-9ab18680-2452-43ea-aa4a-9d93febd2c6f.png">

---

## Suggestions

This is pretty easy to fix, because it just involves changing 
https://github.com/JuliaDocs/Documenter.jl/blob/00b9f75ee7275f72f1ed4d289d8239308db8769d/assets/latex/documenter.sty#L34-L48

So the hard part is deciding what it should be changed to. Here are some suggestions:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/8177701/190283827-a951ace9-3822-47da-8d54-6554b5e96e5d.png">

I'd probably vote for 3 or 6.

**Comment by odow** [comment]
I realized we can implement this with a `custom.sty` file for Option 6. 

Here's the PR to MOI: https://github.com/jump-dev/MathOptInterface.jl/pull/1999

Preview link: https://jump.dev/MathOptInterface.jl/previews/PR1999/MathOptInterface.pdf

I think it looks a lot better:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/8177701/190290756-d078e511-09e9-47be-8d8b-46965e522ff1.png">

but there are a few weird top-margin issues (I think it happens when the code is the first item in a paragraph?):

<img width="484" alt="image" src="https://user-images.githubusercontent.com/8177701/190290862-8e6c0ac4-d64d-487b-93b4-06b4ad154cce.png">

and docstrings expose the fact that the first indent is treated as `{julia}` but the rest are treated as unstyled code block. (This is our fault.)

<img width="484" alt="image" src="https://user-images.githubusercontent.com/8177701/190290907-193d6964-e32a-44cd-948f-d394ee06ddec.png">

**Comment by mortenpi** [comment]
Yeah, I think having just some background color looks much better. And I think it actually looks better to not have any lines/borders. What are you thinking about doing with the outputs though?

> and docstrings expose the fact that the first indent is treated as {julia} but the rest are treated as unstyled code block. (This is our fault.)

Is this #1101, or do you actually have multiple code blocks in a single docstring?

**Comment by odow** [comment]
> I think having just some background color looks much bette

Yip. For code, plain background no borders.

> What are you thinking about doing with the outputs though?

I've played around, but I haven't convinced myself of anything yet.

> do you actually have multiple code blocks in a single docstring?

We have multiple:

https://github.com/jump-dev/MathOptInterface.jl/blob/2aba5d5450b3a5931ff557cb8969efc2987b3ffd/src/attributes.jl#L209-L247

**Comment by odow** [comment]
I'm building the JuMP docs, https://github.com/jump-dev/JuMP.jl/pull/3075, which should give a much larger set of examples to look over (takes an hour to build though).

**Comment by odow** [comment]
I had a look at the top-margin issue. It's because of an interplay with our use of `\nonzeroparskip`. I don't fully understand the calculations, because the background is only wrong when the `{minted}` block is the first in a section. I think that's reasonable though, we should lead in with some text and not have orphaned code sitting alone in a section.

The bigger issue is that it also happens in the docstrings. But we can potentially improve things in #1101 anyway.

**Comment by odow** [comment]
What about a `single` frame around the output:

<img width="420" alt="image" src="https://user-images.githubusercontent.com/8177701/190300499-42adf9a2-ca62-4d2d-94dd-4e1aae2b9442.png">

Or perhaps we should keep the same styling, and add a different way of showing the output.

**Comment by odow** [comment]
So this actually looks quite good:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/8177701/190308448-c295e34e-b970-4c62-be00-6009c70b6568.png">

But the downside is it also frames any other ` ``` ` block:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/8177701/190308314-4a318500-59b9-4bcc-b2ee-94c50ed02a9a.png">

and 

<img width="464" alt="image" src="https://user-images.githubusercontent.com/8177701/190308564-87d0e5d2-7e3f-4089-8f19-76465e500bb6.png">

**Comment by odow** [comment]
I think I have a winner (I ended up just copying the HTML style)

<img width="628" alt="image" src="https://user-images.githubusercontent.com/8177701/190509598-9b7fdd49-d8cc-45d8-ab21-3f0583f70232.png">

https://jump.dev/JuMP.jl/previews/PR3075/JuMP.pdf

There's a few weird things, like if you have a ` ``` ` box by itself:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/8177701/190509741-5668e535-a8bf-4f81-9bd5-76563a117948.png">

but this is much better than before.

**Comment by mortenpi** [comment]
That looks great. The background and border colors could potentially be a little darker? Although I haven't seen in the PDF -- the preview PDF seems to have deleted itself.

> There's a few weird things, like if you have a ``` box by itself:

Are you just checking for an empty `.language/.info` attribute right now? In the HTML we specifically only apply the white background to the output blocks, in the `MultiOutput` writer: https://github.com/JuliaDocs/Documenter.jl/blob/master/src/Writers/HTMLWriter.jl#L2115

Do you think it would also make sense to do that here, and give gray background for the normal blocks, even ones that are not highlighted?
