### ISSUE TITLE
Greek letters mangled in LaTeXWriter

### ISSUE THREAD

**Issue by odow** [JuliaDocs/Documenter.jl#1936]
These are `@example` blocks in the JuMP documentation:

````
```@example
π
```
```@example
typeof(π)
```
````

<img width="628" alt="image" src="https://user-images.githubusercontent.com/8177701/190370932-269097d8-b1d7-4718-8c15-ea1c85a2ec49.png">

Note the new line after the first π and the incorrect location of π in the output of the `typeof` cell.

REPL is
```julia
julia> π
π = 3.1415926535897...

julia> typeof(pi)
Irrational{:π}
```

**Comment by odow** [comment]
The `.tex` file is correct without any spurious new line or escape characters:
```
\begin{lstlisting}
π = 3.1415926535897...
\end{lstlisting}
```
so this is a known problem with unicode in the `{lstlisting}` environments: 
https://tex.stackexchange.com/questions/24528/having-problems-with-listings-and-utf-8-can-it-be-fixed

Given the prevalence of unicode in Julia output, I think we might need to consider an alternative package/environment.

**Comment by mortenpi** [comment]
> Given the prevalence of unicode in Julia output, I think we might need to consider an alternative package/environment.

That sounds reasonable.
