### ISSUE TITLE
Use HTML renderer for docs

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaDocs/Documenter.jl#194]
Now that #171 is merged it would be good to start using it for our own docs. @mortenpi would you like to do the honours?

**Comment by mortenpi** [comment]
I'm looking into this by the way, just trying stuff out to make sure that nothing breaks with the HTML build. However, in principle, setting
```
target = "build",
deps   = nothing,
make   = () -> nothing,
```
in `deploydocs` should actually sufficient, right?

**Comment by MichaelHatherly** [comment]
`cleandir` is run on the `target` prior to `make` (https://github.com/JuliaDocs/Documenter.jl/blob/e20b1f8187cc140f568c424d07d4bf04117c0d28/src/Documenter.jl#L308), so I don't think that would be sufficient.

I'm also trying this out on DocStringExtensions (https://github.com/JuliaDocs/DocStringExtensions.jl/compare/mh/htmldocs?expand=1) to see what would work.

**Comment by MichaelHatherly** [comment]
If we just remove the `cleandir` call things should probably be fine, since a fresh travis clone shouldn't have anything in that directory I suppose. That would mean we can use your approach from above.

**Comment by MichaelHatherly** [comment]
And we could probably add a `make === nothing` check like for `deps` so that it would just be

```
target = "build",
deps = nothing,
make = nothing,
```

**Comment by MichaelHatherly** [comment]
#197 appears to do the right thing I think. Tested on https://michaelhatherly.github.io/DocumenterTests.jl/latest/index.html.

**Comment by mortenpi** [comment]
Yup. I tested it with http://mortenpi.eu/Hafta.jl/latest/ and it also seems to work.
