### ISSUE TITLE
CI failures when trying to push a doc preview

### ISSUE THREAD

**Issue by jlchan** [JuliaDocs/Documenter.jl#1961]
We've started seeing some CI Documentation failures recently in Trixi.jl. These failures occur when trying to push a Documentation preview where the PR comes from a fork and not the main repository (for example, https://github.com/trixi-framework/Trixi.jl/actions/runs/3195919016/jobs/5217171204#step:6:1244). 

I'm not sure if this was due to changes in Documenter.jl (the most recent version v0.27.23 was released before we started seeing these failures), but is there a reason that these CI failures started happening recently?

**Comment by jlchan** [comment]
cc: @ranocha @sloede?

**Comment by fredrikekre** [comment]
Nevermind, that variable is not what I thought it was. I think the problem is https://github.com/trixi-framework/Trixi.jl/actions/runs/3195919016/jobs/5217171204#step:6:910 and I can only assume it was a transient failure when connecting to github or something like that.

**Comment by fredrikekre** [comment]
Github had some errors the last two days: https://www.githubstatus.com/history.

**Comment by ranocha** [comment]
Let's hope it's just some temporary failure of GitHub

**Comment by fredrikekre** [comment]
FYI, turned out to be GR causing problems: https://github.com/jheinen/GR.jl/issues/478
