### ISSUE TITLE
CI failures, preview related (in pull requests, not on master)

### ISSUE THREAD

**Issue by t-bltg** [JuliaDocs/Documenter.jl#1965]
Maybe related to https://github.com/JuliaDocs/Documenter.jl/issues/1961, as discussed on slack, we have also the following curl error, setting `JULIA_DEBUG=Documenter` provides the following stacktrace:
```julia
┌ Debug: Running CURL led to an exception:
│   exception =
│    failed process: Process(`curl -s -S GET -H 'Authorization: token ***' -H 'User-Agent: Documenter.jl' -H 'Content-Type: application/json' --fail https://api.github.com/repos/JuliaPlots/PlotDocs.jl/pulls/306`, ProcessExited(1)) [1]
│    
│    Stacktrace:
│      [1] pipeline_error
│        @ ./process.jl:565 [inlined]
│      [2] run(::Base.CmdRedirect; wait::Bool)
│        @ Base ./process.jl:480
│      [3] run
│        @ ./process.jl:477 [inlined]
│      [4] run_and_capture(cmd::Cmd)
│        @ Documenter ~/.julia/packages/Documenter/yf96B/src/deployconfig.jl:546
│      [5] verify_github_pull_repository(repo::String, prnr::Int64)
│        @ Documenter ~/.julia/packages/Documenter/yf96B/src/deployconfig.jl:523
│      [6] deploy_folder(cfg::Documenter.GitHubActions; repo::String, repo_previews::String, branch::String, branch_previews::String, devbranch::String, push_preview::Bool, devurl::String, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│        @ Documenter ~/.julia/packages/Documenter/yf96B/src/deployconfig.jl:366
│      [7] deploydocs(; root::String, target::String, dirname::String, repo::String, branch::String, repo_previews::String, branch_previews::String, deps::Nothing, make::Nothing, devbranch::Nothing, devurl::String, versions::Vector{Any}, forcepush::Bool, deploy_config::Documenter.GitHubActions, push_preview::Bool, archive::Nothing)
│        @ Documenter ~/.julia/packages/Documenter/yf96B/src/Documenter.jl:553
│      [8] top-level scope
│        @ ~/work/PlotDocs.jl/PlotDocs.jl/docs/make.jl:176
│      [9] include(mod::Module, _path::String)
│        @ Base ./Base.jl:419
│     [10] exec_options(opts::Base.JLOptions)
│        @ Base ./client.jl:303
│     [11] _start()
│        @ Base ./client.jl:522
└ @ Documenter ~/.julia/packages/Documenter/yf96B/src/deployconfig.jl:530
┌ Info: Deployment criteria for deploying preview build from GitHub Actions:
│ - ✔ ENV["GITHUB_REPOSITORY"]="JuliaPlots/PlotDocs.jl" occurs in repo="github.com/JuliaPlots/PlotDocs.jl.git"
│ - ✔ ENV["GITHUB_REF"] corresponds to a PR number
│ - ✔ PR originates from the same repository
│ - ✔ `push_preview` keyword argument to deploydocs is `true`
│ - ✔ ENV["GITHUB_ACTOR"] exists and is non-empty
│ - ✔ ENV["GITHUB_TOKEN"] exists and is non-empty
└ Deploying: ✔
```

The workflow was working before, and suddenly stopped to work. The same workflow passes on master, but fails in `PRs`.

What appears to have changed is this:

**[working](https://github.com/JuliaPlots/PlotDocs.jl/actions/runs/3014993369/jobs/4845907624#step:5:6) - 1 month ago - PR**
```
   bash docs/ci_build.sh
  shell: /usr/bin/bash -e {0}
  env:
    PYTHON: 
    DOCUMENTER_KEY: ***
    GITHUB_TOKEN: ***
```

The `DOCUMENTER_KEY` secret is passed.

**[failing](https://github.com/JuliaPlots/PlotDocs.jl/actions/runs/3207002459/jobs/5241422925) - yesterday - PR**
```
   bash docs/ci_build.sh
  shell: /usr/bin/bash -e {0}
  env:
    ARTIFACTS_PATH: ~/.julia/artifacts
    PACKAGES_PATH: ~/.julia/packages
    REGISTRIES_PATH: 
    PYTHON: 
    GITHUB_TOKEN: ***
    DOCUMENTER_KEY: 
`DOCUMENTER_KEY` is missing
```

EDIT: see https://github.com/JuliaDocs/Documenter.jl/issues/1965#issuecomment-1272406085 logs instead.

The `DOCUMENTER_KEY` seems to have disappeared about a month ago in other PRs [log](https://github.com/JuliaPlots/PlotDocs.jl/actions/runs/3016418409/jobs/4850039801#step:5:6): the secret is now blank (and we have a flag `DOCUMENTER_KEY is missing` triggered by our [script](https://github.com/JuliaPlots/PlotDocs.jl/blob/master/docs/ci_build.sh#L6)).

I know that https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow says:
```
Note: With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
```

However, this worked before. So is it a change in `github` permissions ? What could be a workaround to this ?

**Comment by odow** [comment]
You created the PR from your fork:

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/8177701/194728379-6fc4f0d8-aec3-4fbd-8107-9a14139a9736.png">

Forks do not have access to the environment variables. This has never worked before, and there is no workaround.

**Comment by t-bltg** [comment]
Wrong, this worked before, e.g. https://github.com/JuliaPlots/PlotDocs.jl/pull/289.

**Comment by odow** [comment]
I can't see the log for the old PR, but I assure you, PRs from forks do not have access to `DOCUMENTER_KEY`. 

For https://github.com/JuliaPlots/PlotDocs.jl/pull/289, probably the CI passed but it didn't push the preview?

The PR you linked above as "working" was not made from a fork:

 * https://github.com/JuliaPlots/PlotDocs.jl/pull/299
 * https://github.com/JuliaPlots/PlotDocs.jl/actions/runs/3014993369/jobs/4845907624#step:5:6

**Comment by t-bltg** [comment]
Aside from `DOCUMENTER_KEY`, the problem is that documenter is trying to push a preview, failing because the aforementioned key is missing.

This is what I'm trying to discuss here. Something recent caused `Documenter` try to push the preview were it shouldn't, or hasn't before.

**Comment by fredrikekre** [comment]
Previews from forks have never worked.

To figure out if the PR is made from a fork we have this code: https://github.com/JuliaDocs/Documenter.jl/blob/70017e05f5c0297774c78e0774098577c6885a55/src/deployconfig.jl#L510 , but if that fails we assume it is not a fork: https://github.com/JuliaDocs/Documenter.jl/blob/70017e05f5c0297774c78e0774098577c6885a55/src/deployconfig.jl#L529 In the recent cases with failures that curl have been the problem. It is possible the API have changed, or that there were transient network problems. In any case, it might be good to assume it *is* from a fork when it fails instead.

**Comment by t-bltg** [comment]
Thanks, ok so the change in env variables was a red herring because of the fork / non-fork branches.

I'll try to make a PR tomorrow regarding the curl failure and the fallback assumption then.

**Comment by t-bltg** [comment]
From [this PR from fork log]():

```julia
┌ Info: Deployment criteria for deploying preview build from GitHub Actions: 

13371│ - ✔ ENV["GITHUB_REPOSITORY"]="JuliaPlots/PlotDocs.jl" occurs in repo="github.com/JuliaPlots/PlotDocs.jl.git" 

13372│ - ✔ ENV["GITHUB_REF"] corresponds to a PR number 

13373│ - ✘ PR originates from the same repository 

13374│ - ✔ `push_preview` keyword argument to deploydocs is `true` 

13375│ - ✔ ENV["GITHUB_ACTOR"] exists and is non-empty 

13376│ - ✔ ENV["GITHUB_TOKEN"] exists and is non-empty 

13377└ Deploying: ✘
```
, passing CI.
