### ISSUE TITLE
Different `search_index.js` in `docs/build` and `gh-pages`

### ISSUE THREAD

**Issue by t-bltg** [JuliaDocs/Documenter.jl#1981]
So I'm building `PlotDocs` with `makedocs`, `docs/build/search_index.js` is correct.

Now the docs are deployed using `deploydocs`, and the `gh-pages/<dev>_or_<tag>/search_index.js` differs.

What can cause that ?

**Comment by mortenpi** [comment]
Nothing on Documenter's end that I can think of -- `deploydocs` literally just copies over the files created my `makedocs`.

Are you comparing a local build vs a CI build? Is it possible that you're just calling `makedocs` with different settings on CI? What are the differences you see in the search indexes?

**Comment by t-bltg** [comment]
Thanks for answering.

> Are you comparing a local build vs a CI build

Yes, unfortunately, I wan only compare that, since `docs/build/` is not pushed to `gh-pages`.

Well, in https://github.com/JuliaPlots/PlotDocs.jl/pull/318 and https://github.com/JuliaPlots/PlotDocs.jl/pull/320 I monkey patch `Documenter` to modify search records added to the index.

And those don't show up in `search_index.js`.

> Is it possible that you're just calling makedocs with different settings on CI

That's a good idea to test the build with `CI` env variable = true. Trying that now

> What are the differences you see in the search indexes

Entries such as `"location":"generated/attributes_series.html", ...` are transformed into `"location":"generated/attributes_series/", ...` so something must be converted or transformed, but I do not know by what.

**Comment by mortenpi** [comment]
Ah, I'm pretty sure that is due to: https://github.com/JuliaPlots/PlotDocs.jl/blob/master/docs/make.jl#L173

However, since "pretty URLs" are being used in the deployed, those search entries are the correct ones I think. I.e. they should link to `https://docs.juliaplots.org/stable/generated/attributes_series/`, not `https://docs.juliaplots.org/stable/generated/attributes_series.html`.

**Comment by t-bltg** [comment]
That explains the urls changes I guess, but why are entries such as;
```
{"location":"generated/attributes_series.html","page":"Series Attributes","title":"Series Attributes","text":"show_empty_bins show_empty, showempty, showemptybins","category":"page"}
```

removed ?

Is there any chances there is a duplicate removal pass somewhere ?

**Comment by t-bltg** [comment]
No you're missing the point.

`docs/build/seach_index.js` is correctly written after `makedocs`, so `HTMLWriter` is not faulty here.

It is after, when deploying that it changes somehow.

**Comment by t-bltg** [comment]
Crap, so I can reproduce locally, using `prettyurls` is faulty here.

Nice catch in https://github.com/JuliaDocs/Documenter.jl/issues/1981#issuecomment-1322626121.

**Comment by t-bltg** [comment]
Alright, removing the `.html` suffix in the regex fixes the issues, thanks for the help here @mortenpi, very much appreciated.
