### ISSUE TITLE
Provide option to run some script once before all doctests

### ISSUE THREAD

**Issue by davidanthoff** [JuliaDocs/Documenter.jl#199]
I ran into a problem that my doctests triggered precompile, and then they fail because the precompile output of course is not expected output in the doctest.

I got around this for now by having a ``@meta`` block that has all the ``using`` clauses in there. But my understanding is that this kind of block will now be executed once before every doctest block? Really it would only have to run once overall before any doctest.

**Comment by MichaelHatherly** [comment]
> But my understanding is that this kind of block will now be executed once before every doctest block?

Yes that's correct. Things like downloading files, installing additional deps, or anything else like that should not be added to `@meta` blocks.

> Really it would only have to run once overall before any doctest.

Adding setup code to the `docs/make.jl` file is the way to go with this. For example: do all the `using`/`import`ing of packages that you'll use in doctests in that file before you call `makedocs` and that should solve the precompilation output problems.

**Comment by davidanthoff** [comment]
Yes, that works!
