### ISSUE TITLE
LoadError: ArgumentError: Package does not have HTTP in its dependencies

### ISSUE THREAD

**Issue by iskyd** [JuliaDocs/Documenter.jl#2000]
I have the following folder structure
```
src/
   HttpClient.jl
   SurrealDB.jl
docs/
   make.jl
   Manifest.toml
   Project.toml
   src/
       index.md
Project.toml
Manifest.toml
```

The package is pretty simple

```
module SurrealDB
include("HttpClient.jl")
end
```

In HttpClient I have some using and some logic
```
using HTTP
using Base64
using JSON
....
```

The make.jl was autogenerated from PkgTemplate, I just added the first line follwing the doc and contains the following
```
push!(LOAD_PATH,"../src/")

using SurrealDB
using Documenter

DocMeta.setdocmeta!(SurrealDB, :DocTestSetup, :(using SurrealDB); recursive=true)

makedocs(;
    modules=[SurrealDB],
    authors="Mattia Careddu",
    repo="https://github.com/iskyd/SurrealDB.jl/blob/{commit}{path}#{line}",
    sitename="SurrealDB.jl",
    format=Documenter.HTML(;
        prettyurls=get(ENV, "CI", "false") == "true",
        canonical="https://iskyd.github.io/SurrealDB.jl",
        edit_link="main",
        assets=String[],
    ),
    pages=[
        "Home" => "index.md",
    ],
)

deploydocs(;
    repo="github.com/iskyd/SurrealDB.jl",
    devbranch="dev",
    branch = "gh-pages",
)

```

The Project.toml in the root directory contains all the dependencies and the Project.toml from the docs directory contains
```
[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
SurrealDB = "0dc7cda7-6a2c-4f49-b8ae-2ed91ee7b183"
```

From the root dir I run 
`julia --project=docs/ docs/make.jl`
and I got 
LoadError: ArgumentError: Package Base does not have Http in its dependencies

Julia version: 1.8.2
os: Linux Ubuntu 22.04

**Comment by fredrikekre** [comment]
>  LoadError: ArgumentError: Package Base does not have Http in its dependencies

This usually means you accidentally have code before or after the `module XXX ... end`. (If you literally meant `Base`, the title uses `Package`).

> push!(LOAD_PATH,"../src/")

This should not be needed, what is the purpose of this?

**Comment by iskyd** [comment]
@fredrikekre no code before module. I include Http from HttpClient which is included in the module. Indeed the package works fine.

> This should not be needed, what is the purpose of this?
Find it here https://documenter.juliadocs.org/stable/man/guide/#Building-an-Empty-Document
BTW removing doesn't change the behaviour. Always get 
ERROR: LoadError: ArgumentError: Package SurrealDB does not have HTTP in its dependencies

**Comment by fredrikekre** [comment]
Okay, I guess you added your package to `docs/Project.toml` before adding that dependency then. A single `Pkg.resolve()` would have worked, I think, you should never have to update the manifest manually.

**Comment by iskyd** [comment]
@fredrikekre I think I'm missing something.
When I add a new dependency I simply do ] add Package.
But it is only added to the root Project.toml file and update the Manifest.
But it doesn't add anything to docs/Project.toml. I have to do it manually.
What am I missing here?
