### ISSUE TITLE
HTMLWriter feature idea: option to uncollapse subheadings globally

### ISSUE THREAD

**Issue by tfiers** [JuliaDocs/Documenter.jl#2001]
[Related to the useful `collapselevel`, #1723]

I wanted the following TOC view to be visible everywhere (especially the homepage).
<img width=600 src="https://user-images.githubusercontent.com/3773558/209655843-7dd9bde3-9f57-469e-b435-ed6cc5c222c4.png">

So I tried setting `HTMLWriter(…, collapselevel = 3)`.
But unfortunately that only works for actual pages, not headings _on_ pages:
<img width=600 src="https://user-images.githubusercontent.com/3773558/209655977-5c423843-6b82-4c11-9c48-9c28d787261d.png">

So it would be neat if there was an option that did this. (Or maybe `collapselevel` could do this?)

---

I assume this wouldn't be super hard to implement, given that the extra TOC contents are already rendered on the page itself.
(But I haven't dove into Documenter's source yet)

**Comment by mortenpi** [comment]
> I assume this wouldn't be super hard to implement, given that the extra TOC contents are already rendered on the page itself.

The in-page headings are only generated for the current page.. but in principle I don't think it would be that complicated to generate them all.

I am a little hesitant about adding an option for this though, since there is also push to remove the in-page heading altogether from the left sidebar: #1688. I guess it would really depend on how complex the implementation for this would be. If it's one if statement somewhere, it would be fine to have an option. If it's much more complex than that, then I am concerned about the maintenance burden.

**Comment by tfiers** [comment]
I agree with Logan's point there that the dynamic right-side TOC is very nice in the VS Code docs.
JupyterBook does a similar thing.

On the other hand, we could do the same thing (a dynamic in-page TOC) in its current position (embedded in the main TOC).
Would leave more screen space for people that like to read in a window that takes up half the screen eg.

Thank you for your great work on Documenter btw!

**Comment by mortenpi** [comment]
> On the other hand, we could do the same thing (a dynamic in-page TOC) in its current position: embedded in the main TOC.

I am not sure I quite follow. How is this different from what we have now?

**Comment by tfiers** [comment]
> How is this different from what we have now?

It'd be mostly the same, just "dynamic" as in: follows and highlights your scroll position
e.g. https://code.visualstudio.com/docs
and https://jupyterbook.org/en/stable/content/content-blocks.html

**Comment by tfiers** [comment]
On this issue itself: I don't think it's really necessary anymore.

In the docs I was writing, I split one long page with muliple headings into different pages, and the structure is better now (and the different parts show up in the TOC on every page)

**Comment by mortenpi** [comment]
> It'd be mostly the same, just "dynamic" as in: follows and highlights your scroll position

For what it's worth, I think this would just be a front-end/JS change (other than maybe adding some new CSS classes in the generated HTML), so I think it would be pretty straightforward to merge if someone provides the implementation.
