### ISSUE TITLE
Precompilation

### ISSUE THREAD

**Issue by tfiers** [JuliaDocs/Documenter.jl#2002]
Would it make sense to add [SnoopPrecompile](https://timholy.github.io/SnoopCompile.jl/stable/snoop_pc/) and a short `@precompile_all_calls` block to Documenter?
It might speed up the first doc-build of a session.
I'd be up for making a PR.

**Comment by mortenpi** [comment]
Quite likely. The first run is always pretty slow. Would be happy to look at a PR.

**Comment by KristofferC** [comment]
I somewhat doubt that a lot of that time is compilation time of Documenter itself.

**Comment by tfiers** [comment]
The same `make.jl` on my laptop is quite fast

**Comment by KristofferC** [comment]
Yes, but isn't that mostly code of your package that has to get compiled?

**Comment by mortenpi** [comment]
For a tiny test case, I get `13s` first run with precompilation, `12s` first run without precompilation, and  `0.2s` second run. So I still think it would be worth looking into if we can shift more of that into precompilation (particularly useful for workflows where you call `julia make.jl` repeatedly).

**Comment by mortenpi** [comment]
Although, regarding SnoopCompile as a dependency: is this something that gets often broken by the Julia nightlies?

One of the main considerations for Documenter dependencies is that they wouldn't break as Julia `master` marches on, since you don't want to force people to be fixing patching external dependencies as they work on their PRs (to get doc builds passing). Are the APIs SnoopCompile depends on all public and documented?

**Comment by KristofferC** [comment]
This is the code for SnoopPrecompile https://github.com/timholy/SnoopCompile.jl/blob/master/SnoopPrecompile/src/SnoopPrecompile.jl.

So I wouldn't say that the API are public and documented. But on the other hand, if SnoopPrecompile breaks, then the whole ecosystem breaks so it is likely to be fixed quite fast.

**Comment by mortenpi** [comment]
> if SnoopPrecompile breaks, then the whole ecosystem breaks

Maybe then having it in Documenter would actually be a useful canary.

**Comment by KristofferC** [comment]
Yeah, I don't think there is a big harm in depending on SnoopPrecompile.

I did a minimal test at https://github.com/JuliaDocs/Documenter.jl/pull/2004.

**Comment by tfiers** [comment]
> I did a minimal test at #2004.

That's an amazing time improvement.

Good to merge for me
(No more need for 
> I'd be up for making a PR.

)
