### ISSUE TITLE
Drawback of versioning Project.toml as e.g. `0.28.0-DEV`.

### ISSUE THREAD

**Issue by KristofferC** [JuliaDocs/Documenter.jl#2005]
Right now, if I go to the `docs` project of Documenter and instantiate it I get and old `DocumenterTools v0.1.2` installed. That is because there is no DocumenterTools version that has been released that supports this in progress version of Documenter and in DocumenterTools pre v0.1.2 there was no dependency on Documenter at all (https://github.com/JuliaRegistries/General/blob/ac1c157b96743609ee86b907533714dbebeb40b8/D/DocumenterTools/Compat.toml#L37).

Trying to create the docs with this old DocumenterTools errors. So what I do now is to put back the version to `0.27` and create the docs. This feels like it isn't ideal. I realise it is good to see that the upcoming version will be breaking, but during that time, where no dependencies support it, it becomes awkward to use it.

**Comment by mortenpi** [comment]
I think there is a branch that declares compat with 0.28, and you can use `docs/instantiate.jl` to instantiate the correct environment.

**Comment by KristofferC** [comment]
> docs/instantiate.jl is a hack to work around this exact problem

Okay, I didn't know about that one.
