### ISSUE TITLE
Show figure, hide code in <details> block

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#2006]
I'm trying to use ```<details closed><summary>...</summary></details>``` to hide the code that generates a visible figure.

What I've got:

<img width="505" alt="Screenshot 2022-12-31 at 12 33 07" src="https://user-images.githubusercontent.com/52289/210136886-2183e601-fb9b-4248-aced-fb74bc2f7276.png">

What it looks like:

closed:

<img width="612" alt="Screenshot 2022-12-31 at 12 33 39" src="https://user-images.githubusercontent.com/52289/210136921-0b19724e-c4d5-4741-8547-d23a368b0941.png">

open

<img width="659" alt="Screenshot 2022-12-31 at 12 33 55" src="https://user-images.githubusercontent.com/52289/210136926-94b0115f-fb16-45ec-b420-026cc7f4b8b7.png">

But what I'm trying to do is show the figure all the time and make the code hidden but visible on demand.

It appears that the Markdown source is this structure:

- ```<details>```
- code to make figure
- ```</details>```
- the figure

but in the HTML output it become more like this:

- ```<details>```
- code to make figure
- the figure
- ```</details>```

Is there a trick to get this working?

(using Documenter v0.27.23)

**Comment by mortenpi** [comment]
I think it renders it from the first at-example block. You should have a `nothing # hide` there at the end. And the second at-example could probably be an at-eval, so you don't need the `#hide` there.

**Comment by cormullion** [comment]
Great, thanks - just adding the `nothing # hide` got it working.

```
    ```@raw html
    <details closed><summary>Code for this figure</summary>
    ```

    This code generates the figure below.

    ```@example fig1
    using Luxor
    d = @drawsvg begin
    juliacircles(20)
    end 600 200
    nothing # hide
    ```

    ```@raw html
    </details>
    ```

    ```@example fig1
    d # hide
    ```

```
