### ISSUE TITLE
gh-pages is not created but no error is shown

### ISSUE THREAD

**Issue by iskyd** [JuliaDocs/Documenter.jl#2007]
Hi, I'm trying to deploy a docs using github pages through github actions.

[This is my CI.yml file](https://github.com/iskyd/Bip39.jl/blob/main/.github/workflows/CI.yml)
[This is my make.jl file](https://github.com/iskyd/Bip39.jl/blob/main/docs/make.jl)

As you can see [here](https://github.com/iskyd/Bip39.jl/actions/runs/3821625584) it seems that the actions is executed correcty but no gh-pages branch is being created.

**Comment by mortenpi** [comment]
You can see in the `deploydocs` output that you have a few things that are not properly configured:

```
┌ Info: Deployment criteria for deploying devbranch build from GitHub Actions:
│ - ✔ ENV["GITHUB_REPOSITORY"]="iskyd/Bip39.jl" occurs in repo="github.com/iskyd/Bip39.jl"
│ - ✔ ENV["GITHUB_EVENT_NAME"]="push" is "push", "workflow_dispatch" or "schedule"
│ - ✘ ENV["GITHUB_REF"] matches devbranch="dev"
│ - ✔ ENV["GITHUB_ACTOR"] exists and is non-empty
│ - ✘ ENV["DOCUMENTER_KEY"] or ENV["GITHUB_TOKEN"] exists and is non-empty
└ Deploying: ✘
```

From: https://github.com/iskyd/Bip39.jl/actions/runs/3821625584/jobs/6500951967#step:6:16

**Comment by iskyd** [comment]
@mortenpi I don't get what's not properly configured. 
This seems to be a correct msg to me "ENV["DOCUMENTER_KEY"] or ENV["GITHUB_TOKEN"] exists and is non-empty"
Also "ENV["GITHUB_REF"] matches devbranch="dev"".

**Comment by mortenpi** [comment]
Regarding `dev` vs `main`: you're requiring the latest docs to be deployed from `dev` branch (in `make.jl`), but you only run your CI on the `main` branch. You can go either way, but you either have to run CI on `dev` too, or just deploy the docs from `main`.

The other error indicates that there is something wrong with your `DOCUMENTER_KEY` setup, which you need to deploy the docs. You're also using the `julia-actions/julia-docdeploy` action, and I am not familiar with its internals, so I don't have a good guess where things might be broken.

**Comment by iskyd** [comment]
Removing "devbranch=dev" in make.jl solved the problem.
