### ISSUE TITLE
Page for a `pages` subsection

### ISSUE THREAD

**Issue by tfiers** [JuliaDocs/Documenter.jl#2009]
## Example / motivation

<img width=230 src="https://user-images.githubusercontent.com/3773558/211157390-f4e7bf2c-9de2-4da8-8b6d-d0fd00f34c95.png">

"Home" and "Developer Guide" are clickable; but "Reference" and "Background" are not.

I would write e.g. the following short text on the intro/index page for Background:
> Explanation of choices and tradeoffs, discussion of alternatives, and other PkgGraph-related trivia.

## API
One option:
```
	pages = [
        "Home" => "index.md",
        "Reference" => [
			"ref/index.md",           <----
            "ref/end-user.md",
            "ref/internals.md",
        ],
        "Background" => [
            "bg/index.md",            <----
            "bg/usage-tips.md",
            "bg/related-work.md",
            "bg/graphviz.md",
            "bg/graphsjl.md",
            "bg/abbrevs.md",
        ],
        "devguide.md",
	]
```

**Comment by fredrikekre** [comment]
#701

**Comment by tfiers** [comment]
Thanks. I saw that issue when looking for possible duplicates, but didn't think it was the same idea, on a quick sim

But indeed it seems to be; just with a different API than the current subpages way

**Comment by tfiers** [comment]
I like
> Slightly change the style of non-link items in the navigation menu (e.g. "Manual" or "Library") to make it clear that they are not clickable.
from that thread :)

**Comment by odow** [comment]
closing in favor of #701
