### ISSUE TITLE
Is it possible to use a Documenter function to write PDF from an HTML file input?

### ISSUE THREAD

**Issue by mahiki** [JuliaDocs/Documenter.jl#2020]
I'd like to use the PDF functionality to simply convert an HTML file (a tabular data report) to a pdf page and save it.

I know this is not in any way part of the goal of this project, but perhaps I could create a function for myself from components here. It would help a lot in assembling business metrics reports in Julia.

**Comment by fredrikekre** [comment]
I don't think Documenter would help much. There is no functionality for parsing or working with HTML. Perhaps Quarto might help you? According to https://quarto.org/docs/reference/formats/pdf.html there is HTML to PDF functionality there.
