### ISSUE TITLE
Trailing slashes for the target URL of the version selector

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaDocs/Documenter.jl#2022]
What would I need to change to get that?

It's causing me some problems deploying with netlify without ( see: https://github.com/JuliaPlots/PlotDocs.jl/pull/337 )

**Comment by mortenpi** [comment]
The version selector is handled by this JS: https://github.com/JuliaDocs/Documenter.jl/blob/master/assets/html/js/versions.js

It indeed looks like we don't add a trailing slash to the `<option value="..."` (which we then use to set the `.href` to. I think it would be fine to add a trailing slash to each of the `<option value=`s.

But how does this cause issues for you? Does Netlify not redirect directories without trailing slashes or something like that?

**Comment by BeastyBlacksmith** [comment]
It treats the paths in its redirect settings the same, so I can't set redirects to add that slash and currently it displays the homepage without css, if you select the version via the selector, but if you add the slash the redirect works fine.
