### ISSUE TITLE
How to change "depth" in sidebar?

### ISSUE THREAD

**Issue by roland-KA** [JuliaDocs/Documenter.jl#2028]
In the sidebar Documenter shows only H1 and H2 headlines of a page. Is it possible change that parameter so that deeper nested headlines are also displayed (something like DEPTH when using `@contents`)?

**Comment by mortenpi** [comment]
The short answer is no, that can not be configured. If we do want to allow this, then I think it should be done via #1688 -- I think adding `h3` headings to the left sidebar would make it too long generally.

I don't really know the context of course, but if you feel like you need the `h3` headings in the sidebar, it might be worth considering breaking the page up into multiple pages.

**Comment by roland-KA** [comment]
> The short answer is no, that can not be configured.

Oh, that's a pity.

>  If we do want to allow this, then I think it should be done via https://github.com/JuliaDocs/Documenter.jl/issues/1688 -- 

That would be a nice alternative.

> I think adding h3 headings to the left sidebar would make it too long generally.

Well, at least in my case there is enough space and it would give the reader a better overview of the page.
