### ISSUE TITLE
`@ref` with backticks doesn't work

### ISSUE THREAD

**Issue by roland-KA** [JuliaDocs/Documenter.jl#2029]
I'm using the following `@ref` in a document: `[StorageManager](@ref)`. It works as intended.

But as soon as I put `StorageManager` in backticks (like ``[`StorageManager`](@ref)``), Documenter doesn't make a cross-reference from that expression. Instead I get the following warning:

```
 Warning: no doc found for reference '[`StorageManager`](@ref)' in src/index.md.
```

Why doesn't this work? What do I have to do, if I want the word `StorageManager` formatted as code?

**Comment by mortenpi** [comment]
If the text is formatted as code, the assumption is that you are trying to reference a docstring. On `master`, you should be able to do ``[`StorageManager`](@ref "StorageManager")`` though (#1900). `StorageManager` I presume is a section heading?

**Comment by roland-KA** [comment]
Oh, that's a good hint. StorageManager is a module name as well as a heading. Can I tell Documenter that I want the docstring of the module name in this case or isn't it possible to resolve this ambiguity?

**Comment by mortenpi** [comment]
``[`StorageManager`](@ref)`` should pick up the module (assuming it's available in the current scope, e.g. it's exported or `CurrentModule` is set appropriately).

**Comment by roland-KA** [comment]
Unfortunately it doesn't. It generates the warning cited above.

It gets the docstring, if I omit the backticks and the following expression works also without problems:
```
    ```@docs
     StorageManager
    ```
```
... so the module seems to be available in this context.

**Comment by mortenpi** [comment]
You need to set `CurrentModule`, like [I did here](https://github.com/mortenpi/Example.jl/blob/5640ad08f84c1e4237f6468b17a637021c54ad4b/docs/src/index.md?plain=1#L1-L3). If you build the docs for this branch, it the module link should work: https://github.com/mortenpi/Example.jl/tree/mp/module-docstring

Modules are a bit special though it seems like. Normally, without `CurrentModule`, it can pick up exported names from `Main`, but apparently not modules. If you don't want to use `CurrentModule`, then ``[`MyPackage.MyPackage`](@ref)`` might work, but a better option is probably ``[`MyPackage`](@ref MyPackage)``.

**Comment by roland-KA** [comment]
> then [`MyPackage.MyPackage`](@ref) might work

it didn't work in my case

> but a better option is probably [`MyPackage`](@ref MyPackage)

Oh yes, that's it, thanks!
