### ISSUE TITLE
How to print the docstring without Documenter-specific formatting?

### ISSUE THREAD

**Issue by roland-KA** [JuliaDocs/Documenter.jl#2030]
If I'm using 

```
    ```@docs
    foo
    ```
```

on a function `foo`, Documenter will always print the docstring in a Documenter-specific formatting in a block using a one-column-table with "`foo` -- Function" in the header, then `foo(x, y)` in a box and below that, the rest of the documentation.

In some situations I just want to display the docstring without that fancy stuff around it (more or less what I get, when calling `@doc foo` on the REPL). How can I get that in Documenter?

**Comment by mortenpi** [comment]
The at-eval block should work for this, if you indeed want to just include the docstring without any formatting or processing:

````markdown
```@eval
@doc(foo).content[1].content[1] # or @doc(Main.foo)...
```
````

Note: the `.content[1].content[1]` unwrapping is necessary because the at-doc macro wraps docstrings in multiple layers of `Markdown.MD` objects.

**Comment by roland-KA** [comment]
Ok, thanks, that seems to be what I'm looking for. Unfortunately I'm running with this approach in some context/environment problem:

I've tried
```
   ```@eval
    @doc(lookup)
    ```
```

and the result was this message in the document:

```
No documentation found.

Binding Main.EvalBlockSandbox.lookup does not exist.
```

Trying instead with a fully qualified identifier:
```
   ```@eval
    @doc(LiMa.StorageManager.lookup)
    ```
```

doesn't work either. This results in a Documenter-warning:
```
 Warning: failed to evaluate `@eval` block in src/StorageManager.md
│ ```@eval
│ @doc(LiMa.StorageManager.lookup)
│ ```
│   exception = UndefVarError: LiMa not defined
```

So, in which environment/context does `@eval` execute?

BTW:
```
   ```@docs
    LiMa.StorageManager.lookup
    ```
```
works fine (also using `lookup` without the package names works).

**Comment by fredrikekre** [comment]
>So, in which environment/context does @eval execute?

It's own empty module. Probably you just need `using LiMa` or something before accessing the function name.

**Comment by roland-KA** [comment]
Ah great, that does the trick 😊👍
