### ISSUE TITLE
Question: How does $(EXPORTS) work?

### ISSUE THREAD

**Issue by fsaad** [JuliaDocs/Documenter.jl#2032]
The doc string of the `Documenter` module uses `$(EXPORTS)` to automatically generate a list of names exported by the module:
https://github.com/JuliaDocs/Documenter.jl/blob/71e9f40d51ba855f69e21a46401610891f282d7e/src/Documenter.jl#L11

When I try to replicate this code in a fresh project (say Example.jl), I receive the error
```
~/Example.jl/docs% julia make.jl
ERROR: LoadError: UndefVarError: EXPORTS not defined
```

How can I access the `EXPORTS` variable? I could not find it defined anywhere in the `Documenter.jl` repository:
```
~/Documenter.jl% git grep 'EXPORTS'
src/Documenter.jl:11:$(EXPORTS)
```

**Comment by mortenpi** [comment]
It's from [DocStringExtensions](https://github.com/JuliaDocs/DocStringExtensions.jl/): https://docstringextensions.juliadocs.org/latest/#DocStringExtensions.EXPORTS

**Comment by fsaad** [comment]
Thanks @mortenpi, I will close the issue.
