### ISSUE TITLE
linkcheck 403

### ISSUE THREAD

**Issue by ArnoStrouwen** [JuliaDocs/Documenter.jl#2040]
I'm trying to activate link checking in various SciML packages, but for some links that seem correct, Documenter gets an HTTP 403, e.g.:
`Error: linkcheck 'https://epubs.siam.org/doi/10.1137/0903023' status: 403.`

EDIT:
Here are others I found:
`Error: linkcheck 'https://www.linkedin.com/in/paul-lang-7b54a81a3/' status: 999.`
`Error: linkcheck 'https://journals.physiology.org/doi/full/10.1152/ajpheart.00794.2003' status: 403.`

**Comment by mortenpi** [comment]
It's a problem with the server:

```
$ curl -I https://epubs.siam.org/doi/10.1137/0903023
HTTP/2 403 
date: Mon, 13 Feb 2023 23:09:46 GMT
content-type: text/html; charset=UTF-8
permissions-policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
referrer-policy: same-origin
x-frame-options: SAMEORIGIN
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
set-cookie: __cf_bm=W.t0A575Vz26PD5AZmzzv7bdsfVGh3M0LSoO.bOfzj4-1676329786-0-AROH3FI1HCawfIAm7GYh0wrr7xZSn7sN1jrpDBdfx+5ViCNrbkfNnoC8TRtGOl2vNGju1cfzOJFrcSr27Jt68pA=; path=/; expires=Mon, 13-Feb-23 23:39:46 GMT; domain=.epubs.siam.org; HttpOnly; Secure; SameSite=None
server-timing: cf-q-config;dur=7.9999990703072e-06
strict-transport-security: max-age=15552000
server: cloudflare
cf-ray: 79913bcaca491c53-AKL
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

That said, some servers do some funky filtering based on headers and such to block non-browser requests which we have worked around of in the past (see https://github.com/JuliaDocs/Documenter.jl/pull/1807, https://github.com/JuliaDocs/Documenter.jl/pull/1796). So if someone figures out what we would need to add to the request to make it work, we could definitely do that.

In the meanwhile, you can always disable the checking of those URLs with `linkcheck_ignore`.

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing because this seems non-actionable. There will always be problematic links, and the suggestion is to add them to `linkcheck_ignore`.
