### ISSUE TITLE
Update KaTeX to latest version

### ISSUE THREAD

**Issue by mfsch** [JuliaDocs/Documenter.jl#2043]
I’m currently writing documentation that would benefit from some of the improvements that have landed in more recent versions of KaTeX.

It looks like the version was last updated in #1846, with the plan to upgrade to the latest (breaking) version for 0.28. Since the master branch is now at `0.28.0-DEV`, would it make sense to upgrade KaTeX now? Additionally, would it perhaps make sense to make the KaTeX version configurable through the `KaTeX` struct? From a quick look at `HTMLWriter.jl` this seems like a straightforward change.

**Comment by mortenpi** [comment]
Yes, we need do a round of JS dependency updates for the 0.28/1.0 release.

**Comment by PeturBryde** [comment]
Would it be possible to update the KaTeX version again? Alternatively, would it be possible to make the KaTeX version configurable as mfsch suggested?
