### ISSUE TITLE
Documenter.jl document improvement request

### ISSUE THREAD

**Issue by doganmehmet** [JuliaDocs/Documenter.jl#2045]
If possible, could you please add this info to the ***Documenter.jl***'s documentation?

```
using Pkg

Pkg.activate("..")

push!(LOAD_PATH,"../src/")```

**Comment by fredrikekre** [comment]
Why? That is not a recommend way of doing things.

**Comment by mortenpi** [comment]
> That is not a recommend way of doing things.

Agreed. What we should do is explain the role of the `docs/` environment and dev-deps more clearly, however, since this is a common issue.

It duplicates #1565 though, so closing this on those grounds.
