### ISSUE TITLE
Check JS dependency versions before release

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#2069]
And update if necessary. Should mostly be taken care of by #2066 and #2067, but just a reminder for myself to double check the versions before actually releasing.

**Comment by inkydragon** [comment]
Font Awesome has a major version update (5 => 6)
Shall we try it?

- v5.15.4 2021-08: https://fontawesome.com/v5/download
- v6.3.0 2023-02: https://fontawesome.com/v6/download

doc: [Upgrade to Version 6 | Font Awesome Docs](https://fontawesome.com/docs/web/setup/upgrade/)

**Comment by inkydragon** [comment]
And CSS:
https://github.com/JuliaDocs/Documenter.jl/blob/e5441ba7ec1f3799c12b13cf9dd52ce995fafc6e/assets/html/README.md?plain=1#L5-L10

- bulma: v0.7.5 => v0.9.4
	https://github.com/jgthms/bulma/releases/latest
- darkly: ? => v0.8.1
	https://github.com/jenil/bulmaswatch/tree/v0.8.1/darkly

**Comment by mortenpi** [comment]
Yeah, could try. Probably best to do the themes in a separate PR, since they might be tricky. FontAwesome might require updating out icon use, if their IDs have changed.
