### ISSUE TITLE
linkcheck fails

### ISSUE THREAD

**Issue by tpapp** [JuliaDocs/Documenter.jl#2094]
In https://github.com/tpapp/DynamicHMC.jl/actions/runs/4594434913/jobs/8113464772, the linkcheck fails, yet if I try from the command line on my machine it is fine. How can I debug this?

**Comment by mortenpi** [comment]
It's possible that the server blocks GitHub runners by IP or something. We've had to jump through hoops to make some servers work that are filtering based on HTTP headers... If you want to test, you can SSH into a GitHub runner with something like https://github.com/marketplace/actions/debugging-with-tmate

Also, it's quite likely that there isn't much you can do about it, so `makedocs` also has a `linkcheck_ignore` keyword which you can use to disable checking that particular link.
