### ISSUE TITLE
Site like cppreference?

### ISSUE THREAD

**Issue by JohnAAbbott** [JuliaDocs/Documenter.jl#2098]
I'm fairly new to julia, and come from a background in C++.  Maybe this is not the right place to ask...?

The cppreference website is a wonderfully helpful resource.  Is there anything analogous for Julia?

Of course, I am aware of [https://docs.julialang.org/en/v1/](url)  but find it much more awkward to use than cppreference.  For instance, the search function in the Julia documentation seems to yield a large number of hits of questionable relevance, and the order in which the hits are listed is also "weird".  For example, how should one search effectively for the definition of `Int`?

**Comment by mortenpi** [comment]
I'd say that docs.julialang.org is the "cppreference of Julia". As in, it has the tutorials and reference documentation. Packages usually host their own docs. Search on Documenter sites is a known issue, which would need to be fixed here.

For search, you can also give https://juliahub.com/ui/Packages a try, which can search across the whole package ecosystem.
