### ISSUE TITLE
Manually write docstring within markdown files

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaDocs/Documenter.jl#2101]
Hey,

(I couldn't find a related question anywhere, but it seems like something that others might have asked before, so please close if so)

Due to https://github.com/JuliaDocs/Documenter.jl/issues/558, I cannot document a functor in my package. However, since I can manually find the docstring myself, is there any way I can manually paste that docstring into my markdown files, and have it be rendered like other docstrings that were found automatically?

I couldn't find any special `@` function for this in the docs, and just pasting the docstring into a codeblock would result in non-formatted text which doesn't look as nice.

Thanks!
Miles

**Comment by mortenpi** [comment]
You should be able to reference it as a normal constructor right now. So if you have e.g. 

```
struct Bar ... end 
"..."
(::Bar)(::Array) = 1
```

You should be able to reference it in an at-docs block as:

````markdown
```@docs
Bar(::Array)
```
````
