### ISSUE TITLE
Docstring collapse/expand icon not changing when clicking rapidly

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#2103]
I was playing with the collapse/expand feature a bit, and I noticed that the icon doesn't change correctly if you click on it rapidly a bunch of times:

https://user-images.githubusercontent.com/147757/232263663-b283ed48-0777-4ea0-b1a3-049cb2544b75.mp4

Extremely minor, unlikely to be run into in practice. But might indicate some sort of a race condition or something in the JS.

cc @Hetarth02

**Comment by Hetarth02** [comment]
I think we can put sort of a safety lock so that it doesn't get triggered when its already in triggered(animating) state.
