### ISSUE TITLE
Hamburger `div` should be `display: none` when not shown

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#2107]
It causes the breadcrumb to not be aligned with the page if the hamburger is hidden on a full page:

![Screenshot from 2023-04-18 21-26-24](https://user-images.githubusercontent.com/147757/232742953-81c0ae4f-20f0-4c69-ae45-b4452f307010.png)

From #2076. cc @inkydragon

**Comment by pranavvatsa** [comment]
Hey, I went ahead and changed the display to none on the main.scss under the docs-left div. Please do check it out and lemme know if there are any conflicts/issues/bugs
