### ISSUE TITLE
Be more specific about VERSION cutoffs

### ISSUE THREAD

**Issue by tkelman** [JuliaDocs/Documenter.jl#211]
There are a lot of pretty general `if VERSION < v"0.5-"` or `if VERSION < v"0.5.0-dev"` comparisons around the code here. It would be a best practice to be more specific with a build number, or use `isdefined`, wherever possible in case it's ever necessary to bisect on a base bug that involves this package.

**Comment by mortenpi** [comment]
Sounds like a good practice, although I think we'll be ripping all of those out from master and drop 0.4 support altogether (0.3.x branch will still support it). But I guess we should nevertheless follow this for future 0.6 compat things.

However, is there an easy way of determining the build number when I know the relevant PR or commit (other than checking it out, building it and then looking at `versioninfo`, which is a bit time-consuming)? I was looking into this at some point, but I wasn't quite able to figure it out.

**Comment by tkelman** [comment]
There's a script at `contrib/commit-name.sh`. Best to run it at the merge commit for a given change.

**Comment by mortenpi** [comment]
> There's a script at `contrib/commit-name.sh`.

I had missed that, thanks for the tip! :+1:

**Comment by MichaelHatherly** [comment]
Yeah, some of them definitely need tightening.
