### ISSUE TITLE
Collapse level in menu not working (as expected)

### ISSUE THREAD

**Issue by tamasgal** [JuliaDocs/Documenter.jl#2110]
I am having difficulties with the main menu, not being able to expand them all by default. I thought setting the `collapselevel` parameter of `Documenter.HTML` to a higher value would do it but it seems to have no effect. (here is a live example https://common.pages.km3net.de/KM3io.jl/dev/)

Only the currently selected menu is expanded, everything else is collapsed. Here is a screenshot where "Examples" have been clicked:

<img width="283" alt="Screenshot 2023-04-20 at 14 03 00" src="https://user-images.githubusercontent.com/1730350/233360271-394516ac-783b-4de8-8941-db5ad60c7737.png">

This is my `make.jl`:

```julia
makedocs(;
    modules = [KM3io],
    sitename = "KM3io.jl",
    authors = "Tamas Gal",
    format = Documenter.HTML(;
        assets = ["assets/extra_styles.js"],
        collapselevel = 4,
        warn_outdated = true,
    ),
    pages = [
        "Home" => "index.md",
        "Examples" => "examples.md",
        "API" => "api.md"
    ],
    repo = "https://git.km3net.de/common/KM3io.jl/blob/{commit}{path}#L{line}",
)
```

and `index.md`, `examples.md` and `api.md` contain `#`, `##` and `###` headings.

Any idea what's wrong? I compared my configuration with a few other ones but I can't spot my mistake.

**Comment by mortenpi** [comment]
Yes, that's intended. There is a distinction between page hierarchy and in-page headings. `collapselevel` is only about the former.

You want all in-page headings to always be expanded?

**Comment by tamasgal** [comment]
Ah OK thanks. Yes, I'd like to expand them all. I guess I have to rearrange the pages structure then?

**Comment by mortenpi** [comment]
Yeah, if you want stuff always to be listed in the sidebar, you'd have to turn the in-page headings into separate pages.
