### ISSUE TITLE
Docstring of makedocs does not document the non-keyword vararg components

### ISSUE THREAD

**Issue by yoninazarathy** [JuliaDocs/Documenter.jl#2113]
The`makedocs` function has [one method](https://github.com/JuliaDocs/Documenter.jl/blob/b4c6496f0a60207963f6a5f47c51a15ec685c852/src/Documenter.jl#L266) with the first argument being a vararg `components...`. However the [docstring](https://documenter.juliadocs.org/stable/lib/public/#Documenter.makedocs) does not describe that argument.

**Comment by odow** [comment]
Closing because there's nothing actionable to do here yet. The docstring lists the public API.
