### ISSUE TITLE
HTML Table in ReadMe Not Rendering in HTML Build

### ISSUE THREAD

**Issue by ejmeitz** [JuliaDocs/Documenter.jl#2117]
I have the following HTML in my ReadMe and it renders beautifully; however, when I build with the deploydocs() function the < & > symbols don't get parsed as HTML and isntead get converted to `&lt;` and `&rt;` and my build ends up rendering the HTML as plain text. How can I fix this? I've copied the relevant parts of make.jl below. Any help would be greatly appreciated! I doubt this is a bug I just can't find the parameter I need to set to fix this.

ReadMe Version:
```
<table>
    <tr>
        <th>Crystal Family</th>
        <th align="center">Primitive</th>
        <th align="center">Base Centered</th>
        <th align="center">Body Centered</th>
        <th align="center">Face Centered</th>
    </tr>
...more stuff
\table>

```
Built Version:
`&lt;table&gt;     &lt;tr&gt;         &lt;th&gt;`

make.jl file
```
makedocs(sitename = "SimpleCrystals.jl",
format = Documenter.HTML(
    prettyurls = get(ENV, "CI", nothing) == "true"
), 
pages = [..stuff]
)

deploydocs(
    repo="github.com/ejmeitz/SimpleCrystals.jl.git",
    push_preview = true,
    devbranch = "main"
)
```

**Comment by fredrikekre** [comment]
Crossref #674 and references therein.

**Comment by odow** [comment]
I think this is actually asking for https://github.com/JuliaDocs/Documenter.jl/issues/517

The answer for @ejmeitz is to wrap the table in `@raw html` block
````
```@raw html
<table>
    <tr>
        <th>Crystal Family</th>
        <th align="center">Primitive</th>
        <th align="center">Base Centered</th>
        <th align="center">Body Centered</th>
        <th align="center">Face Centered</th>
    </tr>
...more stuff
\table>
```
````

Closing because Documenter does not support HTML syntax outside a `@raw html` block.
