### ISSUE TITLE
Building docs fails on github CI

### ISSUE THREAD

**Issue by tomchor** [JuliaDocs/Documenter.jl#2118]
Hi, everyone. First, thanks for the great package! I've been using it for some time in other packages that I contribute and I love it!

I'm trying to set Documenter up for the first time for my own package but I'm getting errors when building using Github actions.

The error I'm getting is:

```
ERROR: LoadError: ArgumentError: Package RecipesBase does not have PrecompileTools in its dependencies:
- You may have a partially installed environment. Try `Pkg.instantiate()`
  to ensure all packages in the environment are installed.
- Or, if you have RecipesBase checked out for development and have
  added PrecompileTools as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with RecipesBase
```

I've tried some things but nothing has worked. The package builds locally, so this has something to do with github actions. I _think_ followed [the docs](https://documenter.juliadocs.org/stable/man/hosting/#GitHub-Actions) correctly, but I guess I must be missing something.

Here is the PR where I'm trying to set this up: https://github.com/tomchor/Oceanostics.jl/pull/124
and here is the actions error: https://github.com/tomchor/Oceanostics.jl/actions/runs/4885154272/jobs/8718846076?pr=124

PS: I'm setting the target repo for deployment the same as the repo where the files are, so I'm relying on the [GITHUB_TOKEN](https://documenter.juliadocs.org/stable/man/hosting/#Authentication:-GITHUB_TOKEN), and I haven't set the SSH deplay keys.

**Comment by mortenpi** [comment]
It looks like your docs Manifest might be outdated? Could you try re-resolving it?

**Comment by tomchor** [comment]
> It looks like your docs Manifest might be outdated? Could you try re-resolving it?

Thanks for the suggestion but I've tried that and there were no changes to either Project or Manifest.

**Comment by mortenpi** [comment]
Could try deleting the manifest an re-creating it from scratch? Also, just in case, should make sure that the Julia version is the same as in CI (which uses 1.8 as far as I can tell).

**Comment by tomchor** [comment]
Ah, deleting the manifest did it. Thanks!

Although I still can't preview it. I'm setting `push_preview = true`, and I do see the files at the `gh-pages` branch, but I can't see the preview on https://tomchor.github.io/Oceanostics.jl/previews/PR124. Am I missing something?

**Comment by mortenpi** [comment]
Docs definitely deployed: https://github.com/tomchor/Oceanostics.jl/tree/gh-pages/previews/PR124

Are you correctly serving the GitHub Pages from the `gh-pages` branch?

**Comment by tomchor** [comment]
Ah, I thought I did but indeed it wasn't set. Thank you very much! I think everything's working now.
