### ISSUE TITLE
Doctests never finish if too many "method definition overwritten" warnings appear

### ISSUE THREAD

**Issue by zickgraf** [JuliaDocs/Documenter.jl#2121]
**Steps to reproduce:**

1. Create a doctest with the following content in any package:
```
julia> for i in 1:1024
       eval(:(function f() 1 end))
       end
```
2. Execute tests of the package with "--warn-overwrite=yes":
    * Either with `Pkg.test(..., julia_args = [ "--warn-overwrite=yes" ])`
    * or by using Julia master (which recently has enabled those warnings by default in tests: https://github.com/JuliaLang/Pkg.jl/commit/e576700254b3bd1bbc0a2be2fad257cd70839162)
 
**Expected behaviour:** The test finishes with lots of warnings.

**Actual behaviour:** The test never finishes.

**Note:** The number of warnings is relevant. If one uses 100 instead of 1000 in the range of the for-loop, the test finishes with lots of warnings as expected. So depending on the system one might also have to use a number larger than 1000, I guess.

Tested with Documenter master and both Julia 1.9 and Julia master.

**Comment by mortenpi** [comment]
I have a hunch that it fills some `redirect_stdout`/`redirect_stderr` buffers/pipe in [IOCapture](https://github.com/JuliaDocs/IOCapture.jl) somehow. A more minimal MWE is:

```julia
using IOCapture
c = IOCapture.capture() do
    for i in 1:1024
        eval(:(function f() 1 end))
    end
end
```

Specifically it seems that there probably is a `2^16` byte buffer somewhere, because this works:

```
julia> IOCapture.capture() do
           for i in 1:496
               eval(:(function f() 1 end))
           end
       end.output |> length
64932
```

but this hangs

```
julia> IOCapture.capture() do
           for i in 1:497
               eval(:(function f() 1 end))
           end
       end.output |> length
```

**Comment by zickgraf** [comment]
Thanks for the fast reply and analysis!

I have created a more basic example using the code from IOCapture:
```
# Original implementation from IOCapture.jl (MIT license)
function capture(f)
    default_stderr = stderr

    # Redirect both the `stdout` and `stderr` streams to a single `Pipe` object.
    pipe = Pipe()
    Base.link_pipe!(pipe; reader_supports_async = true, writer_supports_async = true)

    println("start")
    
    # Bytes written to the `pipe` are captured in `output` and eventually converted to a
    # `String`. We need to use an asynchronous task to continously tranfer bytes from the
    # pipe to `output` in order to avoid the buffer filling up and stalling write() calls in
    # user code.
    output = IOBuffer()
    buffer_redirect_task = @async write(output, pipe)
    
    redirect_stderr(pipe.in)
    
    f()
    #wait(@async f())
    
    println("end")
    
    redirect_stderr(default_stderr)
    close(pipe.in)
    wait(buffer_redirect_task)
end

function g1()
    for i in 1:100
        eval(:(function f() 1 end))
    end
end

function g2()
    for i in 1:1024
        eval(:(function f() 1 end))
    end
end

println("g1")
capture(g1)
println("g2")
capture(g2)
```

When executing with `julia --warn-overwrite=yes`, capturing `g1` succeeds but capturing `g2` hangs.

Observation: If one replaces `f()` by `wait(@async f())` then also `g2` succeeds. I have no knowledge of parallelism in Julia but to me it looks like `buffer_redirect_task` simply never gets a chance to run and drain the pipe.

Do you think this is a bug in Julia? Or could making `f()` async be an improvement for `IOCapture.jl`? In the latter case, I would be happy to create a PR there.

**Comment by KristofferC** [comment]
Would be interesting to see if reverting https://github.com/JuliaDocs/IOCapture.jl/commit/2348096b2d4032f4254ca59d87bccf4aca7e6d74 has any effect. In any case, we should have a reader that is continuously reading from the pipe so not sure why it would start blocking.

**Comment by zickgraf** [comment]
> Would be interesting to see if reverting [JuliaDocs/IOCapture.jl@2348096](https://github.com/JuliaDocs/IOCapture.jl/commit/2348096b2d4032f4254ca59d87bccf4aca7e6d74) has any effect.

I just checked and the behaviour is the same.

But another observation: adding a `print("")` between the creation of `buffer_redirect_task` and calling `f()` makes `g2` succeed.

**Comment by KristofferC** [comment]
>  adding a print("") between the creation of

How about adding a `yield()`?

**Comment by zickgraf** [comment]
> > adding a print("") between the creation of
> 
> How about adding a `yield()`?

Indeed, this also does the trick!

**Comment by KristofferC** [comment]
I don't know why that would be the case but there are some other cases where some random looking `yield`s are used to help get things unstuck e.g. https://github.com/JuliaLang/julia/blob/e4924c51de668387c407a54f328e349ae882ac30/contrib/generate_precompile.jl#L332.

So maybe best thing right now is to just slap the `yield` on there since it seems to improve things and shouldn't have any negative effect.

**Comment by mortenpi** [comment]
Interestingly, if you Ctrl+C out of a hanging Julia script process you get:

```
$ julia --warn-overwrite=yes --project test.jl
^CError: Maybe we should never reach this?
```

**Comment by zickgraf** [comment]
> Interestingly, if you Ctrl+C out of a hanging Julia script process you get:
> 
> ```
> $ julia --warn-overwrite=yes --project test.jl
> ^CError: Maybe we should never reach this?
> ```

Do you know who/what prints this line? It did not appear in my tests and grepping through Julia and installed packages does not show anything.

**Comment by mortenpi** [comment]
Apparently it comes from `juliaup`: https://github.com/JuliaLang/juliaup/blob/fb5ce2d479336e298f2ed7f29666d20d4e8310c9/src/bin/julialauncher.rs#L327

If I call the Julia binary directly then it doesn't print anything:

```
$ $HOME/.julia/juliaup/julia-1.9.0+0.x64.linux.gnu/bin/julia --warn-overwrite=yes --project test.jl
^C
```

**Comment by zickgraf** [comment]
> Apparently it comes from `juliaup` (took a while to find, but showed up in the GitHub code search): https://github.com/JuliaLang/juliaup/blob/fb5ce2d479336e298f2ed7f29666d20d4e8310c9/src/bin/julialauncher.rs#L327

Ah, interesting. Probably the signal handling is borked when exiting from the hang?
