### ISSUE TITLE
Specify redirect target in index.html to be dev/?

### ISSUE THREAD

**Issue by fsaad** [JuliaDocs/Documenter.jl#2127]
Related: https://github.com/JuliaDocs/Documenter.jl/issues/937

Is it possible call deploydocs in such a way that the generated index.html file always redirects to ./dev?

It seems the current code automatically determines which of ./stable or ./dev should be used in the redirect, based on the return value of HTMLWriter.expand_versions:

https://github.com/JuliaDocs/Documenter.jl/blob/233a7822d670b063e894f62aea00729bcb3a28dd/src/deploydocs.jl#L339-L348

**Comment by fredrikekre** [comment]
Documenter won't change the file if you manage it on your own, specifically, if the comment `<!--This file is automatically generated by Documenter.jl-->` is not in the file Documenter won't touch it, see https://github.com/JuliaDocs/Documenter.jl/blob/master/src/html/HTMLWriter.jl#L1494-L1496.

(Why would you default to /dev though? Latest stable release seems like a sane default, no?)

**Comment by fsaad** [comment]
Thank you for explaining. It would be good document this behavior, in the following line

https://github.com/JuliaDocs/Documenter.jl/blob/233a7822d670b063e894f62aea00729bcb3a28dd/src/deploydocs.jl#L49-L50

**Comment by mortenpi** [comment]
Happy to accept a PR to get this documented there :slightly_smiling_face: I'll re-open this, with the docs being the actionable item.
