### ISSUE TITLE
LaTeX output requires `pages` argument to `makedocs()`

### ISSUE THREAD

**Issue by johnomotani** [JuliaDocs/Documenter.jl#2132]
When I tried to build LaTeX documentation for a project where HTML documentation was already working, I found the `.tex` file was 'empty' (just the preamble and `\end{document}`). By digging through the source code, I found that this was because `doc.user.pages` was empty here https://github.com/JuliaDocs/Documenter.jl/blob/233a7822d670b063e894f62aea00729bcb3a28dd/src/latex/LaTeXWriter.jl#L116
and could be fixed by passing a `pages` kwarg to `makedocs()`.

It would be helpful to document that the `pages` argument is required, e.g. here https://documenter.juliadocs.org/stable/man/other-formats/#pdf-output.

It would also be nice to default (when `pages` is not passed) to building all the pages in some default order, the way the HTML writer already does. The pages do seem to be present already, e.g. in `doc.blueprint.pages`, so I guess this should not be too difficult?

**Comment by mortenpi** [comment]
> It would also be nice to default (when `pages` is not passed) to building all the pages in some default order, the way the HTML writer already does. The pages do seem to be present already, e.g. in `doc.blueprint.pages`, so I guess this should not be too difficult?

This seems reasonable to me. Not even sure why we don't do that already.

**Comment by mortenpi** [comment]
Note: this is actually a bug -- the documented `pages` behavior is that it should pick up the `.md` files:

> If omitted, Documenter will automatically generate a flat list of pages based on the files present in the source directory.
