### ISSUE TITLE
Building doc fails with "3269 Segmentation fault"

### ISSUE THREAD

**Issue by alexandrebouchard** [JuliaDocs/Documenter.jl#2136]
While running Documenter in a github action CI, I got a cryptic error:

```
/home/runner/work/_temp/c076b19c-5858-4986-a124-aac16c4443ef.sh: line 16:  3269 Segmentation fault      (core dumped) "${julia_cmd[@]}"
```

Full logs at: https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/5075600860/jobs/9116982598

This seems to be a non-deterministic problem, it does not pop up every time, and never locally. It only started showing up a few days ago around once every two builds or so, and we barely changed the docs in that intervals so that came a bit as a surprise. 

I was wondering if anyone has encountered something similar before and/or have ideas to troubleshoot this issue?

Thank you!

**Comment by alexandrebouchard** [comment]
It looks like the '3269' part of the error message is not an error code as it changes, e.g. in the latest crash we get 3104 instead:

```
/home/runner/work/_temp/7084d913-21fd-4efd-9dc3-16bc8722e9c2.sh: line 16:  3104 Segmentation fault      (core dumped) "${julia_cmd[@]}"
```

All the code in the `@example` blocks are also heavily tested in the test CI and do not error.

**Comment by alexandrebouchard** [comment]
The problem seems to have started roughly when the CI started grabbing Julia 1.9 instead of 1.8. For now, we are fixing Julia to 1.8 in CI to see if that's a reliable workaround. I'll report back if the problem occurs with Julia 1.8 as well.

**Comment by kbarros** [comment]
I also see occasional segfaults in the docs builds of our [Sunny](https://github.com/SunnySuite/Sunny.jl) project. This happens after all the docs files are written, so it's something we've been ignoring. The crashes seems nondeterministic. To try reproduce, download Sunny and execute `cd Sunny/docs; julia make.jl --fast`. The `--fast` switch enables `isdraft=true` in the `Documenter.makedocs` command to disable cell evaluation.
```
julia> versioninfo()
Julia Version 1.12.2
Commit ca9b6662be4 (2025-11-20 16:25 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, apple-m1)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 6 virtual cores)
```
