### ISSUE TITLE
The `dev` branch of the docs goes live but tagged versions do not, despite both existing in `gh-pages`

### ISSUE THREAD

**Issue by tomchor** [JuliaDocs/Documenter.jl#2137]
I set up Documenter for my repo here: https://github.com/tomchor/Oceanostics.jl

When going to the [`gh-pages` branch](https://github.com/tomchor/Oceanostics.jl/tree/gh-pages) I can see that the `dev` version is there and so is the `0.11.1` version, but for some reason only the `dev` version goes live. I can see it here: https://tomchor.github.io/Oceanostics.jl/dev/

The stable version throws me a 404: https://tomchor.github.io/Oceanostics.jl/stable/

Can someone point me in the right direction here?

Thanks in advance!

**Comment by odow** [comment]
It seems like it ran on your `v0.11.1-docs` tag and not on `v0.11.1`: https://github.com/tomchor/Oceanostics.jl/tree/gh-pages/v0.11.1-docs

It should work if you make a new tag that is of the format `vX.Y.Z`, or if you explicitly set the `versions` argument to `deploydocs`:
https://documenter.juliadocs.org/stable/lib/public/#Documenter.deploydocs

**Comment by mortenpi** [comment]
If your goal was to re-trigger the build for the tag with the `-docs` tag, you should have used the "build metadata" instead (i.e. `+` not `-`). If you push a `v0.11.1+docs` tag, it should properly deploy `v0.11.1/`. There shouldn't be any need to make any changes to `make.jl`.

**Comment by mortenpi** [comment]
If you look at your CI logs, you see that the CI didn't trigger for the tag. It seems like you don't have `DOCUMENTER_KEY` set up? TagBot [needs that to trigger CI on tags](https://github.com/JuliaRegistries/TagBot#ssh-deploy-keys).

**Comment by tomchor** [comment]
I already have a working ssh key on github. Going through the section of README you sent, I think what was missing was the secret. I think I had accidentally set that up as a variable.

Just to make sure, if the contents of my public ssh key are in `~/.ssh/id_ed25519.pub`, the secret should contain the contents of `~/.ssh/id_ed25519` without the head and the tail, correct?

Also, is there any way to re-trigger the docs without having the re-register the package? Will just re-tagging `v0.11.2` manually work? (And then I can remove the old tag?)

**Comment by mortenpi** [comment]
> Just to make sure, if the contents of my public ssh key are in `~/.ssh/id_ed25519.pub`, the secret should contain the contents of `~/.ssh/id_ed25519` without the head and the tail, correct?

No, it should also be base64-encoded. The easy way is to just use DocumenterTools to generate it for you: https://documenter.juliadocs.org/stable/lib/public/#DocumenterTools.genkeys

**Comment by mortenpi** [comment]
> Also, is there any way to re-trigger the docs without having the re-register the package? Will just re-tagging `v0.11.2` manually work? (And then I can remove the old tag?)

You can push a new tag with "build metadata", like `v0.11.2+docs1`. From Documenter's perspective it's the same as `v0.11.2` and will deploy the docs for that version.

**Comment by tomchor** [comment]
It works! Thanks so much. I appreciate you taking the time to help me :)
