### ISSUE TITLE
Make @example code blocks detected as julia code in VS Code?

### ISSUE THREAD

**Issue by tpoisot** [JuliaDocs/Documenter.jl#2139]
When working with `@example` blocks in VS Code, it's pretty tedious to have to manually edit, indent, etc., everything.

My current workaround is to define the language as *Julia Markdown*, write the examples using `~~~julia` blocks, and then switch to `@example` before commit. It's a little unwieldy.

Is there a way to benefit from the VS code features when editing documenter pages?

**Comment by mortenpi** [comment]
This really seems like something that must be handled in the VS Code Julia extension? I don't think there's anything Documenter itself can do here (other than committing to specific Markdown syntax, which we already have)?

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_ 

Closing because this is not a bug in Documenter.jl. It's probably also hard for VS-Code to detect because the `@example` block is Documenter-specific.
