### ISSUE TITLE
Changing the search engine

### ISSUE THREAD

**Issue by Hetarth02** [JuliaDocs/Documenter.jl#2141]
Issue #1457, Issue #1749 This addresses the problem of getting insufficient or non-ideal search results after the search.

Issue #1832: This issue also proposes the idea of using a different search engine instead of LunrJs to reduce initial lag which happens during the building of the indexes.

Moreover, lunrjs repo has been stale for some time.

I mostly suggest minisearchjs.

- It is designed for memory-constrained cases.
- Is inspired by Lunrjs, so it will be easier to shift to it by not having to re-implement the entire search logic.
- Supports suggestions if you want to improve the search UI in future.

**16 June, 2023**
For anyone wanting to test it out, here is the link to compare both results from both engines.

[Compare Searches](https://documenter-search.netlify.app/compare-search.html)

**Comment by Hetarth02** [comment]
For the cold start times of lunrjs, currently we can have something of an opt-in pre-building of indexes and just load up the serialised index on client-side.

A simple benchmark I did yielded these results,

![img-20230524-wa0001-1.jpg](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/3e103815-3a59-4bf6-86d6-3272269b050a)

![img-20230524-wa0002-1.jpg](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/64efe85a-0d4c-4caf-ba89-25128e304818)

The load times, went to around ~2900ms to ~800ms.

The serialised index size is around 7.6mb

For minisearchjs,

Serialised Index size is around 6.4mb (Around 16% less than lunrjs)

And Instantiation time with prebuild index is around ~500ms.

The only downside for prebuilding index is that we require NodeJs as an environment.

**Comment by mortenpi** [comment]
Looks good, I think we definitely want this on our roadmap. It would be good to have side-by-side demos with the same index for e.g. the Julia manual, to see how the search results differ. And also maybe have it print out the timings and index sizes in the consoles.

**Comment by Hetarth02** [comment]
For anyone wanting to test it out, here is the link to compare both results.

[Compare Searches](https://documenter-search.netlify.app/compare-search.html)

**Comment by mortenpi** [comment]
Alright, I did a few small tweaks to the compare page (https://github.com/mortenpi/documenter-updated-search/commit/04c766c953e09949f618d1ecc3240e1ad0f1a50c; [deployed here](https://mortenpi.eu/documenter-updated-search/compare-search.html)) and tried out a bunch of cases.

My take is that the results are usually slightly better (better priority for some things), but mostly the same. Only in some rare cases it seems that minisearch promotes some strange results. Generally, though, it often seems to filter out some of the less useful ones, which is good (e.g. `base64`).

Not super important, but for `multi threading`, minisearch seems to find a lot of duplicates though. Not sure what's up with that.

All in all though, considering the other benefits minisearch would bring that we've discussed, I'd say yeah, let's go for it!

**Comment by mortenpi** [comment]
> Supports suggestions if you want to improve the search UI in future.

How do these work exactly by the way? If they're easy to implement, then we could add this right away, when we switch.

**Comment by Hetarth02** [comment]
@mortenpi It mostly uses all the options as the original search does. Here is the explanation in the [docs](https://lucaong.github.io/minisearch/#auto-suggestions).

**Comment by mortenpi** [comment]
Would be cool if we could maybe auto-suggest e.g. function names that way. I think often people will start searching for something, but don't necessarily remember the exact name.

**Comment by fredrikekre** [comment]
Partial exakt matches doesn't work great right now it looks like. For example, searching for `cholesky` doesn't give any good resault until `cholesk`.

**Comment by Hetarth02** [comment]
> Partial exakt matches doesn't work great right now it looks like. For example, searching for cholesky doesn't give any good resault until cholesk.

That might have to do with the fuzzy search distance. Currently it only checks for one edit distance for the word. We can increase or decrease it as we please.

**Comment by fredrikekre** [comment]
Yea, that would be good. I think it is pretty common that you type correct thing, and it "feels nice" if you get the correct results before typing the whole thing.

**Comment by Hetarth02** [comment]
> Would be cool if we could maybe auto-suggest e.g. function names that way. I think often people will start searching for something, but don't necessarily remember the exact name.

Yeah, we can I will what I can do UI wise to incorporate it.

**Comment by mortenpi** [comment]
Done in #2172.
