### ISSUE TITLE
Updating the search UI

### ISSUE THREAD

**Issue by Hetarth02** [JuliaDocs/Documenter.jl#2147]
Currently the search UI looks like this,

![Screenshot_2023-06-24-01-10-20-64_a1b1bbe5f63d5b96c1a0f87c197ebfae.jpg](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/530e4990-de5c-4b16-b805-28254008f4b8)

This doesn't display much information about the search results.

I think that the UI should display more information regarding search results like, what category is this from, where did the term match.

Moreover, rather than having a separate page for searching we should have something like a search modal which can be accessible from anywhere. This would be a lot helpful. We can take inspiration from other documentations and how have they implemented their search UI.

[Issue #1437](https://github.com/JuliaDocs/Documenter.jl/issues/1437), [Issue #1986](https://github.com/JuliaDocs/Documenter.jl/issues/1986): These issues also address that the search results should display some more information rather than just the title of the search result.

**Comment by Hetarth02** [comment]
I have made a page having different search mockups. Here is the [link](https://documenter-search.netlify.app/search-ui.html).

Feel free to leave any feedback here.

**Comment by Hetarth02** [comment]
### Update 01 July, 2023.
- I have added some new mockups. (7 onwards)

**Comment by mortenpi** [comment]
I think I like 11 the most out of those ones. I think the overall layout there makes sense. So we could take that and start iterating on it in a fully functional demo (or even start integrating it into Documenter).

![image](https://github.com/JuliaDocs/Documenter.jl/assets/147757/7f817d1c-46f8-4dfc-b395-6ff43cdb87e0)

**Comment by Hetarth02** [comment]
PR #2172 gives some insight as to what the new UI might look like.

I have updated the default list view for the time being and will be working on the search modal along with improving the UI based on your feedbacks.
