### ISSUE TITLE
Using Documenter in non-package context

### ISSUE THREAD

**Issue by roland-KA** [JuliaDocs/Documenter.jl#2161]
To my understanding, `Documenter` always assumes that the files from which the documentation is generated are organized within a package. Is that correct?

Is it also possible to apply `Documenter` to a collection of Julia-files (within a folder) which do not belong to a package?

I have e.g. a collection of Julia scripts which do some file processing. Each one is a standalone Julia script that can be run independently. But I would also like to generate a common documentation from these files (since they are related around a common task/problem).

**Comment by mortenpi** [comment]
> `Documenter` always assumes that the files from which the documentation is generated are organized within a package. Is that correct?

I'd say not really, no. For example, the GitHub orgs [landing site](https://juliadocs.org/) is [generated with Documenter](https://github.com/JuliaDocs/juliadocs.github.io). You can use Documenter on any collection of Markdown files.

If your source files are actually Julia scripts (as opposed to Markdown files), you might want to consider using [Literate](https://github.com/fredrikekre/Literate.jl). It also has a native Documenter integration. If you want to include docstrings from your scripts, then you need to make sure that you can load those scripts (ideally as modules) into `make.jl`.

**Comment by roland-KA** [comment]
> from your scripts, then you need to make sure that you can load those scripts (ideally as modules) into make.jl.

So, I cannot apply Documenter to a Julia file, which is just a collection of functions? These functions have to be placed inside a module? ... that's where the `modules`-parameter of `makedocs` comes into play?

How would a minimal call to `makedoc` look like, if there is just one Julia file (e.g. `MyScript.jl` with a module `MyScript`), in order to extract doc-strings and generate a documentation from them?
Would `makedoc(modules = [MyScript])` be sufficient?

**Comment by mortenpi** [comment]
> So, I cannot apply Documenter to a Julia file, which is just a collection of functions? These functions have to be placed inside a module? ... that's where the `modules`-parameter of `makedocs` comes into play?

Well you can also include docstrings from `Main` into Documenter docs. So they do not, strictly speaking, have to be in a module. The main thing you would lose is the automated checks for docstrings that you've forgotten to include and such.

> How would a minimal call to `makedoc` look like, if there is just one Julia file (e.g. `MyScript.jl` with a module `MyScript`), in order to extract doc-strings and generate a documentation from them?

Minimal is just `makedocs(sitename="...")`. But you must have at least one Markdown file with an at-docs or at-autodocs block that actually includes those docstrings.

**Comment by roland-KA** [comment]
Ok, thanks, that does the trick 😊
