### ISSUE TITLE
Create a collapsible element that contains multi-line Julia code

### ISSUE THREAD

**Issue by Clemapfel** [JuliaDocs/Documenter.jl#2166]
Hi, I'd like to create a collapsible (`details`) that contains a multi-line block of Julia code. [This page](http://cords.in-berlin.de/out/md_10_closing_statements.html) contains an example of what I want, except its C++ generated by doxygen.

I tried the following:
```
\```@raw html
    <details>
    ```julia
    # jula code here
    ```
    </details
\```
```

Where I added the `\` just so it gets rendered properly here on GitHub. Here and in the output of documenter it actually comes out as:

<details>
```julia
# julia code here
```
</details>

I also tried 
```
<details><code>
    # julia code here
</code></details>
```
But this also did not render syntax highlighted, instead it came out the same as here on GitHub:

<details><code>
    # julia code here
</code></details>

Is there a way to do this? It doesn't have to be the `<details>` html element all I want is code inside a collapsible.

**Comment by mortenpi** [comment]
Would the `details` admonition added in https://github.com/JuliaDocs/Documenter.jl/pull/2128 work for you?

**Comment by fredrikekre** [comment]
Alternatively, the trick would be to surround the code block with *two* `@raw` blocks:
````
```@raw html
<details><summary>This is a summary</summary>
```

This text will be in the collapsed block...
```julia
# ... and this code too.
function foo(x::Int)
    return x^2
end
```

```@raw html
</details>
```

````

**Comment by Clemapfel** [comment]
Thank you, this worked perfectly
