### ISSUE TITLE
How do I deploy docs to another repo? 

### ISSUE THREAD

**Issue by Boxylmer** [JuliaDocs/Documenter.jl#2178]
Right now the `deploydocs` documentation tells us that `repo` will specify the repo to push to, however when in Github Actions, we see that this repo must match the repo name, e.g., 

```
Deployment criteria for deploying devbranch build from GitHub Actions:
- ✘ ENV["GITHUB_REPOSITORY"]="Boxylmer/myrepo.jl" occurs in repo="github.com/Boxylmer/someotherrepo"
- ✔ ENV["GITHUB_EVENT_NAME"]="push" is "push", "workflow_dispatch" or "schedule"
- ✔ ENV["GITHUB_REF"] matches devbranch="master"
- ✔ ENV["GITHUB_ACTOR"] exists and is non-empty
- ✔ ENV["GITHUB_TOKEN"] exists and is non-empty
Deploying: ✘
```

How can I modify my deploy to be able to push the built docs to another repo? 
```Julia
deploydocs(;
    repo="github.com/Boxylmer/someotherrepo.git",
    devbranch="master",
)
```

**Comment by mortenpi** [comment]
Probably the easiest option is to just override the `GITHUB_REPOSITORY` variable just before `deploydocs` to "trick" it. E.g. with something like
```julia
ENV["GITHUB_REPOSITORY"] = "Boxylmer/someotherrepo"
deploydocs(;
    repo="github.com/Boxylmer/someotherrepo.git",
    devbranch="master",
)
```

**Comment by Boxylmer** [comment]
This bypassed that issue! Thank you! Next up is work on documenter_key errors, but I'm 100% certain that one is my lack of working knowledge with ssh keys currently. 

Thanks again!
