### ISSUE TITLE
Documenter doesn't recognize module name shortcut?

### ISSUE THREAD

**Issue by gdalle** [JuliaDocs/Documenter.jl#2183]
I'm developing a package called [HiddenMarkovModels.jl](https://github.com/gdalle/HiddenMarkovModels.jl). Since users need to extend functions, I thought prefixing everything with `HiddenMarkovModels.f` would be cumbersome, so I added a shortcut:
```julia
module HiddenMarkovModels

const HMMs = HiddenMarkovModels
export HMMs

# stuff

end
```
This shortcut has a docstring, I put it in a Markdown `@docs` block, and so it [appears in the docs website](https://gdalle.github.io/HiddenMarkovModels.jl/stable/api/#HiddenMarkovModels.HMMs). However, Documenter throws a warning every time it builds (see the [CI log](https://github.com/gdalle/HiddenMarkovModels.jl/actions/runs/5542625290)):
```
1 docstring not included in the manual:

    HiddenMarkovModels.HMMs

These are docstrings in the checked modules (configured with the modules keyword)
that are not included in https://github.com/docs or @autodocs blocks.
```
Not very problematic but still a bit surprising. Any idea why that is?

**Comment by odow** [comment]
To clarify, `const HMMs = HiddenMarkovModels` is for the current module??? 

Does it work if you try `const HMMs = @__MODULE__`?

I wouldn't have expected that `using HiddenMarkovModels` would import a constant `HMMs` that is itself a reference to `HiddenMarkovModels`.

If they want to extend, can't they do `import HiddenMarkovModels as HMMs`?

**Comment by gdalle** [comment]
Okay yeah that's probably more healthy, thanks ^^ closing
