### ISSUE TITLE
Including docstrings from other packages error

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#2199]
For example:
```
ERROR: LoadError: Unable to generate source url for FerriteMeshParser @ /home/fredrik/.julia/packages/FerriteMeshParser/hIhHj/src/FerriteMeshParser.jl:32:49
```
where `FerriteMeshParser` is a `Pkg.add`ed doc dependency. It works if you `Pkg.dev` though.

**Comment by mortenpi** [comment]
Is this a regression? I.e. it works on 0.27?

**Comment by fredrikekre** [comment]
Yes.

**Comment by mortenpi** [comment]
Maybe we could make the error a bit more informative somehow though?
