### ISSUE TITLE
Reduce surface area of docstring folding

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#2204]
I often click on docstring headers in order to copy the URL pointing to it. This folds the docstring which is a bit annoying. Would it be possible to reduce the surface area to fold? Perhaps limited to the arrow, at least if the docstring is open.

**Comment by mortenpi** [comment]
Yep, I've also noticed this. cc @Hetarth02

**Comment by Hetarth02** [comment]
I initially had the idea for keeping the collapse/open on the icon only but then thought that might be too small of an area and people might not notice that it is collapsible at all.

We can definitely make the collapse/expand on icon only.

**Comment by AnzhiZhang** [comment]
Just a quick relative question, I tried search it: How to disable arrow and collapse? I saw some packages disabled it for docstrings, e.g. https://docs.julialang.org/en/v1/base/base/#Getting-Around

**Comment by Hetarth02** [comment]
As far as I know, you can't disable this behaviour. The ones where you see it disable might be an older version of documenter.
