### ISSUE TITLE
Line numbers with highlight.js

### ISSUE THREAD

**Issue by snotskie** [JuliaDocs/Documenter.jl#2234]
How do I enable line numbers for highlight?

I've tried adding [this plugin](https://github.com/wcoder/highlightjs-line-numbers.js) as an asset.

In my `make.jl`:

```julia
makedocs(
    format=Documenter.HTML(assets=[
        asset("https://cdn.jsdelivr.net/npm/highlightjs-line-numbers.js/dist/highlightjs-line-numbers.min.js"),
        "assets/script.js"
    ]),
    ...
)
```

In `script.js`:

```js
hljs.initLineNumbersOnLoad();
```

Raises this error in the browser:

```
highlightjs-line-numbers.min.js:1 highlight.js not detected!
(anonymous) @ highlightjs-line-numbers.min.js:1
(anonymous) @ highlightjs-line-numbers.min.js:1
script.js:11 Uncaught ReferenceError: hljs is not defined
    at script.js:11:1
```

Checking the DOM, seems the custom assets are being loaded before highlight.

I could probably do something rough in `script.js` where I load the plugin dynamically and add line numbers after initial page load, but I'd like to avoid that

Thoughts?

**Comment by mortenpi** [comment]
I think we wrap it in RequireJS, so the `highlight` object (or whatever it's looking for) is probably not visible in the global scope. As a hack, maybe you can overload this function, adding the extra dep and init code there?

https://github.com/JuliaDocs/Documenter.jl/blob/e2bd1940ad9a8ad1320252a2fc3b4468b770e3a4/src/html/RD.jl#L31-L60

**Comment by fredrikekre** [comment]
https://github.com/fredrikekre/DocumenterCodeBlocks.jl provides line numbers (and much more such as line range links etc) with example usage in a real package here: https://ferrite-fem.github.io/Ferrite.jl/dev/tutorials/heat_equation/#heat_equation-plain-program.
