### ISSUE TITLE
[Suggest]Make docstring foldable on web page?

### ISSUE THREAD

**Issue by Xlin0mu** [JuliaDocs/Documenter.jl#2240]
Could we make this block foldable? Otherwise it make docpage too long for viewing when there's so many docstrings especially in Julia Language Manual.
![image](https://github.com/JuliaDocs/Documenter.jl/assets/99205570/56e09bf2-c6b9-4b82-92e4-8e2afbe91fff)

**Comment by mortenpi** [comment]
This is already implemented, just not in a release: #2078. You can try it out on the dev version docs of Documenter for example: https://documenter.juliadocs.org/dev/lib/public/

**Comment by gdalle** [comment]
Bumping to reopen because I think a keyword argument that folds everything by default would make sense. It was mentioned in #2078 but kept for a later PR.

**Comment by mortenpi** [comment]
@gdalle I would suggest opening a new issue for that.
