### ISSUE TITLE
Add a `plugins` keyword argument for `doctests` (and `makedocs`)

### ISSUE THREAD

**Issue by goerz** [JuliaDocs/Documenter.jl#2245]
From https://github.com/JuliaDocs/DocumenterCitations.jl/issues/34, downstream from https://github.com/CliMA/ClimaAtmos.jl/issues/2068

At least in principle, it would be conceivable that a Documenter plugin could do something that would affect doctests. It would be good if there was some way to pass plugins to the `doctest` function.

As a matter of fact (since there's a breaking 1.0 release coming), it might be worth reconsidering how Documenter handles plugins in general. The way plugins are passed as positional arguments is undocumented, see https://github.com/JuliaDocs/Documenter.jl/issues/2113. Maybe it would be better to have a `plugins` keyword argument for both `makedocs` and `doctests`?

**Comment by mortenpi** [comment]
Yeah, I would be okay with changing the positional argument to a keyword in `makedocs`. And yes, I think `doctest` should also take that keyword.

**Comment by goerz** [comment]
Great, I'll take a stab at it maybe this weekend

**Comment by goerz** [comment]
Done, see https://github.com/JuliaDocs/Documenter.jl/pull/2249
