### ISSUE TITLE
Direct link to source repo from the documents

### ISSUE THREAD

**Issue by jmskov** [JuliaDocs/Documenter.jl#2248]
I often want to go to the main branch of the repo hosting the documentation. The closest built in option AFAICT is the `Edit on Github` link that goes to the source of the documentation. Has there been any discussion on an additional link to the repo's main page, or is there a standard practice in place for including such a link?

**Comment by mortenpi** [comment]
This is already implemented on `#master`, will be in 1.0: https://github.com/JuliaDocs/Documenter.jl/pull/1254
