### ISSUE TITLE
HTMLWriter: sidebar doesn't reflect contents?

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#225]
I may be doing something wrong, but the sidebar contents is only picking up the level 2 (`##`) headings from `src/index.md`, whereas the @contents macro is doing the right thing. Presumably they're compiled differently somehow, but shouldn't they be more similar? Or have I omitted some stages (I've just got a single `index.md` file, for example.)

![screen shot 2016-08-22 at 13 35 42](https://cloud.githubusercontent.com/assets/52289/17854984/f79bf450-686d-11e6-98c6-656a2902e1b7.png)

**Comment by MichaelHatherly** [comment]
I believe that the assumption is that each page has a single `<h1>` header followed by any number of nested subheaders. They should be more similar though, you've not omitted any stages.

**Comment by mortenpi** [comment]
Yes, it filters on `<h2>`, the specific function is [here](https://github.com/JuliaDocs/Documenter.jl/blob/master/src/Writers/HTMLWriter.jl#L579-L587), and the code is separate from the `@contents` code. The assumption is indeed that the first `<h1>` is the page title and there shouldn't be any other `<h1>`s.

I am not sure what would be to correct way of interpreting this outline (inner headings that are the same level as the page heading). For example, either MkDocs or Sphinx (don't remember which) only takes the `<h2>` up until the next `<h1>`, for example. We could also "fix" the outline, by assuming that if there are `<h1>`s besides the page title, all the heading would be shifted by a level. Or we could make the additional `<h1>`s bold in the sidebar, to make them distinct from the usual `<h2>`s.

That being said, I don't think we should silently ignore the `<h1>`s, like we do now. Either we should print a warning that the page outline is problematic, or somehow make use of these `<h1>`s.

My question would be: what would you expectation be regarding the sidebar in this case? Should it be the `<h1>`s, without the first one?

**Comment by MichaelHatherly** [comment]
Using bold for additional `H1` and normal for `H2` sounds like it could work reasonably well perhaps. I think it's probably not a good idea to only show a partial header structure even if sphinx/mkdocs do that.

**Comment by mortenpi** [comment]
Here are a few style proposals. Different combinations of making the `<h1>`s bold or add a `border-top`.

![out](https://cloud.githubusercontent.com/assets/147757/17940752/ca00d564-6a30-11e6-8e87-3ec24e33a0c1.png)

**Comment by cormullion** [comment]
@mortenpi I like left one. Pure font changes are sometimes harder to see, but with lines as well, looks great.

**Comment by MichaelHatherly** [comment]
Left one looks good to me as well.
