### ISSUE TITLE
HTML contents not sorted correctly

### ISSUE THREAD

**Issue by carlobaldassi** [JuliaDocs/Documenter.jl#226]
I just tried out the HTML renderer on 0.3.0 and I found that the `@contents` blocks are not sorted as I wrote them, e.g.

    ```@contents
    Pages = [
        "algorithms.md",
        "graph-types.md",
        "graphs-builtin.md",
        "interface.md",
        ]
    Depth = 1
    ```

will show the links in the order provided with mkdocs, but it will show "graph-types", "graphs-builtin", "interface", "algorithms" with the HTML renderer.

BTW Is there any way to only show the contents from depth 2 for a page, i.e. excluding the page title as redundant?

**Comment by mortenpi** [comment]
Thanks for the report, I was able to reproduce it on Documenter's docs as well.

I don't think it's possible to set a minimum depth at the moment. Seems like a reasonable request though. @MichaelHatherly?

What would the use case for that be by the way.. contents of the same page?

**Comment by MichaelHatherly** [comment]
Yes, a minimum depth sounds reasonable. Perhaps using a `UnitRange` instead of an `Int` for the `Depth` value. So something like

    ```@contents
    Pages = [
        "algorithms.md",
        "graph-types.md",
        "graphs-builtin.md",
        "interface.md",
    ]
    Depth = 2:4
    ```

to display only levels `2` to `4`, while internally `Depth = N` is rewritten as `Depth = 1:N`.

**Comment by mortenpi** [comment]
@MichaelHatherly: I believe that the ordering issue arises because the sort in [`populate!`](https://github.com/JuliaDocs/Documenter.jl/blob/master/src/Documents.jl#L321-L326) is sensitive to the file extension. Any thoughts? Perhaps we should keep `page` as the `.source` not the `.build`?

**Comment by MichaelHatherly** [comment]
> Perhaps we should keep `page` as the `.source` not the `.build`?

Yes, that sounds fine to me.

**Comment by carlobaldassi** [comment]
> What would the use case for that be by the way.. contents of the same page?

Yes. It came up because I thought it'd be nice to show the page contents after the introductory paragraph in [this page](https://carlobaldassi.github.io/RRRMC.jl/latest/graphs-builtin/).
