### ISSUE TITLE
Express sizes in more human-readable form?

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#2272]
Congratulations on Documenter 1.0 - I've been using it without issues for various packages. It's awesome!

I think that this output:

<img width="1110" alt="Screenshot 2023-09-19 at 09 18 01" src="https://github.com/JuliaDocs/Documenter.jl/assets/52289/e10b8f94-6931-4436-a570-37b6b96654d3">

could be made better if the "bytes" were converted to something more familiar. These days I'd be happy with MB, but KB could be OK. And perhaps it could be rounded to the nearest sensible amount, the precision here seems unnecessary (and we'd avoid the Kibibytes versus Kilobytes issue too).

**Comment by mortenpi** [comment]
Yeah, absolutely. I was just too lazy to implement it :slightly_smiling_face:

**Comment by mortenpi** [comment]
The only thing is that there is a bit of range to the values, so I think it should pick the appropriate unit based on the order of magnitude (don't need to worry about anything other than `B`, `KiB` and `MiB` though).

**Comment by Hetarth02** [comment]
I would be happy to contribute.

@mortenpi Can you guide me, what we want to achieve(display in kb, mb, etc.) and where should I start looking?

**Comment by mortenpi** [comment]
@Hetarth02 The relevant line of code should be here: https://github.com/JuliaDocs/Documenter.jl/blob/5dafb6488f90d173ca4fcfeead0396332bdc6de6/src/html/HTMLWriter.jl#L1771-L1776

And as far as what we want to achieve: make sure that it prints the file sizes in `B`, `KiB` and `MiB` as appropriate when printing those values. No need to support `GiB` and bigger, since if the user has pages that big, they have bigger problems.

**Comment by cormullion** [comment]
`9223372036854775807` was the worst one 😂

**Comment by mortenpi** [comment]
> `9223372036854775807` was the worst one 😂

That probably needs to be special cased though. I'm using `typemax(Int)` to indicate "no limit".

https://github.com/JuliaDocs/Documenter.jl/blob/5dafb6488f90d173ca4fcfeead0396332bdc6de6/src/html/HTMLWriter.jl#L524

**Comment by mortenpi** [comment]
#2344

**Comment by cormullion** [comment]
Thanks!
