### ISSUE TITLE
Add keyword argument for folding all docstrings by default

### ISSUE THREAD

**Issue by gdalle** [JuliaDocs/Documenter.jl#2282]
I think this would be a very cool feature, it was mentioned in #2078 but then left aside

**Comment by mortenpi** [comment]
cc @Hetarth02

**Comment by Hetarth02** [comment]
There might be many ways to do this.

But I am thinking is this kind of minute control necessary?

**Comment by gdalle** [comment]
The idea came to me because it would make the user guide of AbstractDifferentiation.jl less scary. Basically when you try to mix text and docstrings this is a useful addition

https://juliadiff.org/AbstractDifferentiation.jl/dev/user_guide/

**Comment by Hetarth02** [comment]
Fair point.

Also, another thing I noticed why is the text out of bounds. I think the text should wrap itself.

![Screenshot_2023-09-26-20-51-50-05_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/73b95cf0-5cda-4137-82f4-d0d4ba6f670f)

**Comment by mortenpi** [comment]
One question mark I have is whether we want this to be something you can also control on a per-page basis or not. It wouldn't add much complexity to the implementation.

@Hetarth02 Do you want to open a separate issue for the wrapping?

**Comment by Hetarth02** [comment]
I am happy to open one, but I don't exactly know how would one implement this on per page basis and what would the flag look like.

**Comment by mortenpi** [comment]
So, we put the per-page options in at-meta blocks. But basically, the global flag would go into `HTML`, but we'd have to check for a per-page override then. `EditURL` should work as an example of how to get the user-given value out of the at-meta block, since that is used by HTMLWriter already.

**Comment by goerz** [comment]
Having the docstrings expanded or collapsed on a page-by-page basis is definitely something I'm very interested in. For something like [my API documentation](https://juliaquantumcontrol.github.io/QuantumControl.jl/dev/api/quantum_control_reference/#QuantumControlFunctionalsLocalAPI) (which is generated by a script), I'm currently listing all the members of the module and then have the docstrings below that. This would be much nicer if I can directly have the docstrings, but *only* if they're collapsed.

In any case, I implemented this feature in #2394. It would be great if one of you could review the PR.
