### ISSUE TITLE
Long text in docstring does not wrap on smaller screens

### ISSUE THREAD

**Issue by Hetarth02** [JuliaDocs/Documenter.jl#2293]
![image](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/d3ee4789-9571-4873-8d3c-a32fcb2655d1)

**Comment by Hetarth02** [comment]
One solution would be to `overflow: auto` the `header` tag just like the code content. (I prefer this.)
![image](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/a1f776ba-2305-4b7a-b7a3-ecfa67005a5f)


Another one would be to `word-break: break-all`, but that doesn't look good.
![image](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/2aefb8c6-5eb4-4e80-8810-00e1ececb059)

**Comment by mortenpi** [comment]
Yeah, `overflow: auto` seems better.
