### ISSUE TITLE
cross references errors when an unexported symbol is referenced

### ISSUE THREAD

**Issue by tpapp** [JuliaDocs/Documenter.jl#2304]
Consider

```julia
module Foo

export baz

"Where the magic happens. Not part of the exposed API, I just documented it."
bar(x) = x + 1

"The exposed API, uses [`bar`](@ref)."
baz(x) = bar(x)

end
```

with the `index.md`

````markdown
```@docs
baz
```
````

Documenter.jl (1.1.1) complains about 
```julia
┌ Error: no doc found for reference '[`bar`](@ref)' in src/index.md.
```

I am wondering if this is a bug, or a user error. On the one hand, Documenter.jl rightfully complains that it cannot resolve a link. On the other hand, it is not meant to.

(I know I can use exceptions to work around this).

**Comment by mortenpi** [comment]
This looks like a user error to me. You must include the docstring for `bar` in the manual if you want to reference it.

**Comment by tpapp** [comment]
I understand that this is currently a requirement by Documenter.jl, but I am not sure if this warranted in all cases.

I can imagine a scenario where eg one wants to 

1. document some internals using docstrings,
2. refer to these methods/types in a note (eg `!!! implementation note`) in the docstring of a method that is exposed in the manual and the API,
3. but omit the internals from the manual.

At the same time I understand how Documenter.jl cannot distinguish the above scenario from a mistake (omitted docs, etc).

Would it make sense to add an option for whitelisting symbols where cross-referencing can fail?

**Comment by mortenpi** [comment]
But why do you want to at-ref those symbols in the first place? If you don't include the docstrings in the manual, then those links will never ever work in any context. And so it's equivalent to writing e.g. ``Implementation note: uses `bar` `` (instead of ``Implementation note: uses [`bar`](@ref) ``).

**Comment by tpapp** [comment]
A user looking up docstrings at eg the repl (with `?`) would still see the reference and could follow it if the IDE supports that functionality.

**Comment by mortenpi** [comment]
Is there an IDE that actually supports this?

**Comment by tpapp** [comment]
Not that I am aware of (but I am only familiar with Emacs). I thought VS code supported this, but I don't have it installed at the moment.

**Comment by odow** [comment]
I think this issue should be closed. An `@ref` is a link, and this link does not exist.

**Comment by tpapp** [comment]
@odow: You are right in that `@ref` is indeed a link, and its target does not exist *in the output generated by Documenter.jl*. The situation is not unlike an URL http://fictional.company.vpn.internal, which gets resolved on an internal network. It is a valid URL, but a link checker running outside said network would not find it.

But at present this is pretty much a theoretical point, so feel free to close the issue if you prefer. The practical solution may be just not linking internal docs at present.

**Comment by odow** [comment]
I guess there's a difference between explicitly using a `.vpn` link that you can add to `linkcheck_ignore`, and the automatic `@ref`. If you want to ignore checking a `@ref`, it seems like it is the wrong tool for this job.

**Comment by mortenpi** [comment]
Let's close this. I don't think we're going to implement this. At least as long as we don't get a more higher level standard for what at-refs mean. The VS Code extension should actually be supporting a version of resolving at-ref links, but I'd say that at-ref right now is a Documenter syntax, and so Documenter decides how it should be interpreted (and for Documenter, those are invalid references).
