### ISSUE TITLE
Markdown heading level handling in docstring

### ISSUE THREAD

**Issue by 0815Creeper** [JuliaDocs/Documenter.jl#2308]
Consider docstring:

```
"""
    foo(x, f, k)

Do stuff

# Arguments
- `x`: some argument
- `f`: some function
    ## Pattern
    - `f(t)`
    - `f(t, u)`
    - `f(t, u, c)`
- `k`: some other argument
"""
function foo(x, f, k)
end
```

In REPL help, the format is as expected: \"Pattern\" is indented and a lower level heading as \"Arguments\"

When making the documentation with Documenter on the other hand, \"Pattern\" gets translated to \<h2\> while \"Arguements\" only becomes \<strong\>, not \<h1\>. Therefore it looks quite off.

Using \<h1\> for \"Arguments\" is obviously not a good solution either
=> Idea: translate all heading levels in docstrings to \<strong\> instead of \<h_\>

**Comment by mortenpi** [comment]
Yep, we should do this. I assume the issue is that we don't traverse into the AST when doing the `h1` -> `strong` rewrite, and just rewrite top-level elements.

**Comment by mortenpi** [comment]
I believe the rewriting happens here, if anyone wants to take a stab at PRing this: https://github.com/JuliaDocs/Documenter.jl/blob/6052e5f516800e22c65addec7ce69aaf84b247d5/src/expander_pipeline.jl#L964-L981

**Comment by odow** [comment]
https://github.com/JuliaDocs/Documenter.jl/issues/1146 asks for proper headings in docstrings, so if we decide to fix this, we should probably also close that issue.

**Comment by 0815Creeper** [comment]
About #1146
I would argue, that it is not necessary for "proper headings" to be rendered as part of the docstrings. If this is the prefered option, I assume it would be necessary to format them diffrently than the headings in the rest of the page. Having the `# Arguments` in every function docstring (part of julias docstring standard, not some optional formating) look the same as the headline of the page would seem out of place. I am neither competent enough in Julia nor in html and CSS to implement such a solution, so if someone else would like to take this, feel free ;) I would still be happy with the bolding of the headings within docstrings
