### ISSUE TITLE
How to ignore warnings

### ISSUE THREAD

**Issue by rafaqz** [JuliaDocs/Documenter.jl#2311]
I have broken links reported in this PR
https://github.com/rafaqz/Rasters.jl/pull/550

I get warnings like this `WARNING -  Doc file 'reference.md' contains a relative link '../china_rasterized.png'` and later ` Aborted with 3 warnings in strict mode!`

But they are in fact the correct links.

There appears to be no way to turn off this check, `strict=false` is doing nothing. 

This is currently preventing fixing the Rasters.jl docs:

https://github.com/rafaqz/Rasters.jl/actions/runs/6631395937/job/18014819446?pr=550#step:6:501

Here are some intructions to understand the issue pasted in from slack conversation  with @fredrikekre 

Firstl the problem seems to be that the page is in the `reference` folder so the path is not in the base directory.

See here for an example with the `rasterize` docs
https://rafaqz.github.io/Rasters.jl/stable/reference/#Rasters.rasterize!

You will see this "rasterize" text just above that heading, where and image should be. 

![2023-10-24-221108_184x144_360](https://github.com/JuliaDocs/Documenter.jl/assets/2534009/8671bb04-89be-41df-bab7-35151ef25c78)

This passes strict tests, but actually the link needs to have `..` for it to work. When I change that I get all these warnings, even though it will actually work in the final docs:

https://github.com/rafaqz/Rasters.jl/actions/runs/6631395937/job/18014819446?pr=550#step:6:501

The docs look like this when I add the `..` to the path:

![2023-10-24-221727_649x496_480](https://github.com/JuliaDocs/Documenter.jl/assets/2534009/7a2fa11b-50ea-4bb3-a5e3-2d7a91d64003)

But that can't actually be built given the warning. So what can I do here. Ignoring the warning seems like the simplest solution, but `strict=false` is not doing anything.

**Comment by mortenpi** [comment]
Could you update to Documenter 1.x first, to see if helps? The link handling was overhauled a bit in 1.0.

**Comment by rafaqz** [comment]
DocumenterMarkdown is holding this back.

How do I turn off warnings for v0.27.25 ?

**Comment by mortenpi** [comment]
I don't think there is an option for it.

**Comment by rafaqz** [comment]
Ok, guess we have to fork the old version and fix it there for now.

Is there an option to turn off warnings in 1.0?

**Comment by rafaqz** [comment]
Maybe we can just symlink the dir somehow

**Comment by mortenpi** [comment]
> Is there an option to turn off warnings in 1.0?

Nope. But if you're getting this warning, there is a user error, so the warning is appropriate.

**Comment by rafaqz** [comment]
But, in this case the links that throw warnings correct, and not at all user error. The links that pass are incorrect.

Killing a docs build for that doesnt make sense. There needs to be a way to not check links.

**Comment by mortenpi** [comment]
> When docs generate markdown Documenter doesnt know where the final page will be, so it cant check relative links correctly.

I don't quite follow this. Could you put together an MWE with Documenter 1.0 and the HTML output, illustrating the problem?

**Comment by rafaqz** [comment]
The problem us with using DocumterMarkdown. So Im not sure how thats possible.

But logically, how can Documter possibly know the path of the final html generated from the markdown, and so check relative URLs.

**Comment by mortenpi** [comment]
Wait.. the errors in https://github.com/rafaqz/Rasters.jl/actions/runs/6676904100/job/18146421627?pr=550#step:6:472 are not even coming from Documenter... I believe they're coming from MkDocs.. https://github.com/mkdocs/mkdocs/blob/8909ab3f6dcd0556a8266a8cd6980f89810d1855/mkdocs/structure/pages.py#L390

**Comment by rafaqz** [comment]
Ah right so the "Aborted with 3 warnings in strict mode!" Is also mkdocs? 

The `strict` part got me thinking it was Documenter.jl. mkdocs must use the same terminology.

**Comment by mortenpi** [comment]
Yep: https://www.mkdocs.org/user-guide/configuration/#strict

**Comment by rafaqz** [comment]
Thanks, fixed
