### ISSUE TITLE
Show multiple images side-by-side

### ISSUE THREAD

**Issue by sloede** [JuliaDocs/Documenter.jl#2318]
I am trying to show some funding agency logos side by side, [like we do in our README.md](https://github.com/trixi-framework/Trixi.jl/tree/msl/add-numfocus?tab=readme-ov-file#acknowledgments):
<img width="905" alt="image" src="https://github.com/JuliaDocs/Documenter.jl/assets/3637659/81d8a8f6-80ec-434b-b984-bc0edd1304e2">

When using the same HTML code in our Documenter [docs](https://github.com/trixi-framework/Trixi.jl/blob/0f26ca2e11132f2ac5d9a48dc901dee9d3c0fe22/docs/src/index.md?plain=1#L347-L354), i.e., something like
~~~markdown
```@raw html
<p align="center" style="font-size:0;">
     <img align="middle" src="https://github.com/trixi-framework/Trixi.jl/assets/3637659/f59af636-3098-4be6-bf80-c6be3f17cbc6" height="120px"><!--
  --><img align="middle" src="https://github.com/trixi-framework/Trixi.jl/assets/3637659/e67b9ed3-7699-466a-bdaf-2ba070a29a8e" height="120px"><!--
  ...
  --><img align="middle" src="https://github.com/trixi-framework/Trixi.jl/assets/3637659/8496ac9e-b586-475f-adb7-69bcfc415185" height="120px">
</p>
```
~~~

I only get images one below the other, [like so](https://trixi-framework.github.io/Trixi.jl/previews/PR1697/#Acknowledgments), without even knowing exactly where they get their width/height from (they are all 360 pixels high):
<img width="879" alt="image" src="https://github.com/JuliaDocs/Documenter.jl/assets/3637659/35bda6cc-043f-411d-bd0b-b9ff960eb1a2">

Is there any way I can get them aligned nicely side-by-side in Documenter.jl as well?

**Comment by odow** [comment]
Documenter doesn't have support for this. Your options are probably:

 * create a single image externally with the logos aligned appropriately and include that
 * create a Markdown table with the images inside each cell
 * mess with the HTML and CSS stylings

**Comment by mortenpi** [comment]
A table might be a good idea for this anyway!

Otherwise, I think you might just need to apply `style="display: inline;"` to each of the `<img>` tags.

**Comment by sloede** [comment]
Thanks for the feedback. Unfortunately, none of the proposed solutions seemed to work for my case:
* `style="display: inline;"` does not help
* a table does not work since my images have different width

What I ended up with, after a *lot* of experimentation (you all know how much "fun" tinkering with HTML and CSS is, especially as a non-expert 😭), is the following (as a reference and warning to future lost souls):
```html
<div style="width: 100%; text-align: center; font-size: 0;">
  <div><!--
    BMBF     --><img src="https://github.com/trixi-framework/Trixi.jl/assets/3637659/f59af636-3098-4be6-bf80-c6be3f17cbc6" style="height: 120px; width: auto"><!--
    DFG      --><img src="https://github.com/trixi-framework/Trixi.jl/assets/3637659/e67b9ed3-7699-466a-bdaf-2ba070a29a8e" style="height: 120px; width: auto"><!--
    SRC      --><img src="https://github.com/trixi-framework/Trixi.jl/assets/3637659/48f9da06-6f7a-4586-b23e-739bee3901c0" style="height: 120px; width: auto"><!--
    -->
  </div>
  <div><!--
    ERC      --><img src="https://github.com/trixi-framework/Trixi.jl/assets/3637659/9371e7e4-3491-4433-ac5f-b3bfb215f5ca" style="height: 120px; width: auto"><!--
    NSF      --><img src="https://github.com/trixi-framework/Trixi.jl/assets/3637659/5325103c-ae81-4747-b87c-c6e4a1b1d7a8" style="height: 120px; width: auto"><!--
    DUBS     --><img src="https://github.com/trixi-framework/Trixi.jl/assets/3637659/bb021e6e-42e6-4fe1-a414-c847402e1937" style="height: 120px; width: auto"><!--
    -->
  </div>
  <div><!--
    NumFOCUS --><img src="https://github.com/trixi-framework/Trixi.jl/assets/3637659/8496ac9e-b586-475f-adb7-69bcfc415185" style="height: 120px; width: auto"><!--
    -->
  </div>
</div>
```
