### ISSUE TITLE
Linkcheck does not traverse into docstrings

### ISSUE THREAD

**Issue by goerz** [JuliaDocs/Documenter.jl#2329]
When `makedocs` is called with `linkcheck=true`, the [`Documenter.linkcheck`](https://github.com/JuliaDocs/Documenter.jl/blob/c6abf9d7f00acd0293a6bad90267ea0669c01ab7/src/docchecks.jl#L168) routine does not traverse into `DocsNode`. That is, broken links inside of docstrings will not be reported.

The reason for this is

https://github.com/JuliaDocs/Documenter.jl/blob/c6abf9d7f00acd0293a6bad90267ea0669c01ab7/src/docchecks.jl#L183-L184

Since the `node.element` for a docstring is a `DocsNode`, nothing happens.

To fix this, `linkcheck(node::MarkdownAST.Node, doc::Document; method::Symbol=:HEAD)` should receive `element=node.element` as an explicit second parameter, so that we can dispatch on that. Other places in `Documenter` follow the same approach, e.g., the [`domify`](https://github.com/JuliaDocs/Documenter.jl/blob/c6abf9d7f00acd0293a6bad90267ea0669c01ab7/src/html/HTMLWriter.jl#L1598) function in the `HTMLWriter`.

An alternative solution would be for [`AbstractTrees.PreOrderDFS`](https://github.com/JuliaDocs/Documenter.jl/blob/c6abf9d7f00acd0293a6bad90267ea0669c01ab7/src/docchecks.jl#L172) to traverse into `DocsNode`, but that might be a lot trickier. Besides, [`DocumenterCitations` has the exact same problem](https://github.com/JuliaDocs/DocumenterCitations.jl/issues/58), and there either `linkcheck` would have to dispatch for elements of type [`BibliographyNode`](https://github.com/JuliaDocs/DocumenterCitations.jl/blob/426a649d9f7b465c8fe3f5864ea4f86a641a7737/src/bibliography_node.jl#L32) or `AbstractTrees.PreOrderDFS` would have to traverse into `BibliographyNode`.

I would maybe also refactor [`Documenter.linkcheck`](https://github.com/JuliaDocs/Documenter.jl/blob/c6abf9d7f00acd0293a6bad90267ea0669c01ab7/src/docchecks.jl#L183) a little bit. Right now it is difficult to unit-test. The call to `curl` should be probably be isolated more into a `linkcheck(url::String)` method that returns [`(status, scheme, location)`](https://github.com/JuliaDocs/Documenter.jl/blob/c6abf9d7f00acd0293a6bad90267ea0669c01ab7/src/docchecks.jl#L225C13-L225C37): I don't think that network access on Github workflow runners (or anywhere else the test suite runs) is necessarily robust. For unit-testing, you'd want to mock the call to `curl` and use a pre-defined `(status, scheme, location)` for a given `url`.

We could easily add a `cache` keyword argument to `linkcheck(doc)` and `linkcheck(node, doc; method=:HEAD)` (which should be `linkcheck(node, element, doc; method=:HEAD)`, as discussed above). This `cache` would a `Dict` mapping `url::String` => `(status, scheme, location)`. It would be internal use only (specifically for unit testing, that is). If a `url` is in the `cache` (set up in a test), we'd just use the cached values instead of calling `linkcheck(url)` that goes out to `curl` and the network.

**Comment by goerz** [comment]
https://github.com/JuliaDocs/Documenter.jl/pull/2330/commits/47c31df6dc38a72497cd4251dca141782a5f9f0c illustrates the issue

**Comment by goerz** [comment]
> The call to curl should be probably be isolated

Or maybe, instead of all the refactoring, we can just put a "fake" `curl` executable in the `PATH` during the test that just gives predefined responses without acutally going to the network

**Comment by mortenpi** [comment]
Two notes about testing and refactoring here:

1. We run the "online" tests as part of a separate workflow: https://github.com/JuliaDocs/Documenter.jl/blob/5f736ece209b7c8c001e5310392141ca49da39af/.github/workflows/CI.yml#L152-L162

   The online tests are [in this file](https://github.com/JuliaDocs/Documenter.jl/blob/master/test/online_linkcheck.jl). The idea being that normal tests shouldn't try to access the network. Also helpful for getting Documenter to work on PkgEval etc.

2. We should replace `curl` with Downloads.jl anyway (https://github.com/JuliaDocs/Documenter.jl/issues/1601). Doesn't fully resolve the testing problem. I'd be happy with some Mocking.jl-type stuff. Or I think we could also run a local web server with HTTP.jl that returns the necessary responses, for more "realistic" unit testing.

**Comment by goerz** [comment]
Ah, I missed `online_linkcheck.jl` (and, that it runs separately). I agree, I should move it over there.

Replacing `curl` with `Downloads.jl` sounds like a good plan for the longer term, and maybe disentangling the network access from the main `linkcheck` function for easier testing would be something to do as part of that. I'll hold off on any refactoring for now, though.

For what it's worth, for the [equivalent test](https://github.com/JuliaDocs/DocumenterCitations.jl/pull/62) in `DocumenterCitations` I [tried out](https://github.com/JuliaDocs/DocumenterCitations.jl/pull/62/commits/b24fd57c93bd08af9a6b8007b34e664e8fc19189) a mock [`curl`](https://github.com/JuliaDocs/DocumenterCitations.jl/blob/b24fd57c93bd08af9a6b8007b34e664e8fc19189/test/test_linkcheck/curl) executable that the test [temporarily adds to the `PATH`](https://github.com/JuliaDocs/DocumenterCitations.jl/blob/b24fd57c93bd08af9a6b8007b34e664e8fc19189/test/test_linkcheck.jl#L23) to override the system `curl`. That turns out to work pretty well.
