### ISSUE TITLE
Escape YAML headers?

### ISSUE THREAD

**Issue by tlnagy** [JuliaDocs/Documenter.jl#235]
Another thing that would be nice to have in Gadfly's documentation is the author information that is stored in the YAML front matter. Like so,

``````
    ```
    title: Test
    author: Tamas Nagy
    ...
``````

With the v0.3.0 release of `Documenter.jl`, this is not stripped out of the final product.

**Comment by MichaelHatherly** [comment]
Documenter's equivalent would be the `@meta` blocks, so any page metadata should be added to those rather having to add a YAML dependency to the package. There's currently no support for customised page templates, so custom metadata won't be of much used right now, but we'll probably support it at some point in the future. Which frontmatter other than `title` and `author` have you found you used most?

**Comment by tlnagy** [comment]
I guess `@meta` could work for us. YAML would've been nice for consistency. We mainly used it for the author information.

**Comment by odow** [comment]
I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open

Closing as stale, and because `@meta` seems to do the job.
