### ISSUE TITLE
Files not found have no warnings

### ISSUE THREAD

**Issue by untoreh** [JuliaDocs/Documenter.jl#2359]
If I have a block like
````
```@autodocs
Modules = [MyModule]
Pages = ["api1.jl", "api2.jl"]
```
````
And `api2.jl` does not exist, nothing will be rendered. There is no warning thrown when a a file in the pages list does not exist.

**Comment by fredrikekre** [comment]
You have to submit a reproducible example, this is what I get
```
ERROR: LoadError: 'api2.jl' is not an existing page!
```

**Comment by goerz** [comment]
Duplicate of #2302
