### ISSUE TITLE
Multiple references to the same footnote

### ISSUE THREAD

**Issue by baggepinnen** [JuliaDocs/Documenter.jl#2369]
I have a page where I'd like to reference a particular footnote several times, e.g.,

```
Some fact [^CSS]

Some other fact [^CSS]

[^CSS]: The footnote definition
```

This leads to a n error like
```
┌ Error: no footnotes found for 'CCS' in src/examples/zoh.md.
└ @ Documenter ~/.julia/packages/Documenter/1HwWe/src/utilities/utilities.jl:44
```

It seems somewhat related to #566 but here I only have one definition of the footnote, but several references to it.

Is there a particular reason this is not supported?

**Comment by baggepinnen** [comment]
It turns out that this does work, but it seems like the definition of the footnote has to be in the same section as the first reference to it, not at the bottom of the document like I had first tried. Subsequent references to the same footnote can appear after the definition of it

**Comment by mortenpi** [comment]
> but it seems like the definition of the footnote has to be in the same section as the first reference to it, not at the bottom of the document like I had first tried.

This doesn't seem right. If that is the case, that sounds like a bug (maybe in the parser?). Do you have an MWE? The example in the OP builds correctly for me:

![image](https://github.com/JuliaDocs/Documenter.jl/assets/147757/100483c9-1e11-442e-bdf7-118a5a23a6e3)

On the other hand, the error you posted indicates that you might have had a typo on your footnote reference?
