### ISSUE TITLE
LaTeX (stuff in $ ... $) is rendered in very large font

### ISSUE THREAD

**Issue by TorkelE** [JuliaDocs/Documenter.jl#2370]
I have a problem that when I render certain stuff in latex, e.g. by putting it with $ ... $, the font looks very large. I see this issue both on Documenter v1 and v0.27. I also see this when building docs locally.

Here is an example from Catalyst.jl (using Documenter v0.27): https://docs.sciml.ai/Catalyst/dev/inverse_problems/petab_ode_param_fitting/#Parameters
![image](https://github.com/JuliaDocs/Documenter.jl/assets/18099310/3b2def11-48bc-45bf-a4fe-f30f66c458d5)

Here is an example from JumpProcesses (Documenter 1.0): https://docs.sciml.ai/JumpProcesses/dev/tutorials/simple_poisson_process/
![image](https://github.com/JuliaDocs/Documenter.jl/assets/18099310/a4fb5925-e153-465e-9be1-45e699e95fad)

**Comment by goerz** [comment]
That's probably not going to be something that can be fixed on the Documenter side. This is some interaction between MathJaX/KaTeX and your browser/operating system/font setup.

Also, the rendering in your screenshots doesn't really stand out to me as "very large". They do seem more pixelated than what I'd like. For what it's worth, I'm seeing similar rendering in Safari, and better rendering in Chrome.

I'd maybe raise an issue at https://github.com/KaTeX/KaTeX/issues

**Comment by mortenpi** [comment]
The maths libraries do render things a bit bigger relative to the surrounding font, but that's expected. E.g. I see this [on the showcase page](https://documenter.juliadocs.org/dev/showcase/#Mathematics):

![image](https://github.com/JuliaDocs/Documenter.jl/assets/147757/5fffcbce-3607-4e13-8c99-cdb5abb8a163)
