### ISSUE TITLE
Search should not be case-sensitive

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#2373]
In Documenter's own docs, searching for `editurl` doesn't yield any results:

![image](https://github.com/JuliaDocs/Documenter.jl/assets/147757/9b0dd38a-d9ae-4655-89d6-860f3b79ff73)

But `EditURL` does:

![image](https://github.com/JuliaDocs/Documenter.jl/assets/147757/f9982fd5-edd2-4481-ae53-24bc988d5aea)

We probably want to prioritize case-matches if we can, but I think we should not exclude results just because the case does not match.

FWIW, this seems to be a regression relative to the old search:

![image](https://github.com/JuliaDocs/Documenter.jl/assets/147757/15f03065-5ab5-427b-a559-99f5327ba087)

cc @Hetarth02

**Comment by Hetarth02** [comment]
Yup, I agree this should not be the case. I will try if I can fix this quickly.
