### ISSUE TITLE
Something close to latex's `amsthm` environments ? 

### ISSUE THREAD

**Issue by lrnv** [JuliaDocs/Documenter.jl#2379]
Hey, 

While writing the documentation of Copulas.jl, I have a style that is very close to math, see e.g., there https://lrnv.github.io/Copulas.jl/stable/getting_started/. In particular, I am missing something that would parralel `amsthm`'s latex package, which provides the possibility to construct environments for `theorem`, `definition`, `property`, `remark`, etc… 

I know there is the `!!! note` syntax, but it is not really fitting the need here, so I am for the moment abusing the quote syntax as so:

```
> **Definition (Copula) :** A copula, usually denoted $C$, is the distribution function of a random vector with marginals that are all uniform on $[0,1]$, i.e.
>
> $C_i(u) = u\mathbb 1_{u \in [0,1]} \text{ for all }i \in 1,...,d.$
```

but this is not satisfactory. What would you recomand to match as closely as possible the `amsthm` style ? Maybe some type of adminition *without the ! logo* ? something else ?

**Comment by goerz** [comment]
That’s something that should be implemented as a plugin. Have a look at https://github.com/JuliaDocs/DocumenterMermaid.jl for an example of how to write a plugin for handling custom blocks.

I’ll close this here, as it’s out of scope for Documenter.
