### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by femtotrader** [JuliaDocs/Documenter.jl#2398]
Hello,

I'm building a documentation for [IncTA.jl](https://github.com/femtotrader/IncTA.jl) which is available at https://femtotrader.github.io/IncTA.jl/dev/ but I can't understand why emoji such as :1234: :candle: :m: are not correctly rendered in documentation (but are rendered correctly in Github repository README.md.
Some help to have this support in generated doc will be great.

Kind regards

**Comment by femtotrader** [comment]
I found a workaround by replacing `:1234:` by 🔢 directly in documentation source but I'd prefer to keep documentation source only with ascii characters.

**Comment by goerz** [comment]
That's not really a "workaround": Emojis are unicode letters like any other, so having them directly in the documentation is how it's supposed to work. Hypothetically, you (someone) could write a plugin that replaces codes like `:1234:` with a corresponding unicode symbol, but I don't think that sort of feature would be in the scope of Documenter itself.

**Comment by mortenpi** [comment]
> Hypothetically, you (someone) could write a plugin that replaces codes like :1234: with a corresponding unicode symbol, but I don't think that sort of feature would be in the scope of Documenter itself.

For what it's worth, this seems more like a Markdown-parser level plugin / behavior change. Unlikely it would ever be supported though, since you can just have the Unicode characters in Markdown.
