### ISSUE TITLE
Could not spawn `git rev-parse HEAD` when building document

### ISSUE THREAD

**Issue by cstook** [JuliaDocs/Documenter.jl#240]
On a Windows 10 system, using the master branch of Documenter (v0.3.0+) and julia v0.5.0-rc3 I receive the following error when I try to build the documentation.

```
Documenter: rendering document.
ERROR: LoadError: could not spawn `git rev-parse HEAD`: no such file or directory (ENOENT)
in _jl_spawn(::String, ::Array{String,1}, ::Ptr{Void}, ::Base.Process, ::Base.DevNullStream, ::Base.PipeEndpoint, ::Base.TTY) at .\process.jl:321
in #414 at .\process.jl:478 [inlined]
in setup_stdio(::Base.##414#415{Cmd,Ptr{Void},Base.Process}, ::Tuple{Base.DevNullStream,Pipe,Base.TTY}) at .\process.jl:466
in #spawn#413(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{Base.DevNullStream,Pipe,Base.TTY}, ::Bool, ::Bool) at .\process.jl:477
in (::Base.#kw##spawn)(::Array{Any,1}, ::Base.#spawn, ::Cmd, ::Tuple{Base.DevNullStream,Pipe,Base.TTY}, ::Bool, ::Bool) at .\<missing>:0
in open(::Cmd, ::String, ::Base.DevNullStream) at .\process.jl:539
in read(::Cmd, ::Base.DevNullStream) at .\process.jl:574
in readstring at .\process.jl:581 [inlined] (repeats 2 times)
in readchomp at .\io.jl:338 [inlined]
in (::Documenter.Utilities.##2#3)() at C:\Users\Chris\.julia\v0.5\Documenter\src\Utilities\Utilities.jl:366
in cd(::Documenter.Utilities.##2#3, ::String) at .\file.jl:48
in url(::String, ::String) at C:\Users\Chris\.julia\v0.5\Documenter\src\Utilities\Utilities.jl:365
in render_article(::Documenter.Writers.HTMLWriter.HTMLContext, ::Documenter.Documents.NavNode) at C:\Users\Chris\.julia\v0.5\Documenter\src\Writers\HTMLWriter.jl:320
in render_page(::Documenter.Writers.HTMLWriter.HTMLContext, ::Documenter.Documents.NavNode) at C:\Users\Chris\.julia\v0.5\Documenter\src\Writers\HTMLWriter.jl:168
in render(::Documenter.Writers.Writer{HTML::Documenter.Formats.Format = 2}, ::Documenter.Documents.Document) at C:\Users\Chris\.julia\v0.5\Documenter\src\Writers\HTMLWriter.jl:98
in dispatch(::Type{Documenter.Builder.DocumentPipeline}, ::Documenter.Documents.Document) at C:\Users\Chris\.julia\v0.5\Documenter\src\Selectors.jl:164
in cd(::Documenter.##2#3{Documenter.Documents.Document}, ::String) at .\file.jl:48
in #makedocs#1(::Bool, ::Array{Any,1}, ::Function) at C:\Users\Chris\.julia\v0.5\Documenter\src\Documenter.jl:159
in (::Documenter.#kw##makedocs)(::Array{Any,1}, ::Documenter.#makedocs) at .\<missing>:0
in include_from_node1(::String) at .\loading.jl:426
while loading C:\Users\Chris\.julia\v0.5\FastHenryHelper\docs\make.jl, in expression starting on line 7
```

```git rev-parse HEAD``` works in a terminal in the repo.

The following code was used to build the document.
```
using Documenter
using FastHenryHelper

# Build docs.
# ===========

makedocs(
    modules = FastHenryHelper,
  #  clean   = true,
    format = Documenter.Formats.HTML,
    sitename = "FastHenryHelper",
    pages = [
    "Home" => "index.md"
    ]
)
```

**Comment by MichaelHatherly** [comment]
Is this on the current `HEAD` (https://github.com/cstook/FastHenryHelper.jl/commit/894791af5f3f8c450142e154d73a1036c467a89c) of your package? Can you apply the following diff to Documenter and rerun the `make.jl` file

```diff
diff --git a/src/Utilities/Utilities.jl b/src/Utilities/Utilities.jl
index d9c6103..c2f4b5b 100644
--- a/src/Utilities/Utilities.jl
+++ b/src/Utilities/Utilities.jl
@@ -363,6 +363,7 @@ function url(repo, file)
     remote = getremote(dirname(file))
     isempty(repo) && (repo = "https://github.com/$remote/tree/{commit}{path}")
     commit, root = cd(dirname(file)) do
+        @show pwd()
         readchomp(`git rev-parse HEAD`), readchomp(`git rev-parse --show-toplevel`)
     end
     if startswith(file, root)

```

so we can see which folder things are erroring in.

**Comment by cstook** [comment]
It is not the current `HEAD`.  I just pushed the` doc` branch, which is where I am working.

After applying the diff:
`pwd() = "C:\\Users\\Chris\\.julia\\v0.5\\FastHenryHelper\\docs\\src"`

**Comment by MichaelHatherly** [comment]
Ok, checking out that branch and building `make.jl` on Linux `0.5.0-rc3+0` doesn't give me and error and it finishes fine. My guess is that it's something specific to the Windows build. In the REPL does the following work for you?

```
julia> cd(Pkg.dir("FastHenryHelper", "docs", "src")) do
           readchomp(`git rev-parse HEAD`)
       end
"df495d7cd8cae26d2e16af0fca40e879eeb77287"
```

**Comment by cstook** [comment]
_
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc3+0 (2016-08-22 23:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> cd(Pkg.dir("FastHenryHelper", "docs", "src")) do
                  readchomp(`git rev-parse HEAD`)
              end
ERROR: could not spawn `git rev-parse HEAD`: no such file or directory (ENOENT)
 in _jl_spawn(::String, ::Array{String,1}, ::Ptr{Void}, ::Base.Process, ::Base.DevNullStream, ::Base.PipeEndpoint, ::Base.TTY) at .\process.jl:321
 in #414 at .\process.jl:478 [inlined]
 in setup_stdio(::Base.##414#415{Cmd,Ptr{Void},Base.Process}, ::Tuple{Base.DevNullStream,Pipe,Base.TTY}) at .\process.jl:466
 in #spawn#413(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{Base.DevNullStream,Pipe,Base.TTY}, ::Bool, ::Bool) at .\process.jl:477
 in (::Base.#kw##spawn)(::Array{Any,1}, ::Base.#spawn, ::Cmd, ::Tuple{Base.DevNullStream,Pipe,Base.TTY}, ::Bool, ::Bool) at .\<missing>:0
 in open(::Cmd, ::String, ::Base.DevNullStream) at .\process.jl:539
 in read(::Cmd, ::Base.DevNullStream) at .\process.jl:574
 in readstring at .\process.jl:581 [inlined] (repeats 2 times)
 in readchomp at .\io.jl:338 [inlined]
 in #1 at .\REPL[1]:2 [inlined]
 in cd(::##1#2, ::String) at .\file.jl:48

julia>

**Comment by MichaelHatherly** [comment]
I suppose the `git` isn't included in the Windows binaries any more then. I seem to recall that change being done recently. You'll need to add `git` to your `PATH` for Julia to pick it up correctly then I guess. Not sure of the best way to do that on Windows though.

**Comment by cstook** [comment]
OK.  I'll add git to my path.
Thanks for the help!

**Comment by MichaelHatherly** [comment]
No prob. (Once we remove Julia `0.4` support from the package I'll switch all the `git` usages over to using `Base.LibGit2` which should avoid these kind of problems.)

**Comment by mananbordia** [comment]
<img width="873" alt="Screenshot 2021-05-14 at 5 37 38 AM" src="https://user-images.githubusercontent.com/45929094/118202062-ab6b2b00-b476-11eb-93c2-86b26b5cf8f5.png">

I am facing this issue while deploying pages on GitLab. How can I fix this ?
Link to repo - [https://gitlab.com/mananbordia/astrodynamics.jl](url)

**Comment by mortenpi** [comment]
@mananbordia It looks like you don't have the `git` command available in the GitLab CI image?

**Comment by mananbordia** [comment]
> @mananbordia It looks like you don't have the `git` command available in the GitLab CI image?

What commands do I need to add ?

**Comment by mananbordia** [comment]
> @mananbordia It looks like you don't have the `git` command available in the GitLab CI image?

Thanks a lot. I added a command to install git in my CI file and it worked.
