### ISSUE TITLE
Docs too big

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#2400]
Github tells me my documentation is too big, and can't deploy it:

https://github.com/JuliaGraphics/Luxor.jl/actions/runs/7518520144/job/20466004969#step:2:12

I'm happy to delete or move stuff, but I don't know enough about how git/github or Documenter.jl works to know exactly how to proceed... For example, deleting things doesn't always save space...

Suggestions welcome!

**Comment by fredrikekre** [comment]
You need to clean up the `gh-pages` branch then, most likely. Looking at https://github.com/JuliaGraphics/Luxor.jl/tree/gh-pages a first step would be to nuke all of the `release-*` folders. They are very old, and nobody should read them (not even sure they are accessible from Documenters version selector since Documenter now uses `v*` folders.)

If that doesn't suffice I would suggest cleaning up docs for older patch versions, e.g. remove `vX.Y.Z` if there is `vX.Y.(Z+1)` etc, and only keep the latest in each series.

**Comment by goerz** [comment]
We should add a section on how to manually squash down `gh-pages` to the [Hosting Documentation](https://documenter.juliadocs.org/stable/man/hosting/).

@cormullion In case it isn't clear: to actually recover the space on `gh-pages`, the most rigorous option is to squash the entire `gh-pages` branch down to a single commit with `git rebase -i` or something and then force-push it.

**Comment by goerz** [comment]
I took the liberty of renaming the issue to keep it open, since otherwise this isn't really actionable for Documenter.

**Comment by cormullion** [comment]
> the entire gh-pages branch down to a single commit

Cool, thanks, I’ll try it. This is outside my limited git usage, so would be helpful info for orhers too!

**Comment by fredrikekre** [comment]
I don't think the repo size is the problem here.

**Comment by goerz** [comment]
Ah, right, looks like in this case it's just about the current size of files in the `gh-pages` branch. That makes @cormullion's life easier: Just remove files that are no longer needed, commit and push the result. On the other hand, the repo size is still huge (400MB `.git` folder but only 32MB for the `master` branch), so cleaning that up is probably a good idea. Going forward, you might also want to switch to [Out-of-repo deployment](https://documenter.juliadocs.org/stable/man/hosting/#Out-of-repo-deployment) to keep the main repository lean.

**Comment by cormullion** [comment]
@goerz Thanks. It's nearly 10 years old, it's been accumulating stuff for a long time. 😀 

I'll investigate some alternatives...

**Comment by hersle** [comment]
> We should add a section on how to manually squash down gh-pages to the [Hosting Documentation](https://documenter.juliadocs.org/stable/man/hosting/).

> In case it isn't clear: to actually recover the space on gh-pages, the most rigorous option is to squash the entire gh-pages branch down to a single commit with git rebase -i or something and then force-push it.

I would really appreciate this. Could Documenter even automate it?

**Comment by asinghvi17** [comment]
There is already an option `force_push = true` or something like that in deploydocs that does this for you

**Comment by hersle** [comment]
Oh great, I completely skipped over that. Thank you.

**Comment by asinghvi17** [comment]
I guess the actionable thing here is to add this somewhere searchable / make an FAQ?

**Comment by hersle** [comment]
I think that would have helped me, at least. Judging only by its name, I was not expecting the force push keyword argument to do what I wanted, so I think it is not that easy to discover.

I would expect to find all answers on how to prevent `gh-pages` from becoming extremely large under [`gh-pages` branch](https://documenter.juliadocs.org/stable/man/hosting/#gh-pages-Branch). Maybe it could list all actions one could take to mitigate it (if only just links to other places in the documentation)? Such as

- `push_preview` cleanup workflow
- `forcepush` keyword argument
- External documentation repository / site
- ...
