### ISSUE TITLE
Documentation for "Generator Expressions" is 8th result when searching julia docs for "Generator"

### ISSUE THREAD

**Issue by non-Jedi** [JuliaDocs/Documenter.jl#2405]
Here's a screenshot of what the search results look like for "Generator" today:

![docs julialang org generator search results](https://github.com/JuliaDocs/Documenter.jl/assets/17915621/e7d16e28-fc58-4e94-adc1-ff43167ca2a8)

[Results that have the word in their heading](https://docs.julialang.org/en/v1/manual/arrays/#Generator-Expressions) be given higher priority in the list than results that only have the word in their body text (or where it doesn't appear at all)? For the first few results that appear above the obvious correct result:

- [The word "generator" does not appear anywhere in the section text. The word "generate" appears twice.](https://docs.julialang.org/en/v1/manual/faq/#General)
- [No "generator" or any version of the word "generate". I assume this is matching on "general" for some reason?](https://docs.julialang.org/en/v1/manual/faq/#General)
- [It makes sense for the section on code generation to appear on this list but not above results that include the word "generator" in their heading](https://docs.julialang.org/en/v1/manual/metaprogramming/#Code-Generation)

Overall the problem seems to be that the search engine likes the word "general" as a match for "generator" too much and doesn't weight exact matches in the section title highly enough.

For background, [this issue used to be much worse, with the correct result not appearing at all in search results](https://discourse.julialang.org/t/what-is-a-base-generator/32316/5). A [comment of mine in that same thread has had 908 people click through a link](https://discourse.julialang.org/t/what-is-a-base-generator/32316/4) to find the documentation section for generators; to this day that thread is the first result in a Google search for "Julia Generators", and the Julia docs don't appear on the first page of search results at all:

![google julia generator search results](https://github.com/JuliaDocs/Documenter.jl/assets/17915621/ee4f32ca-d9db-4f36-930e-1b43b00c4ace)

I think this is evidence that poor search results for this specific term are causing a real issue for Julia users.

**Comment by LilithHafner** [comment]
This is fixed in documenter 1.0 which we use to build Julia 1.11, thanks to @Hetarth02's replacing the search backend with a better one in #2172

![Screenshot from 2024-01-19 16-00-31](https://github.com/JuliaDocs/Documenter.jl/assets/60898866/688ebe97-e8db-4c87-a69c-e65be4c76d92)
![Screenshot from 2024-01-19 16-00-41](https://github.com/JuliaDocs/Documenter.jl/assets/60898866/5fc8a1fe-096b-4a02-94da-3b0ef294989a)

**Comment by non-Jedi** [comment]
Good to hear. Didn't realize 1.10 wasn't using the latest Documenter. Thanks @Hetarth02!
