### ISSUE TITLE
Search filter toggle buttons have broken UI [regression]

### ISSUE THREAD

**Issue by LilithHafner** [JuliaDocs/Documenter.jl#2406]
The "Filters" toggle buttons' state is no longer visible in the UI.

![Screenshot from 2024-01-19 10-22-41](https://github.com/JuliaDocs/Documenter.jl/assets/60898866/956799ca-ca02-4932-b86b-38619864b3f3)

After clicking some of the buttons a bunch I got this search result, with no indication of how I can get back to a normal result.

New UI introduced in #2202 cc @Hetarth02. The UI looks fine in the PR demo, but now it seems broken on docs.julialang.org on both IceCat and Chromium.

**Comment by Hetarth02** [comment]
Does julialang's docs introduce some custom css?

I think it may be due to that. Also, can you confirm if this also happens in the light mode as well or not?

**Comment by LilithHafner** [comment]
> can you confirm if this also happens in the light mode as well or not?

Can confirm it works for me in light mode.

**Comment by Hetarth02** [comment]
Did a PR which fixes this in dark mode as well.
