### ISSUE TITLE
Recommend installation in `docs` Project.toml?

### ISSUE THREAD

**Issue by nilshg** [JuliaDocs/Documenter.jl#2425]
First time user so maybe this has been discussed before: I've been advised on Slack that the right way to use Documenter in my package is to do:

```
using MyPkg
] activate docs
] add Documenter
```

which creates a `Project.toml` file under `/docs`. Currently the [Package Guide](https://documenter.juliadocs.org/stable/man/guide/#Installation) just says to do `]add Documenter`, would it be worth changing this to reflect the `docs` Project workflow?

**Comment by mortenpi** [comment]
Related to #2321. In general, yes, I think we expect the users to add Documenter to their local environment, likely under the `docs/` directory in their package. So adding at least a small note about that would probably be good, although I feel that a good solution is to re-think the whole getting started guide.

**Comment by nilshg** [comment]
Thanks - I guess it then comes down to the question of how likely is it that this rewrite happens reasonably soon? Mentioning `docs/` could be a 15 minute PR which might help people immediately with quite a fundamental first step, but I also get the point about not wanting to tinker with things now if everything gets rewritten soon.

**Comment by mortenpi** [comment]
There's nothing in progress right now, so adding a note right now would be good I think -- it would also act as reminder to emphasize this during the rewrite.

**Comment by nilshg** [comment]
Ok. here's a first attempt:

https://github.com/JuliaDocs/Documenter.jl/pull/2429
