### ISSUE TITLE
ERROR: LoadError: The repo path… should not contain the protocol

### ISSUE THREAD

**Issue by mpeters2** [JuliaDocs/Documenter.jl#2427]
In make.jl, if 

```
deploydocs(
    repo    = "https://github.com/SomePerson/Something.jl.git"
    target  = "build"
)
```

contains `https://`, it will give the error:

```ERROR: LoadError: The repo path https://github.com/SomePerson/Something.jl.git should not contain the protocol```

If Documenter.jl can detect `https://`, then it should be robust enough to snip it out of the path go on its merry way.  If that's too hard, a more helpful error message would have been  `...should not contain the protocol 'https://'`, as  "the protocol" is a bit cryptic and non-specific.

**Comment by mortenpi** [comment]
The string version of the `repo` argument is somewhat deprecated, and one should use a [`Remotes` object](https://documenter.juliadocs.org/stable/lib/remote-links/#Documenter.Remotes.GitHub) instead, so I'm not sure we want to change the behavior. However, if anyone wants to improve the error message, then that's up for grabs.
