### ISSUE TITLE
New search window does not appear [intermittent] [bug] [regression]

### ISSUE THREAD

**Issue by LilithHafner** [JuliaDocs/Documenter.jl#2430]
Steps to reproduce

1) Open a new private browsing session
2) Open https://clemens-cords.com/mousetrap/
3) Click "search docs"
4) Type "add_render_task!"
5) Hover mouse over the label "Section" to the right of the first result
6) Click
7) Wait for the page to fully load
8) Click "search docs"
9) Observe that the search pane does not appear.
10) Refresh the page
11) Repeat steps 9 & 10

I've reproduced this repeatedly on IceCat, FireFox, and Chromium browsers, but with only about a 50% success rate. This is an obnoxious kind of bug: very bad for UX and hard to reproduce.

**Comment by mortenpi** [comment]
Ironically, I couldn't repro it with these instructions, but I have definitely run into the case where the search window doesn't open for some reason. cc @Hetarth02

**Comment by thofma** [comment]
Some people (including me) stumbled over this, even after closing and reopening the window.

**Comment by joschmitt** [comment]
I really don't know this stuff, but I could reproduce the problem in locally build docs and got the following error message in the "developer tools" of firefox:
```
Uncaught TypeError: document.querySelector(...) is null
    <anonymous> http://localhost:8000/assets/documenter.js:683
    execCb https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    check https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    enable https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    bind https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    emit https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    each https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    emit https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    check https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    enable https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    init https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    a https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    completeLoad https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
    onScriptLoad https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1
```

**Comment by mortenpi** [comment]
@Hetarth02 Like in the collapse PR, I suspect we need `$(document).ready(function () { ... })` around most of the search stuff?

https://github.com/JuliaDocs/Documenter.jl/blob/deecbd7d3abc395fe31d7a393539bcda4c00d753/assets/html/js/shortcut.js#L49-L59
