### ISSUE TITLE
Hide whole code block for being displayed?

### ISSUE THREAD

**Issue by tlnagy** [JuliaDocs/Documenter.jl#244]
I'm doing a lot of the following in Gadfly's docs:

    ```@example 1
    using Gadfly # hide
    using RDatasets # hide
    srand(1234) # hide
    ```

    ```@example 1
    df = dataset("ggplot2", "diamonds") # hide
    p = plot(df, # hide
             x = :Price, color = :Cut, # hide
	    	 Stat.histogram, # hide
		     Geom.bar) # hide
    p_rendered = deepcopy(p) # hide
    ```

Is it possible to hide the whole code block instead of having to add `#hide` everywhere?

**Comment by tlnagy** [comment]
(I'm having trouble escaping the fenced code blocks with four backticks, doesn't seem to work properly).

**Comment by MichaelHatherly** [comment]
GitHub doesn't support nested fenced code blocks as far as I know. You just have to indent the block instead.

Perhaps we could have

    ```@example 1 # hide
    using Gadfly
    using RDatasets
    srand(1234)
    ```

do this kind of thing.

**Comment by tlnagy** [comment]
That would be great. The previous documentation engine for Gadfly, Judo, had this feature and it was quite nice.

**Comment by MichaelHatherly** [comment]
Or potentially a `@setup` block might be a little less hacky (the `# hide` is a little ugly I think):

    ```@setup 1
    using Gadfly
    using RDatasets
    srand(1234)
    ```

**Comment by tlnagy** [comment]
That is much nicer. The #hide seems hackish.
