### ISSUE TITLE
Typing `th` into the Documenter.jl search bar throws a javascript error

### ISSUE THREAD

**Issue by LilithHafner** [JuliaDocs/Documenter.jl#2441]
I observe this error being thrown on https://documenter.juliadocs.org/dev/ but not https://documenter.juliadocs.org/stable/. I'm guessing it is due to buggy escaping of search query results. 
![Screenshot from 2024-02-03 12-09-59](https://github.com/JuliaDocs/Documenter.jl/assets/60898866/80fc4498-472b-4d62-936d-dfdc1f6d922f)

**Comment by mortenpi** [comment]
#2461
