### ISSUE TITLE
Code examples in `!!! note`

### ISSUE THREAD

**Issue by vchuravy** [JuliaDocs/Documenter.jl#247]
I was wondering about the right way to put code-examples in a `!!! note` block.

As an example see http://dmlc.ml/MXNet.jl/latest/api/io/ and https://github.com/dmlc/MXNet.jl/blame/abc8ffa838d4073fc465add7f62a131453a20b19/docs/src/api/io.md#L82

**Comment by MichaelHatherly** [comment]
Looks like it might be a problem with the python markdown parser: it doesn't seem to be able to handle fenced code blocks nested within admonitions.

**Comment by fredrikekre** [comment]
Works now.
