### ISSUE TITLE
Improve the link vs collapse UX in docstring headers

### ISSUE THREAD

**Issue by gdalle** [JuliaDocs/Documenter.jl#2476]
Is there a way to avoid that? Or is it something we want, and if so why?

**Comment by gdalle** [comment]
Found the trick: you gotta click on the frame but outside of the name itself (which is a link)

**Comment by fredrikekre** [comment]
Perhaps it shouldn't behave like a link when the docstring is folded.

**Comment by mortenpi** [comment]
Let me reopen this -- I thought we had an issue for this, but I can't find one. We would definitely want to improve how the link vs collapsing of the docstring works. The fact that clicking on the text part does both is not ideal.

**Comment by fredrikekre** [comment]
Basically a duplicate of #2204

**Comment by mortenpi** [comment]
It is. That was the issue I wasn't able to find before.
