### ISSUE TITLE
More detailed warnings

### ISSUE THREAD

**Issue by vchuravy** [JuliaDocs/Documenter.jl#248]
Documenter outputs helpful warnings about duplicated docstrings or missing references, but it only provides information about the `md` file where the docstring are included. It would be helpful if documenter would provide an option to be a bit more verbose. Particularly I am interested in the line-number and file of the duplicated doc defintions and where the reference is coming from. (the latter one is easily searchable though)

```
Documenter: expanding markdown templates.
 !! Duplicate docs found for 'MXNet.mx.AbstractDataProvider'. [src/api/io.md]
 !! Duplicate docs found for 'MXNet.mx.AbstractDataProviderState'. [src/api/io.md]
 !! Duplicate docs found for 'MXNet.mx.count_samples'. [src/api/io.md]
 !! Duplicate docs found for 'MXNet.mx.get_batch_size'. [src/api/io.md]
 !! Duplicate docs found for 'MXNet.mx.get_data'. [src/api/io.md]
 !! Duplicate docs found for 'MXNet.mx.get_label'. [src/api/io.md]
 !! Duplicate docs found for 'MXNet.mx.provide_data'. [src/api/io.md]
 !! Duplicate docs found for 'MXNet.mx.provide_label'. [src/api/io.md]
Documenter: building cross-references.
 !! No doc found for reference '[`load_checkpoint`](@ref)'. [src/api/model.md]
 !! No doc found for reference '[`load_checkpoint`](@ref)'. [src/api/model.md]
 !! No doc found for reference '[`every_n_iter`](@ref)'. [src/api/callback.md]
```

**Comment by MichaelHatherly** [comment]
Kind of a dup of #78, since more info in all warnings/errors would be good. As mentioned in that issue, the markdown parser doesn't track linenumbers, so we can't yet provide that information.

**Comment by fredrikekre** [comment]
> As mentioned in that issue, the markdown parser doesn't track linenumbers, so we can't yet provide that information.

Well, we can go look in the source as in #929.
