### ISSUE TITLE
Improve search functionality of DocsNode

### ISSUE THREAD

**Issue by randy3k** [JuliaDocs/Documenter.jl#25]
1. It seems that mkdocs search function only searches over headings. A DocsNode is now rendered as normal text only, which makes the search not able to pick up the DocsNode. Perhaps we should render the `doc.object.binding` as `###  {doc.object.binding}` ?
2. Additionally, the search function of mkdocs does not separate words connected with dot. For example, search is not able to pick up `Lapidary.Path` if we are looking for `Path`.

By editing the render function for DocsNode like this

``` julia
function render(io, mime, doc::DocsNode, env)
    print(io, "\n")
    print(io, "### ", doc.object.binding.var)
    println(io, " (", doc.object.binding.mod, ", *", doccat(doc.object), "*).\n")
    writemime(io, mime, doc.docs)
    println(io, "\n")
end
```

I am able to get better search results. Not sure if it is reasonable.

**Comment by MichaelHatherly** [comment]
If we can avoid working around MkDocs I'd prefer that, seems as though search should be able to handle `.`s. Perhaps a bug upstream?

Do level 3 headers show up in the sidebar nav? I'm not sure if we'd want them to; especially if there's a decent number of them on a single page.

**Comment by randy3k** [comment]
I have submitted an [issue](https://github.com/mkdocs/mkdocs/issues/867) on mkdocs for the `.` search issue, let's see if they could fix it.

The default theme sidebar does not show level 3 headers, I am not sure for other themes.

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing as stale. We don't use `mkdocssearch` anymore, and search is able to look through the text of docstrings, etc.
