### ISSUE TITLE
docstrings in extensions

### ISSUE THREAD

**Issue by palday** [JuliaDocs/Documenter.jl#2527]
Right now, docstrings for extensions are a bit cumbersome. 

For example, consider a package with a stub

```julia
function f end
```

and the stub is filled out in extensions, e.g.

```julia
"""
   f(x::MyExtType)

Do cool things
"""
MyModule.f(x::MyExtType) = "cool things"
```

To get things working with `@autodocs`, you have to do this in your `make.jl`:

```julia
ext = Base.get_extension(MyModule, :MyModuleMyExt),
makedocs(; modules=[MyModule, ext])
```

and then in the docs themselves:

~~~markdown

```@autodocs
ext = Base.get_extension(MyModule, :MyModuleMyExt),
Modules = [MyModule, ext]
```

~~~~

This is necessary because extensions are "hidden" modules in some sense.

**Comment by mortenpi** [comment]
This could use some work, yes. Some docs in the manual would probably be good as a start.

I'll close this issue as a dup of #2124 though.
