### ISSUE TITLE
 Generated files with Documenter.jl and julia-docdeploy have random characters included in their name, not rendering correctly

### ISSUE THREAD

**Issue by brian-dellabetta** [JuliaDocs/Documenter.jl#2536]
I'm not sure if this is an issue for [Documenter.jl](https://github.com/JuliaDocs/Documenter.jl), [DocumenterVitepress.jl](https://github.com/LuxDL/DocumenterVitepress.jl) or julia-docdeploy, but things run fine locally with npm, using the steps outlined [here](https://docs.juliahub.com/General/DocumenterVitepress/stable/getting_started/).

I have a publicly accessible repo using Documenter.jl (see make.jl [here](https://github.com/brian-dellabetta/Fusion.jl/blob/main/docs/make.jl)) and the julia-docdeploy github action [here](https://github.com/brian-dellabetta/Fusion.jl/blob/main/.github/workflows/Documenter.yml#L43-L52). The github actions are successful and the gh-pages branch is updated, but random string segments get injected into the static files generated by Documenter. For example, I create a lorenz.mp4 asset inside my Documenter example [here](https://github.com/brian-dellabetta/Fusion.jl/blob/main/docs/src/index.md#fusion), but the gh-pages branch has a file [lorenz.C1w-s6U0.mp4](https://github.com/brian-dellabetta/Fusion.jl/blob/gh-pages/dev/assets/lorenz.C1w-S6U0.mp4). A similar thing happens with style.css.

Because of this my page loads (https://brian-dellabetta.github.io/Fusion.jl/dev/) but the static elements can't be found (no video, no fonts, no styling). Any idea what I'm doing wrong here? I might just have some configuration incorrect. I won't update any of those links I posted above until this is resolved.

**Comment by brian-dellabetta** [comment]
https://github.com/julia-actions/julia-docdeploy/issues/37

**Comment by mortenpi** [comment]
This seems like a DocumenterVitepress issue. I strongly suspect this is just how Vitepress works -- that looks like the somewhat standard way of handling caching issues, by randomizing the filenames of assets. Not sure why the site would break though. cc @asinghvi17 

I'll close this, since I don't think this is actionable here.

**Comment by asinghvi17** [comment]
Yes, this looks like a DocumenterVitepress issue to me.  Try using `lorenz.mp4` instead of `./lorenz.mp4` and see if that helps?  Vitepress uses Rollup which is pretty specific on file paths and what it considers valid.

Otherwise, you can try to include the video element via Markdown...

**Comment by brian-dellabetta** [comment]
Thanks @mortenpi and @asinghvi17 for the quick response. It ended up being a configuration issue in DocumenterVitepress as you suggested. 

In case others have this issue, dropping `deploy_url` from `DocumenterVitepress.MarkdownVitepress(...` resolved it. Thanks @asinghvi17 for [the PR](https://github.com/brian-dellabetta/Fusion.jl/pull/4)
