### ISSUE TITLE
Feature request: Cross module links

### ISSUE THREAD

**Issue by orenbenkiki** [JuliaDocs/Documenter.jl#2537]
Currently, links like this: ```[`name`](@ref)``` are restricted to entities that are accessible to the code of the module containing the documentation.

However, when documenting a package, it is often very useful to link to entities in modules that depend on the current module (for example, linking to important concrete types implementing an abstract type, to higher-level functions that make use of a lower level function). It is not possible to make such entities accessible to the documented module as this would cause a cyclical dependency. I'm not aware of any workaround (is there one?)

This feature is available in most other documentation generators such as Doxygen and Sphinx. It can be implemented as a final pass for fixing cross-module links.

**Comment by goerz** [comment]
Umm… you already made this feature request at https://github.com/JuliaDocs/Documenter.jl/issues/2493, and the feature was implemented then!

**Comment by orenbenkiki** [comment]
Oops, my bad - I was going through old issues list. Sorry!
