### ISSUE TITLE
compact index

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaDocs/Documenter.jl#254]
Sometimes an Index can be quite lengthy (see http://juliagraphs.github.io/LightGraphs.jl/latest/basicmeasures/). Could it be more convenient to have the names displayed in a (horizzontal) string and without the module prefix (#253)? 

```
Index
foo1, foo2, foo3, ...
```

**Comment by MichaelHatherly** [comment]
If an index is quite lengthy then I'd assume it would be more readable as a formatted list rather than a compacted comma-separated paragraph.

Note that you can already split lengthy `@index` blocks (https://juliadocs.github.io/Documenter.jl/latest/man/syntax.html#@index-block-1) with the `Pages`, `Modules`, and `Order` keywords. Perhaps that would be useful for that page?

**Comment by CarloLucibello** [comment]
yeah, I find myself a little torn on this: a formatted list is better suited for accurate scrutiny, while a compact paragraph is more suited for a quick glance, it conveys faster the big picture. I would give the opportunity for Documenter's user to choose among the two, if it is easy to implement and if there some precedent to it (I don't know of any). 
In any case, for repeated use the list is more readable, and Pages, Modules, and Order can be used to split itas you suggested, so feel free to close this.

**Comment by MichaelHatherly** [comment]
Yeah, I don't think this is a particularly high priority, but if anyone wants/needs this they're welcome to take a crack at it and we can see how it looks.

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing as stale. This doesn't seem like a high priority, and no one else has complained about it. I'd suggest that there are usually better ways of communicating the documentation to users that a paragraph with a list of names. (Even the index as a list isn't great.)
