### ISSUE TITLE
Gadfly docs not deploying to gh-pages, no errors

### ISSUE THREAD

**Issue by tlnagy** [JuliaDocs/Documenter.jl#255]
@MichaelHatherly Do you know why the Gadfly docs aren't deploying properly? Here's the travis log: https://travis-ci.org/dcjones/Gadfly.jl/jobs/158572226

**Comment by MichaelHatherly** [comment]
Probably just needs a `target = "build"` keyword in the `deploydocs` call. If not then I'll take a closer look on the weekend.

**Comment by tlnagy** [comment]
That fixed it. Thanks
