### ISSUE TITLE
Blank title if anything before first header

### ISSUE THREAD

**Issue by tlnagy** [JuliaDocs/Documenter.jl#256]
<img width="565" alt="screen shot 2016-09-08 at 15 27 28" src="https://cloud.githubusercontent.com/assets/1661487/18369154/cdffa6be-75d8-11e6-9cb8-56093181d2cf.png">

See https://dcjones.github.io/Gadfly.jl/latest/man/geometries.html for example. All the pages that appear like that in the index are like this:

    ```@meta
    Author = "Daniel C. Jones"
    ```

    # Geom.bar
 
    Draw bar plots.
    ...

where there is a `@meta` block prior to the only top-level header. A probably related bug is that the header is shown again in the index if it is a named page:

<img width="344" alt="screen shot 2016-09-08 at 15 32 17" src="https://cloud.githubusercontent.com/assets/1661487/18369266/94e3eeb6-75d9-11e6-8953-1ed7df76951f.png">

**Comment by mortenpi** [comment]
This was (intentionally) introduced by #239. Idea was that we'll use the `<h1>` to determine nav. header only if the `<h1>` is the very first block. This was to be consistent with the sidebar outline.

A workaround would be to have the `@meta` block after the header.

By "names pages" you mean when you define the name in the `pages` option in `make.jl`, right? FWIW, the header should be shown in the pages with "-" as well.

However, I do think that we should consider this as a bug. Minimally we should ignore the `@meta` blocks when figuring out the outline, to be consistent with the YAML headers.

**Comment by tlnagy** [comment]
Yeah, named pages are ones that I give an explicit name to in `make.jl`. The duplicate entry in the index wasn't displayed when I didn't have the meta block at the beginning. That is, "Geometries" only had "Available Geometries" as a leaf. I'm using the `@meta` block as mentioned here https://github.com/JuliaDocs/Documenter.jl/issues/235 at the very top of files as a temporary solution until that is added to Documenter.

**Comment by MichaelHatherly** [comment]
> Minimally we should ignore the `@meta` blocks when figuring out the outline

I'd prefer not to special case a single node type. Probably best to just look for the first `<h1>` header on a page and use that no matter whether it's the first, last, or any node in between.

**Comment by tlnagy** [comment]
> I'd prefer not to special case a single node type. Probably best to just look for the first <h1> header on a page and use that no matter whether it's the first, last, or any node in between.

I think this is reasonable. I doubt that someone would use a `<h1>` and expect something else to happen.

**Comment by mortenpi** [comment]
#269 looks good, but a few things for potential future PRs:

The [`collect_subsections`](https://github.com/JuliaDocs/Documenter.jl/blob/master/src/Writers/HTMLWriter.jl#L600) function in `HTMLWriter` should be updated as well -- currently the navigation menu for the HTML is inconsistent with this change (non-first page title `h1`s should show up in the navigation menu).

Also, what about the case when the user has a `h2` (or generally any `hN`) before the first `h1`? I suppose that would be a weird case, and most likely an error on the user's part, so should we be more strict about the outline, instead of trying to accommodate this? But there should probably be a warning that "your outline is weird, some stuff might not work".

**Comment by MichaelHatherly** [comment]
Ah, yeah, good catch @mortenpi. @tlnagy would you like to also update that one?

> Also, what about the case when the user has a h2 (or generally any hN) before the first h1? I suppose that would be a weird case, and most likely an error on the user's part, so should we be more strict about the outline, instead of trying to accommodate this? But there should probably be a warning that "your outline is weird, some stuff might not work".

I'd just say we should ignore any non-`h1`s. We could add a note in the guide mentioning it, but seems like it will probably not be too common to need an explicit warning.

**Comment by MichaelHatherly** [comment]
> @tlnagy would you like to also update that one?

FYI, I'm busy sorting out `collect_subsections` now since I had a little bit of spare time.

**Comment by tlnagy** [comment]
Thanks @MichaelHatherly!
