### ISSUE TITLE
Bypass "originates from the same repository" deploy requirement

### ISSUE THREAD

**Issue by milankl** [JuliaDocs/Documenter.jl#2586]
I would like to allow pull requests from forks to deploy a preview of the documentation. At the moment the requirements for deploying
```
┌ Info: Deployment criteria for deploying preview build from GitHub Actions:
│ - ✔ ENV["GITHUB_REPOSITORY"]="SpeedyWeather/RainMaker.jl" occurs in repo="github.com/SpeedyWeather/RainMaker.jl"
│ - ✔ ENV["GITHUB_REF"] corresponds to a PR number
│ - ✘ PR originates from the same repository
│ - ✔ `push_preview` keyword argument to deploydocs is `true`
│ - ✔ ENV["GITHUB_ACTOR"] exists and is non-empty
│ - ✔ ENV["GITHUB_TOKEN"] exists and is non-empty
└ Deploying: ✘
```

would not allow this though. I don't understand whether this is a general github policy (but I do already have to approve for workflows to run) or whether this is something one could change within Documenter.jl, e.g. as an argument to the `deploydocs` function?

Possibly related: #2278

**Comment by milankl** [comment]
Thanks Fredrik, yes I guess that makes sense but when the documentation is build anyway within the workflow what prevents it from being hosted? I guess I need to give out repo permissions then so that contributors can create their own branches within the repo to bypass this?!

**Comment by fredrikekre** [comment]
>  guess that makes sense but when the documentation is build anyway within the workflow what prevents it from being hosted?

Building it is fine, but we need to publish the build result which requires write access to repository. You would probably agree that it would be a bad idea to give write access to everyone in the world :)

> I guess I need to give out repo permissions then so that contributors can create their own branches within the repo to bypass this?!

Yea if you have collaborators you trust you can add them to the repo so they can make pull requests from branches in the same repository.

**Comment by milankl** [comment]
Thanks for the clarification!
