### ISSUE TITLE
Improve travis experience

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#260]
The `travis` command can be a bit fragile at times. We should probably have a "common issues" section in the manual, and perhaps make Documenter work around some of the potential issues.

Some issues came up in #257 and also on [Gitter](https://gitter.im/juliadocs/users?at=57d64bd3a0e8dbb04f2de9fc):

> One thing, I had problem running the travis genkey thing because I had renamed my repo and it tried to use the old name somehow. I had to manually call `travis encrypt` with the `-r KristofferC/OhMyREPL.jl` to specify the repo to use.

Additional comments on the travis-related user experience are also welcome here.

cc @KristofferC, @tlycken: I opened an issue for this so that we wouldn't completely forget about this.

**Comment by MichaelHatherly** [comment]
If these can be addressed with fixes (more understandable error messages) to the `travis` command itself that would be better, but adding some FAQ-type docs that covers this kind of stuff would be fine though as well.

**Comment by tlycken** [comment]
It seems that the biggest problem here is the git setting `travis.repo`, which seems to be set by `Pkg.generate()` but is then quite difficult to find. Just documenting and/or warning about that in the error message would probably go a long way.

**Comment by KristofferC** [comment]
Or just add the -r USER/REPONAME flag if you want to force it to use the name of the repo. Maybe that is bad in other cases.

**Comment by MichaelHatherly** [comment]
Sufficiently covered by https://github.com/JuliaDocs/Documenter.jl/pull/336, since that completely removes the dependency on `travis`.
