### ISSUE TITLE
Is it possible to execute @example bocks of different MD files in different processes?  

### ISSUE THREAD

**Issue by peremato** [JuliaDocs/Documenter.jl#2611]
I am documenting a package using a set of Markdown  files (examples) that include @example blocks. This package interfaces with a C++ library, which is highly sensitive to proper cleanup and re-initialization due to extensive use of global variables on the C++ side.

Is it possible for the @example blocks in each .md file to be executed in separate Julia processes? While I understand they run in isolated namespaces, this isolation is not sufficient for my use case.

Thank you for your help!

**Comment by goerz** [comment]
No, this is not currently possible.

You might want to look at [Literate.jl](https://github.com/fredrikekre/Literate.jl), which would allow you to run a document in a standalone process, and save the result as an `.md` file with both the inputs and output, suitable for inclusion in Documenter.

**Comment by fredrikekre** [comment]
Why can't you clean up at the end of the file?

**Comment by fredrikekre** [comment]
So it is a limitation of th C++ code that you can't cleanup and restart in the same process? Then I think your current best bet is to use Literate for execution.

**Comment by peremato** [comment]
Thanks. Yes, it is a limitation in the C++ side. I was hoping to have a solution in Julia to overcome the limitation. I can come the issue.

**Comment by fredrikekre** [comment]
Ok, so then something like https://github.com/JuliaDocs/Documenter.jl/pull/2577 wouldn't really help you either.
