### ISSUE TITLE
"Latest" badge does not display

### ISSUE THREAD

**Issue by timholy** [JuliaDocs/Documenter.jl#262]
You can see this on the Documenter homepage itself: there's a badge for "stable" but not for "latest." However, if you click on the stable badge, edit the URL to "latest," you can see that the site works just fine. Also noticed in https://github.com/JuliaImages/ImageCore.jl, which does not yet have a stable build because it has not yet been registered/tagged.

Any ideas about the origin of this?

**Comment by MichaelHatherly** [comment]
Not sure what it could be. I've seen it before a couple weeks ago, but at the moment for me it's still there:

![2016-09-12-203821_4966x1080_scrot](https://cloud.githubusercontent.com/assets/6144086/18447930/fd1737ca-7928-11e6-81e4-f1a7efe40404.png)

Perhaps connection issues with shields.io, or something like that. Possible solution would be to save the image files directly to the repo.

**Comment by timholy** [comment]
Very curious. I get this with Firefox:
![spectacle g12714](https://cloud.githubusercontent.com/assets/1525481/18448333/584b335a-78f0-11e6-8d72-d1b16910d0d0.png)
and this with chromium:
![spectacle g12714](https://cloud.githubusercontent.com/assets/1525481/18448360/73bf91e4-78f0-11e6-9be7-a80f1a448d8a.png)

Clicking on that "broken" icon in chromium indeed takes me to the correct site.

**Comment by MichaelHatherly** [comment]
How's their main site look: https://shields.io/? Any particular pattern to the broken badges?

**Comment by timholy** [comment]
Some of them are gray, but none seem missing.

**Comment by timholy** [comment]
Weird, now everything is working.
