### ISSUE TITLE
Add a root HTML page?

### ISSUE THREAD

**Issue by tlnagy** [JuliaDocs/Documenter.jl#264]
Currently, there is a separation between `stable` and `latest` docs and these are both located in subfolders. This means that going to the root directory gives a 404 error, e.g. https://juliadocs.github.io/Documenter.jl/ or http://gadfly.org. I think it would be nice to have the root directory behave more like official julia docs where it would point to latest stable version and then have have a subfolder for each release and the latest version and be able to switch between them easily.

**Comment by MichaelHatherly** [comment]
Yes, I've also been thinking we should add some kind of project landing page to the root.

**Comment by tlnagy** [comment]
Thanks. Currently we just have a page that redirects to the stable docs.

**Comment by odow** [comment]
Fixed by https://github.com/JuliaDocs/Documenter.jl/pull/1657? Things now redirect to `stable` automatically. I guess you could edit the `index.html` in `gh-pages` manually if you wanted a different landing page for the project.
