### ISSUE TITLE
Feature request: Add convenient syntax  for inserting raw HTML.

### ISSUE THREAD

**Issue by KristofferC** [JuliaDocs/Documenter.jl#272]
Making an issue out of a discussion on Gitter.

It is sometimes desirable to insert raw html into the generated docs. For example I wanted to insert

```
<script type="text/javascript" src="https://asciinema.org/a/14.js" id="asciicast-14" async></script>
```

to show a "widget" in my docs.

@MichaelHatherly suggested:

```
```@eval
Main.Documenter.Documents.RawHTML(
    """
    <script type="text/javascript" src="https://asciinema.org/a/14.js" id="asciicast-14" async>
    </script>
    """
)```
```

which works nice but perhaps a `@html` macro is warranted?

**Comment by hayd** [comment]
👍  to `@html`. One question is: what should happen to this block if generating to something that's not html e.g. what about when generating markdown or latex? Should the block just be ignored?

**Comment by MichaelHatherly** [comment]
Probably just discard the block in those cases. Maybe with a warning.

**Comment by MichaelHatherly** [comment]
#292 implements a slightly more general version of this idea, `@raw <format>`, since this is needed for #288.

**Comment by KristofferC** [comment]
Thanks.
