### ISSUE TITLE
markdown writer doesn't seem to be doing display math correctly (v0.4)

### ISSUE THREAD

**Issue by mweastwood** [JuliaDocs/Documenter.jl#273]
The manual (https://juliadocs.github.io/Documenter.jl/stable/man/latex.html#Display-equations-1) says that I should be able to get display math by wrapping my equations in `$ ... $` and putting a new line before and after the equation. For example:

```
lots of descriptive text, for example the following equation

$1 + 1 = 2$

more text
```

After running `makedocs` I get the following output.

```
lots of descriptive text, for example the following equation

$1 + 1 = 2$

more text
```

Instead I am expecting something like

```
lots of descriptive text, for example the following equation

\[1 + 1 = 2\]

more text
```

It seems like the HTMLWriter correctly replaces the `$ ... $` with `\[ ... \]`, but the MarkdownWriter does not. (At least this is my best guess as to why this seems to be working for the example in the Documenter docs and not my own docs).

I am on Julia v0.4.6 and Documenter v0.4.2.

**Comment by MichaelHatherly** [comment]
This is a bug with `Markdown.plain` in Julia 0.4 that doesn't treat display math differently from inline math. One 0.5+ you should get

```
lots of descriptive text, for example the following equation

$$
1 + 1 = 2
$$

more text
```

as the output, which should display properly.

There's not much that can be done to resolve this other than generating the docs using 0.5+.

**Comment by mweastwood** [comment]
Thanks for the insight. 0.5 isn't so far away so I'll just sit tight. (I'll also let you decide whether or not you want to close this issue)

**Comment by MichaelHatherly** [comment]
Since it's just been tagged https://github.com/JuliaLang/julia/commit/3c9d75391c72d7c32eea75ff187ce77b2d5effc8 you don't have to wait too long! 🎉
