### ISSUE TITLE
inline code rendering as code blocks (instead of inline)

### ISSUE THREAD

**Issue by stephenbnicar** [JuliaDocs/Documenter.jl#275]
Using Documenter.jl with native HTML rendering.  Docs are being built on the "release" version of Julia.  The "[stable](https://stephenbnicar.github.io/BeaData.jl/stable/)" build of my docs (built 29 days ago) looks fine, but on the "[latest](https://stephenbnicar.github.io/BeaData.jl/latest/)" build (built yesterday), all inline code is being rendered as a code block, rather than inline.

For example, instead of:
* `field`: this is one field

I'm getting:
* `field` (the background shading here would take up the whole line)

: this is one field

I can't reproduce it exactly here, but a glance at the difference between the two links above will show what I mean.  I'm not sure what other information would be helpful; just let me know.

**Comment by MichaelHatherly** [comment]
That's pretty weird, are you able to find out which exact versions of Julia and Documenter produced the different outputs?

**Comment by stephenbnicar** [comment]
The stable version online would be from Julia 0.4.6.  I'm going to say Documenter 0.3.0 since I think that was the current version when I last tagged my package. 

The latest online version may have been built after 0.5.0 was tagged yesterday, but I can't tell for sure.  That would have been Documenter 0.4.2. (I'm pretty diligent about updating packages.)

After I noticed the issue, I also rebuilt the docs locally on Julia 0.4.6 and Documenter 0.4.2 and the new local build has the same problem.

**Comment by MichaelHatherly** [comment]
Can you check whether the following diff applied to Documenter fixes the issue?

```diff
diff --git a/src/Writers/HTMLWriter.jl b/src/Writers/HTMLWriter.jl
index b4139cb..1587006 100644
--- a/src/Writers/HTMLWriter.jl
+++ b/src/Writers/HTMLWriter.jl
@@ -615,7 +615,8 @@ end
 # mdconvert
 # ------------------------------------------------------------------------------
 
-md_block_nodes = [Markdown.MD, Markdown.BlockQuote, Markdown.List]
+const md_block_nodes = [Markdown.MD, Markdown.BlockQuote]
+isa(fieldtype(Markdown.List, :ordered), Integer) && push!(md_block_nodes, Markdown.List)
 if isdefined(Base.Markdown, :Admonition) push!(md_block_nodes, Markdown.Admonition) end
 
 """
```

**Comment by stephenbnicar** [comment]
That seems to have fixed it!

**Comment by MichaelHatherly** [comment]
Thanks for checking.

**Comment by stephenbnicar** [comment]
No problem.  Great package, by the way.

**Comment by MichaelHatherly** [comment]
Glad you've found it useful, feel free to add a link to your package to the [examples](https://juliadocs.github.io/Documenter.jl/latest/man/examples.html#Examples-1) page if you'd like to.
