### ISSUE TITLE
Rendering of Tables

### ISSUE THREAD

**Issue by bicycle1885** [JuliaDocs/Documenter.jl#29]
The following table is not rendered correctly in HTML:

**docs/src/man/seq.md**
```
The following table summarizes common sequence types that are defined in the
`Bio.Seq` module:

| Type                               | Symbol type      | Type alias          |
| ---------------------------------- | ---------------- | ------------------- |
| `BioSequence{DNAAlphabet{4}}`      | `DNANucleotide`  | `DNASequence`       |
| `BioSequence{RNAAlphabet{4}}`      | `RNANucleotide`  | `RNASequence`       |
| `BioSequence{AminoAcidAlphabet}`   | `AminoAcid`      | `AminoAcidSequence` |
| `BioSequence{CharAlphabet}`        | `Char`           | `CharSequence`      |
```

**browser view**
![screen shot 2016-03-17 at 17 20 19](https://cloud.githubusercontent.com/assets/905683/13840255/a1688ea2-ec64-11e5-8419-c2b2f0908f48.png)

I guess this is because it is converted to a weird Markdown table:

**docs/build/man/seq.md**
```
The following table summarizes common sequence types that are defined in the `Bio.Seq` module:


                            Type |     Symbol type |          Type alias
-------------------------------: | --------------: | ------------------:
   `BioSequence{DNAAlphabet{4}}` | `DNANucleotide` |       `DNASequence`
   `BioSequence{RNAAlphabet{4}}` | `RNANucleotide` |       `RNASequence`
`BioSequence{AminoAcidAlphabet}` |     `AminoAcid` | `AminoAcidSequence`
     `BioSequence{CharAlphabet}` |          `Char` |      `CharSequence`
```

As you see, the first header line is right aligned in the converted Markdown file.

My current workaround is explicitly writing left-aligned table like below:

**docs/src/man/seq.md**
```
| Type                               | Symbol type      | Type alias          |
| :--------------------------------- | :--------------- | :------------------ |
| `BioSequence{DNAAlphabet{4}}`      | `DNANucleotide`  | `DNASequence`       |
| `BioSequence{RNAAlphabet{4}}`      | `RNANucleotide`  | `RNASequence`       |
| `BioSequence{AminoAcidAlphabet}`   | `AminoAcid`      | `AminoAcidSequence` |
| `BioSequence{CharAlphabet}`        | `Char`           | `CharSequence`      |
```

This is converted to:

**docs/build/man/seq.md**
```
Type                             | Symbol type     | Type alias         
:------------------------------- | :-------------- | :------------------
`BioSequence{DNAAlphabet{4}}`    | `DNANucleotide` | `DNASequence`      
`BioSequence{RNAAlphabet{4}}`    | `RNANucleotide` | `RNASequence`      
`BioSequence{AminoAcidAlphabet}` | `AminoAcid`     | `AminoAcidSequence`
`BioSequence{CharAlphabet}`      | `Char`          | `CharSequence`     
```

This looks as I expected:

**browser view**
![screen shot 2016-03-17 at 17 28 04](https://cloud.githubusercontent.com/assets/905683/13840394/aca6fb68-ec65-11e5-9079-c79ca2c6974b.png)

**Comment by MichaelHatherly** [comment]
The leading whitespace appears to confuse the mkdocs markdown parser, if I'm understanding the issue correctly? GitHub's markdown parser appears to handle those kind of tables fine.

Incidentally [this PR](https://github.com/JuliaLang/julia/pull/15530) may help here since it adds pipes on either side of all tables and so gets rid of the leading whitespace issue. Potentially worth backporting.

I'm not sure there's much that can be done in Lapidary itself to handle this, but we can keep it open until upstream issues are resolved.

**Comment by bicycle1885** [comment]
Yes, I think so.

For a while I can avoid the issue with left-aligning.

Thanks a lot :)

**Comment by MichaelHatherly** [comment]
The sidebars commit is currently being backported for Julia `0.4.6`, so I'll close this now just in case I forget later on.
