### ISSUE TITLE
bullet chars in @example code

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#296]
i had a code example with `@example`in which there was a Julia string containing bullet characters. (possibly "•", although i'd have to check). The example failed to run, although Julia was quite happy to run it as a stand-alone file. (Took me ages to track it down! :))

Is this a known limitation of Documenter/Julia/Markdown interaction?

**Comment by MichaelHatherly** [comment]
There shouldn't be an issue with bullet chars, but without an example to look at myself I really couldn't say. Have you got a small example you can show that exhibits the problem?

**Comment by cormullion** [comment]
Well, after trying for an hour to produce a simple example, I couldn't make anything similar that doesn't work fine. And even the original problem file works perfectly now. Inexplicable, but good news all round. Sorry for the false alarm!

**Comment by MichaelHatherly** [comment]
Ah well, if you happen to come across it again do just reopen this one then.
