### ISSUE TITLE
Don't Require Local Travis?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#298]
Documenter.jl didn't require a local Travis installation before. But now you need it just for the keygen step. Why doesn't the documentation have a way to do this without using a local Travis installation (i.e. for anyone on RHEL or CentOS).

**Comment by MichaelHatherly** [comment]
Do you mean for `Travis.genkeys`? That has always needed `travis` to be able to run correctly I think.

**Comment by ChrisRackauckas** [comment]
There was a way to directly enter the API keys before I thought. I know I didn't have travis and everything setup this time around, and it wasn't my first time making the docs.

**Comment by MichaelHatherly** [comment]
Ah, the `GITHUB_API_KEY` travis env var? That was removed from the docs since using a user/org-wide token like that is more of a security risk since it gives anyone with access to the token read/write access to everything owned by the user/org. That said, it still does work using `GITHUB_API_KEY`, but just isn't documented so that all new setups will used the more secure `.documenter.enc` approach.

**Comment by ChrisRackauckas** [comment]
Is there a safe manual way that could be documented?

**Comment by MichaelHatherly** [comment]
Do you mean a manual way to do the equivalent to what `travis` does? Not that I know of, the `.documenter.enc` file needs to be generated by `travis` as far as I know.

**Comment by mortenpi** [comment]
We could get rid of `.documenter.enc` altogether by storing the SSH key as an unencrypted secured environment variable. This way the key could be set manually on travis-ci.org (but also automatically with `travis env set`).

I've been playing around with variables on Travis a bit now and it seems that it could work -- it appears that the environment variables can be arbitrarily long, so we could just have a base64-encoded version of the key file in one. Security wise, the decryption keys for `.documenter.enc` are already stored as environment variables anyway and seem to have the same privacy settings as user created (non-public) variables, so nothing would change this respect.

**Comment by MichaelHatherly** [comment]
https://github.com/JuliaDocs/Documenter.jl/issues/298#issuecomment-252497392 all sounds like a reasonable plan to me.
