### ISSUE TITLE
Properly Render `<kbd>` tags

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#299]
`<kbd>` tags get mangled instead of getting the proper HTML rendering. For example:

`<kbd>Ctrl</kbd>+<kbd>,</kbd>, or <kbd>Cmd</kbd>+<kbd>,</kbd> on OS X`

translates into

`&lt;kbd&gt;Ctrl&lt;/kbd&gt;+&lt;kbd&gt;,&lt;/kbd&gt;, or &lt;kbd&gt;Cmd&lt;/kbd&gt;+&lt;kbd&gt;,&lt;/kbd&gt; on OS X`

which makes the actual `<kbd>` tags appear in the text.

**Comment by mortenpi** [comment]
This is an upstream bug, the Markdown parser in Base doesn't recognise HTML
tags. I would actually broaden this issue, that the parser should properly
deal with any HTML. I think the CommonMark spec nicely specifies how the
HTML bits could be recognised without a full HTML/XML parser, and then we
could copy them directly to the output. But this would have to be
implemented in Base.

**Comment by MikeInnes** [comment]
I don't think inline HTML of this form is generally supported in Markdown – only block (paragraph-level) elements. It would be good to get support for this in Base for sure but it'd probably have to be in the form of a custom inline element.

**Comment by mortenpi** [comment]
I haven't checked how well most parsers handle inline HTML, but the specs have it. From [Gruber's original spec](http://daringfireball.net/projects/markdown/syntax#html):
> Span-level HTML tags — e.g. `<span>`, `<cite>`, or `<del>` — can be used anywhere in a Markdown paragraph, list item, or header. If you want, you can even use HTML tags instead of Markdown formatting; e.g. if you’d prefer to use HTML `<a>` or `<img>` tags instead of Markdown’s link or image syntax, go right ahead.

and the [Inlines > Raw HTML section of CommonMark](http://spec.commonmark.org/0.26/#raw-html).

**Comment by MikeInnes** [comment]
Ah ok, should've checked properly. I remember the block parts of commonmark and thought the idea was that it just used a pretty dumb heuristic -- looks like inline html requires something more complex (but not a full xhtml parser, as you say).

**Comment by MichaelHatherly** [comment]
Closing as a dup of https://github.com/JuliaLang/julia/issues/17837. Would be nice to have support for this.
