### ISSUE TITLE
Add HTML rendering.

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaDocs/Documenter.jl#3]

**Comment by mortenpi** [comment]
Just to clarify -- the goal here would be to go from the "Documenter flavored" markdown to a fully functioning HTML site, something like mkdocs produces, but have it completely in-house, including the HTML, CSS etc?

**Comment by MichaelHatherly** [comment]
Yes, a self-contained site that could work both locally without a server or hosted somewhere. Things like mathjax can be pulled in from the cdn though, no need to bundle those kinds of deps.

**Comment by MichaelHatherly** [comment]
Assigning to `0.2.0` milestone, which I've given a completion date of August 8 &mdash; a week prior to the final code submissions for GSoC. That will hopefully provide some additional time to handle any patch fixes that are needed after an initial release.
