### ISSUE TITLE
Using Documenter to build organization pages

### ISSUE THREAD

**Issue by timholy** [JuliaDocs/Documenter.jl#301]
We're interested in hosting our main documentation at the organizational level rather than in individual packages. Specifically, [JuliaImages](https://github.com/JuliaImages) is the organization, and https://github.com/JuliaImages/juliaimages.github.io is the repo we intend to use for this documentation.

I'm struggling a bit with using Documenter to deploy the docs. I suspect the problem has to do with special rules for such sites: GitHub distinguishes between "project" pages and "user/organization" pages; the latter must be published from `master` (https://help.github.com/articles/user-organization-and-project-pages/). As you can see, in my `make.jl` I've specified `master` as the branch; however, the deployment isn't succeeding. I suspect it has something to do with the fact that travis says there is [nothing to commit](https://travis-ci.org/JuliaImages/juliaimages.github.io/builds/165501027).

Does this suggest that the solution is to not `gitignore` `docs/build` and commit all built html files to the project? Or is there a better strategy?

**Comment by MichaelHatherly** [comment]
Not sure yet what the issue is, but I'll have a look this weekend if I can.

> Does this suggest that the solution is to not gitignore docs/build and commit all built html files to the project?

Preferably not if possible. I'd like all generated files to always just be autocommited without needing any intervention on the human side.

**Comment by timholy** [comment]
What about starting a repo that's *not* named `orgname.github.io` to host the source docs and then pushing to `orgname.github.io`?

Also, is it possible to push manually?

**Comment by mortenpi** [comment]
> Also, is it ~~possible~~easy to ~~push~~ deploy manually? From my own machine?

Nope, although I think it would be a nice feature to have. You would have to do all the steps manually (`git clone / checkout gh-pages`, remove old directories, copy over `build/`, `commit` and `push`).

I am curious though about one thing -- if I understand correctly you want to take the `docs/src` on master, build them and then push the result back to master? Assuming that travis will run on every push to master, wouldn't this cause an infinite travis loop?

**Comment by timholy** [comment]
It's not that I want to have them in master, it's that github requires it for repos with certain names. That's why I asked about putting the source docs in their own repo. Or I guess I could write the docs on a branch that's not master?

**Comment by MichaelHatherly** [comment]
> Also, is it possibleeasy to push deploy manually? From my own machine?

Yeah, as @mortenpi says it's just a little involved, but honestly not that bad really. Might be nice to have an exported function that does the manual local deploy for us too.

> Or I guess I could write the docs on a branch that's not master?

I think that could work probably.

**Comment by mortenpi** [comment]
> Or I guess I could write the docs on a branch that's not master?

It seems that you can change the "Default branch" away from master on github, while the pages are still hosted from there. This, I think, would make this workaround more or less seamless.

**Comment by MichaelHatherly** [comment]
> It seems that you can change the "Default branch" away from master on github, while the pages are still hosted from there. This, I think, would make this workaround more or less seamless.

Ah, well if that works that's great.

Here's the JuliaDocs org page setup with travis autobuilds: https://juliadocs.github.io/latest/ and https://github.com/JuliaDocs/juliadocs.github.io/tree/source.

It does push to a `lastest` folder at the moment unfortunately, but that could be changed in `deploydocs` with some kind of `unversioned` keyword or something like that that would just push to the root folder.

**Comment by timholy** [comment]
How do you tell it to push to the `latest` folder? I'm trying to copy your setup but not having luck so far.

**Comment by timholy** [comment]
I'm comparing these two travis builds:
juliadocs: https://travis-ci.org/JuliaDocs/juliadocs.github.io
juliaimages: https://travis-ci.org/JuliaImages/juliaimages.github.io

The very final lines of the log differ in probably-important ways, but I don't understand the reason for the difference.

**Comment by MichaelHatherly** [comment]
In `deploydocs` the `target = "build"` keyword is missing. That specifies which folder to push to the remote. By default it's set to `"site"` which is what `mkdocs` needed. I think that's the only significant difference.

**Comment by timholy** [comment]
Yay, works! I thought that was the default, thanks for pointing it out.

As JuliaImages evolves, I can imagine wanting to have "old version" and "new version" docs. Would the procedure be something like this:
- create a branch, `source-oldversion` forked from `source`
- in the `master` branch, copy the entire `latest` folder to `oldversion`
- update `README` links to include `oldversion`.
The part that's unclear to me is how one would deploy to `oldversion` if you ever decided you needed to update the `oldversion` docs.

One other slight oddity, commenting for posterity in case others follow the same path: after building in the `source` branch, it tries to do a build on `master` (triggered by the result of the source build committing to master) and complains about not finding a `.travis.yml` file. It errors, because I deleted this file from the master branch (because there's nothing to build). To prevent this from happening, on Travis I changed one of the project settings to "Build only if .travis.yml present".

**Comment by MichaelHatherly** [comment]
> As JuliaImages evolves, I can imagine wanting to have "old version" and "new version" docs.

Best way to deal with archived versions of the docs would probably be to just push a git tag each time you'd like to create a new versioned folder. (That's what Documenter does whenever `PkgDev.tag` is used.)

> It does push to a lastest folder at the moment unfortunately, but that could be changed in deploydocs with some kind of unversioned keyword or something like that that would just push to the root folder.

A possible way of dealing with the lack of a root `index.html` would be to add a dummy `index.html` to the `master` branch with:

```html
<meta http-equiv="refresh" content="0; url=http://repo.github.io/folder/index.html" />
```

which appears to work fine and just redirects to the subfolder as seen here: https://juliadocs.github.io.

> One other slight oddity

Whoops, I ran into that as well, thanks for mentioning it.

**Comment by MichaelHatherly** [comment]
Not really a bug, just needs some docs explaining how to go about making an org page based on all the discussion in this issue and the linked examples.

I'll get around to doing this at some point, but if anyone wants to write it up then just let us know.

**Comment by timholy** [comment]
I don't think there's anything else we need. It's been long enough since I set that up that I no longer remember if there were pain points that could be addressed.
