### ISSUE TITLE
`F\b` translated to `F^H`

### ISSUE THREAD

**Issue by abhijithch** [JuliaDocs/Documenter.jl#303]
While trying to create documentation for the package `AxisAlgorithms`, the `F\b` part of the documentation on [this](https://github.com/timholy/AxisAlgorithms.jl/blob/master/src/AxisAlgorithms.jl#L16) line is translated to `F^H`. This is creating issues while trying to convert the generated md file to pdf. `pdflatex` does not seem to understand how to render this. How can I work around this?

**Comment by MichaelHatherly** [comment]
`\b` is like `\n`, `\t`, etc. so should just be able to escape the `\` in `\b` as `\\b` and it will print properly.

**Comment by abhijithch** [comment]
Thanks. Will take this up in the respective packages.
