### ISSUE TITLE
Unable to automatically generate docs

### ISSUE THREAD

**Issue by abhijithch** [JuliaDocs/Documenter.jl#306]
I am trying to automate the process of documentation generation for a certain list of packages. I have a function which replaces the `make.jl` file which is as shown below,

```
function make_doc(p)
    p1 = Symbol(p)
    eval(:(using $p1))
    eval(:(using Documenter))
    makedocs(
      modules = [p],
      clean = true,
      format = Documenter.Formats.Markdown,
      sitename = "$p.jl",
      linkcheck = !("skiplinks" in ARGS),
      pages = Any[ # Compat: `Any` for 0.4 compat
          "Home" => "$p.md"
      ]
    )
end
```

The only problem I am having with the above function is the line, `modules = [p]`. This works only if I hard code the name of the package inplace of variable `p`. Is there any work around to this, I would highly appreciate some quick help here.

**Comment by MichaelHatherly** [comment]
Are there any error messages?

You probably need to specify the `root` keyword, since otherwise `makedocs` won't know *where* each `docs` folder is.

**Comment by mortenpi** [comment]
`p` is a `String`, I guess? I think the `modules` argument expects `Module` type objects. Having `modules = [eval(p1)]` might work.

**Comment by MichaelHatherly** [comment]
`p` could be a `Module`:

```
julia> Symbol(Base)
:Base
```

**Comment by MichaelHatherly** [comment]
Is this still an issue for you @abhijithch, or has the `root = ` suggestions solved it for you? Please can you provide any errors/warning that you're seeing as well as versions of packages you're using if this is still a problem, or let us know that things are working so we can close the issue. Thanks.

**Comment by abhijithch** [comment]
`eval(Symbol(module))` solved the issue. Thanks, closing this.

**Comment by MichaelHatherly** [comment]
FWIW, if this was related to the `testapi.txt` script then a better approach might be to make argument `p` a `Module` which will mean you can remove all the `eval`s from `docgen`, something like:

```julia
function docgen(p::Module, temp_dir)
    na = names(p)

    src_path = joinpath(temp_dir,"docs","src")
    docs_path = joinpath(temp_dir,"docs")
    # Create an src folder which will have the .md template file
    if isdir(docs_path)
        rm(docs_path, force=true, recursive=true)
    end
    mkdir(docs_path)
    if isdir(src_path)
        rm(src_path, force=true, recursive=true)
    end
    mkdir(src_path)

    # Create a .md file for each package with all the exported APIs
    open(joinpath(src_path, "$p.md"), "w") do io
        println(io, "## API reference for $p")
        println(io, "")
        println(io,
            """
            ```@autodocs
            Modules = [$p]
            ```
            """
        )
    end

    # Remove the older build folder.
    if isdir(joinpath(docs_path, "build"))
        rm(joinpath(docs_path, "build"), recursive=true)
    end

    try
        println("Running makedocs for $p")
        makedocs(
            root    = docs_path,
            modules = [p],
            clean = true,
            format = :html,
            sitename = "$p.jl",
            pages = ["Home" => "$p.md"],
        )
        println("Done running makedocs for $p")
    catch e
        println("Exception is $e")
        println("Error generating doc for $p")
    end

end
```

Then run it with 

```julia
using MyModule
docgen(MyModule, "temp/")
```

**Comment by abhijithch** [comment]
I could do this too, but if the number of packages are high then there are high chances of namespace conflicts to occur. `workspace` sometimes is not reliable in `Juliav0.5`.

**Comment by MichaelHatherly** [comment]
> but if the number of packages are high then there are high chances of namespace conflicts to occur.

The current script has the same issues doesn't it? Unless you're starting a new Julia process for each `docgen` call? That's pretty much what I've been doing when testing Documenter against a bunch of packages prior to a new release, which works much better than calling `workspace`.

**Comment by abhijithch** [comment]
Yes sorry my bad, will change this as your suggestion.
