### ISSUE TITLE
`makedocs` hangs infinitely 

### ISSUE THREAD

**Issue by abhijithch** [JuliaDocs/Documenter.jl#307]
I am trying to get the documentation for `ASTInterpreter`. I am using the below mentioned `make.jl` file and `arc/ASTInterpreter.md` as shown below, 

```
using Documenter, ASTInterpreter, VT100, TerminalUI

makedocs(
    modules = [ASTInterpreter],
    clean = true,
    format = Documenter.Formats.Markdown,
    sitename = "ASTInterpreter.jl",
    linkcheck = !("skiplinks" in ARGS),
    pages = Any[ # Compat: `Any` for 0.4 compat
        "Home" => "ASTInterpreter.md"
    ]
)
```

```
## API reference for ASTInterpreter

\```@docs
@enter
enter
\```
```

I am running this like this, `julia make.jl`. The locations of the files are,

```
docs
        - make.jl
        - src
               - ASTInterpreter.md
```

When I run this on `windows` it just hangs infinitely, but the same process works fine on `mac`.

```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

```

Any help on solving this would be great.

PS : Please ignore the `\` in `.md`.

**Comment by MichaelHatherly** [comment]
Did you add docstrings to `enter` and `@enter`? As far as I can tell neither of those two are actually documented, which might be what's causing this. I don't have access to a Windows machine, so won't be able to directly debug this. Are you able to replicate this issue without extra packages (no `ASTInterpreter`, etc.)?

**Comment by MichaelHatherly** [comment]
Is this still an issue for you @abhijithch? Could you please provide some feedback to the questions in https://github.com/JuliaDocs/Documenter.jl/issues/307#issuecomment-252469273, thanks.

**Comment by abhijithch** [comment]
This was being caused by the way I was calling the script. I can confirm that it was not caused due to `enter` or `@enter`. Sorry for the trouble.

**Comment by MichaelHatherly** [comment]
No prob, glad it's work for you now.
