### ISSUE TITLE
Documentation: Adding a Logo to the Sidebar

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#308]
I see in the Documenter.jl documentation that you have a logo on the top of the sidebar: how is this done? I didn't it specified in the `makedocs` command. I think specifics like these should be added to the documentation.

**Comment by mortenpi** [comment]
Currently it simplistically checks whether `src/assets/logo.png` exists and uses that if it does.

There's _some_ documentation on the HTML output in [`HTMLWriter`'s docstring](https://juliadocs.github.io/Documenter.jl/latest/lib/internals/writers.html#Documenter.Writers.HTMLWriter). But completely agreed, the documentation of the HTML output should be improved (or rather created).

**Comment by MichaelHatherly** [comment]
Yes, does need some docs, though the HTML output is still, *technically*, considered experimental :) I doubt anything drastic will change in it's behaviour since it seems to be working quite nicely so far.

**Comment by tpapp** [comment]
Not sure if I should open an new issue for this, but it would be nice if other image formats, particularly `src/assets/logo.svg` were allowed.

**Comment by mortenpi** [comment]
Feel free to open a separate issue -- the handling of the logo could be improved.
