### ISSUE TITLE
Task Lists / Checkboxes

### ISSUE THREAD

**Issue by michakraus** [JuliaDocs/Documenter.jl#318]
It would be nice to have the possibility to write task lists like on GitHub (but without interactivity), that is having a list

```
- [ ] task 1
- [ ] task 2
```

which in HTML gets rendered with

```
<input type="checkbox" checked disabled>
<input type="checkbox" disabled>
```

to show as
- [x] task 1
- [ ] task 2

In LaTeX, this could easily be rendered with [enumitem](https://www.ctan.org/pkg/enumitem?lang=de), see e.g. [this discussion](http://tex.stackexchange.com/questions/247681/how-to-create-checkbox-todo-list) on StackExchange.

**Comment by MichaelHatherly** [comment]
Thanks for the suggestion @michakraus, do note that the markdown parser used in Documenter is defined in the `Base.Markdown` module so this is issue needs to be reopened in https://github.com/JuliaLang/julia, thanks.

Worth noting that our markdown parser is primarily based on the CommonMark spec, which does not seem to have task lists. You're more than welcome though to open a PR that implements the feature and we'll be happy to review.

**Comment by michakraus** [comment]
Thanks for the quick reply. I will try to have a look into this issue when having some time...
