### ISSUE TITLE
html code appears in markdown output

### ISSUE THREAD

**Issue by jlapeyre** [JuliaDocs/Documenter.jl#320]
When I run `julia make.jl` on a markdown `index.md`, the output file contains a lot of html code. The `Documenter` documentation says

> Documenter produces a set of Markdown files ...

Is this broken, or is there something I don't understand ?  I am using the following `make.jl`

```julia
using Documenter, MyPackage

makedocs(
    modules = MyPackage,
    clean   = false,
)
```

I find this happens with both the master branch of `Documenter` as well as the latest version.

**Comment by mortenpi** [comment]
HTML output should only happen when `format = :html` is explicitly set in `makedocs`. However, there will be a few HTML tags here and there in case, such as page anchors (e.g. `<a id='Package-Features-1'></a>`) -- HTML is valid in Markdown documents. But the file should still mainly be Markdown.

Could you perhaps post the output `index.md`? Also, do you see the same thing when you run Documenter's `test/examples/make.jl` (Markdown output should end up in `test/examples/build/markdown`)?

**Comment by jlapeyre** [comment]
Ah, I see. It is indeed mostly links and anchors that appear. Like here:  https://github.com/jlapeyre/InverseLaplace.jl . I didn't realize that this is valid markdown.  The github page displays OK.  I guess the failure to render correctly in other cases is probably the fault of the program that does the rendering. E.g. the julia repl displays the README.md as the default doc for packages. But, the html is printed literally in this case.

**Comment by mortenpi** [comment]
For the README Julia has to read it back in and Julia's Markdown parser currently doesn't handle HTML (JuliaLang/julia#17837). Also, on a separate note, it seems that your use case is related to #12.

**Comment by jlapeyre** [comment]
Those links clarify what's happening. I am trying to do the same as a few others; not duplicate material in docstrings and the README.md. This doesn't seem to be what most users of Documenter are doing. As far, as I'm concerned you can close the issue.

**Comment by MichaelHatherly** [comment]
> not duplicate material in docstrings and the README.md. This doesn't seem to be what most users of Documenter are doing.

Yes, the simplest solution to the duplication problem is to have a README.md that just provides a short outline of what the package is for, lists any info (such as travis build status, etc.) that shouldn't be in the user docs, and then provides a very clear link to the docs generated by Documenter. This seems to have been working nicely for the last few months as far as I've seen.
