### ISSUE TITLE
Feature request: Insert custom css in HTML output

### ISSUE THREAD

**Issue by KristofferC** [JuliaDocs/Documenter.jl#327]
I want to emulate a terminal window in my documentation and in order to do so it would be nice if I could define some stuff in the CSS file and then use the raw html macro. Would it be possible to be able to append some custom CSS to the already generated CSS file? Perhaps as a new kwarg to `makedocs`?

**Comment by mortenpi** [comment]
Probably best to support custom stylesheets somehow, e.g. check if user provides `custom.css` and then `<link>` to in the HTML (optionally we could have the user explicitly define it in `makedocs`). For multiple stylesheets the user could just `@import` them in that one.

**Comment by MichaelHatherly** [comment]
The LaTeX writer looks for an `assets/custom.sty` already, so an `assets/custom.css` that does the same thing sounds worth doing to me.
