### ISSUE TITLE
Rename "latest" to "development"

### ISSUE THREAD

**Issue by nalimilan** [JuliaDocs/Documenter.jl#337]
Wouldn't it be better to refer to docs from git master as "development" rather than "latest"? In Julia Base, users frequently get confused when reading the manual for the development version and expecting them to work on the latest release. I'm afraid the same could happen with packages documentation. It's always better to be explicit, as "latest" may convey the idea of "most up-to-date".

**Comment by MichaelHatherly** [comment]
It's probably possible to change the naming scheme now, but given the number of packages already using `latest` and `stable` it's going cause some grief with link changes.

I think the simplest approach is for package authors to label each link to the docs in their readme in a clear way. The wording in Documenter's readme seems to have been doing alright as far as I can tell.

**Comment by ChrisRackauckas** [comment]
"Master"? A lot of people have a "dev" branch which is not "a stable dev branch" like "master".

**Comment by nalimilan** [comment]
Yeah, the description of the links is explicit in the README, but the bold LATEST still isn't ideal, and not all packages will necessarily keep the full description. Of course I know changing links will be disruptive; I'm not sure what's the best way to handle that, but there must be ways to ease the transition.

**Comment by tpoisot** [comment]
I agree with @ChrisRackauckas -- having a `dev` branch is common, and it would be good to have a documentation for it.

**Comment by mortenpi** [comment]
This was changed in #802.
