### ISSUE TITLE
Documenter is skipping docs deployment

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#339]
From the Travis you can see that Documenter is skipping docs deployment: https://travis-ci.org/JuliaDiffEq/DiffEqDocs.jl

However, from the make.jl file you can see that it is setup to build on Linux 0.5: https://github.com/JuliaDiffEq/DiffEqDocs.jl/blob/master/docs/make.jl#L61

Any ideas on what the issue is?

**Comment by MichaelHatherly** [comment]
Can you add a `DOCUMENTER_DEBUG` environment variable to travis with the value `true`, so that we can see some extra output.

I'd guess initially that it's to do with the missing `.documenter.enc` file. The new method for deploying without that hasn't been tagged yet, it's just on `master`. I'll probably be getting around to tagging later today.

**Comment by ChrisRackauckas** [comment]
Yeah, it might be because of the lack of tag: https://travis-ci.org/JuliaDiffEq/DiffEqDocs.jl#L1577

**Comment by MichaelHatherly** [comment]
Yup, looks like that's it.

**Comment by MichaelHatherly** [comment]
Tagged at https://github.com/JuliaLang/METADATA.jl/pull/6937.

**Comment by ChrisRackauckas** [comment]
Works!

**Comment by MichaelHatherly** [comment]
Excellent! Are the `DifferentialEquations.jl` docs linked to on the [examples page](https://juliadocs.github.io/Documenter.jl/latest/man/examples.html#Registered-1) going to be replaced by these new ones (nav menu links look quite similar), or do they supplement those? Could you update the links on the examples page (or add the new ones) once they're ready, thanks.

**Comment by ChrisRackauckas** [comment]
Yes, they are being moved out to a separate repo to handle the docs for the whole org. I'll make a PR for the new link.
