### ISSUE TITLE
Deployment Key error: "MyPackage already has an ssh key"

### ISSUE THREAD

**Issue by stephenbnicar** [JuliaDocs/Documenter.jl#346]
In light of [PSA: Documenter.jl deprecations](https://groups.google.com/forum/#!topic/julia-users/TSnMI5-P2xE), I was trying to generate a new deployment key  and I get the following error:
```
julia> Travis.genkeys("BeaData")
ERROR: BeaData already has an ssh key. Remove it and try again.
 in (::Documenter.Travis.##2#3{String,String})() at /home/stephen/.julia/v0.5/Documenter/src/Documenter.jl:564
 in cd(::Documenter.Travis.##2#3{String,String}, ::String) at ./file.jl:59
 in #genkeys#1(::String, ::Function, ::String) at /home/stephen/.julia/v0.5/Documenter/src/Documenter.jl:562
 in genkeys(::String) at /home/stephen/.julia/v0.5/Documenter/src/Documenter.jl:552
```
I'm sure there's a simple solution to this but I don't know what it is.  Any help is appreciated.  The existing key was generated using the now-deprecated process.

**Comment by MichaelHatherly** [comment]
The [`docs/.documenter.enc` file](https://github.com/stephenbnicar/BeaData.jl/blob/master/docs/.documenter.enc) just needs to be deleted manually. It's not needed anymore with the new authentication method so I felt it was best to clear them out, but didn't want to go and do that without the user's knowledge.

**Comment by stephenbnicar** [comment]
Just figured that out... Thanks!
