### ISSUE TITLE
Test the syntax used in doctests

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#347]
For a module:

```jl
module A
    export foo
    foo(x) = "Hello, world!"
end
```

These doctests pass

\`\`\`jldoctest
julia> bar(1)
\`\`\`

even though `bar` is not defined. The thrown `ERROR: UndefVarError: bar not defined` is not let through unless there is a output comparison. If there is a comparison, the test fail:

\`\`\`jldoctest
julia> bar(1)
"Hello, world!"
\`\`\`

which throws

```
!! Test error in the following code block in 'src/test.md':

        julia> bar(1)
        "Hello, world!"

    in expression:

        bar(1)

    expected:

        "Hello, world!"

    returned:

        ERROR: UndefVarError: bar not defined
         ...
```

It would be useful if the error is let through, to compare syntax used in the docs. For instance if  `foo` previously was called `bar`, then it would be nice if the doctest fail.

**Comment by MichaelHatherly** [comment]
Thanks for the report. I think this is probably just an artefact of the way doctests do the results comparison &mdash; should be fixable though.
