### ISSUE TITLE
Option to highlight doctests with julia rather than jlcon

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#350]
Currently, `jldoctest` blocks are highlighted with `jlcon`. Would be nice with an option to highlight `jldoctest`s with `julia` instead.

**Comment by MichaelHatherly** [comment]
Using `julia` for REPL blocks has the unfortunate problem of getting erroneous highlighting in some outputs, for example:

```julia
julia> x -> x + 1
(::#1) (generic function with 1 method)
```

Note how the comment `#` messes up the highlighting. There's other cases, such as single opening `"` chars that can lead to worst highlighting problems though.

The eventual plan for highlighting is to use the pure Julia highlighters in [Highlights.jl](https://github.com/JuliaDocs/Highlights.jl) that I've been working on instead, which has a `jlcon` lexer that correctly highlights Julia REPL blocks. I've just got to find the time to switch Documenter over to using that package.

**Comment by fredrikekre** [comment]
Yea I am aware of the problems, but just thought it could be nice anyway. Seems like you have a better plan to fix this!
