### ISSUE TITLE
Travis not exiting properly

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#355]
I am having issues with Travis exiting properly on two repositories with Documenter:

https://travis-ci.org/JuliaDiffEq/DiffEqDevDocs.jl
https://travis-ci.org/JuliaDiffEq/DiffEqDocs.jl

They both exit with a 1 while every command exits with a 0.

**Comment by MichaelHatherly** [comment]
If you disable Documenter does it exit with a 0? Or perhaps move the Documenter part of `.travis.yml` to an `after_success:` section in the script, which shouldn't affect the exit code at all.

**Comment by ChrisRackauckas** [comment]
Huh, it was due to it just messing up with cloning or something. Whatever it is, it seems to have fixed itself.

**Comment by MichaelHatherly** [comment]
If it was happening around about the 50th commit then it could have been due to https://github.com/travis-ci/travis-ci/issues/4942 perhaps.
