### ISSUE TITLE
DAG of types a la Doxygen

### ISSUE THREAD

**Issue by juliohm** [JuliaDocs/Documenter.jl#364]
This is a big feature request, but it would be great to have a visualization of the DAG of types defined in a package [a la Doxygen](https://www.google.com/search?q=doxygen+graph&biw=1600&bih=807&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiQtaKgvdzQAhUI_WMKHahoDVwQsAQIMw).

One thing I learned over the years by using and contributing to open source projects is that an "API page" is useless. A quick visualization of how the concepts are connected is a much more helpful documentation.

I personally defend the idea that we should abandon API pages in docs completely as they are not helpful, just boilerplate. In most cases, people should be concentrating their energy in writing examples of usage instead of documenting each single internal function defined in their package.

**Comment by MichaelHatherly** [comment]
Yes, that would be nice I think. Probably best to just use one of the graph plotting packages to do all the heavy lifting. Getting a DAG of a module's types isn't too difficult either. Vertices should obviously be clickable and link to their docstrings.

This would add a large number of deps to the package, which I'd prefer not to do, so we can probably have this in some kind of DocumenterExtensions package of some kind.

I've not really got the time to work on this myself at the moment, so you, or anyone else, are welcome to start implementing it if you'd like.

**Comment by juliohm** [comment]
This is already available in `PlotRecipes.jl`: https://github.com/JuliaPlots/PlotRecipes.jl#julia-type-trees

Maybe we can reuse some of the code there.

**Comment by fredrikekre** [comment]
I don't think anything is needed from Documenter here.

**Comment by juliohm** [comment]
@fredrikekre you mean we can call something like D3TreeTypes.jl directly in Documenter.jl and it will just work?

**Comment by mortenpi** [comment]
@juliohm, yep, it look like it:

![documenter-typetrees](https://user-images.githubusercontent.com/147757/52920885-57943900-3376-11e9-8aba-ea5ea52c4146.png)

What's a bit suboptimal is that [D3Trees outputs a whole HTML document](https://github.com/sisl/D3Trees.jl/blob/948dee6c55650522eedfefffc316728744eaec9d/src/show.jl#L8-L40) with the `<html>`, `<head>` tags etc. Ideally they would just output the body. But it does not seem to cause any immediate rendering issues in the browser.

**Comment by fredrikekre** [comment]
> What's a bit suboptimal is that [D3Trees outputs a whole HTML document](https://github.com/sisl/D3Trees.jl/blob/948dee6c55650522eedfefffc316728744eaec9d/src/show.jl#L8-L40) with the `<html>`, `<head>` tags etc.

It probably shouldn't? No other `text/html` `show` methods do this. Maybe open an issue?

**Comment by juliohm** [comment]
I need to try this on my docs! Can we also have some utilities in Documenter.jl itself to avoid the boilerplate code? Something like a docgraph block?

'''docgraph
MyType
'''

or

'''docgraph
MyModule
'''
