### ISSUE TITLE
Print diff in failing doctest

### ISSUE THREAD

**Issue by KristofferC** [JuliaDocs/Documenter.jl#370]
Throwing out an idea here, but sometimes it is hard to see why a doctest is failing, see for example https://github.com/JuliaLang/julia/pull/19569#issuecomment-266771012.

Maybe it could be possible to print a diff to explicitly show where the problem is. On the other hand, maybe in the vast majority of cases, the difference should be obvious.

**Comment by MichaelHatherly** [comment]
Yes, would be good to have.

**Comment by MichaelHatherly** [comment]
Some basic diff printing in the referenced commit. Probably will need some fine tuning of the output, but I'd say it's definitely an improvement over what gets printed at the moment.
