### ISSUE TITLE
epub backend

### ISSUE THREAD

**Issue by Ken-B** [JuliaDocs/Documenter.jl#371]
As mentioned in julialang/julia#18588, a backend for epub would make the Julia documentation available on ereaders, as it's been over the last years. 

Thank you.

**Comment by MichaelHatherly** [comment]
Thanks.

**Comment by mortenpi** [comment]
We now have https://github.com/laborg/DocumenterEpub.jl

**Comment by NightMachinary** [comment]
[**@mortenpi**](https://github.com/mortenpi) commented on [May 12, 2021, 10:31 AM GMT+4:30](https://github.com/JuliaDocs/Documenter.jl/issues/371#issuecomment-839476951 "2021-05-12T06:01:33Z - Replied by Github Reply Comments"):
> We now have [laborg/DocumenterEpub.jl](https://github.com/laborg/DocumenterEpub.jl)

So where can we download the EPUBs? 😄

**Comment by mortenpi** [comment]
You can find the link to the 1.6.0 one here: https://discourse.julialang.org/t/ann-documenterepub-jl/53435/19
