### ISSUE TITLE
google analytics support

### ISSUE THREAD

**Issue by ViralBShah** [JuliaDocs/Documenter.jl#372]
For HTML docs generated by Documenter.jl, I often want to host them publicly and have a Google Analytics tracker. Would it be possible to build support for this in Documenter, should someone want to enable GA?

**Comment by MichaelHatherly** [comment]
Yes, probably wouldn't be too hard to add.

**Comment by ViralBShah** [comment]
If there is a quick way to add it just for the julia manual and stdlib, it would be great. Since we changed over, we are no longer getting data from the docs. The data has been generally useful for a number of reasons, as you can imagine.

**Comment by MichaelHatherly** [comment]
I'll see what I can do later this evening or tomorrow.

**Comment by ViralBShah** [comment]
Thank you very much.
