### ISSUE TITLE
Unused configuration for MathJax tex2jax extension

### ISSUE THREAD

**Issue by mitya57** [JuliaDocs/Documenter.jl#376]
Dear Documenter.jl developers,

I am the author of the [math extension for Python-Markdown](https://github.com/mitya57/python-markdown-math) which you are using.

It seems that you [are having](https://github.com/JuliaDocs/Documenter.jl/blob/master/assets/mkdocs/mathjaxhelper.js#L2) some configuration for the [tex2jax](http://docs.mathjax.org/en/latest/options/tex2jax.html) extension of MathJax as well (though it looks like it does not get actually used). However these two extensions do the same thing but on different levels, and thus can conflict:

* python-markdown-math converts the math delimiters to `<script type="math/tex">` nodes _during the Markdown → HTML conversion_. This integrates well with Markdown, i.e. the Markdown markup inside math formulas will not be processed. It also allows for escaping the delimiters, i.e. you can use `\\(...\\)` if you want raw `\(...\)` as an output.
* tex2jax also does the conversion of delimiters to `<script type="math/tex">`, but _when the HTML is loaded in the browser_.

When you use both, then the delimiters escaped in Markdown will be still rendered by tex2jax, which is clearly a bug.

I recommend you to get rid of tex2jax extension (or traces of it). To do that, drop the first `MathJax.Hub.Config` call from [`mathjaxhelper.js`](https://github.com/JuliaDocs/Documenter.jl/blob/master/assets/mkdocs/mathjaxhelper.js), and drop the `?config=...` part after the `MathJax.js` URL, you are using a custom configuration anyway (there are multiple variants of `?config` in different files in this repository).

**Comment by MichaelHatherly** [comment]
Thanks for the detailed report @mitya57. We've generally been moving away from outputting markdown in favour of going directly to HTML for the last few months so the markdown backend hasn't seen much attention recently. I'll fix things up as you suggest though when I next get a chance to, thanks!

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing as stale. We don't output to Markdown any more.
