### ISSUE TITLE
BibTeX references

### ISSUE THREAD

**Issue by juliohm** [JuliaDocs/Documenter.jl#379]
Is it possible to include citations to papers following a syntax similar to BibTeX where we have a file with all rereferences `bibliography.bib` and cite specific ones in the documentation with `\cite`,`\citep`,... variants?

**Comment by MichaelHatherly** [comment]
Changes such as these would need to be added to the markdown parser in `Base.Markdown`. Nothing can be done in Documenter to add `\cite` etc syntax to the parser. I'm not sure it's a good idea to start extending the parser with LaTeX-isms, is there any alternative syntax we could borrow (perhaps from pandoc) that would be sufficient for this?

**Comment by juliohm** [comment]
Thank you @MichaelHatherly , I was just curious if that was something doable and worth doing. I believe it is not according to your comment. I will close the issue but let me know if you have an idea on how to incorporate references to articles in the documentation.

**Comment by lucianolorenti** [comment]
I was trying to use the syntax 
```
[<label>](@ref)
```
where `<label>` is the label attached to the item in a bibtex file. 
In the make docs you can specify an array of bibtex files.
```
makedocs(
    ....
    bibtex = [ "/home/luciano/SomeFile.bib"]
)
```

I was trying to use the syntax [<label>](@ref) where <label> is the label attached to the item in a bibtex file. 
In the make docs you can specify an array of bibtex files.
and then [when every search of the <label> reference fail It searches on the bib file.](https://github.com/lucianolorenti/Documenter.jl/commit/eff028c39cd5c7d5c16ea027193779009ca9b490)


[But then I got lost using anchors and links. For now only prints the title.](https://github.com/lucianolorenti/Documenter.jl/commit/8008aa5a5b67aa3ad90fbe7b0f9e1210ac6cf080) I will try again soon.

**Comment by stevengj** [comment]
See also this discussion: https://discourse.julialang.org/t/citations-in-docs/5066

**Comment by simonbyrne** [comment]
See https://github.com/ali-ramadhan/DocumenterCitations.jl
