### ISSUE TITLE
@example blocks issue

### ISSUE THREAD

**Issue by Ward9250** [JuliaDocs/Documenter.jl#380]
Say I have the following documentation:

> # Bio.Phylo: Phylogenetic trees and networks
> 
> ```@meta
> CurrentModule = Bio.Phylo
> DocTestSetup = quote
>     using Bio.Phylo
> end
> ```
> 
> The `Bio.Phylo` module is for data types and methods for handling phylogenetic
> trees and networks.
> 
> ## Phylogenies
> 
> ```@doc
> Phylogeny
> ```
> 
> ### Constructors
> 
> You can create a very simple unresolved phylogeny (a star phylogeny) by
> providing the tips as a vector of strings or a vector of symbols.
> 
> ```@example
> tips = [:A, :B, :C]
> tree = Phylogeny(tips)
> ```
> 

The @example block does not run and the @doc block is not evaluated?

```julia
N95753:docs bward$ julia --color=yes make.jl
Documenter: setting up build directory.
Documenter: expanding markdown templates.
 !! failed to run code block.

UndefVarError(:Phylogeny) [src/man/phylo.md]
 !! Undefined binding 'Bio.Intervals.GFF3Reader'. [src/man/reading.md]
Documenter: building cross-references.
Documenter: running document checks.
 > checking for missing docstrings.
 > running doctests.
 > checking footnote links.
Documenter: populating indices.
Documenter: rendering document.
Documenter: copying assets to build directory.
Documenter: skipping docs deployment.
```

My make.jl file looks like:

```julia
using Documenter, Bio

makedocs()
deploydocs(
    deps = Deps.pip("mkdocs", "pygments", "mkdocs-biojulia"),
    repo = "github.com/BioJulia/Bio.jl.git",
    julia = "0.5",
    osname = "linux",
)
```

**Comment by MichaelHatherly** [comment]
`DocTestSetup = ...` is only for `jldoctest` blocks. For `@example` blocks you can use a named `@setup` block. The separation between doctest blocks and example blocks was intentional to avoid altering state between the two unintentionally since they get executed during different stages. Something like this should do what you need:

    ```@setup my-example
    using Bio.Phylo
    ```

    ...

    ```@example my-example
    tips = [:A, :B, :C]
    tree = Phylogeny(tips)
    ```

**Comment by Ward9250** [comment]
Awesome, that works for me now! Do you know why some docstrings associated with types aren't getting spliced in? 

```@doc
Phylogeny
```

Does not get spliced, and it is both a type, and the constructor methods for said type.

**Comment by Ward9250** [comment]
Ooop an @doc block for some exported methods that have docstrings is also not processed:

'''@doc
isrooted
isrerootable
root
'''

(Again ticks are deliberately wrong for display purpose)

**Comment by Ward9250** [comment]
Final question: Are @example blocks ok to put in docstrings of functions? Or does that mess with the julia prompt help?

**Comment by MichaelHatherly** [comment]
> Are `@example` blocks ok to put in docstrings of functions? Or does that mess with the julia prompt help?

None of the `@` blocks can be used within docstrings, only in markdown files. `jldoctest` blocks should be used in docstrings instead as a substitute when you need testable examples.

**Comment by Ward9250** [comment]
Awesome, thanks!
