### ISSUE TITLE
On-the-fly markdown generation

### ISSUE THREAD

**Issue by tshort** [JuliaDocs/Documenter.jl#382]
Some documentation naturally fits with the structure of a Julia source file. I'd like to be able to generate documentation straight from one or more source files. I've coded this functionality into a [docs/make.jl](https://github.com/tshort/Sims.jl/blob/2e4f71c4a9b2731338e9896c93294e59ec0c1bd3/docs/make.jl) file, but this use case might be a consideration for more general support in Documenter. Here's an example [source file](https://github.com/tshort/Sims.jl/blob/2e4f71c4a9b2731338e9896c93294e59ec0c1bd3/lib/heat_transfer.jl) with corresponding [documentation output](http://tshort.github.io/Sims.jl/latest/lib/heat_transfer.html). 

For this use case, I need the following:

* Direct creation of documentation from one or more Julia files. The order should follow the order in the .jl file. 

* A `@comment` macro to include documentation snippets in a Julia source file.  I've included [this](https://github.com/tshort/Sims.jl/blob/2e4f71c4a9b2731338e9896c93294e59ec0c1bd3/src/docutil.jl) in my package, but if others are interested in this use case, it'd be better to have this somewhere else, so multiple packages don't define this. We had this in the Lexicon/Docile setup.

Right now, I generate files under docs/src. I'm happy with the way this works, but it's a little kludgy.

**Comment by MichaelHatherly** [comment]
Thanks @tshort. If you'd like to put together something for inclusion in Documenter that would be good. At the moment I've not got the time to do anything like this myself, but it does seem like it would be useful to have.

**Comment by tshort** [comment]
Sounds good. Here is one way to go about it:

1. Add a `@comment` macro to Documenter or DocStringExtensions.

2. Allow the `pages` argument to `makedocs` to take Markdown values in addition to the normal filenames. 

With item number 2, the use case above would be supported by a function that returned Markdown from docstrings in a Julia file. Here's how it might look:

```julia
makedocs(
    modules = [Documenter],
    pages = Any[        
        "Home" => "index.md",
        "Manual" => Any[
            "man/examples.md",
            "Guide" => "man/guide.md",
            md"""
              # Builder

              ```@autodocs
              Modules = [Documenter.Builder]
              ```
              """,
            filemd("src/types.jl", Documenter),
...
```

In this example, `filemd` would generate a Markdown string based on the docstrings in the given file in module Documenter. This approach could also be used to handle some of the other feature requests, such as inclusion of documents from other packages (#319) or from tests (#55).

I'm looking for feedback on the approach before I code anything.

**Comment by MichaelHatherly** [comment]
I'm a little wary of adding generated content through the `pages` keyword, since I think that just be for declaring the site structure rather than controlling how things are build. Would be preferable I think to keep all the doc "generation" features within `@` blocks. Perhaps with a new `@literate` (name TBD) block that can stitch together Julia source files:

    ```@literate
    Pages = ["my-file.jl"]
    Modules = [MyModule]
    ```

Which would expand into something like the layout you're generating in Sims at the moment. Could possibly allow `@literate` blocks to create new files themselves instead of being restricted to working only within the enclosing file.

**Comment by MichaelHatherly** [comment]
Also worth nothing that I'm busy with some package-wide refactoring which would definitely impact how this was implemented, so perhaps this should hold on until that has landed in the next few weeks.

**Comment by fredrikekre** [comment]
Some shameless self promotion: https://github.com/fredrikekre/Examples.jl, there is also Weaver for things like this. Not sure what else Documenter needs to provide here.

**Comment by mortenpi** [comment]
> Not sure what else Documenter needs to provide here.

Agreed, this feature appears to be implemented in a package now. And having this in a separate package is probably better anyway.
