### ISSUE TITLE
Make HTML the default backend

### ISSUE THREAD

**Issue by tknopp** [JuliaDocs/Documenter.jl#394]
Hi, I just yesterday explored this great package. From reading through the documentation it would make from my perspective make sense to make the html backend the default. The regular user will be pretty satisfied with it and having to not bother with extra tools is IMHO a huge win.

**Comment by MichaelHatherly** [comment]
Yes, I'd like to do that, though it'll need some kind of deprecation since it will likely break some package's `docs/make.jl` scripts if we just switch over. Will also need some reworking of the manual since it's based on the markdown backend for the most part.

**Comment by tknopp** [comment]
Yes, this was actually my main point. If its the default backend does not matter to much but the documentation could be focused on the simple case. For instance in the "getting started" section one could simply let the user throw the html file into a browser which will give him/her a very pleasant experience.
