### ISSUE TITLE
Add LaTeX rendering.

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaDocs/Documenter.jl#4]

**Comment by hayd** [comment]
For reference the current (rst generated) pdf of julia documentation is here https://media.readthedocs.org/pdf/julia/latest/julia.pdf

**Comment by hayd** [comment]
I think [memoir](http://www.ctan.org/pkg/memoir) ([pdf](http://mirror.jmu.edu/pub/CTAN/macros/latex/contrib/memoir/memman.pdf)) might allow us to give a much better output than readthedocs, it's also very configurable http://ctan.mirrors.hoobly.com/info/latex-samples/MemoirChapStyles/MemoirChapStyles.pdf. Which could allow some iteration on the default, and for packages to play with their own style.

**Comment by MichaelHatherly** [comment]
Thanks for the links, memoir is definitely an option I think.

**Comment by MichaelHatherly** [comment]
#288 will close this. Suggests in that PR for any particular style changes are most welcome.
