### ISSUE TITLE
Run doctests with color disabled (optionally, or by default)

### ISSUE THREAD

**Issue by tkelman** [JuliaDocs/Documenter.jl#418]
This came up a few times in the recent doctest spurt by @fredrikekre, @kshyatt, and @KristofferC

Since markdown and code blocks in html don't usually accept user-defined color formatting, it would be good for showing things like `@code_warntype` output or `!Matched` input arguments in closest-candidate error printing to do those in no-color mode most of the time. Either hackily with an eval to change `Base.have_color`, or by spawning a child process with `--color=no`.

**Comment by MichaelHatherly** [comment]
Closed by #419.
