### ISSUE TITLE
Feature request: Ignore backtraces in doctests

### ISSUE THREAD

**Issue by KristofferC** [JuliaDocs/Documenter.jl#421]
While work is being done in Base it is frequent that line numbers change in doctests stacktraces all over the place. This is a bit annoying because you either update these line numbers all the time or get a bunch of spurious errors that you have to filter through. The possibility of running in a mode which ignores backtraces (or complete error messages if that is easier) would be greatly appreciated.

**Comment by MichaelHatherly** [comment]
Yeah, does get a annoying having to constantly change the numbers. Perhaps ignoring just the line numbers themselves (with something like `r"\.jl:\d+$"m`) in a "non-strict" mode would be enough to ease the pain.

**Comment by KristofferC** [comment]
Now possible.
