### ISSUE TITLE
cannot control image size in html output

### ISSUE THREAD

**Issue by denizyuret** [JuliaDocs/Documenter.jl#423]
I tried all the recommendations from the following page, none of them lets me control the size of the images in HTML output.  Can you suggest a workaround?

http://stackoverflow.com/questions/14675913/how-to-change-image-size-markdown

**Comment by mortenpi** [comment]
The `![]()` syntax doesn't support image size. However, you should be able to use the `@raw` block to insert custom HTML with an `<img>` tag as follows:

````markdown
```@raw html
<img src="..." height="..." width="...">
```
````

**Comment by denizyuret** [comment]
Thanks!

**Comment by timholy** [comment]
What if you want to put the image in a table? I tried this:
```md
| Color separations & SVD |
|-------------------------|
| ```@raw html <img src="assets/demos/color_separations_svd.jpg" alt="svd" width="200"/>``` |
```
but got this in the rendered document:
![image](https://user-images.githubusercontent.com/1525481/46480974-ec2b3f80-c7b7-11e8-979e-e5fabcdd4529.png)

(Yes, I know it's silly to use a table for one image, but this will be a placeholder for more "thumbnails".)

**Comment by Evizero** [comment]
one possibility would be to just do the whole table in html

```
<table>
  <tbody>
    <tr>
      <th>Header1</th>
      <th>Header2</th>
    </tr>
    <tr>
      <td>row1 content1</td>
      <td>row1 content2</td>
    </tr>
    <tr>
      <td>row2 content1</td>
      <td>row2 content2</td>
    </tr>
  </tbody>
</table>
```

----

i use this workaround to mix html with markdown. Its the opposite of your use-case though.

````
```@raw html
<table><tbody><tr><td style="text-align: left;">
```

```@contents
Pages = ["losses/distance.md"]
Depth = 2
```

```@raw html
</td><td>
```

![distance-based losses](https://rawgithub.com/JuliaML/FileStorage/master/LossFunctions/distance.svg)

```@raw html
</td></tr></tbody></table>
```
````

for 

<img width="691" alt="imgtable" src="https://user-images.githubusercontent.com/10854026/46481875-9aed7100-c7f4-11e8-9ae1-eef05c620447.png">

(see http://juliaml.github.io/LossFunctions.jl/stable/#Loss-Functions-for-Regression-1)

**Comment by Evizero** [comment]
also note. if it is something repetitive (in the sense that you have a lot of those tables with fixed sized images) you can also just set the width in a custom `.css` file

e.g. 

```
table td img {
    width: 200px;
}
```

i do something like that here: http://juliaml.github.io/LossFunctions.jl/stable/losses/distance/

**Comment by timholy** [comment]
Cool. I am hoping to replicate something like http://scikit-image.org/docs/stable/auto_examples/ for JuliaImages. Time to learn CSS & HTML!

**Comment by kbarros** [comment]
> The ![]() syntax doesn't support image size. However, you should be able to use the @raw block to insert custom HTML with an <img> tag

Note, however, that switch to `@raw` HTML can subtly change the meaning of relative URL paths. See also:
- https://github.com/tlienart/LiveServer.jl/issues/158
- https://github.com/JuliaDocs/Documenter.jl/issues/921
