### ISSUE TITLE
@ref links to Julia docs

### ISSUE THREAD

**Issue by denizyuret** [JuliaDocs/Documenter.jl#425]
I am almost done porting all of Knet docs to Documenter, so far a great experience, thanks for an awesome utility!

Knet overloads a lot of Julia Base functions, which I want to refer to in the docs.  Is there an easy way to automatically generate links for them to point to Julia docs from Knet docs?

**Comment by mortenpi** [comment]
This is not supported at the moment and would be tricky to support since each package and the julia manual are built and hosted separately. That is, there's no way to resolve the `@ref` link to an external URL when building docs for a package.

**Comment by denizyuret** [comment]
Good point, thanks!

**Comment by goerz** [comment]
This is now possible with [`DocumenterInterLinks.jl`](https://github.com/JuliaDocs/DocumenterInterLinks.jl). Although, until #2366 is accepted and Julia then moves to a future Documenter release that automatically writes inventories, you would have to manually use [this inventory file for Julia 1.10](https://github.com/JuliaDocs/DocumenterInterLinks.jl/blob/master/docs/src/inventories/Julia.toml). It would allow you to put [something like](https://github.com/JuliaDocs/DocInventories.jl/blob/0e4a161b068539003c6f54c7b819558d23086276/src/inventory.jl#L89-L90)

```
* [`sort(inventory)`](@extref Julia Base.sort) – convert an unsorted inventory
  into a sorted one.
```

into your docstrings.
