### ISSUE TITLE
Build not triggered after pushing to GitHub

### ISSUE THREAD

**Issue by juliohm** [JuliaDocs/Documenter.jl#427]
This happened in the past, but I don't understand what is the cause now, I have pushed various commits this week to my package and the documentation was not updated:

https://github.com/juliohm/ImageQuilting.jl

Can you please help me understand what is happening?

**Comment by mortenpi** [comment]
Documenter is skipping the deployment for some reason. Could you please set `DOCUMENTER_DEBUG` environment variable to `true` on Travis and re-run the latest linux 0.5 build?

**Comment by juliohm** [comment]
The only difference I remember now is that I used GitHub Releases and [Attobot](https://github.com/attobot/attobot) to trigger the build and the pull request to METADATA. It shouldn't be an issue though.

I added the environment variable `DOCUMENTER_DEBUG` with the value `true` and restarted the build.

**Comment by mortenpi** [comment]
Ah, you're using the old `GITHUB_API_KEY` method to give Documenter access to the repo. That was deprecated a while back (not fine grained enough) and was removed completely on Jan 29. You need to set up a new SSH key. There's more info here: https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html#SSH-Deploy-Keys-1

Once that's working you should probably also remove the old token from you list [access tokens](https://github.com/settings/tokens).

**Comment by juliohm** [comment]
So the short key generated by `Travis.genkeys` is just the number in the middle after `ssh-rsa` and before the `user@hostname` markers, correct?

**Comment by juliohm** [comment]
Nevermind, GitHub asks for the whole thing. Moving with the process...

**Comment by juliohm** [comment]
Now I am getting an unrelated build error, I will report it in `SimpleTraits.jl`: https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/200428164

**Comment by juliohm** [comment]
Problem solved, thank you @mortenpi. Can you please confirm I can delete the GITHUB_API_KEY from my GitHub account? The new Documenter.jl only uses the DOCUMENTER_KEY variable, correct?

**Comment by mortenpi** [comment]
Good to hear! Yes, you can remove `GITHUB_API_KEY` and you should probably remove the corresponding token from GitHub as well. Can be done on the [access tokens page](https://github.com/settings/tokens) I think.

**Comment by juliohm** [comment]
Thanks, doing it :)
