### ISSUE TITLE
How to move 'stable' build to most recent release

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#430]
For some reason (probably something I've done :)) my recent ["stable" doc build](https://github.com/JuliaGraphics/Luxor.jl/tree/gh-pages) hasn't been updated to reflect the most recent release. It appears to be stuck on the previous release.

How can I 'bump' the 'stable' build so that it reflects the last released version? 

|release | commit | date|                   docbuild|
|---         |---           |---                       |---|
|latest    |fcf2aac    |2 days ago          |“latest” docbuild based on fcf2aac 2 days ago |
|v0.8.0   |87c0c97  |3 days ago         |?|
|             |                |                           |“stable” docbuild based on 43997ff 25 days ago|
|v0.7.5   |43997ff    |25 days ago       |“v0.7.5” docbuild based on 43997ff 25 days ago|
|v0.7.1   |8398d44  |5th Jan               |“v0.7.1” docbuild based on 8398d44 2 months ago|

**Comment by mortenpi** [comment]
I see that you have 0.8.0 tagged, but it seems that it never triggered a build on Travis. Normally each new tag will trigger a build and that will deploy the docs to `vX.Y.Z` and latest.

**Comment by cormullion** [comment]
@mortenpi is there a way of pushing a doc build to "stable" at this point, though?

**Comment by mortenpi** [comment]
If you manage to run the build for the 0.8.0 tag, it should push to stable. Not sure why travis missed the tag in this case though.

**Comment by cormullion** [comment]
Ok, thanks. It will fix itself before too long anyway...

**Comment by mortenpi** [comment]
I noticed that the latest commit on the `v0.8.0` tag has a `[ci skip]` in the commit message -- this is likely the reason Travis decided to ignore this tag.

**Comment by cormullion** [comment]
Yes, I cancelled that one but then the previous one a few minutes before decided to fail... :) It looks like it can't be fixed now.
