### ISSUE TITLE
Suggestion: Give basic advice and O(n) figures for collections

### ISSUE THREAD

**Issue by mark-summerfield** [JuliaDocs/Documenter.jl#437]
On page http://docs.julialang.org/en/latest/stdlib/collections.html
The collections APIs are documented but there doesn't seem to be any introduction saying here are the std. lib. collection types and here is their performance for insert/update/find/delete plus some basic advice on which to use.

**Comment by mortenpi** [comment]
Problems with the Julia manual should be reported on [Julia's main issue tracker](https://github.com/JuliaLang/julia/issues). Documenter.jl is used to generate the HTML pages of the docs, so only technical issues with the docs should be reported here. Julia's manual pages and docstrings reside in the main repository.

I'll close this here and the same applies to #438, #439 and #440. But please do report them on the main tracker.
