### ISSUE TITLE
round() docs don't explain use of negative digits

### ISSUE THREAD

**Issue by mark-summerfield** [JuliaDocs/Documenter.jl#438]
In http://docs.julialang.org/en/latest/stdlib/math.html
There is no explanation or example of using a negative number of digits:
```
x = 12345.6789
for i in (3, 2, 1, 0, -1, -2, -3)
       println(round(x, i))
       end
12345.679
12345.68
12345.7
12346.0
12350.0
12300.0
12000.0
```

**Comment by mortenpi** [comment]
ref https://github.com/JuliaDocs/Documenter.jl/issues/437#issuecomment-284844176
