### ISSUE TITLE
docs for zip() should say it stops when first of its iters is exhausted

### ISSUE THREAD

**Issue by mark-summerfield** [JuliaDocs/Documenter.jl#439]
In http://docs.julialang.org/en/latest/stdlib/iterators.html
the docs for zip() don't say that it stops when the first of its iters is exhausted; I think this ought to be mentioned.

**Comment by mortenpi** [comment]
ref https://github.com/JuliaDocs/Documenter.jl/issues/437#issuecomment-284844176
