### ISSUE TITLE
Suggestions: Add index pages

### ISSUE THREAD

**Issue by mark-summerfield** [JuliaDocs/Documenter.jl#443]
Although the current manual is on its way to being adequate for learning the basics of Julia, it is let down by poor search -- and the lack of index pages.

I suggest that every manual page should have three new links just above or just below the Search: Built-ins, Functions, and Types.

The Built-ins link should be to a page that lists every built in function, type, exception, etc., in alphabetical order (regardless of type and with symbols first) in the form:

nameOfFunction|Type|etc One line description with link to full docs

The Functions link should be to a page that lists every function (starting with those that have symbol names, then A-Z) of the form:

symbol|functionName Type1 Type2 ... TypeN

where the Types are in alphabetical order and each Type is a link to the docs for that function for that type.

The Types link should be to a page that lists every type in alphabetical order in the form:

TypeName Module One line description of the Module

where the Module is a link to the documentation of the Module which defines the type. 

Having these index pages will be very useful for people who have learnt enough Julia to know pretty well what they want but who find lists of links quicker and more reliable than searching.

**Comment by mortenpi** [comment]
Would it be possible for you to create a simple mockup of what you are proposing by any chance? Making things easier to find would definitely be a good thing, so we could definitely consider something like this.

**Comment by mark-summerfield** [comment]
Attached is a mock-up of the suggested Built-ins page.
[jbuiltin.html.zip](https://github.com/JuliaDocs/Documenter.jl/files/830233/jbuiltin.html.zip)
 
I'll try to do a mock-up of the Types page tomorrow.

As for the Functions page, that's much trickier than when I first thought about it because of Julia's multiple dispatch. So I'll have to think about that a bit more.

**Comment by mark-summerfield** [comment]
I've given this more thought and can't figure out a way to have a functions index that would actually be useful.

So here's my revised suggestion.

Immediately above or below the Search have a Modules link to a single (big) page listing every Julia module (plus the Built-ins page I provided a mock-up of as a pseudo-module). As for its design, Python's module index is an excellent example of how it could be done: https://docs.python.org/3/py-modindex.html

**Comment by mortenpi** [comment]
Probably having a single index page would be helpful indeed. Documenter already has an `@index` block actually, and Documenter's documentation has index pages ([public](https://juliadocs.github.io/Documenter.jl/latest/lib/public.html#Index-1) and [private](https://juliadocs.github.io/Documenter.jl/latest/lib/internals.html) methods). Something similar could be done in the manual perhaps, and might not be too hard to achieve with what we have already.

**Comment by odow** [comment]
Closing in favor of https://github.com/JuliaDocs/Documenter.jl/issues/2133
