### ISSUE TITLE
Doctest "apply fix" flag

### ISSUE THREAD

**Issue by tkelman** [JuliaDocs/Documenter.jl#448]
e.g. an official API that accomplishes the same thing as @vtjnash's patch from https://github.com/JuliaLang/julia/pull/20417 in a way you could request with a flag

**Comment by mortenpi** [comment]
Do you think it would be sufficient to have this available as a branch? I have the patch applied on the [`fix-doctests`](https://github.com/JuliaDocs/Documenter.jl/tree/fix-doctests) branch.

For users, this is a one-off thing, so:
```julia
Pkg.checkout("Documenter", "fix-doctests")
# run `julia docs/make.jl` on your package
Pkg.free("Documenter")
```

**Comment by tkelman** [comment]
That's a bit messy to incorporate in a makefile, I was hoping it could be made to work as its own makefile target (via a command line argument to make.jl, most likely)

**Comment by mortenpi** [comment]
Ah, I got confused -- I thought this would be for just the one change referred to in that issue. But doctests likely become outdated in the future as well. Yep, this would be nice to have. Another keyword argument should probably do the trick.

**Comment by tkelman** [comment]
I'll note that I've seen the code in https://github.com/JuliaDocs/Documenter.jl/commit/b376bc61a813c608d5088ea648c36c6e31aadb2c do slightly the wrong thing. If there are two cases of the same output in the same file, but one gets triggered by code that has changed and another gets triggered by code that hasn't, then the find-replace will replace both, trading one doctest failure for another. Adding some context lines around the searched-for string should make this less likely.
