### ISSUE TITLE
Documentation not generated if master branch is protected

### ISSUE THREAD

**Issue by tpoisot** [JuliaDocs/Documenter.jl#451]
I protect the master branch so that code only comes up with pull requests. At the moment, this makes it impossible for documenter to generate the documentation.

**Comment by mortenpi** [comment]
Are you attempting to deploy to `master`? Documenter is designed to be used with the `gh-pages` branch. Generated files shouldn't really be committed to master, I'd say.

**Comment by tpoisot** [comment]
Nevermind, I shouldn't open issues before ☕️
