### ISSUE TITLE
Atsign-meta block in the middle of a "named doctest" series 

### ISSUE THREAD

**Issue by timholy** [JuliaDocs/Documenter.jl#455]
Over at [GtkReactive](https://github.com/JuliaGizmos/GtkReactive.jl) I've tried to insert a [`@meta` block in the middle of a sequence of "named `jldoctest`" blocks](https://raw.githubusercontent.com/JuliaGizmos/GtkReactive.jl/master/docs/src/index.md) (search for `@meta`); this is to simulate a user manipulating an on-screen widget. 

To be sure that this is a Documenter.jl issue and not a consequence of asynchronous Reactive.jl updates, I've pasted a simple repro [in this gist](https://gist.github.com/timholy/f7dfd32f0950ac14882d7203b9bcbd18). To test this, you have to build the directory structure manually.
I tried attaching the `demo1` name to that `@meta` block, but it didn't work.

**Comment by KristofferC** [comment]
Don't you need to simply do:

```
DocTestSetup = quote
    y = 2
end
```
?

**Comment by KristofferC** [comment]
This can probably be closed?

**Comment by fredrikekre** [comment]
Can either be done as Kristoffers comment above, or using a kwarg to the doctest (#650):
````
```jldoctest demo1
julia> x = 1
1
```

```jldoctest demo1; setup = :(y = 2)
julia> x + y
3
```
````
