### ISSUE TITLE
Require Documenter's minor version to be fixed

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#460]
Currently Documenter deployments usually just have
```
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("PACKAGE_NAME")); include(joinpath("docs", "make.jl"))'
```
in their `.travis.yml` file (recommended by the docs). Therefore on every Travis run the latest Documenter available in METADATA gets installed.

This means that currently it is impossible to make breaking changes to Documenter without breaking existing deployments. This came up recently when the old authentication methods were removed -- we ended up with quite a lot of documentation builds failing. A likely near-future breaking change would be switching to having the native HTML output be the default. The issue is further compounded by the fact that it's basically impossible to notice any deprecation warnings or doc build failures on Travis.

We could therefore strongly recommend that people fix the minor version of Documenter in their deployments. Sure, they would have to keep an eye on Documenter's releases and update manually, but it would be better than broken builds.

We could achieve this by recommending using `Pkg.add("Documenter", v"x.y", v"x.(y+1)-")` in `.travis.yml`, so that the deployments would only receive patch-level updates automatically.

It might be worth going one step further -- Documenter could enforce this, unless the user explicitly requests that automatically updating minor and major versions is what they want. One potential way would be to have a `Documenter.versioncheck(v"x.y")` API, which we would guarantee to remain constant even through major versions. Documenter would then refuse to run unless the installed version matches. Alternatively, if we could somehow have custom `docs/REQUIRE` files, then Documenter could check that to see if Documenter is fixed to a specific minor version.

@tkelman I would kindly ask for your thoughts on this, since I think you have a good feel for the Julia ecosystem as a whole.

Edit: related [Discourse thread](https://discourse.julialang.org/t/rfc-requiring-documenter-jl-minor-version-to-be-fixed/3243)

**Comment by tkelman** [comment]
Modifying the Pkg.add lines in existing .travis.yml files requires the fewest changes here. It's not that difficult to programmatically look at the.travis.yml files across all existing registered packages, or even make large numbers of automated pr's.

**Comment by fredrikekre** [comment]
This is now recommended in the docs.
