### ISSUE TITLE
Upgrade dependency on highlight.js

### ISSUE THREAD

**Issue by ararslan** [JuliaDocs/Documenter.jl#465]
In about 5 weeks from this writing, highlight.js will tag a new version that will include updates for new Julia 0.6 syntax as well as an alias for `jldoctest`, which will fix #385. This issue is to remind folks to bump the version of highlight.js to 9.12.0.

The author of highlight.js said that they only do releases once every 6 weeks and that if we need the updated Julia definitions sooner then we could go from the master branch. Would it be possible to set up Documenter to use highlight.js master, at least until a new version is available?

**Comment by mortenpi** [comment]
Is `jldoctest` just an alias for `julia`? I am wondering whether (in theory) only the code line should get highlighted in doctests. E.g. whether maybe the output of the `println` below shouldn't get highlighted

```julia
julia> println("function foo end")
function foo end
```

As for master, I think we would have to bundle the `.js` and `.css` file then (i.e. drop copies into our `assets/` directory here), and then just switch back to the CDN once 9.12 is out. Definitely doable, but I am wondering whether it's worth it, since it's just a few weeks. But if there's a PR I wouldn't oppose it.

**Comment by ararslan** [comment]
> Is `jldoctest` just an alias for `julia`?

Yes. Not entirely ideal, but otherwise we have to duplicate the Julia definitions in highlight and make changes in two places whenever a syntax update or whatever is needed. We would still need the full set of Julia definitions to be able to properly highlight on the REPL prompt lines. This seems like the most workable solution IMHO, at least for now.

> I am wondering whether it's worth it, since it's just a few weeks.

Normally I'd agree, but in this case I think it would be good to have the 0.6 release docs have proper highlighting upon initial release, and that should be happening soon.

**Comment by mortenpi** [comment]
Yup, that's a good point. I've [implemented the change](https://github.com/mortenpi/Documenter.jl/tree/bundle-highlightjs) on Documenter's side (although I might want to do a bit more cleanup with the way we handle the different assets internally). Could you by any chance build the highlight.js library from master (I don't have Node.js installed etc.), add a commit to that branch and do a PR?

As for `jldoctest` -- yup, but I am wondering if we actually need the alias at all then. We could just apply `language-julia` on Documenter's side. However, if we'd in principle like to have a separate highlighter for the REPL/doctest code blocks, then I think it is worth having it as a placeholder.

On a small bikeshedding note though -- is `jldoctest` the best label actually? Perhaps `julia-repl` or something. It's possible that one might want to highlight REPL examples that are not actually doctests ([e.g. as it is under IO in the manual](https://docs.julialang.org/en/latest/manual/networking-and-streams.html#Basic-Stream-I/O-1)), and we can have [script-type doctests](https://juliadocs.github.io/Documenter.jl/stable/man/doctests.html#"Script"-Examples-1) that should be displayed as normal code.

**Comment by ararslan** [comment]
> Could you by any chance build the highlight.js library from master (I don't have Node.js installed etc.), add a commit to that branch and do a PR?

I also don't have Node installed but it's as easy as `brew install node` for me. 🙂 What is it that I should commit to that branch?

> is jldoctest the best label actually?

The benefit of this name is that it clearly denotes doctests, and the jl ensures that it isn't confused with something like https://github.com/onqtam/doctest (which btw is awesome). Though if there's a separate highlighting definition for the REPL, we could have a `julia-repl` for non-tests and `julia-repl-test` that uses the `julia-repl` definition but also runs doctests, then `julia` for the regular definition and `julia-test` for the script tests.

**Comment by mortenpi** [comment]
> The benefit of this name is that it clearly denotes doctests

If we need to e.g. apply specific styling to doctests, I'd be happy to have a separate class for them. However, my issue is that a doctest is not a particular language/syntax to be highlighted, so highlighter shouldn't be concerned with it, and we shouldn't be applying `language-jldoctest` class to those `<code>` tags.

By the way, I think it was me initially who suggested that highlight.js should have the `jldoctest` in the first place -- I didn't really think it through then clearly, so I'm reversing my position on that now :laughing:

But there are, in principle, two different syntaxes -- one for ordinary Julia code, and then the other for console-type code (which the output from most, but not all, doctests is).

I noticed that in [Atom's `language-julia` plugin](https://github.com/JuliaEditorSupport/atom-language-julia/tree/master/grammars) there is precedence in separating these two syntaxes: `julia` and `julia-console`. `julia-console` console seems to be adding highlighting to the single line of code after `julia>` and then the following lines are not highlighted.

Should highlight.js perhaps be consistent with that? I'd be fine with the `julia-console` being just an alias for the time being, and not actually being implemented, but I think it would be useful to apply a semantically correct `language-*` class to the console-like code blocks.

**Comment by mortenpi** [comment]
Also, [Pygments](http://pygments.org/) has a "Julia console" lexer apparently. Their short name for it `jlcon` (I think that's a bit too brief).
