### ISSUE TITLE
Issue when searching with a space (i.e. with many words)

### ISSUE THREAD

**Issue by jebej** [JuliaDocs/Documenter.jl#471]
When searching with multiple words and hitting enter, spaces between the words are replaced with plus signs, which makes the search fail. Tested on chrome.

Since the search is instantaneous, it might just be a matter of ignoring the enter keypress event.

**Comment by mortenpi** [comment]
Yup, can confirm, thanks for catching this. It should be fixed though, not worked around, since you probably often enter the search query on a normal page (and then have to press enter to get to the search page).
