### ISSUE TITLE
Completely fails if a function doesn't have a comment

### ISSUE THREAD

**Issue by essenciary** [JuliaDocs/Documenter.jl#474]
If I accidentally add a function name within a `@docs` block and the function does not have a comment at all, everything fails and no documentation is generated for any of the functions. In my opinion it should output a warning to standard output and carry on.

**Comment by mortenpi** [comment]
Warnings are easy to miss I'd say, especially in Travis builds. Names without docstrings cannot at all be spliced into the documentation, so having a reference to such a function is a pretty big error. So to me failing to build feels appropriate here and I don't see a big problem in having to clean up the docs after removing a docstring from a name.

**Comment by essenciary** [comment]
Sure, but then what about providing a helpful error message? 

In my case it was a pretty bad first experience. It was my first time using the package in a fairly large and complex module with multiple includes. Nothing happened so I didn't know what expect... was Documenter broken, did I encounter a bug or limitation? In the end I went over the functions list, eliminating them one by one, to see what gives - and after a lot of trial and error I figured out which function had which problem.

**Comment by essenciary** [comment]
Let me run some more tests and get back to you with more details. 

Till then, I just wanted to say that the package is amazing, in terms of features and flexibility. I'm now setting up doc hosting for my packages and I love it. Truly a gem in the Julia ecosystem! 👏
