### ISSUE TITLE
@setup block do not affect the following @repl block

### ISSUE THREAD

**Issue by iblis17** [JuliaDocs/Documenter.jl#477]
Hi,
I'm working on the doc of [MarketTechnicals.jl](https://github.com/JuliaQuant/MarketTechnicals.jl).
But cannot get @setup block work with @repl block.

reproduction steps:
1. clone https://github.com/JuliaQuant/MarketTechnicals.jl
2. apply this patch https://gist.github.com/iblis17/802b0d5387d286c1aeb421d1b1719f53
3. `cd docs && make`
4. checkout the rendered `momentum.html`, got something like this in the page
```
julia> macd(cl)
ERROR: UndefVarError: macd not defined
```

**Comment by mortenpi** [comment]
Fixed by #617.
