### ISSUE TITLE
What's the theme of the Documeter.jl?

### ISSUE THREAD

**Issue by memoiry** [JuliaDocs/Documenter.jl#478]
Hi all

I really like the documentation theme of documenter.jl itself in https://juliadocs.github.io/Documenter.jl/, but I found nothing related to this kind of theme after searching for mkdocs theme. Can anyone please provide some information? 

Thanks!

**Comment by memoiry** [comment]
I have found the answer, thanks!

**Comment by mortenpi** [comment]
For future reference to others: Documenter's HTML builds have a custom theme ([`assets/html/documenter.css`](https://github.com/JuliaDocs/Documenter.jl/blob/master/assets/html/documenter.css)) that doesn't interoperate with MkDocs.
