### ISSUE TITLE
Better handling of tagged versions in deploydocs

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#482]
E.g. `-rc*` tags shouldn't deploy to `stable/`.

Ref: JuliaLang/julia#21846

**Comment by huckl3b3rry87** [comment]
Is this related to easily being able to delete old tagged versions?

For instance in my package, there are several tagged versions of the docs
https://juliampc.github.io/MPCDocs.jl/stable/

and I would like to delete all of them but one. Is this possible?

**Comment by mortenpi** [comment]
Not really related. Although we might have

If you are certain you want to get rid of the old versions of the docs then you could edit the `gh-pages` branch of the repo yourself and just delete them. You should also remove them from the `versions.js`, although this would get updated automatically on the next deploy as well.

**Comment by mortenpi** [comment]
Also, when a bugfix is released on an older minor branch, it overwrites `stable/` (e.g. say the highest tag is 0.5.1, but 0.4.5 gets released). Thanks @fredrikekre for bringing this up.

**Comment by mortenpi** [comment]
Fixed by #708.
