### ISSUE TITLE
Undefined binding

### ISSUE THREAD

**Issue by juliohm** [JuliaDocs/Documenter.jl#489]
Could you please help in figuring out why the docstrings for `fit!` and `weights` are not found?

https://github.com/juliohm/GeoStats.jl/blob/master/src/estimators.jl#L22-L34

I am getting warnings that say:
>Documenter: setting up build directory.
Documenter: expanding markdown templates.
 !! Undefined binding 'fit!'. [src/estimation.md]
 !! Undefined binding 'weights'. [src/estimation.md]
Documenter: building cross-references.
Documenter: running document checks.
 > checking for missing docstrings.
 > running doctests.
 > checking footnote links.
Documenter: populating indices.
Documenter: rendering document.
Documenter: skipping docs deployment.
  You can set DOCUMENTER_DEBUG to "true" in Travis to see more information.

**Comment by mortenpi** [comment]
Those functions are not exported, right? So I don't think they exist in `make.jl`'s global scope right now for Documenter to find. You could refer to them with the full name in the `@docs` blocks (e.g. `GeoStats.fit!`).

**Comment by juliohm** [comment]
Indeed! I completely missed that detail, thank you @mortenpi.
