### ISSUE TITLE
```@repl block inside !!! note doesn't show output

### ISSUE THREAD

**Issue by shashi** [JuliaDocs/Documenter.jl#491]
`@repl` block inside an `!!! note` is neither stylized as the REPL nor is the output shown. Is this intended?

**Comment by mortenpi** [comment]
Can confirm. Other special blocks seem to be ignored in admonitions as well. Thanks for the report!

**Comment by mortenpi** [comment]
I'm rather sure that the issue comes from [`src/Expanders.jl#L25-L32`](https://github.com/JuliaDocs/Documenter.jl/blob/6445adc41b1c27aa00f0784ca64571aefca9d339/src/Expanders.jl#L25-L32) -- the expander functions are only called on top-level blocks, and not recursively through the AST.

**Comment by nluetts** [comment]
I just stumbled upon the same problem---is it not resolved yet? Or is there a workaround?

**Comment by KristofferC** [comment]
>  the expander functions are only called on top-level blocks, and not recursively through the AST.

Even if you call it recursively throughout the AST that is not enough. You will get an expanded block entered into `page.mapping` but that will not be used by the renderer. You probably need to propagate this mapping all the way down to `mdconvert`.

**Comment by ettersi** [comment]
I'd really like to see this fixed, and I'm happy to give a hand doing so. However, since there have already been two attempts which seem to eventually have run out of steam, I thought I'd ask for some input first on what people think would be the best way to resolve this.

**Comment by KristofferC** [comment]
Is there anything wrong with https://github.com/JuliaDocs/Documenter.jl/pull/1747?

**Comment by mortenpi** [comment]
#1747 contains some unnecessary changes as far as I can tell. But I think the general approach there (create a new expander step that recurses for certain elements, but only calls as subset of expander steps then) is good. It needs to be updated to the new MarkdownAST-based tree though. @ettersi I'd say you're welcome that adopt that PR finish it up if you'd like.

**Comment by ettersi** [comment]
What's the recommended way to "adopt" a PR? I believe I can't fork a PR. I can of course create a new PR, but that would erase @jmert from the history, which doesn't seem fair.

**Comment by mortenpi** [comment]
You'd have to start a new PR on your fork, but you can use their latest commit as a starting point (although, it might be easier to just re-do it from scratch, since merging with master might be more work at this point). One way or another, I'll make sure that there is a `Co-Authored-By` in the commit message when we merge.

**Comment by ettersi** [comment]
Done: https://github.com/JuliaDocs/Documenter.jl/pull/1970
