### ISSUE TITLE
Problem when search query contains characters like `@` and `!`

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#494]
Searching for e.g. `@inbounds` or `push!` in the documentation doesn't work correctly.

(https://github.com/JuliaLang/julia/issues/20363 and https://github.com/JuliaLang/julia/issues/20828)

**Comment by mortenpi** [comment]
Search needs a lot of work, there's also e.g. #471. And also the way the results are displayed etc. could use some redesign. But this is very much up for grabs, I don't think I'll be able to get to it any time soon to be honest.
