### ISSUE TITLE
Use a different monospace font

### ISSUE THREAD

**Issue by shashi** [JuliaDocs/Documenter.jl#504]
Ubuntu Mono doesn't typeset ASCII tables properly

see http://www.david-anthoff.com/Query.jl/stable/querycommands.html

I'm using Source Sans Pro in juliadb.org (see http://juliadb.org/latest/assets/custom.css)

Also, it would be nice to allow setting the fonts in the config file since you load the fonts in the generated HTML anyway.

Cheers!

**Comment by mortenpi** [comment]
Since [v0.11.0](https://github.com/JuliaDocs/Documenter.jl/releases/tag/v0.11.0) (released about week ago) we're on Roboto Mono. Original discussion for that change: #461.

**Comment by mortenpi** [comment]
As for setting the fonts yourself -- that should be done in a custom CSS file, as you are doing. I don't think it would make sense to have this as a separate option. Via the `assets` argument you can add in additional `<link>` tags if you don't want to use `@import` (using `<link>`s seems generally better).

The only downside is that you can't stop the default fonts from being CDNed in that way (i.e. you can't get rid of the default `<link>` tags at the moment).

**Comment by shashi** [comment]
Ah, neat! Thanks, sorry I should have looked at the recent version before asking.

> The only downside is that you can't stop the default fonts from being CDNed in that way

I guess I can live with that.
