### ISSUE TITLE
Justification of Table Columns

### ISSUE THREAD

**Issue by ccoffrin** [JuliaDocs/Documenter.jl#511]
It seems like the right-side justification on tables is not working.  For example see, https://lanl-ansi.github.io/PowerModels.jl/latest/results.html

Also I noticed that the bold directive does not seem to work on this page.  Both in the body of the text and in the table header.

The bold directive is recognized by github's markdown renderer, https://github.com/lanl-ansi/PowerModels.jl/blob/8d6ffb0dad80be64255d28d16afbff0c9c9e3c94/docs/src/results.md

**Comment by mortenpi** [comment]
Hmm, it appears the HTML writer does not honour alignment at all. It actually came as a surprise to me that cells should be right-aligned by default according to [Base docs](https://docs.julialang.org/en/latest/manual/documentation/#Tables-1). Generally most Markdown table implementations seem to left-align. But in any case, Documenter should simply follow Base here.

Bold looks fine to me though. 
![just](https://cloud.githubusercontent.com/assets/147757/26765985/95d0702a-49db-11e7-9802-9166f5bfb060.png)

**Comment by ccoffrin** [comment]
I also tried `---:` to force right alignment, but it did not seem to help.  As for the bold goes, this is what I am seeing on Chrome Version 58.0.3029.110 (64-bit) on OS X 10.11.6

![screen shot 2017-06-04 at 5 35 38 pm](https://cloud.githubusercontent.com/assets/1105578/26766321/51bd4276-494c-11e7-951d-73fd7b0a006d.png)

**Comment by mortenpi** [comment]
> I also tried `---:` to force right alignment, but it did not seem to help.

Yup, those get ignored in `HTMLWriter` as well.

As for bold: that is interesting. I would guess it is somehow specific to your system though. Would still be good to know what is going on -- could you maybe go in with Chrome devtools and see why the appropriate CSS is not being applied? Do you see the same thing in Safari?

**Comment by ccoffrin** [comment]
Works in Safari 10.1.1 (11603.2.5) on the same computer.  I took a quick glance via chrome inspect, but the CSS is out of my depth and it was not immediately clear to me what was going on.

**Comment by juliohm** [comment]
Is it possible to fix this column alignment or is it something beyond Documenter.jl?

**Comment by scls19fr** [comment]
Center alignment doesn't work also:

```
| object | implemented |  value |
| :---   |    :---:    |   ---: |
| `A`    |      ✓      |  10.00 |
| `BB`   |      ✓      | 100.00 |
```
is rendered as (in Github)

| object | implemented |   value |
| :---   |    :---:    |    ---: |
| `A`    |      ✓      |  $10.00 |
| `BB`   |      ✓      | $100.00 |

but in Documenter.jl it's rendered like:
![deepin capture-ecran_zone de selection _20180823102557](https://user-images.githubusercontent.com/109167/44513927-0523d980-a6bf-11e8-807c-2d050c6f7c77.png)
