### ISSUE TITLE
Document `@raw` block

### ISSUE THREAD

**Issue by omus** [JuliaDocs/Documenter.jl#516]
I discovered the `@raw` block from this [comment](https://github.com/JuliaDocs/Documenter.jl/issues/423#issuecomment-279193192). It should probably be documented in the [syntax section](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/).

**Comment by omus** [comment]
Additionally, it would be nice if you could inline a `@raw` block. Probably would look something like:

````
```raw html; <strong>foo</strong>```
````

**Comment by bicycle1885** [comment]
👍 👍 👍  I thought it was impossible to use HTML but I accidentally found it can be written like `@raw html`.

**Comment by mortenpi** [comment]
This was fixed in #648.

https://juliadocs.github.io/Documenter.jl/latest/man/syntax/#@raw-format-block-1
