### ISSUE TITLE
search for "get" in Julia stable documentation (0.6.0): No Result

### ISSUE THREAD

**Issue by strickek** [JuliaDocs/Documenter.jl#520]
[https://docs.julialang.org/en/stable/search/?q=get](https://docs.julialang.org/en/stable/search/?q=get)

**Comment by mortenpi** [comment]
Search could use quite a bit of work overall. The index we're generating is far from perfect, and maybe we should swap out the js library for something else. If someone wants to take this on it would be greatly appreciated.
