### ISSUE TITLE
Guide should say that mkdocs.yml is optional

### ISSUE THREAD

**Issue by nalimilan** [JuliaDocs/Documenter.jl#525]
The guide [shows](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#The-MkDocs-mkdocs.yml-File-1) an example of a `mkdocs.yml` file to add to the repository, but AFAICT it is completely optional and the default works well. If that's the case, the guide should mention it.

**Comment by mortenpi** [comment]
It's not optional -- on the default Markdown backend it's mandatory. For HTML/LaTeX it's ignored.

**Comment by nalimilan** [comment]
Ah, what wasn't clear to me then is that it's not useful when you're using the HTML backend. Maybe that could be repeated?

**Comment by mortenpi** [comment]
The HTML backend is still not properly documented actually (my apologies). This would be another breaking change, but the goal is to get documented and then made as the default format.

**Comment by nalimilan** [comment]
OK, thanks. It works great anyway! :-)

**Comment by mortenpi** [comment]
The docs for the HTML and Markdown outputs have since been updated, so I don't think this is relevant anymore.
