### ISSUE TITLE
Make deploydocs(julia=...) mandatory

### ISSUE THREAD

**Issue by nalimilan** [JuliaDocs/Documenter.jl#526]
Currently the documentation is deployed from Julia nightlies by default. This isn't great since packages often do not build on Julia master. It would be better to deploy docs from the latest stable release. Currently it's annoying for packages to opt-out from nightlies, since they need to hardcode a given release, which can get of out date without being noticed (since it's in a different file from the other CI settings)

I'm not sure what's the best way to do that. It could work by retrieving the name of the latest Julia version from a website (or hardcoding it), and comparing it to the name of the build. But if a package does not build on that version (e.g. because the Travis CI config hasn't been updated to use it), the docs wouldn't be built at all. Maybe the Julia TravisCI script could set an environment variable only for the highest stable version?

**Comment by mortenpi** [comment]
#466 fixes this already. You have `julia: release` which is the best guess we can make, but the user has to have that in `travis.yml`. Otherwise the user has to specify the version by hand.  But it's a breaking change -- I'd like to check all METADATA packages before tagging a new version with that change.

**Comment by nalimilan** [comment]
Hadn't see that PR, thanks. A problem with this is that I think @tkelman plans to remove/discourage `release` since it's a moving target: packages which might not work on a release will suddenly start using it on CI, and an older release won't be tested anymore. I hope he can comment.

**Comment by mortenpi** [comment]
I didn't know that it might get removed, but I see the reasoning. I think in the end Travis build stages are the way to go -- this way it's up to `.travis.yml` to make sure that Documenter gets run only once.

**Comment by mortenpi** [comment]
So the way to go here is to have the user specify the `julia` argument explicitly, e.g. `julia = "0.6"`. #712 deprecates relying on the default value. At one point we'll disallow it altogether and the user's who haven't done so already need to update their `make.jl` files (#713).
