### ISSUE TITLE
Defining LaTeX commands in a single location for use throughout the docs

### ISSUE THREAD

**Issue by juliohm** [JuliaDocs/Documenter.jl#532]
As discussed on gitter, currently we have to retype `\newcommand` on every markdown file to get a notation that is consistent across documentation pages.

It would be interesting to have a single place where one can define all the LaTeX syntax in the docs.

**Comment by juliohm** [comment]
Any update on this issue with the latest Documenter.jl? :)

**Comment by fredrikekre** [comment]
No but it is trivial to implement if you want to.

**Comment by juliohm** [comment]
Do we have support for this in the new Documenter.jl?

**Comment by mortenpi** [comment]
Yes, we actually do. You can configure [KaTeX](https://juliadocs.github.io/Documenter.jl/stable/lib/internals/writers/#Documenter.Writers.HTMLWriter.KaTeX) & [MathJax](https://juliadocs.github.io/Documenter.jl/stable/lib/internals/writers/#Documenter.Writers.HTMLWriter.MathJax) in `make.jl` now. So for MathJax it should look something like this: 

```julia
makedocs(...,
    format = Documenter.HTML(...,
        mathengine = MathJax(Dict(
            :TeX => Dict(
                :equationNumbers => Dict(:autoNumber => "AMS"),
                # Custom Tex commands:
                :Macros => Dict(
                    :defd => "≝",
                    :ket => ["|#1\\rangle", 1],
                    :bra => ["\\langle#1|", 1],
                )
            )
        ))
    )
)
```

I'll downgrade this to a documentation issue.

**Comment by juliohm** [comment]
Nice to have this feature :+1:

**Comment by wsshin** [comment]
> ```julia
>                 :Macros => Dict(
>                     :defd => "≝",
>                     :ket => ["|#1\\rangle", 1],
>                     :bra => ["\\langle#1|", 1],
> ```
It seems that defining a new command like this works only for MathJax.  Is there an equivalent for KaTeX?

**Comment by mortenpi** [comment]
@wsshin Yes, it should be possible, although I do not have a snippet on hand. But you can pass a configuration dict to [`KaTeX()`](https://juliadocs.github.io/Documenter.jl/stable/lib/internals/writers/#Documenter.Writers.HTMLWriter.KaTeX) too, and [KaTeX accepts a `macros` option](https://katex.org/docs/options.html). Might be a little bit of trial and error to get it working exactly right, but you can double check the generated JS in `build/assets/documenter.js`.
