### ISSUE TITLE
Support REQUIRE file for specifying dependencies

### ISSUE THREAD

**Issue by juliohm** [JuliaDocs/Documenter.jl#534]
As discussed in gitter, it would be great to have some settings in `docs/make.jl` for taking documentation dependencies into account. For example, Plots.jl is often a dependency for `@example` blocks.

**Comment by mortenpi** [comment]
Possible API if we want to implement this in Documenter:

```
Documenter.resolvedeps([file = "REQUIRE"])
```

**Comment by juliohm** [comment]
Will there be any change regarding this idea in Julia v0.7 and the new package system?

**Comment by juliohm** [comment]
Thank you @fredrikekre , I already have a temporary solution, but looking forward to see how it works in Julia v0.7

**Comment by juliohm** [comment]
What is the status of this issue in Julia v1.0? Do we have better ways now with the new package manager to handle doc deps?

**Comment by fredrikekre** [comment]
Yes, use a docs project (https://github.com/JuliaDocs/Documenter.jl/blob/master/docs/Project.toml) and build docs as https://github.com/JuliaDocs/Documenter.jl/blob/8d19e7008e362e961efb8d22ade9a7a9e0b5aeee/.travis.yml#L19-L28

**Comment by juliohm** [comment]
Good news. I will wait then before I can understand how Project.toml files work. I am still using the REQUIRE approach while porting my packages to Julia 1.0
