### ISSUE TITLE
WARNING: deprecated syntax "_ as an rvalue around docs/Docs.jl:522".

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#538]
Not sure what causes this warning to appear in the finished documents (generated on Julia 0.6.0 on macOS)

![screen shot 2017-07-21 at 08 50 57](https://user-images.githubusercontent.com/52289/28454141-07944fe4-6df2-11e7-9612-224eb5eb4120.png)

It's only happening on Travis when the docs are generated though (they've made on macOS with Julia v0.6). Locally it doesn't happen.

**Comment by mortenpi** [comment]
They actually show up in the generated docs? Do you have a MWE by any chance? The error refers to [base/docs/Docs.jl#L522](https://github.com/JuliaLang/julia/blob/903644385b91ed8d95e5e3a5716c089dd1f1b08a/base/docs/Docs.jl#L522) as far as I can tell, but that's not too illuminating.

**Comment by cormullion** [comment]
Yes it appeared in some of the recent runs [here](http://juliagraphics.github.io/Luxor.jl/latest/moreexamples.html). I've no idea how I managed to trigger it though... :)

**Comment by cormullion** [comment]
Perhaps deprecation warnings could be diverted somewhere?

![screen shot 2017-07-27 at 12 35 51](https://user-images.githubusercontent.com/52289/28668605-8145304e-72c8-11e7-893b-cbc93aee15ea.png)

**Comment by mortenpi** [comment]
I was finally able to reproduce the issue in the OP. It comes from the precompilatin on the `using ColorSchemes` line. So it's appears to be a legitimate output, in principle. You should be able to reproduce it by removing `Colors.ji` from `.julia/lib/` (implying it's some package ColorScheme relies on I think).

I'm not sure we could really ignore any of the deprecation warnings. I suppose we could treat `import` and `using` statements in a special way by completely throwing away their output. It should be an option to the block though, i.e. you'd like to see the output by default.

Another workaround would be to import all the packages in `make.jl` -- this way precompilation happens before the `@example` blocks.

**Comment by cormullion** [comment]
Good sleuthing! I think there should definitely be an option to install/use packages "quietly", for when you're making documentation, with the ability to see them all if you needed to. It might be a few releases before we stop seeing so many deprecation warnings... :)

**Comment by juliohm** [comment]
@mortenpi I didn't quite understand what is causing the warning. Why can't it be solved right away?

**Comment by mortenpi** [comment]
There's an `@example` block with a `using ColorSchemes` statement, and the output is from there. The reason it's intermittent is that these deprecation warnings are only emitted during precompilation -- hence why it's showing up on Travis, where packages all need to be precompiled on every run, and not on your own computer, where they have already been precompiled before.

Importing the packages used in `@example` blocks in `make.jl` should get around this. Not much could be done on Documenter's side as far as I can tell.

**Comment by juliohm** [comment]
The warning also appears locally on user machines when they pre-compile a package for the first time. For example, users of my package are seeing this warning and asking me if they should be worried about it: https://github.com/juliohm/ImageQuilting.jl

**Comment by Evizero** [comment]
maybe related to https://github.com/JuliaImages/ImageFiltering.jl/pull/40 ?

**Comment by KristofferC** [comment]
Do `using` on each package you need in the `make` file. I think this can be closed since capturing the exact output seems to be what is intended.

**Comment by cormullion** [comment]
Fair enough. I’m still slightly inclined to the opinion that processing errors shouldn’t make it into the docs (see also https://github.com/JuliaMath/FFTW.jl/issues/46), like, say, LATEX processing warnings shouldn’t make it into the body of the output text...
