### ISSUE TITLE
DocChecks.missingdocs() complains about missing docstrings from external modules

### ISSUE THREAD

**Issue by fjarri** [JuliaDocs/Documenter.jl#542]
It is often convenient to define a constant with the value equal to some long module name, for example
    
    const BT = Base.Test

But when `Documenter` processes a file with such definition, it considers all the contents of such module to be internal and generates multiple warnings about missing docstrings:

    Documenter: running document checks.
     > checking for missing docstrings.
     !! 31 docstrings potentially missing:

        Base.Test.detect_ambiguities :: Tuple
        Base.Test.@test_approx_eq_eps :: Tuple{Any,Any,Any}
    ... and so on

According to the [`missingdocs()` description](https://juliadocs.github.io/Documenter.jl/stable/lib/internals/docchecks/#Documenter.DocChecks.missingdocs-Tuple{Documenter.Documents.Document}), it should ignore the modules not present in the `modules` keyword of `makedocs()`, but, apparently, this check fails here. 

Is it a bug, or is there some option one can use to ignore such external modules?

**Comment by mortenpi** [comment]
This was fixed in #852.
