### ISSUE TITLE
Add code from tests to documentation

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#55]
It would be nice to add code from a test directly into the documentation. Many times examples are included in the package as tests. As the package gets updated, these tests get updated, but corresponding tutorials in documentation might not. If the documentation had a way of getting the code directly form the tests, then it would alleviate this problem. The only issue would be that there would need to be a way to annotate the file a bit more, i.e. add a bunch of strings/markdown to make it a tutorial instead of just a test.

**Comment by MichaelHatherly** [comment]
Perhaps this would be nice to make more accessible than it is currently, but it can be done using `{eval}` code blocks as follows:

In `Package/test/example.jl`:

```julia
A = rand(3, 3)
b = [1, 2, 3]

A \ b
```

and in `Package/docs/src/index.md`:

    ```
    {eval}
    Markdown.Code("julia", readall(joinpath("..", "..", "test", "example.jl")))
    ```

Any suggestions for syntax to annotate the file contents? I'd be inclined to just add them as comments in the test file itself since splitting content and discussion across multiple locations would probably result in things getting out of sync quickly.

**Comment by ChrisRackauckas** [comment]
I agree that it's best if the annotations were in the code (then the code would read as a nice tutorial as well. 

We may want this annotation to match up with JunoLab/atom-julia-client#63. Maybe @pfitzeb would like to chime in. They are looking to make "executable code blocks" where you can divy up a file and have it just execute parts at a time. I think that this would match quite well to this, since in a tutorial you probably want a block of text, then a block of code, then repeat. So maybe just make a block that is only a string? ##"""" """"##, matching the syntax they use?

**Comment by MichaelHatherly** [comment]
Yes, would be good to reuse syntax from elsewhere for this rather than reinventing more things.

**Comment by pfitzseb** [comment]
Not that I'm totally sure if that's what you're looking for, but I'd imagine something like 
```julia
### Starting a new cell
# Let's foo the bar:
foobar = foo(bar)
# And indeed, it's foo'ed:
@test foobar == 42

### Next cell
...
```
to work nicely. It should be quite easy to transform this to

---
## Starting a new cell
Let's foo the bar
```
foobar = foo(bar)
```
And indeed, it's foo'ed:
```
@test foobar == 42
```
## Next cell
...

---
by just having a mapping from literal code to code blocks and then stripping the first `#` from the comments.

**Comment by MichaelHatherly** [comment]
Thanks for the description @pfitzseb, that looks good to me.

**Comment by ChrisRackauckas** [comment]
[I wrote out an example to see what the tests would look like in this syntax](https://github.com/ChrisRackauckas/DifferentialEquations.jl/blob/master/test/introductionExample.jl#L24). I think that the text from block comments should also be allowed because it got kind of cluttered with `#`s.

**Comment by MichaelHatherly** [comment]
> text from block comments should also be allowed

Fine with me.

**Comment by fredrikekre** [comment]
I created https://github.com/fredrikekre/Examples.jl to solve this exact problem. Works quite well and generates markdown and a notebook. The source file is runable julia so they can be included in the tests.

**Comment by mortenpi** [comment]
I am wondering whether there is some API Documenter could provide to make it a bit more natural to include dynamically generated pages. However, this feature exists as package now, so I think we can close this issue, and new issues can be opened if there are more specific requests.
