### ISSUE TITLE
Code-block breaks up list

### ISSUE THREAD

**Issue by omus** [JuliaDocs/Documenter.jl#550]
Given the markdown:

````markdown
1. A list item that has a really long sentence which the user
may want to manually break up.

    ```sh
    # nested code blocks shouldn't break
    # up the list
    ```

1. The second item in a list.
````

I would expect the rendered HTML version to look something like:

---
![image](https://user-images.githubusercontent.com/1675958/29093346-26bf21d0-7c4f-11e7-956b-7c40e0c780d3.png)

---

Instead the Documenter rendered version looks like:

---
![image](https://user-images.githubusercontent.com/1675958/29093387-548f1f5c-7c4f-11e7-8dd3-e6476e2feaa6.png)

---

There are a couple of issues with how this is rendering:
- The list isn't contiguous: the second number should be "2."
- The code block is not nested under the first list item
- The code block isn't using the specified syntax highlighting and is showing the backticks
- The first list item is not part of the same line.

**Comment by mortenpi** [comment]
It should work fine if the line starting with "may" gets indented to the third character.

**Comment by mortenpi** [comment]
It it true that it's not consistent with CommonMark, as far as I can tell. But the parser in Base is often not following CommonMark anyway. So at best it's an upstream issue.

**Comment by omus** [comment]
@mortenpi modifying the indentation of "may" does fix the list item issue. The following markdown works:
```markdown
1. A list item that has a really long sentence which the user
   may want to manually break up.

       # nested code blocks shouldn't break
       # up the list

1. The second item in a list.
```
Unfortunately using fenced code blocks (using backticks) doesn't seem supported when using lists.

**Comment by mortenpi** [comment]
The code block should be indented to three (as opposed to 4) spaces as well, then it works. The parser in Base is apparently really picky about whitespace.

**Comment by omus** [comment]
Ah, thank you. Working example for those reading this later:
````markdown
1. A list item that has a really long sentence which the user
   may want to manually break up.

   ```sh
   # nested code blocks shouldn't break
   # up the list
   ```

1. The second item in a list.
````
Maybe I missed it but is this markdown syntax documented somewhere? Besides that I can close this issue.

**Comment by mortenpi** [comment]
There's a [Markdown syntax section](https://docs.julialang.org/en/stable/manual/documentation/#Markdown-syntax-1) in the manual, but it is not this detailed.

**Comment by mortenpi** [comment]
> I wonder if using CommonMark.jl for parsing would make things a bit more robust for this?

Almost certainly. It's on my wishlist (actually, in general allowing alternative parsers), but integrating it into Documenter is a bit of work (e.g. it has its own AST representation). Another thing to consider there is the interaction with Base docstrings.

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing as stale. I get that the current behavior is suboptimal, but this is a wider issue than just Documenter, and it can be fixed (easily, if tediously) by the user.
