### ISSUE TITLE
add more people to JuliaDocs

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaDocs/Documenter.jl#557]
At this point, Documenter is a pretty critical piece of Julia infrastructure. As such, I think that anyone who can commit to Julia itself should probably have commit rights to JuliaDoc. @MichaelHatherly seems to be somewhat M.I.A. – @mortenpi, do you have rights to add people to the org? If you can make me an admin, I can do the rest.

**Comment by mortenpi** [comment]
Agreed and done. I've been thinking about the same thing for a while actually.

**Comment by StefanKarpinski** [comment]
Thanks, @mortenpi! Hopefully we can also take some of the work off your plate.
