### ISSUE TITLE
HTMLWriter: Ability to get assets from external location?

### ISSUE THREAD

**Issue by TransGirlCodes** [JuliaDocs/Documenter.jl#559]
At BioJulia I'm trying to make the docs all consistent in style. One way to do this is copy the same assets and logo to all the repositories, but this is frustrating and also risks individual updates to individual packages messing up that consistency.

An alternative I thought of would be if a link could be used to determine the asset folder, so Documenter could download such a folder e.g. from a central repository we have for the assets that all docs use. Of course this could just be a step in travis to get the folder first but wondered if the idea was worth anything for Documenter.jl.

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing as stale. It seems like this is much safer for it to be a step in CI or as part of your build script. I don't think Documenter needs to provide functionality to download external assets as part of the build.
