### ISSUE TITLE
Including documentation from another package

### ISSUE THREAD

**Issue by dmbates** [JuliaDocs/Documenter.jl#568]
The [`StatsBase`](https://github.com/JuliaStats/StatsBase.jl) package contains the definitions of many generics to be applied to statistical models.  Model fitting packages, e.g. [`GLM`](https://github.com/JuliaStats/GLM.jl) or [`MixedModels`](https://github.com/dmbates/MixedModels.jl), define methods for these generics applied to particular models.

I would like to include documentation strings from these `StatsBase` generics in an `@docs` block in my documentation for `MixedModels` but have not been able to work out the syntax.  Is it possible to do so and, if so, how?

**Comment by Evizero** [comment]
https://github.com/JuliaImages/juliaimages.github.io does this and there doesn't seem to be any magic to it from what I can tell.

1. include packages in `make.jl` (like https://github.com/JuliaImages/juliaimages.github.io/blob/source/docs/make.jl#L1)

2. use `@docs` as usual (like all the docs in this file https://raw.githubusercontent.com/JuliaImages/juliaimages.github.io/source/docs/src/function_reference.md) 

Personally I have only tried it with a function that was in a sub-module of another package, and was unable to get that to work.

**Comment by dmbates** [comment]
I eventually worked out that I had the named argument
```
modules = [MixedModels],
```
in the call to `makedocs`.  Apparently that restricts the scope when searching for documentation strings.

**Comment by Evizero** [comment]
Oh good catch. I think that might have been my problem as well
