### ISSUE TITLE
Add a 'Pkg.generate'-like function for docs

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaDocs/Documenter.jl#57]
Currently setting up Documenter for a package is a manual process. Would be nice to have a `setup`/`init`/`generate` function that did some of this automatically.

**Comment by hayd** [comment]
(In the longer term /docs/src /docs/make.jl could be generated/stubbed in as part of [PkgDev](https://github.com/JuliaLang/PkgDev.jl) generate.)

**Comment by mortenpi** [comment]
I suppose it would make sense to have `Documenter.generate()` available here and then `PkgDev` would just call that?

**Comment by MichaelHatherly** [comment]
Yeah, that's probably the best approach, though integrating with `PkgDev` should wait a while I think, at least until `Documenter` is registered and tagged for a bit.

**Comment by MichaelHatherly** [comment]
Should probably also have a second argument specifying the format. Just `"mkdocs"` as an option for the moment.

**Comment by MichaelHatherly** [comment]
Closed by #66.
