### ISSUE TITLE
Native HTML Render Themes

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#579]
The mkdocs build allows you to add themes. Can the native HTML render use themes at all?

**Comment by Evizero** [comment]
you can provide a custom css

**Comment by ChrisRackauckas** [comment]
I like themes because I'm awful at any language that isn't Julia haha. The mkdocs build has a ton of documentation themes which look quite nice and it would be nice to be able to plug into something like that.

**Comment by Evizero** [comment]
which I realize isn't that on the same convenience level as what you are asking. Just wanted to mention the option, which is very powerful

**Comment by Evizero** [comment]
right, yes you beat me to it.

**Comment by mortenpi** [comment]
The folks over at Invenia modify the theme with their own custom CSS, e.g.: https://invenia.github.io/Memento.jl/latest/

Can't simply borrow a theme from mkdocs unfortunately, since the structure of the HTML, element ids etc are completely different. You'd have to replicate the theme with your own CSS.

**Comment by Evizero** [comment]
I also mess with my css at Augmentor to make the docstring seamlessly integrate into my documentation (since I want to have a standalone page per functionality). For example most of this page is actually a docstring: https://evizero.github.io/Augmentor.jl/operations/shearx/.

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing because we don't use mkdocs anymore, and because you can provide custom CSS.
