### ISSUE TITLE
Make sidebar stay at same location when clicking a link

### ISSUE THREAD

**Issue by mauro3** [JuliaDocs/Documenter.jl#594]
Scroll down the sidebar, say until you see "Profiling" on https://docs.julialang.org/en/stable/index.html, then click on "Profiling". The sidebar will scroll/jump back to the top.  This is annoying, in particular as a sub-menu opens below "Profiling".  So, the sidebar should stay where it is.

**Comment by fredrikekre** [comment]
Dup of #564?

**Comment by mauro3** [comment]
Yes.
