### ISSUE TITLE
Display the allowed Julia versions

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#595]
It would be nice if Julia helped user find the right documentation version by displaying what version of Julia the current package's documentation is for. For example, if someone is still on v0.5, they can silently get an older version of the package, so it would be nice to easily show that that they need to go back versions in the docs.

**Comment by Datseris** [comment]
+1 here and it would be nice to extend it to also specific package versions.

Currently I have the workaround:

The current documentation was built with the following versions
```@example docs
Pkg.status("DynamicalSystemsBase") # hide
Pkg.status("ChaosTools") # hide
```

in my index.md
and very nicely shows the compatible versions with the documentation. One can also add the julia version there, but maybe it would be cool to have one dedicated block, like e.g. the examples block, something like 

```
\`\`\`@versions
julia
ChaosTools
OrdinaryDiffEq
\`\`\`
```

**Comment by fredrikekre** [comment]
Could easily just be added as a note on the frontpage or similar, don't think anything is needed here.

**Comment by KristofferC** [comment]
With Julia 1.0 and the addition of the version selector, this can be closed.
