### ISSUE TITLE
Provide a sample project with Documenter.jl and PkgTemplate

### ISSUE THREAD

**Issue by scls19fr** [JuliaDocs/Documenter.jl#598]
Hello,

It could be interesting to provide a Julia project template (using [PkgTemplates.jl](https://invenia.github.io/PkgTemplates.jl)) from @invenia @christopher-dG with a default Documenter.jl configuration.

Kind regards

**Comment by mortenpi** [comment]
Do you mean to have an example `PkgTemplates.Template` in the docs here? It indeed wouldn't hurt to link to PkgTemplates (and to PackageGenerator) from Documenter docs, to make it easier for people to set up docs.

**Comment by scls19fr** [comment]
My idea is that we should have in JuliaDocs Github org a template repository that could be use to generate in one line a project which is "Documenter.jl" ready.
Documenter docs could be updated to provide a way to use this template (I won't personally put template in the doc... but in a repository).

**Comment by christopher-dG** [comment]
FWIW, setting up Documenter is just adding one plugin to a template, so I'm not sure if extra documentation is required. There's some talk about incorporating `PkgTemplates` into the new package manager, so at that point I would probably consider documenting a recommended template that meets standards for registered packages, but in the meantime `PkgTemplates` has always been about customization so I'm wary of telling people exactly how to use it.

**Comment by fredrikekre** [comment]
Doesn't `Documenter.generate` do exactly this?

**Comment by fredrikekre** [comment]
DocumenterTools.generate are mentioned in the docs, and PkgTemplates can also generate a skeleton.
