### ISSUE TITLE
Plot not rendering in `@example` block with Travis CI

### ISSUE THREAD

**Issue by mforets** [JuliaDocs/Documenter.jl#607]
An example block such as:

```@example example_ih
using LazySets, Plots

X = Ball2(ones(2), 0.5)
```

(some text)

```@example example_ih
plot(X, 1e-3, aspectratio=1)
```
displays the plot in my local machine. However, it does not show the plot through the Travis CI setup for that package, [with this docs/make.jl](https://github.com/JuliaReach/LazySets.jl/blob/master/docs/make.jl). Only empty space is rendered.

This full example is [interval_hulls.html](https://juliareach.github.io/LazySets.jl/latest/man/interval_hulls.html)

Did you have this problem before? Any hint is highly appreciated :)

**Comment by mforets** [comment]
We got this working by installing GR in the Travis CI build (by default it was using Plotly), via `- julia -e 'Pkg.add("Documenter"); Pkg.add("GR")'`. Thus for our purposes i consider this issue as fixed.

**Comment by mortenpi** [comment]
Thanks for reporting it though -- it might be useful for others in the future. It seems that Plotly does not work because the javascript library it requires does not get properly loaded.
