### ISSUE TITLE
PyPlot.ioff() # hide does not actually hide the command

### ISSUE THREAD

**Issue by Datseris** [JuliaDocs/Documenter.jl#613]
For example:

````markdown
```@example plot
using DynamicalSystems
using PyPlot
PyPlot.ioff() # hide

ds = Systems.logistic()
```
````

does not hide the line `PyPlot.ioff() # hide` when it is compiled.

**Comment by Datseris** [comment]
Notice that other hide commands work for me. For example:
`savefig("logisticdiagram.png"); nothing # hide` is hidden in the output

**Comment by joshday** [comment]
I've found something similar.  Some `@example` blocks hide lines correctly and some don't, and I haven't found a common pattern between them yet.

http://joshday.github.io/OnlineStats.jl/latest/visualizations.html

**Comment by KristofferC** [comment]
Maybe fixed by https://github.com/JuliaDocs/Documenter.jl/pull/991?

**Comment by mortenpi** [comment]
Yeah, this seems likely. I'll close this. If someone still runs into this (with Documenter 0.22 or higher), we can re-open.
