### ISSUE TITLE
Offline testing of docs locally when using format=:html

### ISSUE THREAD

**Issue by navidcy** [JuliaDocs/Documenter.jl#619]
I was wondering how can I test my documentation offline locally when I use `format=:html` in `makedocs`. That is, how can I simulate the html page of my documents without committing and invoking travis-ci?

**Comment by mforets** [comment]
don't know if this really helps; what i do to see html docs locally is to do `$ julia --color=yes docs/make.jl` from the projects' root folder, and then open the file `docs/build/index.html`. this also runs your doctests (the flag  `doctest = true` is on by default).

**Comment by navidcy** [comment]
Doing that doesn't seem to be producing a fully operative html site. Is this how we are supposed to write the docs before pushing them?

**Comment by mforets** [comment]
FWIW you may need internet connection so that the markdown renders fine. yes, at least for me  that is the workflow used before pushing and it works fine. if you give a more precise description of the problem it would help.

**Comment by mortenpi** [comment]
If you have the `html_prettyurls` option enabled, then you might need to serve it as a web page (you can quickly host a web server out of the current working directory with Python: either `python3 -m http.server` or `python -m SimpleHTTPServer`). Otherwise, the local build should be completely operative (but does require an internet connection as @mforets pointed out).

**Comment by fredrikekre** [comment]
Nothing to do here.

**Comment by floswald** [comment]
> If you have the `html_prettyurls` option enabled, then you might need to serve it as a web page (you can quickly host a web server out of the current working directory with Python: either `python3 -m http.server` or `python -m SimpleHTTPServer`). Otherwise, the local build should be completely operative (but does require an internet connection as @mforets pointed out).

i don't get a working html site either. the links to other pages don't resolve properly, it opens up my file browser instead of the correct html page. this is my 

```
makedocs(
    format = Documenter.HTML(),
    sitename = "MomentOpt.jl",
    modules = [MomentOpt],
    pages = [
    	"Getting Started" => "index.md",
    	"Eval Object" => "eval.md",
    	"Slices" => "slices.md",
    	"Moment Algorithms" => "algo.md"]
)
```

on a positive note: learning here about `python -m SimpleHTTPServer` finally allows me to view my site! :-)

**Comment by mortenpi** [comment]
@floswald If you want to make the site browsable locally, then you need to pass `format = Documenter.HTML(prettyurls = false)`.

> on a positive note: learning here about `python -m SimpleHTTPServer` finally allows me to view my site! :-)

You may also want to check out a pure-Julia version that has become available in the mean time: [LiveServer](https://github.com/asprionj/LiveServer.jl) :slightly_smiling_face:

**Comment by floswald** [comment]
D’oh! Completely didn’t get that. Ok now it’s clear and will try out that
server as well! Thanks
