### ISSUE TITLE
support rel="canonical" so search engines only index the latest stable version

### ISSUE THREAD

**Issue by tkluck** [JuliaDocs/Documenter.jl#621]
Serving similar content (e.g. different versions of the same documentation) can make content hard to find in search engines. [The site readthedocs.io address this by using canonical URLs](https://docs.readthedocs.io/en/latest/canonical.html). This seems a useful feature for Documenter.jl's html output as well.

What do you think? I could maybe squeeze in a pull request if you support the idea.

**Comment by mortenpi** [comment]
Good idea, a PR would be welcome!

The canonical URLs can't really be relative, right? So I don't really see any way of determining the canonical URL automatically, but an option like `html_canonical = "https://juliadocs.github.io/Documenter.jl/latest/"` to determine the root of the URL could be the way to go perhaps.

**Comment by mortenpi** [comment]
Closed by #622.
