### ISSUE TITLE
@autodocs presented directly on the usage page

### ISSUE THREAD

**Issue by matbesancon** [JuliaDocs/Documenter.jl#623]
Some browsing through other repos is necessary before finding the `@autodocs` macro, which is what package developers will mostly use in my opinion.  

It would be good to present it right after `@docs` in the [Usage section of the docs](https://`juliadocs.github.io/Documenter.jl/stable/man/guide/#Usage-1)

**Comment by mortenpi** [comment]
The commit actually referred to the wrong issue. This one actually hasn't been addressed.

**Comment by odow** [comment]
Closing because this is now documented at https://documenter.juliadocs.org/stable/man/syntax/#@autodocs-block
