### ISSUE TITLE
modules keyword not working?

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaDocs/Documenter.jl#63]
I am getting an error generating documentation for PETSc.jl using the `modules=[PETSc]` keyword.

```
jared@k475:~/.julia/v0.4/PETSc/doc$ julia4 ./make.jl 
Documenter: setting up build directory.
Documenter: copying assets to build directory.
Documenter: expanding markdown templates.
 !! No docs for 'Base.!' from provided modules. [src/index.md]
 !! No docs for 'Base.!=' from provided modules. [src/index.md]
 !! No docs for 'Base.*' from provided modules. [src/index.md]
 !! No docs for 'Base.+' from provided modules. [src/index.md]
 !! No docs for 'Base.-' from provided modules. [src/index.md]
 !! No docs for 'Base..*' from provided modules. [src/index.md]
 !! No docs for 'Base../' from provided modules. [src/index.md]
 !! No docs for 'Base..\' from provided modules. [src/index.md]
 !! No docs for 'Base..^' from provided modules. [src/index.md]
 !! No docs for 'Base.==' from provided modules. [src/index.md]
 !! No docs for 'Core.===' from provided modules. [src/index.md]
 !! No docs found for '=>'. [src/index.md]
 !! No docs for 'Base.>=' from provided modules. [src/index.md]
 !! No docs for 'Base.@doc' from provided modules. [src/index.md]
 !! No docs for 'Base.@eval' from provided modules. [src/index.md]
 !! No docs found for '@v_str'. [src/index.md]
 !! No docs found for 'AO'. [src/index.md]
ERROR: LoadError: "AO_" is not defined in module Main
 in error at ./error.jl:21
 in which_module at ./reflection.jl:315
 in call at ./docs/bindings.jl:8
 in expand at /home/jared/.julia/v0.4/Documenter/src/modules/Expanders.jl:153
 in expand at /home/jared/.julia/v0.4/Documenter/src/modules/Expanders.jl:75
 in expand at /home/jared/.julia/v0.4/Documenter/src/modules/Expanders.jl:76
 in expand at /home/jared/.julia/v0.4/Documenter/src/modules/Expanders.jl:69
 in process at /home/jared/.julia/v0.4/Documenter/src/modules/Builder.jl:195
 in process at /home/jared/.julia/v0.4/Documenter/src/modules/Builder.jl:196
 in process at /home/jared/.julia/v0.4/Documenter/src/modules/Builder.jl:191
 in anonymous at /home/jared/.julia/v0.4/Documenter/src/Documenter.jl:120
 in cd at ./file.jl:22
 in makedocs at /home/jared/.julia/v0.4/Documenter/src/Documenter.jl:119
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/jared/.julia/v0.4/PETSc_current/doc/make.jl, in expression starting on line 3
```
If I have understood the documentation correctly, it should be looking for `AO_` in `PETSc`, not `Main`.

The `index.md` file contains every name used in the `PETSc` module (and is auto generated), some of which are defined in different modules, but `AO_` is defined within `PETSc`.
The `make.jl` file and the script that creates `index.md` are here: https://github.com/JuliaParallel/PETSc.jl/tree/doc/doc

**Comment by MichaelHatherly** [comment]
The `modules` keyword passed to `makedocs` just specifies which root modules to check for missing docs in. To set the current module for a particular page, `docs/src/index.md` in this case, you need to add a [`@meta`](http://michaelhatherly.github.io/Documenter.jl/latest/man/syntax/#@meta-block-1) block prior to the `@docs` block like so

    # PETSc.jl
    
    ```@meta
    CurrentModule = PETSc
    ```
    
    ```@docs
    
    ```

Regarding the `extract_docs.jl` script, you probably want to use an [`@autodocs`](http://michaelhatherly.github.io/Documenter.jl/latest/man/syntax/#@autodocs-block-1) block there instead, which is designed to do pretty much the same thing.

    ```@autodocs
    Modules = [PETSc]
    ```

**Comment by JaredCrean2** [comment]
Ah, I understand now.  The `@autodocs` is great too, thanks for pointing it out.  I successfully generated documentation locally, so now I am working on deploying it.  Two questions:

1) To generate ssh keys I tried:
```julia
julia> using Documenter

julia> Travis.genkeys("PETSc")
ERROR: 'which' not found.
 in genkeys at /home/jared/.julia/v0.4/Documenter/src/Documenter.jl:399
```
In the terminal I did:
```
jared@k475:~/.julia/v0.4/Documenter/src$ which -v
Illegal option -v
Usage: /usr/bin/which [-a] args
```
I checked my local man page, and the only option this version of `which` accepts is `-a`.  For reference, my OS info is:
```
jared@k475:~/.julia/v0.4/Documenter/src$ uname -a
Linux k475 3.16.0-39-generic #53~14.04.1-Ubuntu SMP Wed May 27 10:03:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

2) The docs say I need to have `travis` installed to generate keys.  Are they referring to this: http://packages.ubuntu.com/xenial/travis or something else?

**Comment by MichaelHatherly** [comment]
> and the only option this version of `which` accepts is `-a`

I'll change that one to `which which`, which seems to do the right thing.

> The docs say I need to have `travis` installed to generate keys.

It's referring to https://github.com/travis-ci/travis.rb. I'll add a link to the docs.

**Comment by MichaelHatherly** [comment]
Done in https://github.com/MichaelHatherly/Documenter.jl/pull/65/commits/0852c10cc96b119d461693259265fc0a79a2067f.

**Comment by JaredCrean2** [comment]
Made more progress.  I installed travis and generated a key, but got this error:

```
WARNING: removing private key.
ERROR: UndefVarError: readstring not defined
 in anonymous at /home/jared/.julia/v0.4/Documenter/src/Documenter.jl:423
 in cd at ./file.jl:22
 in genkeys at /home/jared/.julia/v0.4/Documenter/src/Documenter.jl:407
```

I think `readstring` was introduced for Julia 0.5, but backported.

**Comment by MichaelHatherly** [comment]
Missing `Compat` import... fixed in e7eccde4cdbd3d6dc35c2adc135403ab322ebff6 hopefully.

**Comment by JaredCrean2** [comment]
Documentation successfully generated and deployed.  Thanks for all the help over the last few days.

One final question: is there a way to automatically generate documentation by file rather than by module?  Something like `@autodoc file1.jl file2.jl`

**Comment by MichaelHatherly** [comment]
> Thanks for all the help over the last few days.

No prob, glad it's working now. Thanks for helping to shake out the bugs.

> generate documentation by file rather than by module

I've thought of adding something like that. Would probably be possible to do. Could you open a new issue to track that feature request?

**Comment by JaredCrean2** [comment]
Done: #72
