### ISSUE TITLE
@autodocs for specific source files

### ISSUE THREAD

**Issue by crstnbr** [JuliaDocs/Documenter.jl#630]
From Documenter.jl's documentation of [`@autodocs`](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@autodocs-block-1):

> [...], a **Pages** vector may be included in @autodocs to filter
> docstrings based on the source file in which they are defined:
>
>     ```@autodocs
>     Modules = [Foo]
>     Pages   = ["a.jl", "b.jl"]
>     ```

However, it also says

> Note that page matching is done using the end of the provided strings
> and so a.jl will be matched by **any source file that ends in a.jl**, i.e.
> src/a.jl or src/foo/a.jl.

How can I restrict the `@autodocs` block to specific source files?

My package's source code is organized as

    src/
        foo/a.jl
        foo/b.jl
        ignore/a.jl
        ignore/b.jl
        other.jl

How to make the `@autodocs` block only consider files `src/foo/a.jl` and `src/foo/b.jl` but not `src/ignore/a.jl` and `src/ignore/b.jl`?

Unfortunately, `Pages = ["foo/a.jl", "foo/b.jl"]` didn't do it for me.

If this feature doesn't yet exist, consider this a feature request. I might even try to implement it myself, but first I wanna make sure I'm not overlooking something.

x-ref: https://discourse.julialang.org/t/documenter-jl-autodocs-for-specific-source-files/8784
x-ref: https://stackoverflow.com/questions/48587995/documenter-jl-autodocs-for-specific-source-files

**Comment by mortenpi** [comment]
It should work. You're not building on Windows by any chance? It's likely that we're not normalizing path separators here.

**Comment by crstnbr** [comment]
Indeed, I'm using Windows. I'll try different path separators.

**Comment by crstnbr** [comment]
In fact, `Pages = ["foo\\a.jl", "foo\\b.jl"]` works on Windows. Thank you. Should I leave this open for a PR on normalizing path separators?

**Comment by KristofferC** [comment]
`joinpath("foo", "a.jl")`? I don't think it is Documenters job to fix the paths.

**Comment by crstnbr** [comment]
Fair enough. But at least on Windows 10 using a path with different separators like `C:/Users\\username/Desktop`, despite being terribly ugly, works fine in other places (for example in `readdir`). Anyways, I'll close this. Please reopen if this is considered a bug to be fixed.
