### ISSUE TITLE
Casing of search result types should be consistent

### ISSUE THREAD

**Issue by waldyrious** [JuliaDocs/Documenter.jl#634]
Initially reported as part of #629. In the example there, a search for "markdown" (http://docs.julialang.org/en/latest/search/?q=markdown) produced the following results:

>- [Markdown syntax](https://docs.julialang.org/en/latest/manual/documentation/#Markdown-syntax-1)(section)
>- [Markdown](https://docs.julialang.org/en/latest/stdlib/Markdown/#)(page)
>- [Markdown](https://docs.julialang.org/en/latest/stdlib/Markdown/#Markdown-1)(section)
>- [Markdown Syntax Extensions](https://docs.julialang.org/en/latest/manual/documentation/#Markdown-Syntax-Extensions-1)(section)
>- [InteractiveUtils.varinfo](https://docs.julialang.org/en/latest/stdlib/InteractiveUtils/#InteractiveUtils.varinfo)(Function)
>- [Advanced Usage](https://docs.julialang.org/en/latest/manual/documentation/#Advanced-Usage-1)(section)
>- [Tables](https://docs.julialang.org/en/latest/manual/documentation/#Tables-1)(section)
>- [Links](https://docs.julialang.org/en/latest/manual/documentation/#Links-1)(section)
>- [Documentation](https://docs.julialang.org/en/latest/manual/documentation/#Documentation-1)(section)
>- [Unicode Input](https://docs.julialang.org/en/latest/manual/unicode-input/#Unicode-Input-1)(section)
>- [Language changes](https://docs.julialang.org/en/latest/NEWS/#Language-changes-1)(section)
>- [Deprecated or removed](https://docs.julialang.org/en/latest/NEWS/#Deprecated-or-removed-1)(section)

It's unclear why "(Function)" is in uppercase, while "(section)" and "(page)" are in lowercase. I would expect this to be consistent (all in lowercase).

This seems an easy enough issue that even someone not familiar with the codebase could fix, but I'd need some pointers regarding which files / lines to look at. Perhaps somewhere around here? https://github.com/JuliaDocs/Documenter.jl/blob/master/src/Utilities/Utilities.jl#L280-L284

**Comment by KristofferC** [comment]
Maybe because `Function` is the Julia type `Function` which is spelled with capital F?

**Comment by waldyrious** [comment]
@KristofferC the search results doesn't seem to provide a hint in this direction, though. Perhaps rendering it as `code` would make this clearer? I'd go as far as making it a subtle (i.e. unstyled) link to https://docs.julialang.org/en/stable/manual/functions/, but that may be overkill :)

**Comment by fredrikekre** [comment]
I'm confused, it says `Function` because it is a link to the `varinfo` `Function`. Similar as there are sometimes methods that are documented, where it will instead say `Method`.

**Comment by mortenpi** [comment]
It [comes from the `doccat` function](https://github.com/JuliaDocs/Documenter.jl/blob/master/src/Writers/HTMLWriter.jl#L656) and the capitalization seems to be an arbitrary choice (possibly due to how it the string was used in the Markdown builds). `lowercasing` [here, which is where the categories get written into the search index](https://github.com/JuliaDocs/Documenter.jl/blob/master/src/Writers/HTMLWriter.jl#L559), should be easiest and least intrusive fix.

**Comment by waldyrious** [comment]
Thanks for the pointer @mortenpi; I'll see if I can take a stab at that in the next few days.
