### ISSUE TITLE
Horizontal line in menu between sections is too thin

### ISSUE THREAD

**Issue by KristofferC** [JuliaDocs/Documenter.jl#635]
![screen shot 2018-02-08 at 17 06 18](https://user-images.githubusercontent.com/1282691/35984157-1be6c854-0cf4-11e8-8936-b51741404bae.png)

It's like 1 pixel.

**Comment by mortenpi** [comment]
It's literally 1px :laughing: But to my eye it separates the sections well. Do you have a retina display? We might need to define it in `em` units.

**Comment by mortenpi** [comment]
Would `.07em` look better to you by any chance?

**Comment by KristofferC** [comment]
Yes, it is a retina display. How do I test it with `.07em`?

**Comment by mortenpi** [comment]
Can you replace the CSS e.g. in browser developer tools or in the local build with https://gist.github.com/mortenpi/0a181dcaad84eada7c809a99a002b8dc ?

**Comment by KristofferC** [comment]
I think the problem is that it is a bit too similar to the background?
Something like `border-top: .08em solid #807b7b;` looks good to me.

**Comment by mortenpi** [comment]
Yup, could do. Maybe with `#909090`, since `#807b7b` looks a bit too strong to my eye.

On a separate note, it seems that `font-weight: bold` does not render very visibly for you, which otherwise also helps separating the sections. On my system the menu looks like this:
![documenter-navmenu-toplevel-style](https://user-images.githubusercontent.com/147757/36053581-0fdc4fe8-0e57-11e8-8fab-2632f3666566.png)

**Comment by KristofferC** [comment]
Oh, that's odd. The lack of bold in sections was going to be my next remark, but looks like something is up on my end then. With the bold text, the line is not at all as important.

**Comment by mortenpi** [comment]
It could be a font issue.. could you check whether changing the font CDN URL to `https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i|Roboto+Mono` changes anything? You could either change the `<link>` tag with developer tools or build the docs with this patch:

```diff
diff --git a/src/Writers/HTMLWriter.jl b/src/Writers/HTMLWriter.jl
index 725fecb..7c32682 100644
--- a/src/Writers/HTMLWriter.jl
+++ b/src/Writers/HTMLWriter.jl
@@ -82,7 +82,7 @@ using ...Utilities.MDFlatten
 
 const requirejs_cdn = "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.2.0/require.min.js"
 const normalize_css = "https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css"
-const google_fonts = "https://fonts.googleapis.com/css?family=Lato|Roboto+Mono"
+const google_fonts = "https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i|Roboto+Mono"
 const fontawesome_css = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css"
 const highlightjs_css = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css"
 
```
