### ISSUE TITLE
Navigation sidebar not usable on iPad

### ISSUE THREAD

**Issue by goerz** [JuliaDocs/Documenter.jl#638]
When browsing any site generated with Documenter on an iPad Pro 12.9 inch, the navigation sidebar on the left is hardly usable: Swiping over it doesn't smoothly scroll in the sidebar. Sometimes it scrolls (non-smoothly), and sometimes instead  the main content on the right scrolls; a rather frustrating experience.

**Comment by mortenpi** [comment]
Thanks for reporting this. Can't test it myself unfortunately, but #626 might help with this.

**Comment by mortenpi** [comment]
@goerz Could you by any chance test the sidebar of the new front end to see if that is any better than the old one?

> http://mortenpi.eu/gsoc2019-mockups/bulma/v3-julia/

**Comment by goerz** [comment]
It's definitely better. Nothing seems completely broken, the only thing that could be improved on is the lack of inertial scrolling. I think that with the redesign of Safari in iOS13 this will probably go away automatically. I'll try it out this weekend, when I have access to an iPad running the iOS13 beta.

**Comment by mortenpi** [comment]
> the only thing that could be improved on is the lack of inertial scrolling

I don't think that's anything we can really fix on Documenter's end -- this seems to be up to the OS. I have inertial scrolling on both Android and on a Surface tablet. But let me know how it goes on iOS13.

**Comment by goerz** [comment]
As I expected it works fine on iOS 13, so feel free to close as far as I'm concerned

**Comment by mortenpi** [comment]
@goerz I was hoping I could have you test another version of the sidebar on ipads, as I am fiddling around with it at the moment:

> https://mortenpi.eu/gsoc2019-mockups/bulma/v9/julia/stdlib/FileWatching.html

Is it fine or are the issues back?

**Comment by goerz** [comment]
It's totally fine on iOS13. On the current iOS12, it's still hard to scroll the navigation bar.

**Comment by goerz** [comment]
However, there is a problem with the navigation toolbar disappearing completely when I rotate the iPad from landscape to portait mode. The "menu icon" (three horizontal bars) on the top right is not visible. I'm actually also seeing this bug in the reactive design on the desktop: When I resize the browser window, first the navigation bar disappears, and then the menu icon only appears if I make the window even narrower, see [this video](https://vimeo.com/352126728). It seems the iPad has exactly the screen size that is between those two transitions.

**Comment by mortenpi** [comment]
> It's totally fine on iOS13. On the current iOS12, it's still hard to scroll the navigation bar.

Thanks for testing. I have to declare iOS12 a _wontfix_ then -- the dashboard approach that seemed to work better for this has a bunch of other issues that I want to get rid of. It looks like it's partly a browser problem anyway if iOS13 works fine.

Re: bad responsive design -- I thought I fixed it, but apparently not. Is fixed now!
