### ISSUE TITLE
Unrelated missing docstrings

### ISSUE THREAD

**Issue by bramtayl** [JuliaDocs/Documenter.jl#651]
Recently, my builds have been failing due to missing docstrings from unrelated modules. See e.g. https://travis-ci.org/bramtayl/LazyCall.jl/jobs/346224405

**Comment by mortenpi** [comment]
Yup, I've noticed them as well (in Documenter's own builds) and been meaning to look into it. It looks like it _might_ have been introduced in #643.

**Comment by KristofferC** [comment]
Nice find.

**Comment by bramtayl** [comment]
Thanks! Would be great to get this published asap because none of my packages will pass CI without it.

**Comment by mortenpi** [comment]
The new Compat fixes 0.6 builds, but nightlies are still broken as far as I can tell (e.g. [the latest Documenter builds with Compat 0.55.1](https://travis-ci.org/JuliaDocs/Documenter.jl/jobs/347335572#L577-L864)).

**Comment by fredrikekre** [comment]
Will be fixed by https://github.com/JuliaLang/julia/pull/26293

**Comment by mortenpi** [comment]
Fixed on master now and should reach Travis as soon as the next nightly is built.
