### ISSUE TITLE
Printing of error in doctest

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#653]
The following doctest, taken from julia base
````
```jldoctest
julia> struct MyException <: Exception
           msg::AbstractString
       end

julia> function Base.showerror(io::IO, err::MyException)
           print(io, "MyException: ")
           print(io, err.msg)
       end

julia> err = MyException("test exception")
MyException("test exception")

julia> sprint(showerror, err)
"MyException: test exception"

julia> throw(MyException("test exception"))
ERROR: MyException: test exception
```
````

fails on the last expression. Instead of `ERROR: MyException: test exception` Documenter evaluates to `MyException("test exception")` so somehow we never end up in the custom `showerror` function.

**Comment by fredrikekre** [comment]
Probably some logic that is incorrect here
https://github.com/JuliaDocs/Documenter.jl/blob/56e9f6236da00449bb3bc53beed995bc9229b886/src/DocChecks.jl#L288-L298

**Comment by mortenpi** [comment]
It's not related to world-age stuff by any chance? `showerror` might need `Base.invokelatest`?

**Comment by fredrikekre** [comment]
Ah, good catch! That fixes it.
