### ISSUE TITLE
ArgumentError("`source` doesn't support the supported streaming types of `sink`: DataType[DataStreams.Data.Field]") 

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaDocs/Documenter.jl#660]
My documentation was building fine
https://juliampc.github.io/MPCDocs.jl/stable/tutorials/RobotArm/main.html

with the source
https://github.com/JuliaMPC/MPCDocs.jl/blob/8f850285020f1212327365fbcaeb115f3d4c48a6/docs/src/tutorials/RobotArm/main.md

but now I am getting these errors
```
ArgumentError("`source` doesn't support the supported streaming types of `sink`: DataType[DataStreams.Data.Field]") [src/tutorials/RobotArm/main.md]
 !! failed to run code block.
```
And my documentation is broken
https://juliampc.github.io/MPCDocs.jl/latest/tutorials/HyperSensitive/main.html

Where there any changes that may be causing these errors? 

Thanks!

**Comment by huckl3b3rry87** [comment]
I have tried a few things, but I still get the above error in the log file
https://api.travis-ci.org/v3/job/357015916/log.txt

https://travis-ci.org/JuliaMPC/MPCDocs.jl

**Comment by huckl3b3rry87** [comment]
I am thinking this commit
https://github.com/JuliaMPC/MPCDocs.jl/commit/a54a8e6b60cd2345b47a9bbd443f8ce176d878d7

will fix it, we will see in 20 min

**Comment by huckl3b3rry87** [comment]
the above did not work. This is a strange error because sometimes it works

https://juliampc.github.io/MPCDocs.jl/latest/tutorials/Brachistochrone/main.html

and sometimes it does not
https://juliampc.github.io/MPCDocs.jl/latest/tutorials/Rocket/main.html

**Comment by KristofferC** [comment]
This doesn't look like Documenters fault, just that you code you have in that block doesn't run properly?

**Comment by fredrikekre** [comment]
Those errors are from DataStreams.jl:
https://github.com/JuliaData/DataStreams.jl/blob/6fd55153d157da21e81aacb857a274d9bd842465/src/DataStreams.jl#L493
https://github.com/JuliaData/DataStreams.jl/blob/6fd55153d157da21e81aacb857a274d9bd842465/src/DataStreams.jl#L519
or 
https://github.com/JuliaData/DataStreams.jl/blob/6fd55153d157da21e81aacb857a274d9bd842465/src/query.jl#L712

Documenter does not use DataStreams, so there must be a problem in how you use DataStreams in your documentation.

I would suggest that you build the docs locally, and make sure everything works, instead of trying to debug from Travis.

**Comment by fredrikekre** [comment]
In particular, the problem seem to be when you call `allPlots`. Here is the full stacktrace from the `RobotArm` example:
```
julia> allPlots(n)
ERROR: ArgumentError: `source` doesn't support the supported streaming types of `sink`: DataType[DataStreams.Data.Field]
Stacktrace:
 [1] #stream!#5(::Array{Any,1}, ::Function, ::String, ::Type{CSV.Sink}, ::Bool, ::Dict{Int64,Function}, ::String, ::Vararg{String,N} where N) at /home/fredrik/.julia/v0.6/DataStreams/src/DataStreams.jl:154
 [2] #write#36(::Bool, ::Dict{Int64,Function}, ::Array{Any,1}, ::Function, ::String, ::String) at /home/fredrik/.julia/v0.6/CSV/src/Sink.jl:150
 [3] #resultsDir!#27(::String, ::String, ::Function, ::NLOptControl.NLOpt) at /home/fredrik/.julia/v0.6/NLOptControl/src/utils.jl:304
 [4] #allPlots#2(::Int64, ::Function, ::NLOptControl.NLOpt) at /home/fredrik/.julia/v0.6/PrettyPlots/src/NLOptControl_plots.jl:9
 [5] allPlots(::NLOptControl.NLOpt) at /home/fredrik/.julia/v0.6/PrettyPlots/src/NLOptControl_plots.jl:9
```
if that can be of any help. Seem to be a bug in NLOptControl, CSV or DataStreams.

**Comment by fredrikekre** [comment]
For future debugging, try to run the example in the REPL like I did, that way you avoid seeing the errors thrown from inside Documenter and you get full stacktraces like above. Of course if the example works in the REPL it might be a Documenter bug.

Also note that there is an extra `` ` `` in `RobotArm.md`:
```diff
diff --git a/docs/src/tutorials/RobotArm/main.md b/docs/src/tutorials/RobotArm/main.md
index fdde5d5..a9a78bc 100644
--- a/docs/src/tutorials/RobotArm/main.md
+++ b/docs/src/tutorials/RobotArm/main.md
@@ -25,7 +25,7 @@ nothing # hide
 
 # Differential Equations
 
-````@example RobotArm
+```@example RobotArm
 # expressions
 I_t= :((($Q-x1[j])^3+x1[j]^3)/3*sin(x5[j])^2);
 I_p= :((($Q-x1[j])^3+x1[j]^3)/3 );
```

**Comment by huckl3b3rry87** [comment]
@KristofferC and @fredrikekre I am very sorry about this. I assumed that those errors must have had something to do with Documenter because I had never seen them before. I will be sure to test the code in the future.

**Comment by huckl3b3rry87** [comment]
Running that code on m system in the REPL does not throw that error. I have some debugging to do...
