### ISSUE TITLE
deployment experience on Gitlab

### ISSUE THREAD

**Issue by tpapp** [JuliaDocs/Documenter.jl#661]
I have been exploring Gitlab and summarized my solutions in a minimal repository [GitlabJuliaDemo.jl](https://gitlab.com/tkpapp/GitlabJuliaDemo.jl) that demonstrates CI + docs generation + docs deployment.

Some issues I encountered:

1. Documenter.jl needs a `git` binary, so one needs to be installed, either via `apt` or the Docker image. The first option is easy but adds considerably to the build time. I wonder if `Libgit2` could be used instead? But I realize this is a major overhaul.

2. I follow the [suggestion](https://juliadocs.github.io/Documenter.jl/stable/lib/public/#Public-Interface-1) in the manual and use
```julia
repo = "https://gitlab.com/tkpapp/GitlabJuliaDemo/blob/{commit}{path}#L{line}"
```
but get URLs like
```
https://gitlab.com/tkpapp/GitlabJuliaDemo/blob/master/docs/src/index.md#L{line}
```
(ie `{line}` literally}), which also seems to be incorrect, but I don't know what the correct one is. Did the template syntax change?

The bright side: deployment is very easy, just moving the files to `public`, no key setup or anything.

**Comment by mortenpi** [comment]
I'll close this issue, since 2. has been addressed and I opened a dedicated issue for 1. (switching to LibGit2 is a good idea I think). Thanks, by the way, for playing around with Documenter on GitLab and writing these things up -- this is really helpful feedback!
