### ISSUE TITLE
Excessive whitespace in generated docs

### ISSUE THREAD

**Issue by KristofferC** [JuliaDocs/Documenter.jl#668]
In my opinion, the current css creates an excessive amount of whitespace between elements:

<img width="821" alt="screen shot 2018-03-11 at 14 24 29" src="https://user-images.githubusercontent.com/1282691/37253908-45fc32ee-2538-11e8-97db-4328d95316fd.png">

The same can be said for the menu. This causes a lot of scrolling to be needed.

**Comment by mortenpi** [comment]
Note that the whitespace was intentionally added for readability in #518. While not against it per say and the spacing can probably be optimized, I do think that the tiny bit of extra scrolling is not really a issue and readability considerations are more important.
