### ISSUE TITLE
Unresolved html links

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#673]
Getting 9 `!! Invalid local link: unresolved path` on julia master.

---

These 5 are all from the same docstring (https://github.com/JuliaLang/julia/blob/983f0f9f4822635f1a7178dbbd89f3015324e7aa/base/strings/basic.jl#L325-L326)
```
 !! Invalid local link: unresolved path
    'strings.html#Base.isvalid-Tuple{Any}' in base/strings.md
 !! Invalid local link: unresolved path
    'strings.html#Base.ncodeunits-Tuple{AbstractString}' in base/strings.md
 !! Invalid local link: unresolved path
    'strings.html#Base.thisind' in base/strings.md
 !! Invalid local link: unresolved path
    'strings.html#Base.nextind' in base/strings.md
 !! Invalid local link: unresolved path
    'strings.html#Base.prevind' in base/strings.md
```
and the rendered html links becomes
```
doc/_build/html/en/base/base/strings.html#Base.isvalid-Tuple{Any}
doc/_build/html/en/base/base/strings.html#Base.ncodeunits-Tuple{AbstractString}
doc/_build/html/en/base/base/strings.html#Base.thisind
doc/_build/html/en/base/base/strings.html#Base.nextind
doc/_build/html/en/base/base/strings.html#Base.prevind
```
where all of those have an extra `/base` insterted. Note that in the docstring above, the ref to `lastindex` is correct.

---

This one come from [this docstring](https://github.com/JuliaLang/julia/blob/983f0f9f4822635f1a7178dbbd89f3015324e7aa/base/abstractset.jl#L206)
```
 !! Invalid local link: unresolved path
    'collections.html#Base.in' in base/collections.md
```
where the html link again has an extra `/base`: `doc/_build/html/en/base/base/collections.html#Base.in`

---

Next one is from https://github.com/JuliaLang/julia/blob/983f0f9f4822635f1a7178dbbd89f3015324e7aa/base/strings/substring.jl#L109
```
 !! Invalid local link: unresolved path
    'arrays.html#Base.reverseind' in base/arrays.md
```
where we again get `doc/_build/html/en/base/base/arrays.html#Base.reverseind` with an extra `base/`

---

Then from https://github.com/JuliaLang/julia/blob/983f0f9f4822635f1a7178dbbd89f3015324e7aa/base/strings/substring.jl#L107
```
 !! Invalid local link: unresolved path
    'iterators.html#Base.Iterators.reverse' in base/arrays.md
```
which becomes `doc/_build/html/en/base/base/iterators.html#Base.Iterators.reverse` with double `base/`.

---

The last one is a bit different I think
```
 !! Invalid local link: unresolved path
    'arrays.html#Base.permutedims' in stdlib/LinearAlgebra.md
```
which comes from https://github.com/JuliaLang/julia/blob/983f0f9f4822635f1a7178dbbd89f3015324e7aa/stdlib/LinearAlgebra/src/transpose.jl#L156 and the html link becomes `doc/_build/html/en/stdlib/stdlib/arrays.html#Base.permutedims` which should be `doc/_build/html/en/base/arrays.html#Base.permutedims`

This last one is documenting an extended method (`Base.copy`) which is a bit different from the other examples.

**Comment by fredrikekre** [comment]
Hmmm... Actually, I think the problem is that the offending docstrings are included multiple times, at different pages, in the documentation, in different `@docs` block. So trying to restrict this should probably solve the issue.

**Comment by KristofferC** [comment]
I've created a minimum repo for this problem: https://github.com/KristofferC/DocProblem

```
➜  DocProblem git:(master) ✗ tree .
.
├── docs
│   ├── make.jl
│   └── src
│       ├── base.md
│       ├── index.md
│       └── strings
│           └── strings.md
├── src
│   └── DocProblem.jl
└── test
    └── runtests.jl
```

Running documenter on this results in

```
 !! Invalid local link: unresolved path
    'strings/strings.html#DocProblem.Strings.f2' in strings/strings.md
```

without any warnings at markdown template expansion.

In `base.md` we have

````
```@docs
DocProblem.f
```
````

and in `strings/strings.md` we have

````
```@docs
DocProblem.Strings.f(::AbstractString)
DocProblem.Strings.f2
```
````

`DocProblem.Strings.f(::AbstractString)` has a `[@ref]` reference to `DocProblem.Strings.f2`.

The generated HTML docs for `DocProblem.f` includes the `DocProblem.Strings.f(::AbstractString)` method.
When the HTML for `DocProblem.Strings.f(::AbstractString)` is generatated, it uses the one from `base.md` (including the relative links), but these are now wrong because we are in another directory.
