### ISSUE TITLE
HTML comments in html backend

### ISSUE THREAD

**Issue by tknopp** [JuliaDocs/Documenter.jl#674]
HTML comments in the html backend are visible in the resulting documentation. Can this be changed?

**Comment by mortenpi** [comment]
The Markdown parser in Julia does not parse HTML (JuliaLang/julia#17837). Also, this is somewhat a duplicate of #517, but a slightly different use case.

If you need comments in the markdown files then, as a workaround, it should be possible to use `@meta` blocks with just Julia comments:

````markdown
```@meta
# foo
```
````

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing in favor of #517, and because `@meta` is the appropriate tool to use for comments in Markdown files.
