### ISSUE TITLE
depwarns in doctests

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#679]
Documenter does not capture depwarns in the doctest output. I think we should do that, since deprecated documentation is the same as broken documentation.

One way to find these for now is to run julia with `--depwarn=error` becuase we catch errors.

**Comment by mortenpi** [comment]
Where to the depwarns go to though? Doesn't Documenter capture all the stdout/err when `eval()`ing the doctests?

**Comment by fredrikekre** [comment]
It works correctly on julia 0.6 so I think it has to do with the new logging system in Base; we are not redirecting the stream for the logging. Things like this also fails
````
"""
    foo(x)

```jldoctest
julia> @info "Hello"
[ Info: Hello
```
"""
````
