### ISSUE TITLE
UndefVarError: Unicode not defined with Documenter and JuliaPro

### ISSUE THREAD

**Issue by btd1** [JuliaDocs/Documenter.jl#681]
When loading Documenter with using Documenter I get the following error message:

```
INFO: Precompiling module Documenter.
ERROR: LoadError: LoadError: 
UndefVarError: Unicode not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/Documenter/src/Documents.jl, in expression starting on line 18
while loading /Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/Documenter/src/Documenter.jl, in expression starting on line 30
Failed to precompile Documenter to /Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/lib/v0.6/Documenter.ji.
```

How can I resolve this problem?

**Comment by fredrikekre** [comment]
Likely a problem with JuliaPro. What's the output of
```
Pkg.status("Compat")
```
and
```
Pkg.status("Documenter")
```
?

**Comment by btd1** [comment]
Hello !

Here the output:


Pkg.status("Compat")

 - Compat                        0.39.0
Pkg.status("Documenter")

 - Documenter                    0.12.5

best regards
Daniel

Am 21.03.2018 um 11:23 schrieb Fredrik Ekre <notifications@github.com<mailto:notifications@github.com>>:


Pkg.status("Documenter")

**Comment by fredrikekre** [comment]
`Documenter` `v0.12.5` requires `Compat` `v0.58.0`. So you need to upgrade `Compat` to at least `v0.58.0`.

**Comment by btd1** [comment]
It worked (I had to edit the REQUIRE file)!

Thank you
Daniel


Am 21.03.2018 um 11:32 schrieb Fredrik Ekre <notifications@github.com<mailto:notifications@github.com>>:


Documenter v0.12.5 requires Compat v0.58.0. So you need to upgrade Compat to at least v0.58.0.

**Comment by fredrikekre** [comment]
We could update the REQUIRE entry in METADATA, but IIUC that could be problematic and confuse the package manager. This is a rather old version of Documenter anyway, so the solution to this issue is probably to upgrade.

You could try to download JuliaPro 0.6.2.2 and hopefully that version have a newer Documenter version included.

**Comment by fredrikekre** [comment]
I don't think there is anything to do here. It is unfortunate that that release had a mistake in its REQUIRE, but its a rather old release and not worth mixturing with METADATA I think.
