### ISSUE TITLE
Switch over to LibGit2

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#686]
Since LibGit2 is available in core Julia, we should probably use it in `deploydocs` etc., and not depend on the `git` binary. Should make using Documenter on Windows a bit easier and also relevant for container-based builds (e.g. on GitLab, #661).

**Comment by tpapp** [comment]
It seems that even `makedocs` uses `git`, eg with a repo spec like
```julia
    repo = "https://gitlab.com/tkpapp/GitlabJuliaDemo.jl/blob/{commit}{path}#{line}"
```

**Comment by mortenpi** [comment]
Superseded by #2348. LibGit2 is basically deprecated, so we don't want to build on that.
