### ISSUE TITLE
Specialcase InterruptException in order to rethrow them from code blocks being evaluated?

### ISSUE THREAD

**Issue by KristofferC** [JuliaDocs/Documenter.jl#687]
It is quite hard to interrupt a running doc generation because the interrupt exceptions are caught.

```
InterruptException() [src/examples/juliatypes.md]
^C^C !! failed to run code block.

InterruptException() [src/examples/juliatypes.md]
^C !! failed to run code block.

InterruptException() [src/examples/juliatypes.md]
^C !! failed to run code block.
```

etc etc.

Perhaps InterruptExceptions should be rethrown.

**Comment by mortenpi** [comment]
Sounds reasonable. `InterruptException` should never really get thrown by normal doctesting, right? And it's all the at-blocks and doctests where it gets caught, right?

**Comment by KristofferC** [comment]
> InterruptException should never really get thrown by normal doctesting, right?

I don't think so.

>  And it's all the at-blocks and doctests where it gets caught, right?

Yes
