### ISSUE TITLE
Incremental examples

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#694]
It would be very useful if there was an easy way to divide ```` ```@example ```` blocks and delay evaluation of the content. Example
````
```@example test
A = []
for i in 1:10
```

Some text

```@example test
    push!(A)
end
A
```
````
This will not work because the first block is not a complete julia expression. It is possible to kinda simulate this with

````
```@example
A = []
for i in 1:10
    push!(A) # hide
end # hide
A # hide
nothing # hide
```

Some text

```@example test
A = [] # hide
for i in 1:10 # hide
    push!(A)
end
A
```
````
but copy-pasting like that is rarely a good solution.

**Comment by fredrikekre** [comment]
Perhaps a keyword argument? Not sure what it should be called though... `execute = (true|false)` where `true` is default maybe?

**Comment by mortenpi** [comment]
Just as a curiosity: do you have an example of an at-example block in the wild that you would like to split up like this?

`execute` does not feel ideal. Maybe `continued` (as in "continuation line")?

**Comment by fredrikekre** [comment]
> Just as a curiosity: do you have an example of an at-example block in the wild that you would like to split up like this?

Not yet :smile: . But when writing more involved examples with, for example, a function spanning more than  a few lines it can be nice to splice in markdown explaining things, instead of trying to explain the whole chunk in one go either before of after the full function.
