### ISSUE TITLE
Impossible to use `"` in a filter

### ISSUE THREAD

**Issue by tribut** [JuliaDocs/Documenter.jl#696]
It is not possible for the filter regexp to contain an escaped `"` character:

    ```jldoctest; filter = r"^\"[a-zA-Z0-9]+ "
    julia> hello=randstring(8) * " hello world"
    "m8ZmO0MY hello world"
    ```

Results in:

~~~
 > running doctests.
 !! Invalid syntax for doctest keyword arguments in /home/eckhofer/.julia/v0.6/TEM/src/paths.jl:11-13
Use ```jldoctest name; key1 = value1, key2 = value2

```jldoctest; filter = r"^"[a-zA-Z0-9]+ "
julia> hello=randstring(8) * " hello world"
"m8ZmO0MY hello world"
```
~~~

Replacing `\"` by `.` works but of course is not explicitly matching the `"`.

Running julia v0.6.2 and Documenter.jl v0.16.1.

**Comment by fredrikekre** [comment]
In docstrings (`.jl` files) you need to escape the backslash:
````
"""
```jldoctest; filter = r"^\\"[a-zA-Z0-9]{8}"
julia> hello = randstring(8) * " hello world"
"m8Zk0MmY hello world"
```
"""
foo
````
works for me.

**Comment by tribut** [comment]
Ah, you're right. Escaping both the backslash and the `"` appears to work (`\\\"`). Sorry, got confused a bit with the escaping. Feels weird inside a ``` block, but probably makes sense.
