### ISSUE TITLE
Make DOCUMENTER_KEY decoding error more helpful

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#697]
If there's something wrong with `DOCUMENTER_KEY` and Documenter can't decode it, the error is a bit cryptic, e.g.:

```
...
Documenter: setting up target directory.
Documenter: pushing new documentation to remote: github.com/JuliaMath/DoubleFloats.jl.git:gh-pages.
ERROR: LoadError: ArgumentError: malformed base64 sequence
Stacktrace:
 [1] decode_slow(::UInt8, ::UInt8, ::UInt8, ::UInt8, ::Base64.Buffer, ::Int64, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Ptr{UInt8}, ::UInt64, ::Array{UInt8,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/site/v0.7/Base64/src/decode.jl:166
...
```

**Comment by mkborregaard** [comment]
Finding this issue was a great help to me at least!

**Comment by diegozea** [comment]
Hi! I've found that error: https://travis-ci.org/diegozea/MIToS.jl/jobs/463040461 How can I solve it?

**Comment by diegozea** [comment]
I solved the problem in my package by generating a new key as described in https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#SSH-Deploy-Keys-1
