### ISSUE TITLE
Search index for stdlibs in Base not included

### ISSUE THREAD

**Issue by KristofferC** [JuliaDocs/Documenter.jl#704]
![screen shot 2018-04-10 at 11 13 27](https://user-images.githubusercontent.com/1282691/38547767-4016042e-3cb0-11e8-8462-e67502f636ba.png)

Not sure where this issue should be filed but perhaps a Documenter issue?

**Comment by KristofferC** [comment]
Well that would explain it! :D I'll look into why it is excluded.

**Comment by mortenpi** [comment]
The LibGit `index.md` lives directly in `docs/`, not `docs/src`. Arguably, maybe all the stdlib pages should be moved to up to `docs/`, since there are no `make.jl` etc. scripts for stdlib.

**Comment by KristofferC** [comment]
Yeah, I found this too now (https://github.com/JuliaLang/julia/pull/26766). I think the long term plan is to move out the stdlibs to separate repos and then they would presumably have make scripts.
