### ISSUE TITLE
Error when building docs for a non-git folder

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#716]
I get this when building the docs in a folder that have not been `git init`ed. `git init` solves the problem, but probably should not assume we are in a git repo?
```
ERROR: LoadError: MethodError: no method matching startswith(::String, ::Nothing)
Closest candidates are:
  startswith(::String, ::String) at strings/util.jl:49
  startswith(::AbstractString, ::AbstractString) at strings/util.jl:22
  startswith(::AbstractString, ::Union{AbstractChar, Tuple{Vararg{AbstractChar,N} where N}, Set{#s55} where #s55<:AbstractChar, AbstractArray{#s56,1} where #s56<:AbstractChar}) at strings/util.jl:25
Stacktrace:
 [1] (::getfield(Documenter.Utilities, Symbol("##3#4")){String})() at /home/fredrik/.julia/v0.7/Documenter/src/Utilities/Utilities.jl:363
 [2] cd(::getfield(Documenter.Utilities, Symbol("##3#4")){String}, ::String) at ./file.jl:72
```

AFAICT this
https://github.com/JuliaDocs/Documenter.jl/blob/e6d29f8b108d7eccc3c74e39a3de449e182dfa80/src/Utilities/Utilities.jl#L340-L357
is the problematic method, which return `nothing` unless we find a git repo root.

**Comment by fredrikekre** [comment]
Also happens with Pkg3: https://travis-ci.org/KristofferC/Tensors.jl/jobs/370567822

**Comment by mortenpi** [comment]
> probably should not assume we are in a git repo?

Correct. `repo_root`'s behaviour is correct though -- it is supposed to return `nothing` if it's not a repository. But functions calling it need to check that.

In Pkg3 the checked out source trees for the packages are not Git repos anymore, right? Documenter will need quite a few changes to support that, since we're using information from the repo quite a bit.

**Comment by KristofferC** [comment]
It will still be a repo so don't worry :). This came up when trying to make Pkg3 work with the old CI scripts (the ones for the old package manager) , I right now have just tried to not have it as a repo but will likely change that.

**Comment by mortenpi** [comment]
Hmm, locally installed packages will still be in non-repo directories (unless they're in dev mode), right? I don't know how much Pkg3 likes if the contents of those directories is modified, but you might want to build the docs for them.

**Comment by KristofferC** [comment]
As long as the source code is not modified, then it doesn't really matter what happens in the local package folder. But yes, those are non-repo checkouts at specific versions of the package.
