### ISSUE TITLE
Auto generate documentation per file

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaDocs/Documenter.jl#72]
There are cases where it would be useful to auto generate documentation for particular files, allowing more granular control than the current `@autodoc module`.

**Comment by MichaelHatherly** [comment]
Probably using similar syntax to `@index`.

    ```@autodocs
    Pages = ["foo.jl", "bar.jl"]
    ```

Should the docstrings be ordered by line number as well? That can be done on Julia 0.5, but not 0.4 unfortunately.

**Comment by JaredCrean2** [comment]
I think the behavior of the `Order` keyword for `@autodocs` is more useful, although having an option to order by line number would be a neat enhancement in the future.

**Comment by hayd** [comment]
Perhaps `@index` could accept either Modules or Files setting. I don't think this should require a new name? I guess ordering by line number would only be possible/make sense with Files...

**Comment by mortenpi** [comment]
@hayd: `@index` just generates a list of links, whereas `@autodocs` generates full docstrings (like `@docs`), so it doesn't really fit to `@index`. Also, `@autodocs` already exists, so it is just a matter of adding another parameter to it.

**Comment by vchuravy** [comment]
I would love to see this feature. I am currently in the process of transitioning a library to `Documenter` and having this would be lovely.

**Comment by MichaelHatherly** [comment]
I think the interface for `@autodocs` with `Pages` will probably be something like this:

    ```@autodocs
    Modules = [...] # required, otherwise search becomes expensive
    Pages = [...]   # optional
    Order = [...]   # optional
    ```


Ordering of the docstrings will be by `Modules` first then, `Pages`, `Order`, and finally lexicographically. 


Ordering docs on each page by line number won't work on `0.4` since we didn't start tracking line number until recently, so I'll leave that as something to potentially add once `0.5` is out and we've dropped `0.4` support.

**Comment by vchuravy** [comment]
That looks reasonable. My usecase is that my module is not split up in a lot of submodules, but the logical separation is in the files.
