### ISSUE TITLE
“When was the documentation last updated?”

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#724]
If I want to know when a documentation set was built, where should do I look? Say, is there anywhere where a string says “docs generated 2016-12-34” or something? “Stable” is OK, but is there anything in more detail?

(In earlier times, they used to include a [colophon](https://en.m.wikipedia.org/wiki/Colophon_\(publishing\)).)

There is a sneaky way of finding out, I just remembered. But it isn’t obvious...

**Comment by mortenpi** [comment]
The HTML backend has never had a colophon, but this is a feature that would be nice to have, I think. At the moment, the best option would be to check the `gh-pages` branch of the repository. It tracks all the changes and the commit message says which commit was used to build the particular doc. E.g.: https://github.com/JuliaDocs/Documenter.jl/tree/gh-pages

X-ref: #212

**Comment by cormullion** [comment]
I’m think for end users that’s not ideal... :) I do one for Luxor (http://juliagraphics.github.io/Luxor.jl/latest/) for my own benefit, but it might be good to be consistent!

**Comment by fredrikekre** [comment]
Perhaps we can add a footnote, similar to your manually added text, at the index page. Nice way to sneak in some advertisement for Documenter too :)

**Comment by cormullion** [comment]
I’d say go for it; there’s going to be a lot more documentation action in the next few months... :)

**Comment by mortenpi** [comment]
In the HTMLWriter we could do a proper footer as well. Also, in HTML you have the `<meta>` tags too. It would be good to have a list of what information should be displayed there. Julia, Documenter versions, commit/tag of the package, build time?

**Comment by cormullion** [comment]
Also which platform the documentation was generated on? For example I noticed that certain fonts were unavailable when I build on, say, Linux rather than MacOS. Could be useful.
