### ISSUE TITLE
Markdown section in v0.7 docs?

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#725]
I spotted an empty page:

<img width="887" alt="screen shot 2018-05-14 at 11 35 31" src="https://user-images.githubusercontent.com/52289/39992567-21f53304-576b-11e8-94f4-c3723cc1c11c.png">

wasn't sure it was supposed to be empty?

(I suppose you could put "Notes" here... :))

**Comment by fredrikekre** [comment]
This is because that file is empty: https://github.com/JuliaLang/julia/blob/master/stdlib/Markdown/docs/src/index.md so perhaps you can open an issue on `JuliaLang/julia` about documenting the Markdown stdlib?

**Comment by cormullion** [comment]
@fredrikekre Oh, wrong repo, sorry!
