### ISSUE TITLE
markdown output contains excessive amounts of whitespace

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#729]
````
shell> cat src/index.md
# Hello

Some text

```@example index
foo(a, b) = a + b
foo(2, 3)
```
````
turns into
````
shell> cat build/index.md

<a id='Hello-1'></a>

# Hello


Some text


```julia
foo(a, b) = a + b
foo(2, 3)
```

```
5
```

````

Seems like using only one empty line between elements would be enough?

**Comment by fredrikekre** [comment]
I guess the double new line is needed if we have two consecutive lists. Perhaps we can just pre- and append lists with a newline.

**Comment by mortenpi** [comment]
OTOH, it doesn't affect rendered MkDocs output, right? And no one would normally read it, so I am not sure that this is worth changing and making more complicated. Especially since it might break something we have thought about.
