### ISSUE TITLE
Deployment woes

### ISSUE THREAD

**Issue by bramtayl** [JuliaDocs/Documenter.jl#732]
I'm trying to deploy the docs for KeyedTables with so far no success. I'm getting the error: `ERROR: LoadError: ArgumentError: incorrect base64 format, block must be at least 2 and at most 4 bytes` (see https://travis-ci.org/bramtayl/KeyedTables.jl/jobs/385362741#L500). I've tried regenerating the keys several times; bizarrely, this error only happens for KeyedTables; documentation is working fine for all my other packages set up the same way (with OnlinePackage.jl). I'm guessing I'm being thick but I thought I'd ask if anyone knows anything.

**Comment by mortenpi** [comment]
It looks like the key was copied incorrectly -- any chance it is missing or has a few characters extra? Looks like a dup of #697.

**Comment by bramtayl** [comment]
Ok, fixed. Yeah that must have been it.
