### ISSUE TITLE
PDFs with deployed docs

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#734]
Apparently `:latex` can be used to build PDFs from docs, but it doesn't seem like anyone has this working on Travis and there doesn't seem to be a "download PDF" button in the standard template. IMO this should be something that's offered by default, but I can't find out how to get it done.

**Comment by mortenpi** [comment]
Building the PDF on Travis _may_ be problematic. I remember @MichaelHatherly was trying to get Documenter's PDF tests to work there, but the whole Tex Live distro took too long to install and the tests started timing out. But it may not be a problem if the doc building is in a separate build stage and/or happens in a container build.

To fully integrate with the HTML build, the build pipeline needs a bit of redesign, to allow generically combining different writers etc. In principle it's on the [roadmap](https://github.com/JuliaDocs/Documenter.jl/wiki/Documenter.jl-roadmap#document-build-pipeline), but not sure when I get to it.

A first-order solution would be to document how to get this working Travis with another `makedocs` call. `deploydocs` should just copy the `.pdf` from `build/` and deploy it. The user would have to manually link to the PDF from a page though.

**Comment by fredrikekre** [comment]
Works now, see docs.
