### ISSUE TITLE
Header names starting with numbers get the number stripped when the HTML `id` is generated

### ISSUE THREAD

**Issue by anthony-wang** [JuliaDocs/Documenter.jl#744]
I may have noticed a bug when using headers that start with numbers.

Here is the MWE:
```markdown
# Header test
Hi

## Header 1
Hello

## 2nd header
Welp
```

which generates the HTML snippet
```html
<h2><a class="nav-anchor" id="nd-header-1" href="#nd-header-1">2nd header</a></h2>
```

The number "2" is stripped from the header and as a result, the anchor `id` becomes `nd-header-1`.

It should be allowable that an anchor `id` starts with a number, according to [W3C](https://www.w3.org/TR/html5/dom.html#element-attrdef-global-id)

> § 3.2.5. Global attributes
> There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.

Thanks!

**Comment by odow** [comment]
I confirm that this is still a problem with the latest Documenter v1.1.2.
