### ISSUE TITLE
Reduce editDistance to reduce search results?

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#746]
While sometimes the search doesn't return enough results, it often returns too many.

I wonder whether it's worth investigating tweaking the search parameters for the main Julia documentation (stored in `/Applications/Julia-0.7.app/Contents/Resources/julia/share/doc/julia/html/en/assets/search.js` on my computer.) The `editDistance` is 2, but if you change it to 0 (or 1), you get fewer results.

<img width="1594" alt="screen shot 2018-06-21 at 14 39 01" src="https://user-images.githubusercontent.com/52289/41722923-b77a50c6-7561-11e8-98ca-4c039569168a.png">

and sometimes it seems more precise:

<img width="1595" alt="screen shot 2018-06-21 at 14 47 01" src="https://user-images.githubusercontent.com/52289/41723046-03fd7d88-7562-11e8-8edd-0edc1a928dff.png">

(OK, I confess I cherry-picked those two examples where the difference was very noticeable. I don't know how we could find an objective comparison of search results...)

I don't know how the code works, but at the moment it looks like if you search for, say, "fuse", you're getting things like "using", "Base", "flush" because they're "close enough".

Given the generally slow performance of search and the nature of the docs, might it be better to return fewer relevant results more quickly rather than too many fuzzy approximations?

**Comment by mortenpi** [comment]
> I wonder whether it's worth investigating tweaking the search parameters for the main Julia documentation 

Definitely. And help with the search would be much appreciated.

I don't think we should disable fuzzy matching completely though, since we'll start missing e.g. macros (see #560, where `editDistance=2` was added). You could maybe get better results if you treat e.g. function names etc. differently from general text (e.g. disabling fuzzy matching for the latter)? The search index can probably be tuned, so that it would give the most relevant results.

**Comment by cormullion** [comment]
Interesting that Olivernn thought that the `editDistance` setting of 2 might be too high.

**Comment by miguelmorin** [comment]
I would also reduce the `editDistance`: for example today I searched for `alpha` transparency in [Gadfly](http://gadflyjl.org/stable/search.html?q=alpha), got eight results, and after opening each page and searching for `alpha`, I realized that none of the pages had a match.

**Comment by cormullion** [comment]
@miguelmorin I think it's picking up `alias` :(

**Comment by mortenpi** [comment]
With #754 merged, I'll close this. But if there are additional suggestions for search, feel free to open another issue. I'll tag a release and bump the Documenter version in Base in the next few days as well.
