### ISSUE TITLE
Doc-testing without makedocs

### ISSUE THREAD

**Issue by miguelmorin** [JuliaDocs/Documenter.jl#756]
I asked on [StackOverflow](https://stackoverflow.com/questions/50763456/julia-can-i-run-doctests-without-makedocs?noredirect=1#comment88541681_50763456) about doc-testing without makedocs. @fredrikekre there mentioned that this was a possible feature in future versions. I could not find an issue for it and am adding one.

**Comment by fredrikekre** [comment]
See also https://github.com/JuliaDocs/Documenter.jl/wiki/Documenter.jl-roadmap

**Comment by mortenpi** [comment]
Yup, this is on the roadmap and on top of my list actually, but needs some refactoring of the internals. There's some work on [`mp/parse-step`](https://github.com/JuliaDocs/Documenter.jl/tree/mp/parse-step), but it needs to be finished up. I should have some time in the coming 3-4 weeks to finish it off.
