### ISSUE TITLE
git not found on windows even though its there

### ISSUE THREAD

**Issue by Datseris** [JuliaDocs/Documenter.jl#761]
I am trying to create deploy keys for documenter. I am on windows and not on linux.

I have to say it is tremendously difficult. I have spend _several hours_ now, and still had very little progress. The documentation is really not helpful for windows users, there is no information whatsoever. 

So far I have tried to create keys using `puttygen` but travis hangs, requesting passphrase. Seems like the only way to create working keys is using documenter itself.

But that is impossible on windows:

```
julia> using Documenter

julia> Travis.genkeys("JuliaMusic_documentation")

 in module Travis
in #2 at C:\Users\datseris\.julia\packages\Documenter\eULE\src\Travis.jl
ERROR: 'git' not found.
Stacktrace:
 [1] error at .\error.jl:33 [inlined]
 [2] #genkeys#1(::String, ::Function, ::String) at C:\Users\datseris\.julia\packages\Documenter\eULE\src\Travis.jl:49
 [3] genkeys(::String) at C:\Users\datseris\.julia\packages\Documenter\eULE\src\Travis.jl:48
 [4] top-level scope at none:0

shell> git
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

```
latest julia, latest documenter versions.

As a side note, I really have to express that this also makes me feel very unwelcomed: why would there be not a single sentence of support for someone that doesn't use linux? (in the documentation)

**Comment by fredrikekre** [comment]
What is
```
shell> which git
```

**Comment by mortenpi** [comment]
As a workaround, as long as you have `ssh-keygen` available, you should be able to run these commands on Windows to get the keys:

```julia
shell> ssh-keygen -N "" -f privatekey
julia> read("privatekey", String) |> base64encode |>  println # this should become a secure environment variable on Travis called DOCUMENTER_KEY
julia> read("privatekey.pub", String) |> println # this should be added as a Deploy Key on GitHub (https://github.com/$user/$repo/settings/keys)
```

**Comment by mortenpi** [comment]
Closing this in favor of JuliaDocs/DocumenterTools.jl#5
