### ISSUE TITLE
Feature request: executing lines in jldoctest without a result line (like Python)

### ISSUE THREAD

**Issue by miguelmorin** [JuliaDocs/Documenter.jl#766]
Sometimes I want to test part of an object instead of the full structure. So I bind it to a variable first and then test part of it. If I write a test ending with a semicolon and an empty line next, the test passes:

````
```jldoctest
julia> c = (10, 20);

julia> c[1] == 10
true
```
````

But if I omit that empty line, as I would in a Python doc-test, then `c` is not defined:

````
```jldoctest
julia> c = (10, 20);
julia> c[1] == 10
true
```
ERROR: UndefVarError: c = (10, 20);not defined
````

This is similar to #452, but separate in my view.

**Comment by fredrikekre** [comment]
But that is not how it looks in the REPL?

**Comment by miguelmorin** [comment]
No, indeed it is not, and the Python REPL simply omits the empty line. Is the objective to show the code inside ` ```jldoctest` as if it were typed in a REPL?

**Comment by KristofferC** [comment]
Yes, you can copy paste the code from a `jldoctest` straight into the REPL (unless you are on windows, unfortunately).

**Comment by fredrikekre** [comment]
I don' think we will change this.
