### ISSUE TITLE
Question about documenter

### ISSUE THREAD

**Issue by wbhart** [JuliaDocs/Documenter.jl#77]
Hi, thanks for your work on Documenter.jl. Unfortunately after going through a large file and documenting it according to the instructions in the Documenter documentation, no docstrings seem to be inserted when I run "julia build.jl". It displays the following output:

```
Welcome to Nemo version 0.4.0

Nemo comes with absolutely no warranty whatsoever

Documenter: setting up build directory.
Documenter: copying assets to build directory.
Documenter: expanding markdown templates.
Documenter: building cross-references.
Documenter: running document checks.
Documenter: rendering document.
Documenter: skipping docs deployment.
```

In other words, no errors. But the output in build/polynomial.md still contains all the ```@docs ``` blocks and nothing has been replaced.

I wonder if you can give me a hint what I might be missing.

Here [1] is a link to the branch on GitHub with the current documentation we are trying to process with Documenter (the documentation6 branch of our Nemo.jl project).

Thanks in advance for any hints you can give us as to why it doesn't seem to be working.

[1] https://github.com/wbhart/Nemo.jl/tree/documentation6/doc

**Comment by MichaelHatherly** [comment]
What commit is your local copy of `Documenter` on? The `@docs` syntax was recently added, so perhaps you're still using commit that only has the old `{docs}` syntax.

If that's not the problem, I'll build `Nemo` later this evening and see what I can find.

**Comment by wbhart** [comment]
That was indeed the problem. Thanks very much.

**Comment by MichaelHatherly** [comment]
Side note: you can put multiple docs into a `@docs` block, one per line. You don't need to have a separate one for each one, saves a bit of repetitive typing.

**Comment by wbhart** [comment]
Yeah I noticed that when I read the up-to-date docs. Originally I had been
using @{blah} instead of @docs, hence it looks quite basic at the moment
since I'm just attempting to get it to work before I make it more advanced.

We'll submit some feature requests once we get ourselves sorted. For
example, we really wanted to be able to bold the function prototypes in the
docstrings, though perhaps that is something that has to be fixed on the
Julia side first.

**Comment by MichaelHatherly** [comment]
> we really wanted to be able to bold the function prototypes in the docstrings

For those kind of requests #15 is probably the most relevant issue at the moment. Additional work on improving the look of the generated docs will be happening soon, so any additional feature requests/ideas are definitely welcome.
