### ISSUE TITLE
Mistake in Documentation - SSH Deploy Keys

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaDocs/Documenter.jl#778]
This is in the stable documentation as of today, in the section 'SSH Deploy Keys':

> Add the public ssh key to your settings page for the GitHub repository that you are setting up by following the .../settings/key link provided. Click on Add deploy key, enter the name documenter as the title, and copy the public key into the Key field. Note that you should include no whitespace when copying the key. Check Allow write access to allow Documenter to commit the generated documentation to the repo.
> 
> Next add the long private key to the Travis settings page using the provided link. Again note that you should include no whitespace when copying the key. In the Environment Variables section add a key with the name DOCUMENTER_KEY and the value that was printed out. Do not set the variable to be displayed in the build log. Then click Add.

There seems to be two issues here:

For Github to accept the public key there must be a **single space** after "ssh-rsa".

The public key was followed by a space and the name of the computer it was generated on. Both the space and the computer name had to be removed for Github to accept the key.

**Comment by dmbates** [comment]
Furthermore, the documentation indicates that `Travis.genkeys` is in the `DocumenterTools` package which is neither available nor needed in Julia v0.7.0 and later.

**Comment by fredrikekre** [comment]
The stable docs does not say that (I hope).

**Comment by dmbates** [comment]
I should have indicated that this is in the Dev or "Latest" docs.

**Comment by jingpengw** [comment]
I have not found the `Travis` module in Documenter...

**Comment by mortenpi** [comment]
@jingpengw Make sure you are using v0.19.6, the latest _released_ version. `Travis` has been moved to DocumenterTools (unreleased) on master.

**Comment by mortenpi** [comment]
Ref: https://github.com/JuliaDocs/Documenter.jl/pull/779#issuecomment-449533783
