### ISSUE TITLE
Backtrace Information

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#78]
Currently the backtrace information does not tell you where the error occurred. It should tell the file and the line in order to be useful.

![error](https://cloud.githubusercontent.com/assets/1814174/15728705/1ae3d716-2813-11e6-9798-f32a1f10d02b.PNG)

**Comment by MichaelHatherly** [comment]
Better info here would indeed be good. The markdown parser doesn't track line/column info currently though, so would probably need us to search through the original file contents in Documenter itself.
