### ISSUE TITLE
Unicode ∀, ∃ etc. missing in with Roboto Mono in the PDF

### ISSUE THREAD

**Issue by adamryczkowski** [JuliaDocs/Documenter.jl#803]
I suggest changing the monospace font used by the PDF documentation, so the special Unicode strings displayed in e.g. Manual -> Strings -> Unicode and UTF-8.

**Comment by mortenpi** [comment]
Good catch.. Roboto really doesn't have very good Unicode coverage.. related to #618. Would welcome suggestions for what to replace it with though (that would also be freely available cross-platform).

**Comment by mortenpi** [comment]
I don't think Fira Code would be a good choice. While the ligatures are pretty neat, I quite strongly feel that they would confuse the average user who is not familiar with the ligature monospaced fonts. And I don't think there's a way to suppress that feature of the font.

Everson Mono is proprietary unfortunately. [Source Code Pro](https://fonts.google.com/specimen/Source+Code+Pro) showed up on the fileformat.info page though.

**Comment by simonbyrne** [comment]
I'm not sure if it's a good way to check, but I tried pasting the characters `∀✓⊻⊗` into the sample text box on all the Google monospace fonts:

Support all except the `✓`:
- https://fonts.google.com/specimen/Nanum+Gothic+Coding
- https://fonts.google.com/specimen/Nova+Mono
- https://fonts.google.com/specimen/Overpass+Mono

Support all except `⊻`
- https://fonts.google.com/specimen/B612+Mono

**Comment by mortenpi** [comment]
If the result is not too jarring, one option might be to layer several monospace fonts to get better coverage of the different symbols?

**Comment by simonbyrne** [comment]
Actually, the ✓ doesn't need to be monospace, so we could also pick one without that.

**Comment by mortenpi** [comment]
A small clarifying question here: with the current font setup, are the Unicode characters actually not being displayed for you? @adamryczkowski you linked to [Strings / Unicode and UTF-8](https://docs.julialang.org/en/v1/manual/strings/#Unicode-and-UTF-8-1) page as an example in the OP. If yes, what browser and OS is that on?

**Comment by mortenpi** [comment]
So, my current approach is to switch to the DejaVu fonts (#1066) -- the headings don't look as pretty as they could necessarily, but I would say that not having missing characters is more important.

If someone wants to look into changing the build to XeTeX though, that might allow us to have more control over the fonts.
