### ISSUE TITLE
Skipping deployment

### ISSUE THREAD

**Issue by pkofod** [JuliaDocs/Documenter.jl#81]
I'm trying to use Documenter.jl do generate the Optim.jl docs, and I've created a dummy package to do so: https://github.com/pkofod/OptimDoc.jl . However, I can't seem to get it to work. I really tried before posting here, but I'm sure it's a trivial mistake.

I've set up the travis keys, and they seem to be fine. As you can see ( https://travis-ci.org/pkofod/OptimDoc.jl/jobs/134970859 ) the make.jl is run, but it is skipping deployment for some reason. Do you have any idea why that might be?

**Comment by MichaelHatherly** [comment]
Can you add a `DOCUMENTER_DEBUG` key to your travis settings page for that repo with the value `true` and then rebuild the last commit. That should give us some more useful info to work with.

**Comment by pkofod** [comment]
https://travis-ci.org/pkofod/OptimDoc.jl/jobs/134986634 here is the result

```jlcon
The command "julia --color=yes -e "Pkg.build(\"${JL_PKG}\")"" exited with 0.
after_success.1

7.79s$ julia -e 'Pkg.clone("https://github.com/JuliaDocs/Documenter.jl")'

INFO: Cloning Documenter from https://github.com/JuliaDocs/Documenter.jl

INFO: Computing changes...

INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git

INFO: Installing Compat v0.7.20

after_success.2

12.58s$ julia -e 'cd(Pkg.dir("OptimDoc")); include(joinpath("docs", "make.jl"))'

Documenter: setting up build directory.

Documenter: copying assets to build directory.

Documenter: expanding markdown templates.

Documenter: building cross-references.

Documenter: running document checks.

Documenter: rendering document.

 ?? TRAVIS_REPO_SLUG       = "pkofod/OptimDoc.jl"

 ?? TRAVIS_PULL_REQUEST    = "false"

 ?? TRAVIS_OS_NAME         = "linux"

 ?? TRAVIS_JULIA_VERSION   = "release"

 ?? TRAVIS_BRANCH          = "master"

 ?? TRAVIS_TAG             = ""

 ?? git commit SHA         = 45c5350

 ?? GITHUB_API_KEY exists  = false

 ?? .documenter.enc path   = /home/travis/.julia/v0.4/OptimDoc/docs/.documenter.enc

 ?? .documenter.enc exists = true

 ?? should_deploy          = false

Documenter: skipping docs deployment.

```

**Comment by MichaelHatherly** [comment]
The `nightly` build got further https://travis-ci.org/pkofod/OptimDoc.jl/jobs/134986635

By default `Documenter` tries to deploy docs from the `nightly` build.

From the error that that build gave it looks like the public key hasn't been added to the github repo. 

    ...
    Permission denied (publickey).
    ...

Did you add the public key to https://github.com/pkofod/OptimDoc.jl/settings/keys?

**Comment by pkofod** [comment]
It would appear I did not. I'll try to fix it.

**Comment by MichaelHatherly** [comment]
Once you've copied the contents of `docs/.documenter.pub` into a new key on that settings page, would also be good to delete the public key file as well. Only the `.enc` file needs to be checked in for things to work.

**Comment by pkofod** [comment]
Thank you for the help! http://pkofod.github.io/OptimDoc.jl/latest/

**Comment by MichaelHatherly** [comment]
Nice!

**Comment by pkofod** [comment]
Yeah. Most of the stuff in there is only added to test individual features. I will fill in the blanks soon :)
