### ISSUE TITLE
How to generate module documentation in the PDF format from the command line?

### ISSUE THREAD

**Issue by adamryczkowski** [JuliaDocs/Documenter.jl#810]
I am still very new to the Julia ecosystem and what I want is to be able to read the Module documentation on my e-book reader. 

I can build the Julia's current manual in the PDF format, so I guess I know how to satisfy all the system dependencies. 

But to build the Julia's manual is relatively self-explanatory: there is a `Makefile` in the `docs` folder with the `pdf` target, so I immidately guessed how to build it: `make pdf`. 

What I miss is how to invoke the PDF build process of the module, where the only file in the `docs` folder is `make.jl`. 

Invoking `julia make.jl pdf` does not work. It only produces `html` format.

**Comment by mortenpi** [comment]
You usually have to modify the `format` option for `makedocs` in `make.jl`. So, it should be `makedocs(format=:latex)`.

**Comment by fredrikekre** [comment]
This should now be sufficiently documented here: https://juliadocs.github.io/Documenter.jl/stable/man/other-formats/#PDF-Output-via-LaTeX-1
