### ISSUE TITLE
Question about default output precision in v1.0

### ISSUE THREAD

**Issue by mforets** [JuliaDocs/Documenter.jl#811]
Hello,
With the v0.7/v1.0 upgrade, we found that some doctests fail due to different default behavior of the output precision in the REPL mode (see example below). Is there a recommended workaround with `Documenter`? Such as specifying the error tolerance? Thanks.

```julia
julia> using LazySets

julia> B = Ball2(zeros(5), 0.5)
LazySets.Ball2{Float64}([0.0, 0.0, 0.0, 0.0, 0.0], 0.5)
```

v0.6:

```julia
julia> σ([1.,2.,3.,4.,5.], B)
5-element Array{Float64,1}:
 0.06742
 0.13484
 0.20226
 0.26968
 0.3371
```

v0.7:

```julia
julia> σ([1.,2.,3.,4.,5.], B)
5-element Array{Float64,1}:
 0.06741998624632421
 0.13483997249264842
 0.20225995873897262
 0.26967994498529685
 0.3370999312316211
```

**Comment by fredrikekre** [comment]
It is not Documenter that changed, it is Julia Base. Can't you just update the examples?

**Comment by mforets** [comment]
I can update the examples, but then i have to give up on having a "transition" release that supports both julia  versions for all `@jldoctest` examples (like what `Compat` allows us to do).

**Comment by fredrikekre** [comment]
You can choose to run the doctest on only one system (that is what most packages do I think)
