### ISSUE TITLE
Spurious warnings in at-repl blocks

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#812]
A potential bug that only appears to show up on 0.7. If there are empty lines in at-repl blocks, you get warnings:

```
┌ Warning: Deprecated syntax `underscores as an rvalue`.
└ @ none:0
```

Ref: JuliaCollections/DataStructures.jl#436, cc @scls19fr

**Comment by fredrikekre** [comment]
Doesn't happen on Julia 1.0 so...
