### ISSUE TITLE
How to get custom.sty used by the LaTeX format?

### ISSUE THREAD

**Issue by adamryczkowski** [JuliaDocs/Documenter.jl#814]
I want to track changes made to the documentation between two Julia versions. For this I used `latexdiff` on both versions of the `TheJuliaLanguage.tex` LaTeX sources of the PDF documentation.

Then I invoked LaTeX with `perl /usr/bin/latexmk -f -interaction=nonstopmode -view=none -lualatex -shell-escape diff.tex`

The `.tex` files use two Julia-specific styles: `documenter.sty` - which is easily found in the `Documenter.jl` repository - and the mysterious `custom.sty` which is nowhere to be found.

I understand that the former supplementary LaTeX file is somehow generated by the Julia during the documentation process. The question is how to generate it manually, so one can generate PDF from `.tex` source manually.

**Comment by mortenpi** [comment]
I think `custom.sty` is just an empty file by default. I think it is meant for including user-provided commands (i.e. that the user could customize the LaTeX build).

https://github.com/JuliaDocs/Documenter.jl/blob/924d99b36841999c0126b87f7a3f4de53910fe94/src/Writers/LaTeXWriter.jl#L92-L115

**Comment by adamryczkowski** [comment]
Thank you! It works.
