### ISSUE TITLE
Develop a parser for reStructuredText in Julia

### ISSUE THREAD

**Issue by laurentheirendt** [JuliaDocs/Documenter.jl#821]
As discussed with @mortenpi, the idea is to develop a parser in Julia for `.rst` files.

According to Morten, this parser should 

> live in a separate package and provides a `parse()` function that parses a file / string into a tree-like data structure. The Markdown parser in base can be used as a source of inspiration I suppose

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing as stale and because this seems like a very low priority. Adding a new parser is a very big job that I don't think we want to start on.

**Comment by mortenpi** [comment]
It doesn't look like there's too much interest in this. But if anyone does want to do it, or something similar for some other markup language, then nowadays the approach would be to implement this as a separate package that parses into MarkdownAST. That could then basically be fed into Documenter.
