### ISSUE TITLE
Generating ssh key on Windows

### ISSUE THREAD

**Issue by odow** [JuliaDocs/Documenter.jl#827]
I just spent the last wee while bashing my head against this. I had done it a while ago and didn't think to write it down because it seemed obvious. When I went to do it again it wasn't so obvious.

I'm busy this afternoon but I will try to add a section to the docs going through this when I get the chance.

Here are the steps I took:
## Generate a key
1.	Open PuTTY Key Generator. ([Download link](https://www.ssh.com/ssh/putty/windows/puttygen).)
![image](https://user-images.githubusercontent.com/8177701/45131792-a09a6b80-b1e2-11e8-885b-499237651c29.png)
2.	Click Generate, and follow the instructions, moving the mouse around to create randomness.

## Add the public key to Github
3.	To go https://github.com/[YOUR_USER_NAME]/[YOUR_REPO_NAME]/settings/keys and click `Add deploy key`
![image](https://user-images.githubusercontent.com/8177701/45131985-4fd74280-b1e3-11e8-9d95-46539845ee3a.png)
4.	Make the title `documenter`
5.	Copy and paste the highlighted text from PuTTY beginning with ssh-rsa into the key 
![image](https://user-images.githubusercontent.com/8177701/45131800-a728e300-b1e2-11e8-8d40-dbb4fa383ff5.png)
6.	Click allow write access
7.	Click Add key

## Add the private key to travis
8.	Go back to the PuTTY Key Generator. Under the `Conversions` tab, click `Export OpenSSH key`. Click through the prompt that says you are saving without a password (Travis needs a key with no passphrase). Save that key somewhere.
![image](https://user-images.githubusercontent.com/8177701/45131813-b4de6880-b1e2-11e8-82bd-ec8ceb44a976.png)
9.	Run `Julia> Documenter.base64encode(readstring(“path/to/the/private/key”))`
10.	Open https://travis-ci.org/[YOUR_USER_NAME]/[YOUR_REPO_NAME]/settings 
![image](https://user-images.githubusercontent.com/8177701/45132034-801ee100-b1e3-11e8-8152-b407f0e89770.png)
11.	Under the `Environment Variables` heading, add an environment variable. The name should be `DOCUMENTER_KEY` and the value should be the output of the Julia command from step 9 (make sure to remove the surrounding quotes).
12.	Check that the “Display value in build log” is switched off and then click Add.

**Comment by mortenpi** [comment]
Ideally `DocumenterTools.Travis.genkeys` would just work on Windows, but there will always probably be setups where it does not. Having a walkthrough like this would be handy! A subpage of [Hosting Documentation](https://juliadocs.github.io/Documenter.jl/latest/man/hosting/) perhaps?

Do you think it would make sense to split it up a bit? There are things that are platform-independent (adding keys to GitHub/Travis), and might also be useful for non-Windows users.

There is also a snippet you can use as long as you have `ssh-keygen` available: https://github.com/JuliaDocs/Documenter.jl/issues/761#issuecomment-404195667 Might be good to have that as well as one of the alternatives.

**Comment by odow** [comment]
That all sounds good. 

The only platform dependent bit is generating the key. The bit that stumped me is needing to export the private key rather than just clicking the obvious save private key button.
