### ISSUE TITLE
Markdown lists and code blocks

### ISSUE THREAD

**Issue by KarolisM** [JuliaDocs/Documenter.jl#830]
Example:
1. Install conda:
```bash
   wget -P miniconda https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh &&
   chmod 755 ./miniconda/Miniconda3-latest-Linux-x86_64.sh &&
   ./miniconda/Miniconda3-latest-Linux-x86_64.sh
````
2. Continue ...

This numeration should work with a code block. Although it does not seem to with a Documenter.jl. List numeration is reset after a code block.

Thanks.

**Comment by fredrikekre** [comment]
You need to indent code too, just like normal text, in lists.

**Comment by KarolisM** [comment]
Thanks @fredrikekre  but still with indentation:

1. Install `conda`:
    ```bash
       wget -P miniconda https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh &&
       chmod 755 ./miniconda/Miniconda3-latest-Linux-x86_64.sh &&
       ./miniconda/Miniconda3-latest-Linux-x86_64.sh
    ```

2. Add path...

Result is:

![image](https://user-images.githubusercontent.com/8409950/45547630-15485800-b82a-11e8-94cd-51d16027dfc2.png)

While expected to be:
![image](https://user-images.githubusercontent.com/8409950/45547661-33ae5380-b82a-11e8-9925-ea130c624432.png)

Any other suggestions? 
Thank you.

**Comment by fredrikekre** [comment]
Indent 3 spaces, not 4.
