### ISSUE TITLE
I get told to  to set DOCUMENTER_DEBUG for more info even if it is already set

### ISSUE THREAD

**Issue by oxinabox** [JuliaDocs/Documenter.jl#836]
I think this is caused by
https://github.com/JuliaDocs/Documenter.jl/blob/2a986d0fc03568d3ade30ece6b065282922e6ff8/src/Documenter.jl#L473

Not actually checking if it is already set.

It is a bit confusing being told to do something I have already done.
Unless there is a check, and I have just screwed up setting the environment variable in Travis somehow.

**Comment by fredrikekre** [comment]
Yea I am planning to completely rewrite this soonish.
