### ISSUE TITLE
Followed the docs and didn't get the same results

### ISSUE THREAD

**Issue by TheOnlyArtz** [JuliaDocs/Documenter.jl#846]
Hey, so I've followed the docs on how to get started with an example.
And when I call `makedocs()` all the files are being generated except from `index.md`
and the documentation clearly says it should create an `index.md` file.
What am I doing wrong?
**src/test.jl**
https://hastebin.com/beqacixoho.jl

**make.jl**

```julia
using Documenter

makedocs()
```
Build/ has everything the docs says it should except `index.md`

**Comment by fredrikekre** [comment]
Did you have an `index.md` to begin with?

**Comment by TheOnlyArtz** [comment]
> Did you have an `index.md` to begin with?

No? I thought Documenter should generate it as an initial file, so I got it now thanks.
