### ISSUE TITLE
docs/build in GitHub gitignore template?

### ISSUE THREAD

**Issue by yakir12** [JuliaDocs/Documenter.jl#857]
See my attempt and the question it spurred [here](https://github.com/github/gitignore/pull/2833#discussion_r224765451). It's a good question. I mean, would you say it's totally wrong for someone to locally build their docs and then push those to github to serve and that letting CI do that is the *only* correct way? If so then yes, we should add those to the "official" gitignore for Julia.

**Comment by mortenpi** [comment]
If you are using Documenter for your package, you should definitely have the output directories in `.gitignore`. Pushing Documenter-generated docs to the master/code branches is definitely wrong I'd say.

However, my question is whether Documenter should be considered standard enough that it should be in the default `.gitignore`? Not all packages use Documenter, especially many small ones where a simple README is sufficient.

**Comment by yakir12** [comment]
Yea, I think you're right. I'll close that PR.
