### ISSUE TITLE
Missing `index.html` with hyperlinks in Documenter v0.20

### ISSUE THREAD

**Issue by blegat** [JuliaDocs/Documenter.jl#868]
I have tried updating [MathOptInterface](https://github.com/JuliaOpt/MathOptInterface.jl) to Documenter v0.20: https://github.com/JuliaOpt/MathOptInterface.jl/pull/552
The transition went smoothly and the `make.jl` got largely simplified but when trying locally (I assume the same happens when it is built on Travis), I noticed that links do not work.
For instance, the `Manual` link from the index redirects to
```
file:///home/blegat/.julia/dev/MathOptInterface/docs/build/apimanual/#Manual-1
```
instead of
```
file:///home/blegat/.julia/dev/MathOptInterface/docs/build/apimanual/index.html#Manual-1
```
Looking at the the doc build with Documenter v0.19 at
http://www.juliaopt.org/MathOptInterface.jl/stable/index.html
it used to redirect to
http://www.juliaopt.org/MathOptInterface.jl/stable/apimanual.html#Manual-1
When looking at the Documenter doc, it seems that the link does not contain `index.html` but it works without it.

**Comment by fredrikekre** [comment]
From the changelog:

> * ![BREAKING][badge-breaking] "Pretty URLs" are enabled by default now for the HTML output. The default value of the `html_prettyurls` has been changed to `true`.
> 
>   For a page `foo/page.md` Documenter now generates `foo/page/index.html`, instead of `foo/page.html`.
>   On GitHub pages deployments it means that your URLs look like  `foo/page/` instead of `foo/page.html`.
> 
>   For local builds you should explicitly set `html_prettyurls = false`.
> 
>   **For upgrading:** If you wish to retain the old behavior, set `html_prettyurls = false` in `makedocs`. If you already set `html_prettyurls`, you do not need to change anything.

To do this automatically you can set something like
```
html_prettyurls = get(ENV, "HAS_JOSH_K_SEAL_OF_APPROVAL", nothing) == "true"
```
(or choose some other by default defined environment variable on travis, like `TRAVIS`, see https://docs.travis-ci.com/user/environment-variables#default-environment-variables)

**Comment by blegat** [comment]
Indeed, I missed it from the CHANGELOG, thanks !

**Comment by scls19fr** [comment]
Maybe we could have a test web server which handle properly pretty url, ie instead of opening build/index.html in a browser we could run a local web server and browse doc at http://127.0.0.1:portnumber or something like that
