### ISSUE TITLE
Display number of line or any tip to find error more easily

### ISSUE THREAD

**Issue by scls19fr** [JuliaDocs/Documenter.jl#872]
Hello,

When compiling doc I'm getting

```
julia --color=yes make.jl
Documenter: setting up build directory.
Documenter: expanding markdown templates.
Documenter: building cross-references.
 !! No doc found for reference '[`pipeline`](@ref)'. [src/index.md]
Documenter: running document checks.
 > checking for missing docstrings.
 > running doctests.
 > checking footnote links.
Documenter: populating indices.
Documenter: rendering document.
 !! Invalid local link: unresolved path
    '@ref' in index.md
Documenter: skipping docs deployment.
Documenter: You can set DOCUMENTER_DEBUG to "true" in Travis to see more information.
```

https://github.com/JuliaDocs/Documenter.jl/blob/8a56ec8f815d584606b7480a09de96a92a09a3a9/src/CrossReferences.jl#L161

https://github.com/JuliaDocs/Documenter.jl/blob/2a986d0fc03568d3ade30ece6b065282922e6ff8/src/Writers/HTMLWriter.jl#L1096

It can be hard to find exactly where error is.
Maybe displaying number of line could help to find more easily where error is.

Kind regards

**Comment by mortenpi** [comment]
Dup of #248 and #78.

**Comment by Jollywatt** [comment]
I think this issue should be reopened. As of `Documenter.jl` v1.1.0, we still have to put up with these kinds of messages for failed `@ref`s:

```
┌ Error: no doc found for reference '[`graded_prod`](@ref)' in src/reference.md.
└ @ Documenter ~/.julia/packages/Documenter/9kOxY/src/utilities/utilities.jl:44
```

Very hard to track down 1) where and 2) why this is failing. (In my case, `graded_prod` is a function with a docstring. Frustrating!)
