### ISSUE TITLE
`linkcheck` checks non-HTTP URLs but can only verify HTTP URLs

### ISSUE THREAD

**Issue by iamed2** [JuliaDocs/Documenter.jl#873]
```julia
doc = Documenter.Documents.Document(; linkcheck=true)
link = md"[IANA](ftp://ftp.iana.org/tz/data/etcetera)".content[1].content[1]
Documenter.DocChecks.linkcheck(link, doc)
```
gives
```
 !! invalid result returned by `curl -sI ftp://ftp.iana.org/tz/data/etcetera`:

Last-Modified: Sat, 27 Oct 2018 12:10:09 GMT
Content-Length: 2790
Accept-ranges: bytes

false
```
This is a valid FTP response. I think `linkcheck` should either not handle non-HTTP(S) URLs, support FTP, or use some other measure of success.

**Comment by mortenpi** [comment]
As a quick fix, filtering out non-`http`/`https` protocols would work. I'd say we are currently only promising that HTTP(S) URLs are checked.

**Comment by mortenpi** [comment]
`curl` uses heuristics to guess which protocol to use in that situation though. We could require the protocol to be specified in the general case and restrict `curl` to HTTP/HTTPS for URLs that do not specify the protocol.

Also, note that I am in no way opposed to supporting link checking for additional protocols. But there will always be protocols that we do not support, so we should also have a resonable fallback behaviour.
