### ISSUE TITLE
Index not getting all @docs blocks

### ISSUE THREAD

**Issue by joa-quim** [JuliaDocs/Documenter.jl#875]
Hi, sorry for double posting. I posted this first in Discourse but got no answer and message was getting out of sight.

I’ve been fighting with Documenter for a while but can’t understand why it does what it does. The problem starts, and this is probably a good symptom of the root issue, with the fact that in my index.mb file the instruction ```@index ``` does not generate any index. So I had to go for the solution of creating @docs [blocks for each function](https://github.com/GenericMappingTools/GMT.jl/blob/master/docs/src/index.md) that I want documented. And here comes the puzzling part. I have > 80 functions and methods to pick up but Documenter only accepts with ~40. For the remaining it prints

```
Documenter: expanding markdown templates.
 !! No docs found for 'filter1d(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
 !! No docs found for 'fitcircle(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
...
```

and later
```
 > checking for missing docstrings.
 !! 45 docstrings potentially missing:

    GMT.sample1d :: Union{Tuple{}, Tuple{String}, Tuple{String,Any}}
    GMT.gmtselect :: Union{Tuple{}, Tuple{String}, Tuple{String,Any}}
    GMT.gmtconnect :: Union{Tuple{}, Tuple{String}, Tuple{String,Any}}
    GMT.grid_type :: Union{Tuple{Any}, Tuple{Any,Any}}
    GMT.grdfft :: Union{Tuple{}, Tuple{String}, Tuple{String,Any}, Tuple{String,Any,Any}}
    GMT.grdfilter :: Union{Tuple{}, Tuple{String}, Tuple{String,Any}}
...
```

but I can’t see any difference between the docstrings that it accepts and those the it ignores (what’s wrong in, for example, [filter1d ](https://github.com/GenericMappingTools/GMT.jl/blob/master/src/filter1d.jl#L1)?). In fact, for testing, I even renamed one that it accepts to one it ignores and and this latter was then ignored. This proves that the refusal is not based on the docstrings contents.

The full list of indexed files can be seen [here ](https://genericmappingtools.github.io/GMT.jl/latest/#Index-1)and the ensemble of all that should be indexed [here](https://github.com/GenericMappingTools/GMT.jl/tree/master/src).

I really can’t figure out why some are considered good, and indexed, while others are stubbornly ignored.

Thanks for any help to fix this.

**Comment by mortenpi** [comment]
at-index only generates an index of docstrings that are already spliced into the page. Were you looking for [at-autodocs](https://juliadocs.github.io/Documenter.jl/latest/man/syntax/#@autodocs-block-1) by any chance?

For the explicitly included docstrings -- your signatures may be too specific. But actually I do not exactly know how the signature matching work off the top of my head. We were discussing the rules a bit in #839.

**Comment by joa-quim** [comment]
Thanks, yes autodocs did it.

Regarding the signatures, they are mostly equal and equal to those that have been found. A small example below.

```
 !! No docs found for 'filter1d(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
 !! No docs found for 'fitcircle(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
 !! No docs found for 'gmt2kml(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
 !! No docs found for 'gmtconnect(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
 !! No docs found for 'gmtconvert(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
 !! No docs found for 'gmtread(fname::String, data; kwargs...)'. [src\index.md]
 !! No docs found for 'regress(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
 !! No docs found for 'gmtselect(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
 !! No docs found for 'gmtset(cmd0::String="", kwargs...)'. [src\index.md]
 !! No docs found for 'gmtsimplify(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
 !! No docs found for 'gmtspatial(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
 !! No docs found for 'gmtvector(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
 !! No docs found for 'gmtwich(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
 !! No docs found for 'grd2cpt(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
 !! No docs found for 'grd2kml(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
 !! No docs found for 'grd2xyz(cmd0::String="", arg1=[], kwargs...)'. [src\index.md]
...
```
