### ISSUE TITLE
consider adding documentation for NLOptControl.jl to examples

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaDocs/Documenter.jl#880]
Hi, I was looking at your examples:
https://juliadocs.github.io/Documenter.jl/stable/man/examples/#Registered-1

And I thought that maybe you want to add in NLOptControl.jl. It used Documentor to show how to solve and plot optimal control problems, here is an example
https://juliampc.github.io/MPCDocs.jl/latest/tutorials/RobotArm/main.html#Post-Process-1

what do you think?

**Comment by fredrikekre** [comment]
Right above the list you linked to:
>  If you have a package that uses Documenter then please open a PR that adds it to the appropriate list below; a simple way to do so is to navigate to https://github.com/JuliaDocs/Documenter.jl/edit/master/docs/src/man/examples.md.

So feel free to make a PR!

**Comment by huckl3b3rry87** [comment]
cool! thanks!!
