### ISSUE TITLE
sitename missing from makedocs docstring

### ISSUE THREAD

**Issue by tpapp** [JuliaDocs/Documenter.jl#883]
I think `makedocs(sitename = ...)` is still required, but is no longer mentioned at 
https://juliadocs.github.io/Documenter.jl/dev/lib/public/

**Comment by tpapp** [comment]
Friendly bump --- until a decision is reached, would it make sense to mention `sitename` in the docstring of `makedocs`? It is still used and even tested for.

**Comment by fredrikekre** [comment]
Yea, please make a PR.
