### ISSUE TITLE
docs not deployed

### ISSUE THREAD

**Issue by tpapp** [JuliaDocs/Documenter.jl#884]
For my package https://github.com/tpapp/LogDensityProblems.jl I think I am using the v0.20 recommended setup, yet for some reasons the relevant directory in the `gh-pages` branch contains [only a siteinfo.jl](https://github.com/tpapp/LogDensityProblems.jl/tree/gh-pages/dev). [Travis logs](https://travis-ci.org/tpapp/LogDensityProblems.jl/jobs/452274993) look OK (to me).

**Comment by fredrikekre** [comment]
From the latest Travis log:
> Documenter: New docs identical to the old -- not committing nor pushing.

**Comment by fredrikekre** [comment]
I think you are missing a call do `docs/make.jl` here: https://github.com/tpapp/LogDensityProblems.jl/blob/00ecf5e0065c1ef1c8b13e12f76f1ae77f405752/.travis.yml#L34 so you are just deploying an empty folder I think (?).

**Comment by tpapp** [comment]
Thanks, that helped me figure out what is going on. I was calling `makedocs` in the tests, and expected that to be available for deployment. But with the new setup that is in a different pass, so I expect it has a clean slate.

Incidentally, if I want to tests docs generation and generate the docs anyway in the tests, is there a way  to use that for deployment? Or do I have to regenerate again?

**Comment by fredrikekre** [comment]
> But with the new setup that is in a different pass, so I expect it has a clean slate.

Yea, no data is preserved between build stages.

> Incidentally, if I want to tests docs generation and generate the docs anyway in the tests, is there a way to use that for deployment? Or do I have to regenerate again?

Why can't you do this in the next stage only?

**Comment by tpapp** [comment]
I want to have a "failed" build status if doctests/generation fails. Does that happen anyway with the recommended travis config?

**Comment by fredrikekre** [comment]
Yes, it does, see https://discourse.julialang.org/t/psa-use-a-project-for-building-your-docs/14974.

**Comment by tpapp** [comment]
Thanks for your help. Closing the issue.
