### ISSUE TITLE
Rendering of bullets after line breaks

### ISSUE THREAD

**Issue by kescobo** [JuliaDocs/Documenter.jl#894]
Often, one wants to add new lines in the plain text that are not rendered as new lines in html. Documenter seems to treat these differently than other markdown renderers. For example:

```
# Test Doc

- A bullet
- Long bullet text **not**
    wrapped to new line
- Long bullet text
wrapped to new line
```

In the markdown formatters I'm familiar with, the 2nd and third bullets are rendered the same - the 4 spaces in the second bullet don't change anything. Eg, in Atom's markdown preview:

<img width="632" alt="screen shot 2018-11-29 at 9 40 49 am" src="https://user-images.githubusercontent.com/3502975/49229388-5f69c000-f3bb-11e8-91e1-445d5d47c2fd.png">

But documenter treats them differently:

<img width="352" alt="screen shot 2018-11-29 at 9 41 03 am" src="https://user-images.githubusercontent.com/3502975/49229434-7c9e8e80-f3bb-11e8-8ebd-2dcb606a516d.png">

This isn't a major issue - I actually like the inclusion of some whitespace to indicate that the content is supposed to go with the previous line. It just caused me some confusion when my docs were rendered in a way I wasn't expecting (and in a way that's different from the preview I was using to edit).

**Comment by KristofferC** [comment]
This would need to be fixed in the `Markdown` stdlib in Julia base.

**Comment by kescobo** [comment]
Ahh, ok - Better to close this issue and open one there?

**Comment by KristofferC** [comment]
Yeah, I think so. The MWE could be

```jl
julia> using Markdown

julia> md = Markdown.parse("""
       - Long bullet text
       wrapped to new line
       """);

julia> md.content
2-element Array{Any,1}:
 Markdown.List(Any[Any[Paragraph(Any["Long bullet text"])]], -1, false)
 Markdown.Paragraph(Any["wrapped to new line"])                        

julia> md
    •    Long bullet text

  wrapped to new line
```

**Comment by kescobo** [comment]
Stdlib issue: https://github.com/JuliaLang/julia/issues/30198
