### ISSUE TITLE
.HTML(prettyurls=false) not working

### ISSUE THREAD

**Issue by kescobo** [JuliaDocs/Documenter.jl#895]
I was trying to follow the [note section here](https://github.com/JuliaDocs/Documenter.jl/blob/master/docs/src/man/guide.md#building-an-empty-document) regarding local preview of docs:

````
2. You can disable the pretty URLs feature by passing `prettyurls = false` with the
   [`Documenter.HTML`](@ref) plugin:

   ```julia
   makedocs(..., Documenter.HTML(prettyurls = false))
   ```
````

But I've got an error:

```
julia> include("make.jl")
ERROR: LoadError: MethodError: no method matching HTML(; prettyurls=false)
Closest candidates are:
  HTML(::T) where T at docs/utils.jl:23 got unsupported keyword argument "prettyurls"
  HTML(::Any...) at docs/utils.jl:27 got unsupported keyword argument "prettyurls"
Stacktrace:
```

My entire `make.jl` file so far is just:

```
using Documenter

makedocs(
    sitename="Klepac-Ceraj Lab Documentation",
    pages=[
        "Home" => "index.md"],
    Documenter.HTML(
        prettyurls = false)
    )
```

The python webserver option works for now, but this feature would be nice. I tried digging around in the sourcecode, but couldn't make heads nor tails of it. The [HTML writer stuff](https://juliadocs.github.io/Documenter.jl/latest/search/?q=prettyurl) in the docs didn't help me much either. I'm sure there's something simple I'm missing.

**Comment by KristofferC** [comment]
Aren't you looking at the dev documentation instead of the latest release documentation?

**Comment by fredrikekre** [comment]
https://juliadocs.github.io/Documenter.jl/v0.20/

**Comment by kescobo** [comment]
🤦‍♀️
