### ISSUE TITLE
No way to skip checking output of script with doctest

### ISSUE THREAD

**Issue by galenlynch** [JuliaDocs/Documenter.jl#910]
I can't find a way to not check the output of a script in a doctest. For the sake of example, I would like to be able to do something like:
```julia
```jldoctest; output = false
A = rand(5)
B = rand(5)
A + B

# output

[...]
``` #end of jldoctest
```

Looking at [`eval_script`](https://github.com/JuliaDocs/Documenter.jl/blob/5a29390aa1dd5253269195698041c1f1506d787a/src/DocTests.jl#L182) makes it seem like it's impossible to ignore the output, which if I understand is controlled by `result.hide`.

**Comment by KristofferC** [comment]
Maybe I am being dense, but If you don't want to check the output, why is it a `jldoctest`?

**Comment by galenlynch** [comment]
It's for an example of how to construct a filter object. The filter values don't really matter, but it would be nice to check that the steps to build the filter are valid (I.e. prevent the documentation from not matching the API). There doesn't seem to be a way to check just the first part of the filter array, or the type of the returned value either.

**Comment by KristofferC** [comment]
You could perhaps seed the random number generator so that the numbers are the same every time it is run, or alternatively use the filtering: https://juliadocs.github.io/Documenter.jl/stable/man/doctests/#Filtering-Doctests-1.

**Comment by galenlynch** [comment]
Ok filtering seems reasonable here. In general, when demonstrating an api, I think that showing the return value may not be informative if the value is large or complicated to display. Nonetheless it would be nice to check that the API still matches the example. You can achieve this with single statement examples by appending a semicolon to the doctest, but if the example is a 'script' with multiple statements then it's not currently possible (from what I can tell). The utility is the same in both cases, but for scripts it's not yet implemented.

**Comment by mortenpi** [comment]
It should be possible to use an [at-example block](https://juliadocs.github.io/Documenter.jl/latest/man/syntax/#@example-block-1) for this, if you really do not care about the output:

```@example
A = rand(5)
B = rand(5)
A + B
nothing # hide
```

The `nothing # hide` part will make the block return `nothing`, which hides the output, and `#hide` hides that line in the input block. Documenter should still fail to build the docs if it fails to evaluate the at-example block.

**Comment by galenlynch** [comment]
Thanks @mortenpi that's exactly what I want.
