### ISSUE TITLE
Build stages deletes data

### ISSUE THREAD

**Issue by bramtayl** [JuliaDocs/Documenter.jl#918]
The new recommended work flow, to build documentation in a second build stage, seems great, but I'm having some trouble.

I used run makedocs in test/runtests.jl, with  `root = joinpath(dirname(@__DIR__), "docs")` and `strict = true`. This allowed me to include doctests as part of the regular testing suite, and also have them count for coverage.

That doesn't work anymore; the documentation is entirely deleted and I have to start again in the second build stage. Is there any good solution here?

**Comment by mortenpi** [comment]
There is no way to store state between stages (unless you set something up yourself with S3 or something), but build stages is just a recommendation for the common case. You can still keep the old workflow, where you run documentation as part of tests or in `after_success:`.

In the future, we can hopefully provide a lightweight way to run doctests -- I have a WIP PR for that which I need to get back to (#774).

**Comment by bramtayl** [comment]
I pretty easy solution is just to put everything inside the /test folder. `deploydocs` bails if not on travis so that solves that.
