### ISSUE TITLE
stable refers to wrong tagged release

### ISSUE THREAD

**Issue by Balinus** [JuliaDocs/Documenter.jl#947]
Hello,

When building the documentation step on TravisCI, the stable release is linked with an older tagged release, not the latest release.

For example, my latest tagged release is [v0.11.1](https://github.com/Balinus/ClimateTools.jl/releases) but I get the following
`Warning: removing "stable" and linking "stable" to "v0.8.0".`  [Link](https://travis-ci.org/Balinus/ClimateTools.jl/jobs/490250834).

There is no apparent bug as far as I can tell, so I'm assuming that I'm getting the wrong configuration in [make.jl](https://github.com/Balinus/ClimateTools.jl/blob/master/docs/make.jl) or [.travis.yml](https://github.com/Balinus/ClimateTools.jl/blob/master/.travis.yml) perhaps?

Any help appreciated, thanks for the Documenter package!

**Comment by mortenpi** [comment]
You're not running Travis on tags (https://github.com/Balinus/ClimateTools.jl/blob/master/.travis.yml#L19-L21), hence you have never deployed any docs for any version after 0.8.0 (except master; you can see which have deployed on [your `gh-pages` branch](https://github.com/Balinus/ClimateTools.jl/tree/gh-pages)).

If you want to use `branches: only:` you should also whitelist version tags. See [the Travis docs here](https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches).

**Comment by Balinus** [comment]
Oh! I see. So, if I simply remove the safelist it should deploy for every push I make to Github?

**Comment by mortenpi** [comment]
It will then run Travis, including the Documenter build, when you push to _any branch_ and when you tag (previously only if you pushed to `master`). Documenter will only deploy docs to `gh-pages` when it's building the `master` branch or a version tag though.

Also, as far as the missing docs go, unfortunately there is no good way to create them automatically now (the `.travis.yml` on the tags prohibits them from every being built). If you want them, then you should locally check out all the missing tags, build the docs locally, copy the `build/` directories over to `gh-pages` and commit and push.

**Comment by Balinus** [comment]
ok, worked! Thanks for the infos. :)
