### ISSUE TITLE
Some suggestions for the pdf manual first page

### ISSUE THREAD

**Issue by ViralBShah** [JuliaDocs/Documenter.jl#949]
The pdf version of the manual is amazing to have. Thank you.

Here's a few suggestions:
- [x] Include the Julia version on the first page
- [x] Include the Julia logo
- [x] Start the table of contents on the next page
- [x] If formatted as a latex book, it would be good to have it as 3 part book - single pdf (manual, base API, dev docs). I understand that three separate PDFs would be difficult because of cross-linking issues.

**Comment by odow** [comment]
I think these four points are all done. Is there anything still actionable?
