### ISSUE TITLE
Doctest with a semicolon fails

### ISSUE THREAD

**Issue by tkf** [JuliaDocs/Documenter.jl#959]
Following doctest fails in Documenter 0.21.1--0.21.3 and 24ee0067847bacbc37bb29b3e5d0977e13509c25 but not in 0.21.0:

`````markdown
```jldoctest
julia> "hello"; "world"
"world"
```
`````

**Comment by fredrikekre** [comment]
`git bisect` blames 8d17f686fa2b95b4c4f0aa8237e8e874d96fa7d6
