### ISSUE TITLE
Documenter didn't create docs for JuMP 0.19

### ISSUE THREAD

**Issue by mlubin** [JuliaDocs/Documenter.jl#965]
We just tagged JuMP 0.19, but the documentation at http://www.juliaopt.org/JuMP.jl/v0.19/ was never created. Previous tags worked, e.g., http://www.juliaopt.org/JuMP.jl/v0.19-beta2/. My only guess for the explanation is that the tagged commit had `[ci skip]`, could that be the cause?

**Comment by KristofferC** [comment]
Commits with ci skip are not run on CI so Documenter doesn't really have a chance to do anything.

**Comment by fredrikekre** [comment]
I would have thought that tag builds would be run regardless, but I don't see a build for the 0.19 tag in your Travis logs.

**Comment by mortenpi** [comment]
Yep, the tag was rejected by Travis due to the `ci skip`: https://travis-ci.org/JuliaOpt/JuMP.jl/requests

**Comment by mlubin** [comment]
Ok thanks. Guess we need to tag 0.19.1.

**Comment by mortenpi** [comment]
> Ok thanks. Guess we need to tag 0.19.1.
Or you can build locally and push to `gh-pages` manually.
