### ISSUE TITLE
List "admonition-like" syntax

### ISSUE THREAD

**Issue by Datseris** [JuliaDocs/Documenter.jl#969]
![image](https://user-images.githubusercontent.com/19669089/53435665-9ae74b00-39f9-11e9-8b23-915f9968f9a9.png)

Although it is clear that there is support for Admonition-like syntax, this does not seem to be listed somewhere in the documentation :
* https://juliadocs.github.io/Documenter.jl/stable/search/?q=admonition 
* https://juliadocs.github.io/Documenter.jl/stable/search/?q=warning

I think you should list (a) which admonition-like blocks are possible (I assume only `note` and `warning`) and (b), for newcomers, how to actually use the syntax?

I know that we can just see it by clicking "edit on GitHub", but I still don't know which syntaxes are available.

**Comment by mortenpi** [comment]
They are actually documented in the Base manual: https://docs.julialang.org/en/v1/stdlib/Markdown/#Admonitions-1

**Comment by Datseris** [comment]
Ah didn't know this. Of course you could say that this is just Markdown-specific and not just documenter specific, but still mentioning this and sharing the link could be helpful.

**Comment by mortenpi** [comment]
Do you think https://github.com/JuliaDocs/Documenter.jl/pull/985/files#diff-1842511d55effdf48dacc8c5de700712 would be enough?

**Comment by Datseris** [comment]
yeap! Only thing I would add is after the word syntax is a parenthesis: `(like how to use Admonitions)`
