### ISSUE TITLE
[Feature Request] Custom Translation on Assets and Text

### ISSUE THREAD

**Issue by Roger-luo** [JuliaDocs/Documenter.jl#977]
There are some text in English generated by rendering, it would nice if we could change these text to customized version. e.g

https://github.com/JuliaDocs/Documenter.jl/blob/28de68c0a10c7f7e8f7e6de9dcf266f9ab5947e1/src/Writers/HTMLWriter.jl#L592

And also it would nice to allow have custom html lang tag, e.g `zh-cn`

FYI:
https://github.com/JuliaCN/JuliaZH.jl/pull/49

We are using a overwritten version of the above functions as a workaround in JuliaZH currently.

**Comment by mortenpi** [comment]
We could definitely support this, I would be happy to review a PR for this. Passing a custom dictionary to `HTML()` is probably the way to go. Or perhaps there is some better approach to i18n library code?

**Comment by odow** [comment]
Closing in favor of https://github.com/JuliaDocs/Documenter.jl/issues/297.
