### ISSUE TITLE
Syntax highlighting for indented code blocks

### ISSUE THREAD

**Issue by christopher-dG** [JuliaDocs/Documenter.jl#978]
The usual convention for docstrings is to do something like this:

```jl
"""
    myfunction(myarg::MyType) -> MyReturnType

My function.
"""
```

But when you do this instead of a triple-backticked code block, you lose out on syntax highlighting. Would it be possible to convert indented code blocks into backticked Julia ones?

**Comment by mortenpi** [comment]
The parser in the Markdown stdlib does not distinguish between triple-backticked and indented code blocks (i.e. the resulting AST is the same). So the only way to achieve this would be to always apply Julia highlighting to all code blocks that do not specify the language. However, I am a bit hesitant, as that goes against how Markdown codeblocks normally get interpreted.

I guess, another way would be to special-case this particular use case -- the first code block in a docstring gets highlighted as Julia (unless another language is explicitly specified).

**Comment by christopher-dG** [comment]
Thanks for this info. I'm also a little hesitant of defaulting to Julia, maybe an alternative could be an opt-in `makedocs` option which sets the default?
I do also like the special case idea.

**Comment by mortenpi** [comment]
We could have an opt-out special casing maybe?
