### ISSUE TITLE
stdout not being captured

### ISSUE THREAD

**Issue by JackDunnNZ** [JuliaDocs/Documenter.jl#986]
On the current master, the following doesn't show any output being captured

    ```@example
    println("hello world")
    ```

Works as expected on 0.21.5

**Comment by mortenpi** [comment]
Seems to be due to #938. We're just discarding the `buffer` variable now:

https://github.com/JuliaDocs/Documenter.jl/blob/9d30975b24822fe653f677b918311b544209aaa2/src/Expanders.jl#L532-L571

Looking into a fix.

**Comment by JackDunnNZ** [comment]
Thanks @mortenpi !
