### ISSUE TITLE
assets placement and Documenter version

### ISSUE THREAD

**Issue by tlienart** [JuliaDocs/Documenter.jl#998]
Travis CI failed with 

```
ERROR: LoadError: MethodError: no method matching Documenter.Writers.HTMLWriter.HTML(; prettyurls=true, assets=["assets/custom.css"])
```

However this was prompted to me by Documenter with

```
┌ Warning: The `assets` keyword argument should now be specified in the
│ `Documenter.HTML()` format specifier. To fix this warning replace
│ ```
│ assets = ...
│ ```
│ with
│ ```
│ format = Documenter.HTML(assets = ...)
│ ```
└ @ Documenter ~/.julia/packages/Documenter/8vUAI/src/Documenter.jl:214
```

I imagine this is a version issue (?). I'm using Documenter 0.22.2 locally and Travis seems to be on 0.21.5.

Any recommendations on how to avoid this? I have reverted to the old behaviour of putting `assets` as a kwarg of `makedocs` instead of putting it in `Documenter.HTML` for now.

Thanks

**Comment by mortenpi** [comment]
Make sure that you're using the latest Documenter on Travis. If you use the recommended setup with `docs/Project.toml`, you need to update the `[compat]` section in there. If you are checking in a manifest, make sure that it's updated.

**Comment by tlienart** [comment]
Thanks for the quick response, I had ommited to check the Documenter Project.toml which had a stray compat field that I removed.

Thanks again

**Comment by mortenpi** [comment]
> stray compat field that I removed.

It's best if you keep it, and just update the version number. Documenter 0.23 may contain breaking changes that will break your setup.
